### ISSUE TITLE
Remove the publisher date requirement when adding a new book

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3301] opened 2020-04-02 19:20 UTC
There are multiple issues with the publish date in the data dump (called "publish_date" there), but one of them is in #2039. The other issue is when fake publisher dates are added due to a lack of knowledge of what they are (like putting in all 0's, or 1234 to fill it in when it's unknown):

![image](https://user-images.githubusercontent.com/55302685/78292348-bb76b400-74db-11ea-9c6e-54a0112188a9.png)
This was pointed out by Mek in https://github.com/internetarchive/openlibrary-librarians/issues/1

Proposed solution: Take out the requirement to add a publisher date, as it may be hard to find, unknown, or possibly doesn't exist: 
![image](https://user-images.githubusercontent.com/55302685/78292488-f547ba80-74db-11ea-9233-db41375e7b61.png)

**Comment by guyjeangilles** [comment] 2020-04-03 02:13
If we make a standard input format for publisher's date we'll likely have to take into account localization. @tfmorris chime in if I'm missing anything.

**Comment by BrittanyBunk** [comment] 2020-04-03 04:11
@guyjeangilles true. Outside of the US, most countries put the date first. I just think each site would have its consistency so that it's readable for each locality - like the US OL would be different than the Polish version worked on, for instance: https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by seabelis** [comment] 2020-04-03 09:07
This seems like a duplicate of https://github.com/internetarchive/openlibrary/issues/2039

**Comment by dcapillae** [comment] 2020-04-03 16:01
I usually use only the year, sometimes adding the month, rarely I use the complete date (although some editions include it).

I propose to use the same date format that is suggested by Open Library to enter the date of birth or date of death of an author (e.g. 21 May 2000). Likewise I recommend using only the year if the full date (day or month) of an edition is irrelevant or unknown.

If we want to use a number-only format for saving dates, the ideal option is the international YEAR-MONTH-DAY format (e.g. 2000-05-24).

**Comment by seabelis** [comment] 2020-04-03 16:58
@dcapillae 

> If we want to use a number-only format for saving dates, the ideal option is the international YEAR-MONTH-DAY format (e.g. 2000-05-24).
See #2039. This is the format that should be used. Year only is fine.

**Comment by BrittanyBunk** [comment] 2020-04-03 16:58
@dcapillae @seabelis it'll be possible to fill out only one of the boxes if needed. The data dump will be difficult to sort with lettering (as numbers are easier to work with), and it takes up too much space - as the editions file is at 5.7GB. Removing the lettering helps a lot!

**Comment by BrittanyBunk** [comment] 2020-04-03 16:59
@seabelis true, part of this is a duplicate. I will condense it to the other 1/2 of this issue then.

**Comment by BrittanyBunk** [comment] 2020-04-03 17:02
@seabelis I will address your thoughts on the date format in the github issue you were talking about.

**Comment by tfmorris** [comment] 2020-04-03 18:11
@guyjeangilles Yes, we'll need to localize date handling. Most user friendly would be a parser which accepted text in the user's local format and converted it to our internal EDTF / ISO 8601 format.

An option to consider would be to restrict this instead to just publication **year**. That would be much simpler to do data validation on and easier for users to get right.

The pieces to this include:
* our internal storage format
* conversion of existing data to the new storage format (and cleanup in the process)
* importer (MARC, Amazon, etc) transformations to the internal format
* user web entry validation and transformation to internal format
* output rendering using the users locale

**Comment by tfmorris** [comment] 2020-04-03 18:11
BTW, since this was all triggered by a small handful of records with `9999` dates, that is actually the result of an importer bug combined with bad MARC records https://github.com/internetarchive/openlibrary/issues/2711#issuecomment-608585653

**Comment by tfmorris** [comment] 2020-04-03 18:56
I just realized that this issue got changed to be about something completely different. I was commenting on the original issue (as was pretty much everyone else), so the comments make no sense in the context of the completely revised issue.

Making the publication date optional is fine, but it should be accompanied by tighter data validation.

**Comment by BrittanyBunk** [comment] 2020-04-03 20:18
@tfmorris I'm sorry - I put my idea in the wrong place, as I thought it was the same idea.

True!

**Comment by hornc** [comment] 2020-04-07 11:56
I think removing the requirement for a publication date is a bad idea and goes against the data model. Without a specific date of publication a book record is at the 'work' level which is an abstract entity. Open Library's data model for a page per book is targeting book Editions. An edition record without enough data to identify which edition it is isn't much use. A subsequent editor won't have enough to go on to add a 'correct' date later, they will simply check whether an edition they know about exists, and add it if not. Editions without dates will become dupes with little to no value.

**Comment by BrittanyBunk** [comment] 2020-04-07 16:15
I don't believe that's true, as book record does stay at the edition level without a publication date. Because a publish date is not required overall, it gets deleted anyway, leaving this:
![image](https://user-images.githubusercontent.com/55302685/78692186-5e4d7a80-78ae-11ea-912a-f065e25cccf3.png)

I feel just feel having an incorrect date is just as useless as having no date at all. What separates them is their name and hopefully other classifications, like a cover image, ISBN, LCC, DDC, etc. Maybe it's better to just go straight to the edit page instead of having an 'add book' page, so that people could enter books with other classifications when they don't know the publish date. The reason is that any requirement is going to have inherent issues (like requiring book covers would just lead to false book covers just to add in the edition), so it's best to leave out this intermediary step.

**Comment by seabelis** [comment] 2020-04-07 16:21
How is a cover image a classification?

**Comment by seabelis** [comment] 2020-04-07 16:25
A date should be populated when a person adds an edition. Even if this is xxxx to positively identify that there is no date. The classification has nothing at all to do with the date requirement.

**Comment by BrittanyBunk** [comment] 2020-04-07 16:52
@seabelis I see what you mean, but that just addresses one part (where the date is unknown). However, publisher dates are still left blank on the example I listed (as they might be deleted after the 'add book' page or a bot just doesn't add it in where there's no difference in publisher date and title.

**Comment by seabelis** [comment] 2020-04-07 18:07
It doesn't work, but the field can be adjusted to allow the xxxx format.

**Comment by BrittanyBunk** [comment] 2020-04-08 04:36
That's all I'm asking - to remove the requirement for a year. I even proposed: https://github.com/internetarchive/openlibrary/issues/3308 and this could accommodate x's and -'s for what's unknown. This could even be on the 'add book' page. I'll add my thoughts to #3308 to account for what we discussed.

**Comment by seabelis** [comment] 2020-04-08 07:13
I'm not saying remove the requirement. I'm saying modify the input restriction for that field to allow x.

**Comment by BrittanyBunk** [comment] 2020-04-08 15:02
@seabelis we're kind of talking about the same thing - right now it requires a year, and so that should be removed in some format, be it removing the ability to add a date or taking it out of the 'add book' page. The issue with your idea is that people can still take out the xxxx's.

I would rather have it that a person doesn't face an 'add book' page, but goes directly to the edit page, and if they don't put anything down for the date, it automatically fills in all x's, but I would rather see it blank if there's no date, as it clogs up the data dump - a lot! Also, if it's going to be all x's anyway, then there's no need for requiring the publish date anyway, as there'd be nothing to add. It just doesn't make sense and is an unnecessary intermediary step for what's not needed.

**Closed** 2020-07-13 05:01 UTC
Labels: Affects: Data, Lead: @mekarpeles, Priority: 2, Type: Feature Request
