### ISSUE TITLE
Add user's star ratings to users' Already-Read page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#959] opened 2018-05-10 05:28 UTC
/account/books/already-read

**Comment by jdlrobson** [comment] 2018-12-26 23:06
Duplicate of 1032

**Closed by jdlrobson** 2018-12-26 23:06 UTC
Labels: accounts, ratings

**Comment by tfmorris** [comment] 2018-12-27 06:38
Traditionally one keeps the oldest report of a set of duplicates. Is there a reason this one is being closed in favor of one that was created months later?

p.s. The # sign in front of an issue number is critical to creating xrefs forward and back.

**Comment by jdlrobson** [comment] 2018-12-27 06:54
#1032 is much **much** more descriptive then this one... I'm still not sure about the protocol for editing issues posted by others.

I've found in Wikimedia projects, keeping the most descriptive/most discussed is a better rule than age.
