### ISSUE TITLE
Firefox constantly reloading

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#8184] opened 2023-08-13 09:52 UTC
Firefox mobile ios is constantly reloading Openlibrary pages, Login isnt possible as is any other page.

- **Logged in (Y/N)?** yes and no
- **Browser type/version?** Firefox mobile on ios or ipados, latest version
- **Operating system?** ios
- **Environment (prod/dev/local)?** prod

**Comment by 20481A05K0** [comment] 2023-08-14 15:40
**hey** there!!

> can i take up this issue or still anyone working on it

**Comment by mekarpeles** [comment] 2023-08-14 19:03
Is anyone else experiencing this problem? @bitnapper it may be good for us to try and jump on a call together so we can see what's going on?...

**Comment by bitnapper** [comment] 2023-08-15 10:23
When I reported this issue, OL seemed to have some trouble delivering pages in general. No page loaded completely. It was ok-ish in most browsers but that time it was worse than ever before and lasted several days. Since I don't have this issue at the moment, I can't show you but would be available If you like to talk about it. I send you my preferred contacts in slack.

It seems Firefox mobile has different behaviour when timeouts are met than its desktop counterparts or other browsers I guess.

**Comment by bitnapper** [comment] 2023-08-15 10:24
When I reported this issue, OL seemed to have some trouble delivering pages in general. No page loaded completely. It was ok-ish in most browsers but that time it was worse than ever before and lasted several days. Since I don't have this issue at the moment, I can't show you but would be available If you like to talk about it. I send you my preferred contacts in slack.

It seems Firefox mobile has different behaviour when timeouts are met than its desktop counterparts or other browsers I guess.

**Comment by cdrini** [comment] 2023-08-15 21:13
(deleted accidental duplicate comment)

**Comment by mekarpeles** [comment] 2023-08-17 15:04
I am marking as "cannot reproduce" for now. Please re-open if folks are still hitting this! It seems important.

**Closed by mekarpeles** 2023-08-17 15:04 UTC
Labels: Type: Bug, Priority: 1, Lead: @mekarpeles
