### ISSUE TITLE
Rework for subjects

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6434] opened 2022-04-14 17:22 UTC
I suggest using this issue for discussing what should be changed about subjects

@mekarpeles said that OL may move to subject system similar to 'Archive of our own' ([their FAQ](https://archiveofourown.org/faq/tags?language_id=en#whatisatag)). I'm not familiar with it, but I kinda like that their tags can have synonyms

> If you post a work in Spanish and you tag with muerte temporal de personajes this will be translated and then made synonymous with the English canonical tag Temporary Character Death.

### what I want to be added
- I would like to have hierarchical subjects. For example, we have "Dark Fantasy" and "Fantasy". Obviously, the first one is sub-genre to the second one, so it would be logical if works with the first subject were automatically added to the second one
- subjects merging (mentioned in 2022-04-12 meeting)
### Related issues
- [x] #6050 

- [ ] #6162 
### Possible scheme

- [ ] #2819

**Comment by mekarpeles** [comment] 2022-04-14 17:50
Thank you for creating this issue! We should discuss at an upcoming community call.

**Comment by tfmorris** [comment] 2022-04-18 18:02
This is a duplicate of #2819 from more than 2 years ago. 

The FAQ mentioned above requires agreeing to a legal agreement, which makes it inaccessible, and, speaking of inaccessible, why schedule discussion for a private call that requires real-time presence rather than discussing it in the open on the relevant ticket like most open source projects due?

I think making subjects first class objects would be a significant improvement without adding the complexity of hierarchies -- particularly multilingual, multicultural hierarchies, as would be required.

**Comment by mekarpeles** [comment] 2022-09-12 19:07
Thanks @tfmorris, moving over the P2 + Needs Community discussion and closing this duplicate of #2819

**Closed by mekarpeles** 2022-09-12 19:07 UTC
Labels: Priority: 2, Needs: Community Discussion, Lead: @mekarpeles, Lead: @jimchamp, Theme: Book Tags
