### ISSUE TITLE
"Read" type availability button absent in Lists

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2564] opened 2019-10-25 23:27 UTC
Should have 'read' button, as how the 'borrow' button looks
![Untitled](https://user-images.githubusercontent.com/55302685/67609942-49d45600-f744-11e9-8f39-e6c1be27fbd2.png)

**Comment by mekarpeles** [comment] 2019-10-27 05:29
This looks like a problem with availability statuses (i.e. a readable book is not showing up as such). This is a duplicate of #2141

**Comment by BrittanyBunk** [comment] 2019-10-27 12:47
@mekarpeles hey. This is different than that one, as that one's about malfunctioning buttons, not that it's missing a feature. Bug vs feature.

**Comment by cdrini** [comment] 2019-11-07 22:18
@BrittanyBunk could you provide a link to the list? And to that edition? I can investigate to see if it's the same problem.

**Comment by BrittanyBunk** [comment] 2019-11-09 14:12
@cdrini This is an entire site feature. Not one book that's able to be read has the 'read' button on it. https://openlibrary.org/people/hawaiisunfun/lists/OL106255L/my_edited_books Almost all of these haev a pdf. So I'm just requesting for adding the feature to lists altogether.

**Comment by mekarpeles** [comment] 2019-12-18 00:20
@BrittanyBunk I think this is a regression -- and you're right. This used to work.

I think this is because we backed away from using availability.js to paint available editions.

One of the problems is that Lists can contain all sorts of things that are not `edition`s. So we need to run a function which takes a List, identifies the editions, and then injects Archive.org availability into (only) these editions.

**Comment by BrittanyBunk** [comment] 2019-12-18 01:12
@mekarpeles right, as it won't be possible for works. Got it. Thanks for understanding.

**Comment by jimchamp** [comment] 2022-04-18 17:39
This seems to be resolved, unless I'm missing something.  I'm seeing all types of availability buttons on your list items.

Feel free to re-open this if I'm incorrect.

**Closed by jimchamp** 2022-04-18 17:39 UTC
Labels: Type: Feature Request, Priority: 3, Theme: Reading Log, Affects: UI, Lead: @jimchamp
