### ISSUE TITLE
E-Book borrow graph redirecting to wrong page

### ISSUE THREAD

**Issue by ScarlettRed** [internetarchive/openlibrary#3232] opened 2020-03-21 05:59 UTC
The e-book burrow stats graph on the home page is redirecting some irrelevant page.

### Relevant url?
https://openlibrary.org/subjects/in_library#ebooks=true

### Steps to Reproduce

1. By clicking on the link with e-book borrow graph on the home page

* Actual: redirected page is an irrelevant one.
* Expected: page showing e-books borrowed list page

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
A new page should be created showing a list of e-books borrowed w.r.t. open library site with details of borrower, book borrowed, time, etc.

### Stakeholders
@mekarpeles

**Comment by BrittanyBunk** [comment] 2020-03-22 03:02
I did not know this was an issue! That's smart - pointing to the 'borrow' books subject page instead of 'read' ones - or are you talking about stats - like how many books are available to borrow with a list to make that possible?

**Comment by ScarlettRed** [comment] 2020-03-22 03:36
i think  as the graph on the home page is showing the stats for the e-books burrowed in the past day...so the redirecting page should provide information about burrowed e-books like we have recent activity page(showing users activity w.r.t. time, but right now recent activity page doesn't show details about burrowed and returned books). So, i think a new page should be made for showing these details of burrowed and returned books separately or for second thought we could include this in already existing recent activity page.

**Comment by BrittanyBunk** [comment] 2020-03-22 04:09
I see it - the last graph on the home page: https://openlibrary.org/. By recent activity page, it's https://openlibrary.org/recentchanges, right? You're right - it's not on there. I checked - I didn't see it anywhere on the site really. 

I kind of have an idea - it might be a little messy though: 1) let's not have usernames and times associated with books that they borrow, 2) it would look similar to what's there now: https://openlibrary.org/subjects/in_library#ebooks=true, but with books recently borrowed, 3) since people can't borrow books that other people are taking out - as they'd just be shown the waiting list, I think https://openlibrary.org/stats/readinglog might be awesome to add underneath it. 

So a mashup of those two in one page?

**Comment by guyjeangilles** [comment] 2020-03-22 21:14
I want to make sure I understand this issue correctly. The problem is that the "EBooks Borrowed" link at the bottom of the homepage redirects to https://openlibrary.org/subjects/in_library#ebooks=true, which isn't related to "EBooks Borrowed?"
![3232_ol](https://user-images.githubusercontent.com/7256157/77260774-e6623c00-6c81-11ea-826d-ff1011ddd6ca.png)

>I kind of have an idea - it might be a little messy though: 1) let's not have usernames and times associated with books that they borrow, 2) it would look similar to what's there now: https://openlibrary.org/subjects/in_library#ebooks=true, but with books recently borrowed, 3) since people can't borrow books that other people are taking out - as they'd just be shown the waiting list, I think https://openlibrary.org/stats/readinglog might be awesome to add underneath it.
>
>So a mashup of those two in one page?

@BrittanyBunk this sounds different than the problem described in the original description.

**Comment by tfmorris** [comment] 2020-03-22 23:38
The immediate issue is that the subject `in_library` is no longer used as a way to indicate that a volume is (potentially) available, so, at a minimum, that obsolete link should be updated.

Possible options include:
1. Update the link to the current equivalent showing all available eBooks
2. Link to equivalent of the Recently Returned Books carousel on the home page
3. Link to trending Most Wanted books https://openlibrary.org/stats/readinglog#Most_Wanted_(This_Month)
4. Link to more detailed stats: https://openlibrary.org/stats/stats#Borrows
5. Link to some fancy new page to be developed

The anchors for 3 & 4 don't yet exist, so would need to be created. 2 & 5 require more development time than just changing the link. 

Approval will never be granted for showing users borrowing history, so anything like recently returned books is always going to be anonymous. 

Showing a list of high demand books has the risk that none of them will be borrowable, making for frustration on the users' parts.

I think we should choose one of 4, 3, 1 as a first step and then have a separate discussion about whether additional changes are desirable.

**Comment by BrittanyBunk** [comment] 2020-03-23 01:55
Maybe if we just have a # of how many books are borrowed in one day (instead of what they are), that could work. Then instead of books that are actually borrowed, it could be books recently returned instead - so people could check them out. That would kind of require reverse engineering the stats on the home page to have 'books returned' instead of 'books borrowed' (even though that is a better stat) - so people have better access to books. That might be a messy way of fixing it though. I agree about the other fancy links there - like https://openlibrary.org/stats/readinglog#Most_Wanted_(This_Month) is sufficient for lots of the needs here.

**Comment by mekarpeles** [comment] 2020-03-23 05:49
I think @tfmorris is right on. Let's please link to (4) https://openlibrary.org/stats/stats#Borrows for now. Bringing the patron to the stats page which shows more info on books borrowed when they click on the "# borrowed books" stats graph seems like the right decision to me.

@ScarlettRed I'm assigning you if you're up for the challenge :tada: :)

**Comment by ScarlettRed** [comment] 2020-03-23 06:33
As the initial problem and proposed solution was to introduce a new page showing some stats about ebooks borrowed, but I totally agree with @tfmorris as showing info about ebooks borrowed currently won't be allowed due to users privacy. So, instead of this, we could redirect to some page showing some more stats as @tfmorris described.
Thank you @mekarpeles for assigning me. I will do it Step by step then.

**Comment by ScarlettRed** [comment] 2020-03-23 06:37
I think for the first step, the link should be updated showing all available e-books that can be borrowed. Then we will replace it by **most_wanted** ones.

**Comment by mekarpeles** [comment] 2020-04-01 16:56
@ScarlettRed this ticket can be fixed with a single line...

https://github.com/internetarchive/openlibrary/blob/cc94dcd822d85f1c2afdf4773abdeeb120ab9f5b/openlibrary/templates/home/stats.html#L38

This url just needs to be changed from /borrow to /stats.

**Comment by ScarlettRed** [comment] 2020-04-04 14:55
@mekarpeles I have also designed a whole different page of Ebook borrow stats graph. here is the link to the design.
https://xd.adobe.com/view/c44286cb-6190-461e-7aee-8357af397550-b273/

**Closed** 2020-04-10 18:10 UTC
Labels: Lead: @jdlrobson, Priority: 3, Type: Bug
