### ISSUE TITLE
Sort by publication year doesn't recognize all date formats

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1440] opened 2018-10-26 20:34 UTC
For a number of works, I've adjusted the date so that the year is first, i.e. 2008 January and what seems to happen is some sort of grouping according to string length. So dates with months sort first (or last) followed by dates that are years only. But within the group that includes more than the year, there doesn't seem to be any order. I've tried using a numerical date only but same results. See https://openlibrary.org/works/OL18342W/Unless and https://openlibrary.org/works/OL16313124W/Harry_Potter_and_the_Chamber_of_Secrets

But sometimes there seems to be no logic to the sort at all, see: https://openlibrary.org/works/OL362705W/Romeo_and_Juliet

**Comment by LeadSongDog** [comment] 2018-11-01 15:54
Not sure, but comparing the adjacent lines, I think that it just might be a typo:  
https://github.com/internetarchive/openlibrary/blob/75452cf6f0e3c23e1030395c93e232686ebaa417/openlibrary/macros/Search.html#L56

It looks that <option value="DateDesc">$_.date ($_.newest_first)</option>
should read <option value="DateDesc">$_.date ($_t.newest_first)</option>

**Comment by tfmorris** [comment] 2018-11-13 07:32
The column is titles and publication information (year & publisher). From a quick glance at the code, I don't think it's even attempting to sort on publication date/year.

**Comment by tfmorris** [comment] 2019-01-03 00:17
Perhaps a duplicate of #806.

**Comment by guyjeangilles** [comment] 2019-10-25 01:24
Agreed that this is a duplicate of #806. Closing.

**Closed by guyjeangilles** 2019-10-25 01:24 UTC
