### ISSUE TITLE
2021-01-31 combined data dump missing data/out of date data

### ISSUE THREAD

**Issue by rmtobin** [internetarchive/openlibrary#4671] opened 2021-02-24 01:33 UTC
I recently pulled down the combined data dump located here: https://archive.org/details/ol_cdump_2021-01-31 and have found a few different instances where data is missing or out of date, based on last modified timestamps.

### Evidence / Screenshot (if possible)
For example, take this edition: https://openlibrary.org/books/OL25618096M/The_color_of_magic.

It is present in the data dump under the key '/books/OL25618096M', but it is missing lots of data in its record like isbn13, authors, series, various identifiers, etc that are present when viewing via the website. Additionally, the last modified timestamp for the data dump record is 2014-09-01T16:27:08.490439, which is very out of date compared to the edit history. Additionally, while there is a works key with the aforementioned edition (OL453676W), no works records with that key seems to be present in the dataset.

I would expect for the data dumps to be the same as the data available when browsing the openlibrary website, and for edition to work references to be consistent.

### Proposal & Constraints
Validate the data dumps are consistent with the content provided via the openlibrary website. A

**Comment by rmtobin** [comment] 2021-02-24 01:34
This may be a duplicate of https://github.com/internetarchive/openlibrary/issues/4621, but I opened a new issue just in case since I have some additional details.

**Comment by cclauss** [comment] 2021-03-05 16:10
@rmtobin There are two new [sets of dumps](https://archive.org/details/ol_exports?sort=-publicdate) from 02-26 (Python 3) and 02-28 (Python 2) that I will start to look into next week.  Please let me know your thoughts if you have time.  Thx!

**Comment by cclauss** [comment] 2021-03-29 15:57
This issue was fixed in https://archive.org/download/ol_dump_2021-03-19 but let's leave it until the April 1st dump.

**Comment by cdrini** [comment] 2021-04-06 20:06
Looks like a duplicate of #4621 ; closing in favour of that since it has more discussion.

(Status update: We're still working on it :/ )

**Closed by cdrini** 2021-04-06 20:06 UTC
Labels: Lead: @cclauss, Needs: Triage, Type: Bug
