### ISSUE TITLE
Weird syntax a typo?

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#847] opened 2018-03-12 21:32 UTC
https://github.com/internetarchive/openlibrary/blob/f8092840a77c7479a352fd83fd068d340f97d3e3/openlibrary/solr/inside/index_all.py#L29

The single reversed comma quotation marks (&#8219;) or (\`) or whatever this (\`) is here, and repeated lower in this module, seem anomalies. Is it a typo, or a real thing?

**Comment by tfmorris** [comment] 2018-03-12 22:50
Duplicate of #846

**Closed by tfmorris** 2018-03-12 22:50 UTC
