### ISSUE TITLE
Changing name of edition shouldn't change work name

### ISSUE THREAD

**Issue by JeffKaplan** [internetarchive/openlibrary#620] opened 2017-10-30 18:28 UTC
There's a few cases where an edition is incorrectly classified under a work.

To fix this, some users are renaming the edition.
This is cascading and causing the parent work's name to change.
Here are two examples:
https://openlibrary.org/books/OL6202508M/The_Tales_Of_Rabbi_Nachman
https://openlibrary.org/books/OL362681M/Stupid_celebrities

What should happen is, something like, changing the name of the edition *causes* it to be turned into its own work and forked (or be added to an existing matching work?)

@mekarpeles suggested tagging @hornc and @cdrini who have been working on merge/split logic.

Thanks!

**Comment by LeadSongDog** [comment] 2017-10-30 20:30
Yes, this is one more reason why editing an edition should allow manual selection of a work. Somehow the work "Stupid celebrities" https://lccn.loc.gov/98022887 by Ross Petras & Kathryn Petras has been conflated with the work "Genre" https://lccn.loc.gov/90176161 by Stephen Neale, 1950- 
Admin priviledges are needed to sort this out.

**Comment by LeadSongDog** [comment] 2017-10-30 20:34
Partially duplicates #412

**Comment by cdrini** [comment] 2017-10-31 22:22
You know, that might be a really simple/elegant way to handle this. After all `works` are stored on an edition, so we could just have a list of work ids editable from the edition page (similar to how you add authors right now). This would probably be pretty fast to implement as well...

**Comment by cdrini** [comment] 2017-10-31 22:27
@mek if that solution sounds good to you, I think this would be a good candidate for a hackathon project. It would require a bit of knowledge about the code base, but I feel most of the code is already there, and would just need some copypasta.

**Comment by mekarpeles** [comment] 2017-10-31 23:23
Sounds good, feel free to tag on #603 -- if you can provide any context about implementation (or files where things may exist) i'm sure a courageous volunteer would be eternally grateful!

**Comment by cdrini** [comment] 2017-11-01 00:43
Nominating for #603!

Option to change the works associated with an edition

1. Implement a `works/_autocomplete` endpoint
  - abstract/reuse `authors/_autocomplete`  `\openlibrary\plugins\upstream\addbook.py:authors_autocomplete`
2. Mirror the way one can edit authors (with the autocomplete and stuff)
  - js autocomplete is here: `\openlibrary\plugins\openlibrary\js\autocomplete.js`
  - template where Authors edit UI is added to edition page: `\openlibrary\templates\books\edit.html`
  - where the works field should be: `\openlibrary\templates\books\edit\edition.html`

Caveats:
- prevent moving an edition if its the only edition on the work (future: merge works, but for now avoid)

**Comment by guyjeangilles** [comment] 2019-10-24 00:03
I can duplicate this bug.

@cdrini @mekarpeles I'm not sure we want to leave this issue to a hackathon volunteer. Do either one of you want to be assignee? Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by cdrini** [comment] 2019-11-07 21:38
Manual selection of a work is no possible, so closing this as complete.

**Comment by guyjeangilles** [comment] 2019-11-10 20:06
This isn't fixed @cdrini. See the history of this edition: https://openlibrary.org/books/OL27096953M/Children_of_Blood_and_Bone

**Comment by tfmorris** [comment] 2019-11-10 20:17
> This isn't fixed. See the history of this edition: https://openlibrary.org/books/OL27096953M/Children_of_Blood_and_Bone

More specifically, a single change (60537807) modified both the edition and the work titles:

https://openlibrary.org/works/OL19912375W.json?m=history
https://openlibrary.org/books/OL27096953M.json?m=history

**Comment by hornc** [comment] 2019-11-10 21:02
I do not see what the problem is with edit https://openlibrary.org/books/OL27096953M/Children_of_Blood_and_Bone  (change (60537807) ) -- it looks like the work and edition title were correctly changed in a single edit.

From the edition edit page:
![image](https://user-images.githubusercontent.com/905545/68550306-9a4af380-0466-11ea-9fe2-f8b1f84a42fa.png)
Is where users can change the _Work_ title

The edition title is shown and can be edited here:

![image](https://user-images.githubusercontent.com/905545/68550329-be0e3980-0466-11ea-8839-f69eefae6e1c.png)

To get the effect of the _Children of Blood and Bone_ edit above, both fields would have been edited, which looks to me to be the correct thing to do in this case.

Sure, the field labelling is not great, but I'm not sure how it relates to the original issue report, and this example shows that despite arguably poor naming, a user did the right thing.

We currently have the following features from the edition edit page:

1. A user can change an edition name without changing the work name in one edit.
2. A user can change the work name without changing the edition name in one edit.
3. A user can change both the work name and edition name in one edit.

We also have

4. A user can split an edition from its current work and move it to an _existing_ work
with 
![image](https://user-images.githubusercontent.com/905545/68550488-0b3edb00-0468-11ea-8baa-aaaae8856f4a.png)


What we _don't_ have, which I _think_ is closer to the intent of the original report is:

5. A user should be able to split an edition off from an existing work and create a _new work_ in one edit.

 5 seems like an uncommon use-case, and I'd like to see some examples where it is appropriate. I'd like to understand how we get into the situation where editions are incorrectly added to existing works instead of creating a new work. _That_ seems like a bug we should fix at the source, rather than adding a new work flow.  I think if 5. is really needed it could be done currently in some complex multi-step workflow appropriate to the specific situation.

_Alternatively_ this issue is really meant to be: 
6. the first title shown on the edition edit page is actually the _Work_ title, and that is not obvious to many first time users _(because it is not very intuitive at all)_ so some people are changing what they think is the edition title, and it's not having the intended effect. 

If this is 5., I'd say "won't implement" -- let's find the root cause and fix that
If it is 6., let's fix that by adding some explanatory text by the title field, _or_ re-design the edition edit page.

**Comment by hornc** [comment] 2019-11-10 21:25
I have just created https://openlibrary.org/works/OL20443899W/Genre  to move the Genre editions to.

The correct author is https://openlibrary.org/authors/OL7008084A/Stephen_Neale (1950)

**Comment by tfmorris** [comment] 2019-11-11 00:41
@hornc You're right, it looks like these were two field edits done at the same time. I tested editing the edition title only [here](https://openlibrary.org/books/OL26879357M/Children_of_Blood_and_Bone?b=4&a=3&_compare=Compare&m=diff) and it correctly had no effect on the work title.

I think the edit form could definitely be improved, but that can be the topic of a separate issue.

Use case 5 seems dangerous to me. In the original issue, it was phrased as:

> What should happen is, something like, changing the name of the edition causes it to be turned into its own work and forked (or be added to an existing matching work?)

It would cause no end of problems with translations and editions having different titles (but which belong to the same work).

The original problem with the _Genre_ editions appears to have been created by the Workbot, but I'm not even sure we'd be able to track down the code that it was actually using on the 15 Dec 2009 run. Another instance where lack of provenance hampers us...

**Comment by cdrini** [comment] 2020-01-06 16:33
5 has been implemented as librarian feature in #2668 , so closing this.

**Closed by cdrini** 2020-01-06 16:33 UTC
Labels: Affects: Admin/Maintenance, Affects: Data, Lead: @cdrini, Priority: 3, State: Backlogged, Type: Bug
