### ISSUE TITLE
Logo overlapped by "Browse" dropdown on IE11

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2754] opened 2019-12-18 18:24 UTC
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/71112439-78e1d380-2199-11ea-9728-d746d2a43b00.png)

### Relevant url?
e.g. https://openlibrary.org , but any page

### Steps to Reproduce

1. Go to https://openlibrary.org

* Actual: Logo is overlapped
* Expected: Logo is separate

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** IE11
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@nsharma123

**Comment by mightysood** [comment] 2020-03-25 10:40
Hi @cdrini 
This issue is only reproduced in the IE browser.
Works fine in Chrome, Firefox, and Microsoft Edge. 
There are 5 elements in the header tag of which logo-component, search-component, navigation-component and account-component are shown in Web UI. 
If we give logo-component a width of 20%, it prevents logo overlapping in IE and doesn't distort the logo in other browsers.

**Comment by nynaalekhya** [comment] 2021-01-07 18:18
@jdlrobson Since this one is open, can I work on this one?

**Comment by jdlrobson** [comment] 2021-01-08 20:37
should be fixed now.

**Closed by jdlrobson** 2021-01-08 20:37 UTC
Labels: Affects: UI, Lead: @jdlrobson, Priority: 3, Regression, Theme: Design, Type: Bug
