### ISSUE TITLE
List creation not working

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1984] opened 2019-03-14 20:27 UTC
## Description
> Cannot create a new list.

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?
Normally one can use the drop-down list of lists to create a new list. This is not currently functioning.

## Details
I have tried refreshing the page, but no fix.
> Logged in (Y/N)?
Y
> Browser type/version?
Chrome Version 72.0.3626.121 (Official Build) (64-bit)

> Operating system?
Win 7 Pro
## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by shreyansh23** [comment] 2019-03-16 07:30
Duplicate of #1970

**Comment by tfmorris** [comment] 2019-03-18 21:29
Closing as a duplicate of #1970.

**Closed by tfmorris** 2019-03-18 21:29 UTC
Labels: duplicate
