### ISSUE TITLE
Add current user's lists underneath Want to Read

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3630] opened 2020-07-27 14:25 UTC
We would want to show the user's lists beneath the Want to Read button and show all lists below the fold 

### Stakeholders

@cdrini

**Comment by prakashaditya369** [comment] 2020-12-30 12:24
@tabshaikh We could add both the user's list as well as all lists in the "Menu of Want to Read Button" with different categories.

Is this issue open to work?

**Comment by cclauss** [comment] 2021-01-04 21:59
@prakashaditya369 This issue is in an open state so if you know how to fix it then please submit a pull request.  Waiting is not required.

**Comment by jdlrobson** [comment] 2021-01-10 23:19
Can you expand the description here?

i'm not sure what the problem is. There doesn't seem to be any user lists under the want to read button?
https://openlibrary.org/books/OL1402526M/The_kitchen_god's_wife
Am I looking in the wrong place?

<img width="513" alt="Screen Shot 2021-01-10 at 3 19 13 PM" src="https://user-images.githubusercontent.com/148752/104138147-33b9b200-5357-11eb-8e3b-1b056f3ecbcf.png">

**Comment by mekarpeles** [comment] 2021-02-07 01:59
It used to be the case that below the lists widget was a section of your lists which contained this book.

We don't want the list widget expanded; these are two different components.

**Comment by jdlrobson** [comment] 2021-02-07 03:13
What is"the list widget" in respect to [our DPL](https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library) ? 
Seems like we need to get a shared vocabulary on this one before revisiting this task.

I think if there is a problem with the current implementation the best course of action is to revert the patch.

**Comment by prakashaditya369** [comment] 2021-02-07 08:23
I think I got it wrong. Instead of bringing all the lists out. It should display the lists, in which book is already added, beneath the `Want To Read` button. Am I right?

**Comment by mekarpeles** [comment] 2021-02-07 13:02
@prakashaditya369 no problem, we're working through it and learning together. :)

Everyone's efforts have been in good faith and are appreciated. We have time to iron them out.

Your updated interpretation is more correct -- 
> It should display the lists in which the book is already added beneath the `Want to Read` button
**and** also it should only show the logged in patron's lists. 

## Background

Our Books pages used to look like this, where there was a List button and then a list of **all** Lists that this book was on:
![web archive org_web_20181202121632_https___openlibrary org_books_OL3412222M_The_wealth_of_networks](https://user-images.githubusercontent.com/978325/107147048-b86d0100-6900-11eb-8a80-f17594411cc8.png)

When we redesigned the page, we added a new section below the fold **which we want to keep** called "Lists containing this Book":
![openlibrary org_works_OL4899356W_A_question_of_physics_edition=questionofphysic00buck](https://user-images.githubusercontent.com/978325/107146956-34b31480-6900-11eb-9016-569e49212ce2.png)

Currently, when a patron adds a book to one of their Lists... the list item/link disappears from the List Widget dropdown. The only way for a patron to manage their list is to scroll all the way down and click the `[x]` on the appropriate list, to remove the book from this list. Furthermore, this requires a page refresh (for it to even show up in this section)
![openlibrary org_works_OL4899356W_A_question_of_physics_edition=questionofphysic00buck](https://user-images.githubusercontent.com/978325/107146956-34b31480-6900-11eb-9016-569e49212ce2.png)

## What we want

1. We want to keep the List Widget (`Want to Read` button) exactly as it was:

![web archive org_web_20181202121632_https___openlibrary org_books_OL3412222M_The_wealth_of_networks](https://user-images.githubusercontent.com/978325/107147048-b86d0100-6900-11eb-8a80-f17594411cc8.png)

2. We want to keep the "Lists containing this Book" section exactly where it is, below the fold:
![openlibrary org_works_OL4899356W_A_question_of_physics_edition=questionofphysic00buck](https://user-images.githubusercontent.com/978325/107146956-34b31480-6900-11eb-9016-569e49212ce2.png)

3. We want to **re**-introduce the component (below the `Want to Read` button) and design it exactly as @prakashaditya369  says -- it should "display ~the~ [specifically the patron's] lists in which the book is already added", with `[x]`s so the patron can easily remove the book from their list(s)

**Comment by Yashs911** [comment] 2021-02-07 15:30
@mekarpeles 
We also need to add padding to `My Reading lists:`, `Use this Work`, and `Create a new list`
![image](https://user-images.githubusercontent.com/64412143/107151151-19d7b300-6987-11eb-9037-57d07e4dc1e2.png)

**Comment by jdlrobson** [comment] 2021-02-07 15:42
Perhaps #4480 could be merged into the requirements here before taking this on.

Can we use Vue for this new component?

**Closed** 2021-04-27 21:30 UTC
Labels: Affects: Experience, Lead: @tabshaikh, Priority: 3, Theme: Lists, Type: Feature Request
