### ISSUE TITLE
State of the REST API for upload

### ISSUE THREAD

**Issue by JbIPS** [internetarchive/openlibrary#9047] opened 2024-04-08 17:51 UTC
### Question
Which REST API should I use for book data upload?

### Additional context
The [wiki](https://github.com/internetarchive/openlibrary/wiki/Endpoints#creating-works) points to 
```
POST https://openlibrary.org/api/new.json
```
but the OpenLibrary python client seems to use
```
url = self.base_url + '/books/add'
```
and the wiki is...well not very insightful:
>   How to upload
>
>    - Create an archive.org account: https://archive.org/account/signup
>    - FTP the files to catalog-upload.archive.org using the username (most likely your email address) and password you just created. This doesn't seem to be working right now.
>    - Contact us and let us know if you have uploaded something.

For context, I'm looking to help a FOSS app [OpenReads](https://github.com/mateusz-bak/openreads) to upload user-written description when the book doesn't exist in OL (see https://github.com/mateusz-bak/openreads/issues/85)

### Issue resolution criteria
A clear wiki entry/webpage/REST API schema for data upload

**Comment by scottbarnes** [comment] 2024-05-06 04:40
@JbIPS, sorry for the horrifically late reply, and I'm sorry for the poor documentation around the APIs.

To some extent, it depends a bit on what you want to do. If you'd like control over the specific fields, the API located at `/api/import` may be the best. That's documented (twice apparently...) [here](https://github.com/internetarchive/openlibrary/wiki/Endpoints#data-import) and [here](https://github.com/internetarchive/openlibrary/wiki/Developer's-Guide-to-Data-Importing#importing-json), with the latter being perhaps a bit more complete. I'll look at trying to consolidate these pages, as I didn't know that endpoint page existed.

If you're using Python, the [openlibrary-client](https://github.com/internetarchive/openlibrary/wiki/Developer's-Guide-to-Data-Importing#using-openlibrary-client-1) directions may also be useful.

`/api/import` will require a bot account, though that's not an especially hard hurdle to overcome. If you're still interested in this, do you have any ideas how authentication might be handled? Are you thinking of having one account that would simply update descriptions on behalf (whatever that means) of OpenReads patrons?

Are you the [Internet Archive Slack](https://openlibrary.org/volunteer)?

**Comment by scottbarnes** [comment] 2024-05-06 13:29
@JbIPS , I realize I should have mentioned if you start experimenting in the [local development environment](https://github.com/internetarchive/openlibrary/tree/master/docker#welcome-to-the-docker-installation-guide-for-open-library-developers), the default `openlibrary@example.com` account will work. That may be the best way to start, and will make it easier to get the bot account approved because you'll be able to determine exactly what you want to do, and you'll be able to experiment against the local development environment rather than the production data.

Also, if you know which `Edition` or `Work` you want to modify, the [openlibrary-client](https://github.com/internetarchive/openlibrary-client) (this link is different from the previous openlibrary-client link, and is about using it for more than just imports) is probably the way to go, though that assumes you're using Python.

There's also [this client in C#](https://github.com/Luca3317/OpenLibrary.NET?tab=readme-ov-file). Between that and the Open Library client, hopefully you get a good sense of what to do if you're using another language.

Both of these are mainly working with the the JSON endpoints, and you can see how saving is done [here](https://github.com/internetarchive/openlibrary-client/blob/940ac24e47bb1ed3e793fc4afcfe721cc0a2061a/olclient/openlibrary.py#L282-L287).

`/api/import` is meant for things that may not be in Open Library, and not all fields will be updated via that API, so depending on how you plan or want to do things, I realized that API not be the great. But if you're working in Python and know the `Edition` or `Work` you want to modify, `openlibrary-client` makes it really easy and there are [examples](https://github.com/internetarchive/openlibrary-client/tree/master?tab=readme-ov-file#usage) on in the `openlibrary-client` repository.

**Comment by JbIPS** [comment] 2024-05-06 13:37
Thank you for the advise. I tried to play with the development docker earlier but got `401` on `/api/import/` with the default account (I think it's `openlibrary@example.com`). Maybe I missed something in the cookie...

My use case, at first, is to create a book entity if it does not already exist in OL, so Edition/Work modification won't be enough. The android app is in Flutter, so it will be a JS implementation, maybe it will be an opportunity to do a JS client :blush:.

I'll take a look at the bot repository, some seems to be a good start for my usecase.

**Comment by scottbarnes** [comment] 2024-05-13 14:58
Any luck, @JbIPS? I can try to reproduce the error if you share a bit more about what you tried, if it's still not working.

**Comment by JbIPS** [comment] 2024-05-21 15:27
I hit a rough patch but I think I finally got the hang of it!

A minimal import request in Node.js
```nodejs
import { request } from "undici";

// First, login
const { headers } = await request(
  `${INSTANCE_URL}/account/login?username=openlibrary@example.com&password=admin123`,
  { method: "POST" },
);

// Get auth cookie
const cookie = headers["set-cookie"].find((c) => c.startsWith("session="));

// Import a book
const res = await request(
  "https://8080-internetarc-openlibrary-tyfnhypx0ux.ws-eu114.gitpod.io/api/import",
  {
    method: "POST",
    headers: {
      cookie: cookie,
    },
    body: JSON.stringify({
      title: "Test import",
      source_records: ["api"],
      authors: [{ name: "Jb" }],
      publishers: ["node"],
      publish_date: "2024",
      isbn_13: ["1234567890"],
    }),
  },
);

console.log(await res.body.text());
```
outputs
```json
{"success": true, "edition": {"key": "/books/OL5M", "status": "matched"}, "work": {"key": "/works/OL1W", "status": "matched"}}
```
And after a moment (maybe a batch needs to trigger?), I can search and find
![image](https://github.com/internetarchive/openlibrary/assets/2248473/86ccd54b-8a02-403a-b767-2722d51aa591)

Now I'll look deeper on the data mapping to have a cleaner import. If you have any tips/suggestions/warning, I'll be glad to get advise :smiley:

**Comment by JbIPS** [comment] 2024-05-21 20:56
Thank you, I was already using the `import.schema.json` but the other ones will be useful!

What are the next steps? I was thinking:
- [ ] Creating an [OpenAPI](https://www.openapis.org/) spec for the REST API, so everyone could use it and complete it
- [ ] Creating a NodeJS client lib (which will follow the OpenAPI specs)

From that, any project could easily use the API in their JS project (including OpenReads) and they will be responsible for creating the valid credentials to create books for their users.

Is that right? Did I miss something?

**Comment by scottbarnes** [comment] 2024-05-22 18:56
Adding the import API to the (admittedly quite limited) OpenAPI integration on Open Library could be helpful, especially if you were able to create a script to read the spec from the schema in Open Library client and generate the appropriate OpenAPI spec.

You may have seen this already, but here's the PR that added that support: https://github.com/internetarchive/openlibrary/pull/6018, and that has a link to the OpenAPI spec here: https://github.com/internetarchive/openlibrary/blob/master/static/openapi.json. There is also this, if you've not seen it: https://openlibrary.org/swagger/docs#/

All of this is getting outside of the scope of the original question, though, so I will close this particular issue as resolved, but please feel free to open a new issue if you have additional questions. Please also consider checking out the Slack if you've not already done).

**Closed by scottbarnes** 2024-05-22 18:56 UTC
Labels: Priority: 3, Affects: Documentation, Needs: Community Discussion, Type: Question, Needs: Response, Lead: @scottbarnes
