### ISSUE TITLE
line up titles with their sub-content

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#5099] opened 2021-04-26 16:28 UTC
Problem:
Titles don't start at the top of columns. It's kind of unreadable
![image](https://user-images.githubusercontent.com/55302685/116117918-a2eeb400-a671-11eb-814e-30e1a7363229.png)

Solution:
move titles to top of column

**Comment by lephemere** [comment] 2021-04-26 17:20
Duplicate of #4787

**Closed** 2021-04-26 20:53 UTC
Labels: Needs: Lead, Needs: Triage, Type: Bug
