### ISSUE TITLE
Library Explorer: Autocomplete + jump directly to a Classification / shelf

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4320] opened 2020-12-22 01:54 UTC

**Comment by tallforasmurf** [comment] 2020-12-22 03:09
Key here is doing it while staying in the virtual UI. Need a drop-down of Dewey/LoC categories perhaps?

**Comment by BrittanyBunk** [comment] 2021-02-01 15:26
what does this even look like? I don't get it - however, it's not a priority for me to understand, as I"m not going to be working on it.

**Comment by cdrini** [comment] 2023-11-20 16:18
Duplicate of #4356

**Closed by cdrini** 2023-11-20 16:18 UTC
Labels: Priority: 2, Lead: @cdrini, Theme: Library Explorer
