### ISSUE TITLE
Voided work page throws an error

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#3564] opened 2020-07-10 02:51 UTC
After moving the last edition to a different work, the voided work page throws an error

### Relevant url?
* https://openlibrary.org/works/OL10667890W/Sofia_Petrovna and
* https://openlibrary.org/works/OL6570951W/Best_American_Short_Stories_1972?edition=bestamericanshor1972mart

```
<type 'exceptions.AttributeError'> at /works/OL6570951W
'url'
```

### Evidence / Screenshot (if possible)
```
L: 195. $:_("This edition doesn't have a description yet. Can you <b><a href='%(url)s'>add one</a></b>?", url=edition.url('/edit')+"#about/about")
```

May be a redirect edition?

### Steps to Reproduce
Go to ... https://openlibrary.org/works/OL6570951W/Best_American_Short_Stories_1972?edition=bestamericanshor1972mart&debug=true

### Related files
file: openlibrary/templates/type/work/view.html

**Comment by seabelis** [comment] 2020-07-10 10:04
I've also documented this issue in #3561.

**Comment by dcapillae** [comment] 2020-07-11 17:03
I had noticed this bug too. It's a little annoying when you're working on moving editions to the main work and redirecting works. It could lead to some unwanted results, such as empty or misdirected work pages.

**Comment by LeadSongDog** [comment] 2020-07-11 17:48
It’s not a perfect answer, but probably the work record should, at the time it is voided, be redirected to the work which is newly linked to the last edition

**Comment by tfmorris** [comment] 2020-07-11 17:59
> probably the work record should, at the time it is voided, be redirected to the work which is newly linked to the last edition

Only if the two works are equivalent/duplicates. If the newly emptied work was a conflation of multiple works, it should just be deleted.

**Comment by LeadSongDog** [comment] 2020-07-11 18:17
So a user dialog is needed?

**Comment by seabelis** [comment] 2020-07-12 08:01
If conflated because it contained volumes of a series, I will frequently leave links to the individual volumes. I think everyone is in agreement that it should not simply break.

**Comment by mekarpeles** [comment] 2020-07-17 02:40
I think my recent issue #3592 is a duplicate of this; going to close 3592 and copy its example here.

**Comment by spamspambaconspam** [comment] 2020-07-17 13:15
I came here to open a ticket for this issue, but found this one is already open.
I had prepared an example of works that threw the error versus did not, so I'm adding it here, in case it helps.

https://openlibrary.org/works/OL6570950W
https://openlibrary.org/works/OL19612030W
https://openlibrary.org/works/OL6770962W

![image](https://user-images.githubusercontent.com/9367321/87789913-c5fc5580-c80d-11ea-85bd-811fd2d021a4.png)

**Comment by hornc** [comment] 2020-07-20 02:14
This relates to #2727 also. The current merged UI expects editions to exist, and fails with the reported error if not.

**Closed** 2020-08-31 17:01 UTC
Labels: Affects: UI, Lead: @mekarpeles, Priority: 2, Type: Bug, Type: Subtask of Epic
