### ISSUE TITLE
Author search shows edition count not work count

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9558] opened 2024-07-11 16:14 UTC
### Problem

Says 13 books when the author has 3 works and 13 editions.

#### Evidence / Screenshot
![image](https://github.com/internetarchive/openlibrary/assets/921217/8a6405da-7710-4417-aac0-7b46f56783bb)
![image](https://github.com/internetarchive/openlibrary/assets/921217/f3c3ee0a-f84b-47c8-9931-44857a49261d)

#### Relevant URL(s)
https://openlibrary.org/search/authors?q=Christian%20B.%20Long
https://internetarchive.slack.com/archives/C0ETZV72L/p1720709925862829

#### Stakeholders

@cdrini 
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by Souvik-Cyclic** [comment] 2024-07-11 17:30
@RayBB I would like to fix this, assign this to me.

**Comment by RayBB** [comment] 2024-07-11 18:24
@Souvik-Cyclic you can look into this a bit, but we should wait until this is triaged by the staff early next week before spending too much time on it.

**Comment by Souvik-Cyclic** [comment] 2024-07-11 18:28
@RayBB Got it.

**Comment by tfmorris** [comment] 2024-07-15 16:13
This was broken for several weeks, but appears to have been fixed some time in the last few days.

**Comment by RayBB** [comment] 2024-07-15 16:16
Although it is fixed for the example I gave in the original post it seems to still be an issue for some authors like: https://openlibrary.org/search/authors?q=chris+wiggins&mode=everything

**Comment by nymishkash** [comment] 2024-07-16 05:27
@RayBB I would like to fix this issue. Could you assign this to me?

**Comment by RayBB** [comment] 2024-07-16 07:32
@nymishkash if you would like to contribute you can look into and post your findings here but @Souvik-Cyclic is currently assigned to the issue.

Feel free to pick another issue that isn't assigned yet.

**Comment by Souvik-Cyclic** [comment] 2024-07-21 18:45
Can you guide me, how should I proceed ? I have understood the issue. @RayBB @tfmorris

**Comment by RayBB** [comment] 2024-07-22 08:44
@cdrini can you chime in? I'm not quite sure how to look into this one further.

**Comment by tfmorris** [comment] 2024-07-25 22:56
https://openlibrary.org/search/authors.json?q=chris+wiggins shows a `work_count` of 8 being returned for the first hit (when it's really 2 works of 3 editions each), so you can eliminate anything in the front end. It's either a problem with the Solr updater or the API.

Also, https://openlibrary.org/authors/OL3874685A/works.json shows 2 works, so the underlying data is correct.

Since this only got broken in the last couple of months, it'll be something that was changed recently.

**Comment by cdrini** [comment] 2024-07-29 17:03
Ah it looks like this is caused by #8191 . By adding the author fields to the edition records in solr, this is incorrectly counting during updating. This did happen in the last couple of months as well.

The fix will be here: https://github.com/internetarchive/openlibrary/blob/82884bbff0ba17ea308f99c73c2a23c47d3db4d8/openlibrary/solr/updater/author.py#L15-L29

Add a new parameter: `('fq', 'type:work'),`.

**Comment by Souvik-Cyclic** [comment] 2024-07-29 17:46
Thank you so much, @cdrini, for figuring this out. We had been struggling with it for quite a while.

**Comment by tfmorris** [comment] 2024-07-29 21:33
> Ah it looks like this is caused by https://github.com/internetarchive/openlibrary/pull/8191 .

But how could an unmerged draft PR be affecting production data?

**Comment by cdrini** [comment] 2024-07-31 18:32
Our solr is in a bad state :( See https://github.com/internetarchive/openlibrary/issues/8234#issuecomment-2145119643 . Moving solr from our staging server to the production server failed, so prod has been hooked up to the staging copy. The authors PR was part of the staging solr to test, and it passed my testing. My plan was to merge it in when the deploy finished but it's all a tangle I'll need to resolve later, once I determine a new strategy for doing the move from the staging solr to the prod solr.

**Closed** 2024-08-30 20:23 UTC
Labels: Type: Bug, Theme: Search, Priority: 3, Module: Authors, Lead: @cdrini
