### ISSUE TITLE
stats: Unique Visitors & Borrow Graphs Not Loading

### ISSUE THREAD

**Issue by dwaipayan05** [internetarchive/openlibrary#4606] opened 2021-02-15 13:08 UTC
The Graphs of Unique Visitors & Borrows Graph are not Loading

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/53687927/107950262-7dcc2e00-6fbc-11eb-85d6-619725e7b7f6.png)

### Relevant url?
https://openlibrary.org/stats

### Steps to Reproduce

1. Go to https://openlibrary.org/stats
2. Check the Graphs

* Actual: Graph Not Displaying
* Expected: Should Display the Graphs

### Details

- **Logged in (Y/N)?**  Y
- **Browser type/version?** Chrome 88.0.4324.150
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment] 2021-02-17 19:43
Thank you! Duplicate of #3924

**Closed by mekarpeles** 2021-02-17 19:43 UTC
Labels: Needs: Lead, Needs: Triage, Type: Bug
