### ISSUE TITLE
Edition count with no records found

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1799] opened 2019-01-03 10:51 UTC
No records found is stated despite edition count of 1+

- Relevant url: https://openlibrary.org/works/OL74663W/My_life_as_a_man

### Screenshot (if possible):
![fullscreen capture 132019 114455 am bmp](https://user-images.githubusercontent.com/17739465/50634034-9f3d3d80-0f4d-11e9-9e5f-40d9ceab50b7.jpg)

### Expectation
Should see list of editions when over 0.

## Details
- Browser type/version? Version 71.0.3578.98 (Official Build) (64-bit)
- Operating system? Windows 7 Pro

**Comment by seabelis** [comment] 2019-01-03 10:55
Refreshing the page seems to resolve.

**Comment by jdlrobson** [comment] 2019-01-03 16:18
@mekarpeles sounds like caching problem?
I too cannot reproduce.

**Comment by jdlrobson** [comment] 2019-01-08 03:59
I'm seeing 11 editions now..
https://openlibrary.org/works/OL74663W/My_life_as_a_man

Let's keep an eye on this and reopen if we see it again as there's not much we can do here. cc @mekarpeles

**Comment by seabelis** [comment] 2019-09-16 18:03
Reopening since two other users reported experiencing this yesterday.

**Comment by seabelis** [comment] 2019-10-29 18:13
Seems resolved at least atm.

**Comment by tfmorris** [comment] 2019-10-29 19:26
If the system gets an error, it should inform the user to retry, not show them bad results. There's something broken in the search code that provides the results for this page that's not correctly propagating the error to the client.

A similar situation can happen on author pages where it shows 0 works (with no error) and then will show the correct data when refreshed. I saw this several times yesterday.

We need to figure out where these errors are getting swallowed.

**Comment by cdrini** [comment] 2019-11-12 04:42
Yep; I've observed this as well and it tends to disappear after ~15min. This makes me think it's solr related.

**Comment by guyjeangilles** [comment] 2019-11-22 00:40
@cdrini Do you think the solution to #2628 will fix this problem? Has anyone seen this since Novemeber 15th when #2628 was closed?

**Comment by cdrini** [comment] 2019-11-25 12:23
@jdlrobson No, I don't think that affected this. I think it's a latency issue with solr results, so it'll likely be fixed by Solr 8.1 / #2246 .

**Comment by mekarpeles** [comment] 2019-12-13 00:43
:+1: on solr latency; closing.

**Closed by mekarpeles** 2019-12-13 00:43 UTC
Labels: Needs: Assessment, Priority 3: Normal, State: Backlogged, Type: Bug
