### ISSUE TITLE
Author page failing to render due to AttributeError (data problem)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1845] opened 2019-01-24 19:56 UTC
## Description

Author page failing to render because something is wrong with rendering their book list(s) -- suspecting one of their books erroneously has multiple `authors` instead of an `author` field (?)

https://openlibrary.org/authors/OL6598895A/Horst_Kurnitzky?debug=true

## Evidence 

https://openlibrary.org/authors/OL6598895A/Horst_Kurnitzky?debug=true

## Expectation

author page should be correctly displaying

## Proposal & Constraints

We should fix the macro template `openlibrary/macros/SearchResultsWork.html` (not the author metadata record) so it's robust against the problem we're facing

## Stakeholders

@mekarpeles, @JeffKaplan

**Comment by tfmorris** [comment] 2019-01-25 00:01
The second author listed: https://openlibrary.org/authors/OL7169223A.json
for the work: https://openlibrary.org/works/OL16802242W.json
is corrupt and needs to be deleted.

**Comment by tfmorris** [comment] 2019-01-25 02:49
Oops, just noticed your proposed fix buried in all the boilerplate. Sorry I destroyed your test case!

**Comment by guyjeangilles** [comment] 2019-11-04 23:37
@mekarpeles @tfmorris @JeffKaplan Is there another test case to confirm that this is still an issue?

**Comment by tfmorris** [comment] 2019-11-24 19:57
I've [reverted my edit](https://openlibrary.org/works/OL16802242W/Chollima_Korea?m=history) and broken the [author page](https://openlibrary.org/authors/OL6598895A/Horst_Kurnitzky?page=2) again so that the code can be fixed properly.

**Comment by SouthGoingZax** [comment] 2020-10-25 16:40
This looks like the same root cause that breaks several other things on the site (a few more are listed in #3695), which is an assumption that all author entities will have a 'name' field.  It seems like we should re-scope one of these issues to include a checklist of places where that assumption is made so someone can work through them all and then close the other issue as a dupe of the larger one.

**Closed** 2020-11-20 00:57 UTC
Labels: Affects: UI, Lead: @mekarpeles, Priority: 3, Type: Bug, authors
