### ISSUE TITLE
/search/subjects results report inaccurate count of books having subject

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#816] opened 2018-02-28 20:55 UTC
cc @JeffKaplan

**Comment by LeadSongDog** [comment] 2018-03-01 03:35
Possibly a symptom of #789 ?

**Comment by hornc** [comment] 2020-01-14 00:00
I think this relates to #2249 which was fixed by #2684 and caused by the ebook filtering being unintentionally added to the results

**Comment by hornc** [comment] 2020-01-14 00:02
possible example: https://openlibrary.org/subjects/museums.json

shows `"ebook_count": 5304` and `"work_count": 5304` which seems suspicious

**Comment by hornc** [comment] 2020-02-10 07:01
This seems to be resolved on the json API which respects ebook filtering correctly:

https://openlibrary.org/subjects/herpetology.json?has_fulltext=true&limit=100
shows 28 results
https://openlibrary.org/subjects/herpetology.json?has_fulltext=false&limit=100
shows 85 

The front-end should be covered by #3002

**Closed by hornc** 2020-02-10 07:01 UTC
Labels: Affects: Data, CH: subjects, Data Cleanup, Needs: Investigation, Priority: 3, State: Backlogged, Theme: Search, Type: Bug
