### ISSUE TITLE
Find People email search in OL admin interface is case-sensitive and should not be

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#383] opened 2016-11-20 16:30 UTC

**Comment by guyjeangilles** [comment] 2019-10-22 00:03
@mekarpeles @jessamynwest Is this still an issue? If so, @mekarpeles are you willing to be assignee for this issue?

I've added labels given the issue's context. Let me know if your thoughts.

**Comment by jessamynwest** [comment] 2019-10-22 01:11
I no longer have access to the admin interface,sorry to not be able to help.

**Comment by cdrini** [comment] 2019-11-07 21:12
I can't reproduce this; I tried searching for an all lower-case email in upper case and it matched, and I tried searching for a mixed case email in lower case and it also matched; so closing.

**Closed by cdrini** 2019-11-07 21:12 UTC
Labels: Affects: Admin/Maintenance, Needs: Assessment, State: Backlogged, Type: Bug
