### ISSUE TITLE
Lists-related pages throwing "AttributeError: 'module' object has no attribute 'Seed' (falling back to default template)"

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4019] opened 2020-11-05 00:59 UTC
Caused by https://github.com/internetarchive/openlibrary/releases/tag/deploy-2020-11-04 .

`/opt/openlibrary/deploys/openlibrary/824a904/openlibrary/templates/recentchanges/lists/comment.html: error in processing template: AttributeError: 'module' object has no attribute 'Seed' (falling back to default template)`

Lots of occurrences in sentry: https://sentry.archive.org/sentry/ol-web/issues/10323/?environment=production

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/98184251-ea249500-1ed7-11eb-9362-c54580ad530d.png)

### Relevant url?
e.g:
- https://openlibrary.org/people/ScarTissue/lists
- https://openlibrary.org/people/ScarTissue/lists/OL139466L/Test_Sep_2019

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF82
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cclauss @mekarpeles

**Comment by cclauss** [comment] 2020-11-05 01:01
Is this a dupe of #4015?
Will it be fixed but #4018?

**Comment by cdrini** [comment] 2020-11-05 01:03
This looks like a different error, and on py2. Not sure if that will fix it?

**Comment by cdrini** [comment] 2020-11-05 01:09
Maybe this?

![image](https://user-images.githubusercontent.com/6251786/98184987-b0ed2480-1ed9-11eb-8d34-109c2695c7f9.png)

https://github.com/internetarchive/openlibrary/compare/deploy-2020-10-19...deploy-2020-11-04#diff-9a03e714bd068dae76b2a99fdde09aff001fd7c547b11b0ea016079d3a567c8eL22

**Comment by cdrini** [comment] 2020-11-05 01:12
Tested on dev; bringing that back fixed it!

**Closed** 2020-11-05 01:32 UTC
Labels: Priority: 1, Type: Bug
