### ISSUE TITLE
/isbn/{isbn} endpoint without logged in user gives an error

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1783] opened 2018-12-30 04:52 UTC
## Description
Visiting a URL like
https://openlibrary.org/isbn/0062225243?debug=true
without being logged in gives an error:
<type 'exceptions.AttributeError'> at /isbn/0062225243
'NoneType' object has no attribute 'key'

Relevant code from the stack trace:
https://github.com/internetarchive/openlibrary/blob/6f9995f/openlibrary/catalog/add_book/__init__.py#L444-L451

## Evidence 
> What does the experience look like today? What are the symptoms?

> Relevant url:

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

If the book is not present on OL, it should be auto-imported as ... some user?

## Details
> What page(s) are impacted?

 `https://openlibrary.org/isbn/...`

> Logged in (Y/N)?

N

## Proposal
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

Unsure. It is valid to hit this endpoint without being logged in, not sure what value should be passed as a default user in this case.

## Constraints
> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

## Stakeholders
> @ tag stakeholders of this bug / feature
@mekarpeles

**Comment by mekarpeles** [comment] 2019-03-08 02:19
Duplicate of #1461

**Closed by mekarpeles** 2019-03-08 02:19 UTC
Labels: amazon, public-apis
