### ISSUE TITLE
Lists in list dropper not populating correctly for works

### ISSUE THREAD

**Issue by agmckee** [internetarchive/openlibrary#6897] opened 2022-08-19 13:02 UTC
Starting today I noticed that the list widget doesn't render correctly on some edition pages. At first I thought it was just an isolated issue with a specific book edition and assumed there must be something wrong with that edition, now I've observed it on a few different pages.

### Evidence / Screenshot (if possible)
![screenshot-of-list-widget-issue](https://user-images.githubusercontent.com/722096/185623121-b22d4457-afcb-44e7-be84-d852d06ae834.png)

### Relevant url?
[https://openlibrary.org/books/OL18347637M/](https://openlibrary.org/books/OL18347637M/)

Also:
[https://openlibrary.org/books/OL16869993M/](https://openlibrary.org/books/OL16869993M/)

### Steps to Reproduce
1. Go to the above linked relevant URL
2. Observe that the widget doesn't load correctly
3. Click on the widget and no lists are shown

* Actual: The widget doesn't show any of my lists
* Expected: The widget shows my lists

### Details

- **Logged in (Y/N)?** Yes
- **Browser type/version?** Firefox 91.12.0esr
- **Operating system?** Debian 11
- **Environment (prod/dev/local)?** prod

**Comment by agmckee** [comment] 2022-08-19 13:07
I found another example at https://openlibrary.org/books/OL16819242M and something it has in common with one of the other examples is that it was imported without an author being set.

**Comment by bicolino34** [comment] 2022-08-19 13:38
As far as I know, it is because this is orphaned editions (without assigned work). It should be enough to edit them once, and work will be automatically created for them.

**Comment by muditjuneja** [comment] 2022-08-22 11:32
@bicolino34  Should it be fixed in the code? Like hiding the entire widget if this is the case? Because after editing them with work, the whole view changes, and Add to list button is visible under the drop-down.

**Comment by bicolino34** [comment] 2022-08-22 13:59
@muditjuneja I don't know if this is a good decision. Better ask @cdrini or @mekarpeles

**Comment by muditjuneja** [comment] 2022-08-22 17:43
@jimchamp @mekarpeles let me know, I can give it a try if needed.

**Comment by mekarpeles** [comment] 2022-08-22 17:46
I am not able to reproduce this issue -- is it possible it has since been fixed by @jimchamp ?

**Comment by mekarpeles** [comment] 2022-08-22 17:47
@muditjuneja if you're able to reproduce this issue, please do give it a try and we're happy to answer questions!

**Comment by muditjuneja** [comment] 2022-08-22 17:50
@mekarpeles Visit this URL : https://openlibrary.org/books/OL16819242M/Turncoat_a_parody_of_the_tragedy_of_Athelstan._In_one_act
<img width="1725" alt="Screenshot 2022-08-22 at 11 19 22 PM" src="https://user-images.githubusercontent.com/15162221/185986370-dc6d000d-82de-4739-a7af-53b18d3e1370.png">

You will see that the lists are not being loaded (bcoz this item don't have work)

**Comment by mekarpeles** [comment] 2022-08-22 19:47
Awesome, thanks for sharing this link! @jimchamp and I can confirm that these are happening specifically to orphaned editions. We can investigate from here.

**Comment by jimchamp** [comment] 2022-08-23 01:26
The list widget is expected to look this way on orphaned edition pages.  The issue is that none of a patron's lists are present in the dropper on orphaned editions pages.  This may be related to a breaking change to list widgets that occurred some time ago (PR: #6159).

Before #6159 was merged, lists displayed in the drop-down would be updated when the "Use this Work" checkbox was toggled:
![use_this_work_checkbox](https://user-images.githubusercontent.com/28732543/186046500-6f2508b9-cf41-4af0-8541-40e227cc4428.png)
When clicked, only lists that didn't contain the book's work OLID would be present in the dropper (more clearly, lists not containing the work were listed in the dropper).  The lists would update to lists not containing the edition if the checkbox was unchecked.

Today, the view does not update when the checkbox is toggled.  One can still choose to add a work or edition to a list by using the checkbox, though.

I noticed that a can add an orphaned edition to a new list (the current record is added to any newly created list).  When added, I noticed that the new list didn't appear in the `#already-lists` container (this is directly below the dropper, and provides a way for people to remove an item from a list).

All this is to say that the underlying list functionality is working properly, but the view is not initially being populated correctly nor updated properly on orphaned editions pages.

**Comment by agmckee** [comment] 2022-08-23 21:22
Updated the title to reflect what we've already learned through this discussion, and thank you to all who've participated so far :)

**Comment by jimchamp** [comment] 2023-04-28 20:34
I think that, at its core, this issue is that one cannot add a work to a list via the UI, as the UI doesn't properly update when "Use this work" is selected.

@DebbieSan, not sure if you're aware of this.  I'll fix this while we're improving on the lists dropper.

**Comment by DebbieSan** [comment] 2023-04-28 21:12
I noticed that the " use this work" box wasn't necessarily working at times. Is this what you are referring to? 

Thank you for all of this, I really appreciate it as I was blocked for a bit.

**Comment by jimchamp** [comment] 2023-05-05 21:35
@DebbieSan sorry for the delay!  That's exactly what I mean.  I'm pretty sure that I broke this when I worked on adding "Want to Read" buttons to search results.

**Closed** 2023-09-21 22:25 UTC
Labels: Type: Bug, Theme: Lists, Priority: 3, Lead: @jimchamp
