### ISSUE TITLE
Amazon.* identifiers do not save when entered

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6300] opened 2022-03-16 13:29 UTC
Identifiers for Abebooks and non .com Amazon identifiers do not save values when entered.
### Relevant url?

Any edit form, https://openlibrary.org/books/OL26373880M/Cats_on_Instagram/edit 
### Steps to Reproduce

1. Go to ...Identifiers section
2. Do ...add one of the identifiers mentioned above

* Actual: no value entered
* Expected: identifier should be saved

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Since identifiers for amazon sites are the same, maybe just remove the non .com options?

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by cdrini** [comment] 2022-04-04 17:57
Removing non.com amazon identifiers sounds good to me! I also renamed Amazon.com ID to "Amazon ID (ASIN)"

Removed the following. Note data for these is still there and needs to be migrated or removed.

```
-   label: Amazon.ca
    name: amazon.ca_asin
    notes: ''
    url: https://www.amazon.ca/gp/product/@@@/
-   label: Amazon.de
    name: amazon.de_asin
    notes: ''
    url: https://www.amazon.de/gp/product/@@@/
-   label: Amazon.it
    name: amazon.it_asin
    notes: ''
    url: https://www.amazon.it/gp/product/@@@/
-   label: Amazon UK
    name: amazon.co.uk_asin
    notes: ''
    url: https://www.amazon.co.uk/gp/product/@@@/
```

**Comment by cdrini** [comment] 2022-04-04 17:58
What should we do about abebooks, @seabelis ? I think the actual bug here is that these fields had `.` in the name.

**Comment by tfmorris** [comment] 2022-09-30 18:28
This has the same root cause as #7032.

**Comment by cdrini** [comment] 2023-01-05 01:43
Shifting this one to be specifically about amazon. #7032 has better info about the JS error that needs to be addressed, so closing in favour of that.

**Closed by cdrini** 2023-01-05 01:43 UTC
Labels: Type: Bug, Needs: Triage, Affects: Librarians, Lead: @cdrini
