### ISSUE TITLE
Book Widget fails for Redirects after books merged

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5046] opened 2021-04-14 17:56 UTC
When a book is merged, iframes which reference the pre-merged work show the entire open library books page rather than the widget view.

https://openlibrary.org/works/OL1063339W/How_to_win_friends_and_influence_people/widget

Should look like this:
![openlibrary org_books_OL21094918M_How_to_win_friends_and_influence_people_widget](https://user-images.githubusercontent.com/978325/114756688-dcd5c700-9d0f-11eb-8d05-349db154e385.png)

But instead redirects to the new page (not in widget view)

### Evidence / Screenshot (if possible)

https://openlibrary.org/works/OL1063339W/How_to_win_friends_and_influence_people/widget
should look like...
https://openlibrary.org/books/OL21094918M/-/widget

**Comment by STAMATIOSL** [comment] 2021-04-19 16:43
Can I take this issue?

**Comment by STAMATIOSL** [comment] 2021-04-24 12:48
The code linked with the issue is in the https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lists/widget.html ? @mekarpeles

**Comment by arimanyus** [comment] 2021-08-30 03:28
Hey @STAMATIOSL, are you looking into this?

**Comment by STAMATIOSL** [comment] 2021-08-30 10:58
@arimanyus No, you can go for it!

**Comment by pranjii** [comment] 2021-09-03 15:36
Can I do this??

**Comment by sagnik2001** [comment] 2021-12-03 18:46
Can I work on this ?

**Comment by tuminzee** [comment] 2021-12-10 21:41
> @arimanyus No, you can go for it!

Hello @arimanyus are you still working on the issue?

**Comment by ejgonzalez17** [comment] 2021-12-18 22:10
Hi , I would like to work in this Issue .

**Comment by mekarpeles** [comment] 2022-02-02 00:19
The code for the widget is here
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/code.py#L242-L262

The html is here
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/widget.html

The step to fix this:
In https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/code.py#L246 after we have the olid -- i.e. `web.ctx.site.get(olid)`, we need to check its infogami type to see if it's a `redirect`. If it is, we need to do a while loop to keep doing `web.ctx.site.get(olid)` until we no longer have a redirect. 

@arimanyus, if you're available, why don't you take a shot at it? :)

**Comment by Shofiya2003** [comment] 2022-03-07 13:13
Can I work on this issue?

**Comment by tuminzee** [comment] 2022-03-07 14:07
@arimanyus how you are doing so far. Do you need any help?
If you are occupied let me know, than I can assign this issue to @Shofiya2003

**Comment by mekarpeles** [comment] 2022-03-07 20:09
@Shofiya2003 I'd say give it a shot! I'll assign you :)

**Comment by Shofiya2003** [comment] 2022-03-08 12:08
Thanks a ton. I am starting to work on it and will get back to you if I need any help.

**Comment by Shofiya2003** [comment] 2022-03-11 00:00
Hello
I have made changes but I am having a tough opening the webpage using gitpod to check the changes. Do I need to set up the project on my local machine. I need help.

**Comment by mekarpeles** [comment] 2022-03-28 19:16
@Shofiya2003 did you have any other questions?

**Comment by mekarpeles** [comment] 2023-09-15 05:03
should be solved by #7059

**Closed** 2023-09-15 05:03 UTC
Labels: Type: Bug, Module: Merging, Priority: 3, Good First Issue, Lead: @mekarpeles, Affects: Experience, Theme: Record Merging
