### ISSUE TITLE
The menu button on the webpage can be improved

### ISSUE THREAD

**Issue by Raunakk02** [internetarchive/openlibrary#3263] opened 2020-03-25 11:56 UTC
### The Issue
The menu button on the webpage can be improved. Currently, it opens the menu when clicked for once but doesn't close the menu when clicked again and we need to explicitly click on the empty space on the webpage to close the menu.

### Webpage url
https://openlibrary.org/

### Steps to Reproduce

1. Go to the webpage.
2. Click on the menu button(The 3 horizontal lines on the top-left corner of the webpage.)

* Actual: It opens menu when clicked once but doesn't closes it when clicked again.
* Expected: It should open menu when clicked once and close it when clicked again.

### Proposal & Constraints

This issue can be fixed if we can store(in a variable say, _tapsCount) the no. of taps done on the menu button since the webpage is opened and increment its value each time the button is pressed. Lets say that the _tapsCount is initialized to '0'. Now if the value of _tapsCount after a certain no. of taps is odd then this would mean that menu is to be displayed and if its even then the menu needs to be closed. This fix will certainly improve the user experience. Also if the value of this _tapsCount becomes more than say 2 then we can update its value to 1 again so that we don't go on increasing its value to infinity(just in case).

**Comment by guyjeangilles** [comment] 2020-03-25 21:17
I can duplicate this on mobile, but not on desktop (currently you just have to hover over the menu's on/off desktop menus to open and close them).

**Comment by Raunakk02** [comment] 2020-03-26 09:20
I found this when i trying out the webpage on my phone's(android) chrome browser

**Comment by Raunakk02** [comment] 2020-03-26 09:21
I hope this helps!

**Comment by jdlrobson** [comment] 2020-03-29 16:29
Duplicate of https://github.com/internetarchive/openlibrary/issues/1708

**Closed by jdlrobson** 2020-03-29 16:29 UTC
Labels: Affects: UI, Lead: @jdlrobson, Priority: 3, Type: Bug
