### ISSUE TITLE
Author search results pages show many more works per author than there actually are

### ISSUE THREAD

**Issue by stopregionblocking** [internetarchive/openlibrary#9256] opened 2024-05-10 17:09 UTC
### Problem

Search results for authors don't always show accurate numbers of works, but recently they frequently seem to be several times higher than the actual number of works.

#### Relevant URL(s)
Sample searches:
https://openlibrary.org/search/authors?q=jeeves
https://openlibrary.org/search/authors?q=jarid
https://openlibrary.org/search/authors?q=kom%27boa
https://openlibrary.org/search/authors?q=bishara

### Reproducing the bug

1. Search for an author
2. Observe the number of works attributed on the author search result page
3. Observe the number of works attributed on the author page

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by jchefdeville** [comment] 2024-05-12 16:36
Hi
I wrote a message an "Gitter". I wanted to reproduce this issue, but I can't do it on localhost. I don't have any results

**Comment by scottbarnes** [comment] 2024-05-12 16:39
@jchefdeville, I can't speak to reproducibility, but in terms of finding results, the following may show some authors: http://localhost:8080/search/authors?q=*&mode=everything

**Comment by cdrini** [comment] 2024-09-23 15:18
This is a duplicate of #9558 . The fix for this has been merged in, but will require a full solr reindex before it takes effect. That will likely happen in ~1 month or so.

**Closed by cdrini** 2024-09-23 15:18 UTC
Labels: Type: Bug, Theme: Search, Needs: Triage, Needs: Investigation, Lead: @cdrini
