### ISSUE TITLE
i18n lines missing in messages.pot

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6844] opened 2022-08-06 17:26 UTC
There are some buttons on site that can't be i18nalized because there are no lines for them in [messages.pot](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/messages.pot)

"My books" in top navbar
![зображення](https://user-images.githubusercontent.com/58372007/183258079-d26fe12e-53ef-4e35-8368-5907a10ef6f9.png)

"Trending Books" carousel and "Trending" button in profile hamburger
![зображення](https://user-images.githubusercontent.com/58372007/183258920-5010d87f-8e79-4436-8183-c01b88a8867e.png)

Buttons "Details" and "Related Books" don't have lines in messages.pot. In Overview labels "Publish Date", "Pages" and "Previews available in:" don't have lines for them too. Please note that "Overview" and "View %s editions" buttons have corresponding lines they just haven't been translated yet in Ukrainian i18n
![зображення](https://user-images.githubusercontent.com/58372007/183259121-ecfd4931-2b91-442d-ac5e-71919bd4ea56.png)

Community reviews section, "Feedback?" button
![зображення](https://user-images.githubusercontent.com/58372007/183259387-efb414e3-4f40-44f5-b85c-69d93182524e.png)

Carousels on work page
![зображення](https://user-images.githubusercontent.com/58372007/183259411-30358e8e-bc17-41e1-8531-ec06a97d9a51.png)

"Book Details" and "Published in" labels
![зображення](https://user-images.githubusercontent.com/58372007/183259633-811272dd-9e36-4b84-8170-948e3dc0d772.png)

That's not all missing lines, I will be adding new ones when I find them.

**Comment by tfmorris** [comment] 2022-08-08 15:57
Why are developers still being allowed to introduce code which isn't internationalized?

Wouldn't it be a lot simpler to make it part of the coding standards that everything must be internationalized? And enforce that during code reviews, of course.

**Comment by cdrini** [comment] 2022-08-08 23:08
Most of these are actually correctly i18n'd in the HTML ; the .pot file just needs to be regenerated! You can do this like so:

```
docker-compose run --rm -uroot home ./scripts/i18n-messages extract
```

(See https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n ).

**Comment by agmckee** [comment] 2022-08-10 15:58
@cdrini, that script is also failing with a similar error to the one affecting copydocs.py. When not run as root it works but can't write the file due to permissions, when run as root it errors with "ModuleNotFoundError: No module named 'web'".

**Comment by cdrini** [comment] 2022-08-10 16:11
@agmckee Can you try it with setting python path? So:

```sh
docker-compose run --rm -uroot -e PYTHONPATH=. home ./scripts/i18n-messages extract
```

**Comment by agmckee** [comment] 2022-08-10 16:19
Yes, I should have mentioned that I already tried that. Same result. I've just now tried it again (just to eliminate any possibly error on my part), still same result - "No module named 'web'".

**Comment by cdrini** [comment] 2022-08-10 16:46
Oh, on unix we need `-uroot` to modify files but I don't think `-uroot` works correctly anymore :/ Can you try removing the .pot file and trying again without `-uroot`?

**Comment by cdrini** [comment] 2022-08-10 16:46
If you're on Windows it should just work without `-uroot`

**Comment by agmckee** [comment] 2022-08-10 16:56
I'm not on Windows, I'm on Debian 11. As mentioned before trying it without the `-uroot` option just results in no file being written due to permissions issues.

**Comment by cdrini** [comment] 2022-08-10 18:10
Ok; try changing the permissions for the directory:

```sh
# Set the group to be the same as the openlibrary group
sudo chown -R $UID:999 .
# Give the group write access to the files
sudo chmod g+w -R .
```

**Comment by muditjuneja** [comment] 2022-08-12 20:35
@cdrini This command works on my Mac after removing uroot. File has been generated. @agmckee  I can create a PR if you are still facing the issue.

**Comment by agmckee** [comment] 2022-08-14 09:04
@muditjuneja Please feel free to create a PR, I ran out of time to work on this issue while troubleshooting the command. @cdrini I can confirm changing the permissions worked for me.

**Comment by cdrini** [comment] 2022-08-15 19:13
Awesome, thanks folks! I'll assign this to you @muditjuneja . Please open a PR!

**Comment by muditjuneja** [comment] 2022-08-18 20:02
Hi @cdrini, I have created a PR with newly generated messages.pot file. Check here - https://github.com/internetarchive/openlibrary/pull/6893

**Closed** 2022-08-18 21:38 UTC
Labels: Type: Bug, Good First Issue, 1-off tasks, Theme: Internationalization, Priority: 2, Needs: Help, Lead: @cdrini
