### ISSUE TITLE
Delete duplicates in contributors list

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6132] opened 2022-02-10 07:27 UTC
I noticed that there are some duplicates in contributors list (reviewer and reviewers), also, there are roles in other languages which also duplicate existing roles (Typografische Gestaltung, revisão, recenzent). Finally, end of the list is not sorted by alphabet

### Steps to Reproduce

1. Go to ... editing of any book
2. Do ... open contributors roles list

### Stakeholders
@mekarpeles @jimman2003

**Comment by brierjon** [comment] 2022-02-14 16:00
Issue screenshot
![image](https://user-images.githubusercontent.com/717866/153899517-00d1f4f9-30f2-4aac-b6cc-8923d32c0485.png)

**Comment by mekarpeles** [comment] 2022-02-14 20:18
Marking this as a Librarian task for @seabelis:

This may be edited here
https://openlibrary.org/config/edition.yml?m=edit

**Comment by seabelis** [comment] 2022-05-05 09:02
This would probably be better with a blank field for the role title rather than a fixed list. Some of these seem unnecessary, but I'm hesitant to delete them without knowing the reason(s) they were added in the first place.

**Comment by brierjon** [comment] 2022-05-11 14:45
@seabelis Are you suggesting rolling back to free text? I would suggest checking which works use each term claimed to be "unnecessary" and try to identify why the term was added. It may indicate 1. misunderstanding for data entry 2. an overlooked use case. 

Could you create a list of items considered "unnecessary" and associated edition examples that could be evaluated to why those labels are being used?

What is the distribution of each of the title uses and their associated works type/subject? Is there an edge case where the contributor field is being used instead of another field? 

I would like to keep a fixed list and add definitions and add synonyms with a clear workflow to add missing titles (with description of the title and why it should be added). Keeping a fixed list ensures consistency for entry, easier translation with less fragmentation, and enables unique IDs, definitions, and linking synonyms. We should be working toward structured data instead of free text as it helps to build more semantically linkable metadata in the long term.

**Comment by seabelis** [comment] 2022-05-27 10:47
@brierjon This relates to edition-level contributors only. I don't have a way of tracing back the origin of each label to determine why it was added or when.

Duplicate of #2227.

**Comment by hornc** [comment] 2022-07-01 11:56
@seabelis No, I don't think I did this on purpose at all -- sorry. I don't remember doing this, I may have fumbled something on my phone interface when reviewing notifications some time ago. I'll close it.

**Closed by hornc** 2022-07-01 11:56 UTC
Labels: Type: Bug, Priority: 3, Lead: @seabelis
