### ISSUE TITLE
Search for translations in different languages to the original work

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#1432] opened 2018-10-25 09:40 UTC
Hi,

When we search for a title in Open Library, the search results refer to works published with that title in the original language. This is inconvenient when we search for an edition published in a language different from the original work (translation).

For example, if someone searches for a Spanish edition of "The Human Condition" by Hannah Arendt, he would write "La condición humana" (Spanish title) in the Open Library search box. This search does not offer any results related to the book "The Human Condition" by Hannah Arendt, only to works with the original title "La condición humana" published by other authors.

The Open Library guidelines say that the "work" data should reflect the original language and we should connect editions and translations to the work [1]. I think that is correct, but then we can not satisfactorily search for translations in other languages of an original work without knowing the title of the original work and the language. This is not desirable.

A Spanish reader will not usually look for "The Human Condition" to find Hannah Arendt's book. He would write "La condición humana" in the Open Library search box and expect that Arendt's book would appear in the top positions of search results. However, using the Open Library search box, Arendt's book does not even appear in the search results.

This inconvenience is common to all languages, not only in Spanish. The same would happen if someone tried to find a translation in English of an original work published in Spanish. The search engine does not offer results of editions or translations, only works with the original title.

Could the search method be improved to avoid this inconvenience?

Thank you and greetings from Spain.

Regards,
Daniel

[1] [https://openlibrary.org/help/faq/editing#work-edition](https://openlibrary.org/help/faq/editing#work-edition)

**Comment by mekarpeles** [comment] 2018-10-25 19:16
Thank you @dcapillae! This is a highly requested feature and I think we (@cdrini, @tfmorris, @hornc, @JeffKaplan and others) are in full support. The question will be finding the resources to push this forward.

Please feel welcome to join any of our weekly community calls and we'd be happy to discuss further and listen to your ideas --
https://github.com/internetarchive/openlibrary/wiki#communication

**Comment by LeadSongDog** [comment] 2018-10-25 20:09
#342 and #643 all over again. I still have seen no explanation offered for why the work is presented instead of the matching edition.

**Comment by mekarpeles** [comment] 2018-10-25 20:44
Thanks! @dcapillae, we're going to close this as duplicate (to be merged with #643) :)

@LeadSongDog -- you do deserve an explanation, but unfortunately there isn't a philosophical explanation I can give you because we all agree with you and others. The explanation is because of resource-constraint. Working with solr (especially given our setup) is not trivial (I think @hornc, myself, @tfmorris, and @cdrini are the only folks with the right expertise?). @cdrini is in school, @tfmorris is currently busy, and @hornc and I have a ~2 month backlog of critical tasks (like... getting Open Library import to work and to make sure we have a working sitemap 😅). If you happen to have the time and expertise to work on this issue, by all means we'll gladly support you as we all believe in the importance of multi-language search :)

I think you'll find the issue has its technical challenges, compounded by the reality no full-time staff currently has the bandwidth to take it on. We're open to a volunteer working on this -- @cdrini worked on a similar effort #599 which *still* hasn't been merged because testing and re-indexing solr is such a pain-point for us (some of this pain may be mitigated as we move our development environment to user docker, with its own solr image). Finally, these changes span not only solr but UI and will have cascading consequences which we haven't fully investigated. I'd imagine this is at least a 2-person, 2-week project (and we currently have 0 people available for it). So even though the answer is disappointing, that's the most honest explanation I can offer :)

sorry :(

**Closed by mekarpeles** 2018-10-25 20:44 UTC
Labels: internationalization, languages, search

**Comment by LeadSongDog** [comment] 2018-10-25 20:57
@mekarpeles I don’t mean to whine but there seems to be more priority on making things pretty than functional. That’s just wrong.

**Comment by mekarpeles** [comment] 2018-10-25 21:09
@LeadSongDog I don't view it as whining -- we want people to passionately advocate for the issues they feel are important.

Very few of our changes in the last 6 months have involved making things pretty. Most have been addressing technical debt so that we can more easily respond to issues like this one.

Having a working sitemap, a site that works for mobile devices, fixing our bookcover service for partners, enabling multiple-copy lending, supporting library partners so we can get new books into our library, fixing UI regressions (so the website works for patrons), switching to docker (so we can work on solr issues), are just a few things which we've been juggling.

I think you'll find that every Tuesday (and every day on our slack channel) we make ourselves available and directly listen to feedback from the community (including @JeffKaplan who answers emails every day from users who request features like these). You're also welcome to schedule a time with me any Sunday to discuss/propose how this initiative and others like it may be fit into our roadmap.
