### ISSUE TITLE
Adding a code of conduct and issues template to our repo

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1560] opened 2018-11-11 16:52 UTC
We should probably add a code of conduct and issues template to our repo this will help us getting a defined form of issues.
![community-standards](https://user-images.githubusercontent.com/31198893/48315747-334ef080-e600-11e8-9cb6-43288e0116df.png)

**Comment by himanshuc3** [comment] 2018-11-13 12:29
I would try to do this.

**Comment by shreyansh23** [comment] 2019-03-10 10:12
@tabshaikh
 https://archive.org/about/terms.php Will this serve the purpose of CODE_OF_CONDUCT?

**Comment by tabshaikh** [comment] 2019-03-11 13:52
@shreyansh23 something more like this https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md

**Comment by mekarpeles** [comment] 2019-03-11 15:12
I think in general we shouldn't create paperwork to create paperwork. this would be a great place for us to document regressions and resolutions as we encounter issues.

At the present it needs say little more than: Be open, inclusive, respectful, and suportive

**Comment by shreyansh23** [comment] 2019-03-11 15:37
Okay @mekarpeles

I will try if I can submit a simpler version of CONTRIBUTING.md as described by you.

**Comment by shreyansh23** [comment] 2019-03-11 17:16
@tabshaikh Any suggestion for #1974?

**Comment by cdrini** [comment] 2019-09-09 18:08
@tabshaikh I'm going to close this, since we now have an issue template, and #2319 is tracking adding a code of conduct.

**Closed by cdrini** 2019-09-09 18:08 UTC
Labels: Affects: Documentation, Good First Issue
