### ISSUE TITLE
Search fails for authors with non-Latin1 characters

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#714] opened 2018-01-02 03:36 UTC
or perhaps it's that AKA names aren't being indexed.

For whatever reason, neither of these searches return anything, when they should:

Æschylus https://openlibrary.org/search/authors?q=%C3%86schylus&mode=everything
Αἰσχύλος https://openlibrary.org/search/authors?q=%CE%91%E1%BC%B0%CF%83%CF%87%CF%8D%CE%BB%CE%BF%CF%82&mode=everything

They should both return, at a minimum, https://openlibrary.org/authors/OL74434A/Aeschylus

Unicode folding would take care of (or workaround) the first, but wouldn't help with the second.

**Comment by tfmorris** [comment] 2018-01-02 07:44
A couple more Unicode searches that don't work:

- Kālidāsa https://openlibrary.org/search/authors?q=Ka%CC%84lida%CC%84sa&mode=everything 
   should return https://openlibrary.org/authors/OL528A/Kālidāsa
- Āśāpūrṇā Debī https://openlibrary.org/search/authors?q=A%CC%84s%CC%81a%CC%84pu%CC%84rn%CC%A3a%CC%84+Debi%CC%84&mode=everything 
    should return https://openlibrary.org/authors/OL821A

**Comment by LeadSongDog** [comment] 2018-03-12 15:30
It's odd that searching for Αἰσχύλος using
https://openlibrary.org/search/authors?q=%CE%91%E1%BC%B0%CF%83%CF%87%CF%8D%CE%BB%CE%BF%CF%82&mode=everything gets no hits while 
https://openlibrary.org/search?q=%CE%91%E1%BC%B0%CF%83%CF%87%CF%8D%CE%BB%CE%BF%CF%82&mode=everything
gets 954 hits. The Greek spelling is listed in the alternative names for https://openlibrary.org/authors/OL74434A/Aeschylus

**Comment by tfmorris** [comment] 2018-03-12 17:37
That's an interesting observation and good clue. It sounds like the alternate names aren't included in the default author search.

**Comment by tfmorris** [comment] 2018-03-13 00:52
The different results from the different search end points is a red herring. 

The non-author search is returning *works* records, not author records. Those works have Αἰσχύλος in the `author_alternative_name` field where it got copied from the author's `alternate_name` field.

I've confirmed that author `alternate_names` doesn't appear to be indexed at all. It's not restricted to non-Latin characters. Neither https://openlibrary.org/search/authors?q=AEschyle nor https://openlibrary.org/search/authors?q=alternate_names%3AEschyle return any results. The general query syntax with field names in the query *does* work, because https://openlibrary.org/search/authors?q=name%3A%22Aeschylus%22+AND+work_count%3A%5B5+TO+*%5D returns the expect results.

I think the alternate_names issue is separate from the non-Latin characters issue because https://openlibrary.org/search/authors?q=Ka%CC%84lida%CC%84sa&mode=everything doesn't return the desired record even though that's the exact name string from the author record cut & paste into the search field. Of course, this could be confounded by the search index update issues, so who knows how many problems are really here.

**Comment by LeadSongDog** [comment] 2018-03-13 15:07
Whether this is due to #848 or #714, the author dropdown when editing the work also fails to see the alternate names, so when Αἰσχύλος is entered, the dropdown offers to create a new author record rather than suggesting https://openlibrary.org/authors/OL74434A

**Comment by LeadSongDog** [comment] 2018-11-02 22:05
Hmm, using the search box, an author-search for Αἰσχύλος finds nothing,
https://openlibrary.org/search/authors?q=%CE%91%E1%BC%B0%CF%83%CF%87%CF%8D%CE%BB%CE%BF%CF%82&mode=everything

but an all-search hits the jackpot, finding that string in the "Alternative names" for OL74434A 
https://openlibrary.org/search?q=%CE%91%E1%BC%B0%CF%83%CF%87%CF%8D%CE%BB%CE%BF%CF%82&mode=everything

**Comment by tfmorris** [comment] 2018-12-26 22:10
It looks like the ligature in Æschylus is getting converted to the replacement character (?schylus) someplace before the query gets to Solr. Now to track down where...

`solr_1       | INFO: [] webapp=/solr path=/select params={fq=type:author&fq=&q.op=AND&q=?schylus&start=0&rows=100&fl=*&qt=standard&wt=json&sort=work_count+desc} hits=0 status=0 QTime=4 
`

**Comment by tfmorris** [comment] 2019-08-04 20:57
These author searches all appear to perform correctly with my dev Solr :
* Æschylus - 3 hits including OL74434A
* Kālidāsa - 40 hits including OL528A
* Āśāpūrṇā Debī - 6 hits including OL821A

We don't transliterate Αἰσχύλος, but it will match on the alternate names field

**Comment by guyjeangilles** [comment] 2019-11-19 23:14
#2246 seems like it will fix/affect this.

**Comment by LeadSongDog** [comment] 2019-11-20 02:45
Perhaps even worse, hyphenated author names are not found by the type ahead. Leaving out the hyphen, the hyphenated name is found, so it has to be the query which is the problem.  Example: https://openlibrary.org/works/OL18318482W/Soldiers_and_oil?_compare=Compare&b=2&a=1&m=diff

**Comment by mekarpeles** [comment] 2021-01-22 02:26
Seems to work now! :tada:

**Comment by mekarpeles** [comment] 2021-01-22 02:26
> Perhaps even worse, hyphenated author names are not found by the type ahead. Leaving out the hyphen, the hyphenated name is found, so it has to be the query which is the problem. Example: https://openlibrary.org/works/OL18318482W/Soldiers_and_oil?_compare=Compare&b=2&a=1&m=diff

This may be a separate issue worth opening? @LeadSongDog

**Comment by tfmorris** [comment] 2021-01-22 06:16
Works in what way? I didn't go through all the examples, but https://openlibrary.org/search/authors?q=Ka%CC%84lida%CC%84sa&mode=everything returns zero results.

Since nothing has been done with SOLR, I wouldn't expect the results to have changed. @mekarpeles Can you cite the commit that you believe fixed this issue?

**Comment by LeadSongDog** [comment] 2021-01-22 17:25
@tfmorris That search returned nothing in Chrome on iPadOS but 28 hits in Safari on iPadOS. Meanwhile even on the latter, merging as below returns an “Internal server error”:
![0EC4C85B-BBC6-4B78-AD2E-9E6D2C7487A2](https://user-images.githubusercontent.com/11435431/105523766-d0137b00-5cac-11eb-919a-64365b6a3302.png)

**Comment by tfmorris** [comment] 2021-01-22 18:34
@LeadSongDog Remember that if you merge/edit the entry, you stand a good chance of changing the behavior in a way that makes the bug unreproducible, requiring the developers to search for another test case.

**Comment by LeadSongDog** [comment] 2021-01-22 18:56
Right. That’s why I didn’t try to merge more than one of the many.

**Comment by tfmorris** [comment] 2021-08-30 16:03
@mekarpeles You never replied to my request for clarification https://github.com/internetarchive/openlibrary/issues/714#issuecomment-765160179

I just retested and neither of the searches from my January 2018 comment work on openlibrary.org https://github.com/internetarchive/openlibrary/issues/714#issuecomment-354715235

I'm still interested in:
* a pointer to the commit / PR that's claimed to fix this
* an explanation of why it was closed when half of the test cases still fail

I know it's fixable since I had it fixed on my dev branch a couple of years ago, before I abandoned it on the realization that it would never get merged, but I don't see that it's fixed in the current production instance.

**Comment by cdrini** [comment] 2021-08-31 16:23
I'm guessing he tested the searches in the description, which do work now, and didn't see that there were more cases below. The changes that likely fixed those are the (1) full solr reindex; there is some NFC normalizing code in update_work: https://github.com/internetarchive/openlibrary/blob/14a6b5b67854b9b6b6e10593bba8be2d04913526/openlibrary/solr/update_work.py#L153 ; but a full solr reindex would be needed to see that applying everywhere? So maybe that. or (2) The solr 8 upgrade (#4337 ) ; double solr versions could have had an impact.

Now that we're on solr 8, nothing is blocking those fixes :) So cleaned them up an put them in #5600 .

Note this is _kind of_ a duplicate of #178 , but kind of not. Despite the misleading naming, that issue is generally meant to deal with "Ignore diacritics in author search". This issue is about Unicode normalization. But both will be fixed by #5600.

**Comment by LeadSongDog** [comment] 2021-08-31 23:43
Perhaps overtaken by events, but observe that https://openlibrary.org/search/authors?q=Ā*+Basu finds four author records while https://openlibrary.org/search/authors?q=A*+Basu finds none.

**Closed** 2021-09-15 05:00 UTC
Labels: Type: Bug, Theme: Search, Module: Solr, Priority: 3, Module: Authors, Lead: @cdrini
