### ISSUE TITLE
Possible malformed editions vs. works URLs

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#346] opened 2016-10-10 06:47 UTC
User reports that we have "editions" which are showing up in URL paths that contain the /books/ string which shouldn't be happening/possible. Here's the email:

> I came to this example by searching for "Maria theresia", but just note that my email below shows two URLs. One has /books/ in the path while the other has /works/ yet both refer to OL5669117M. Normally the ...M should only be found with the /books/ path, while a distinct ....W id is used for the /work/ of which that book is one example. Can you construct a search of the works directory for records ending with M (there shouldn't be any, so they'll all need fixing.)"
> So in short, if an item has an M at the end of it (designating it's an edition) it shouldn't show up in a URL string with /books/

**Comment by hornc** [comment] 2017-05-08 10:26
What seems to be happening here is that these /works/OL...M records are Editions without Works, see #153 , that show up in search results. There are a large number of these further down in the search results for https://openlibrary.org/search?q=Maria+theresia 

OL seems to resolve any /works/OLID url to the correct record based entirely on the OLID. It happens for authors, I know this because all the wikidata links to OpenLibrary authors use /works/OL...A author links, and they all resolve to the correct place.

example: https://openlibrary.org/works/OL9388A  <== author page as /works

I think for practical purposes, this is a duplicate of #153

**Comment by hornc** [comment] 2017-09-18 23:02
closing as duplicate / subset of #153

**Closed by hornc** 2017-09-18 23:02 UTC
