### ISSUE TITLE
Import quality books 2010 - present

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2332] opened 2019-08-23 01:47 UTC
This is a graph showing how many editions by publication year are catalogued by Open Library from the July 2019 data dump.

![Graph of edition counts by publication year (at June 2019)](https://docs.google.com/spreadsheets/d/e/2PACX-1vRXTYkmE6wRV82Z-zJaCsPAJ91SBIEWOyCaPCK1U89c379_Ing4RReHsnTX_0JiShyDnySLgjd5ejKN/pubchart?oid=723822477&format=image)

There is a drop off in recent years. This epic is to create a process to fill in this gap.

We need to:
* Specify and agree upon  a definition of 'quality books', and define a minimal set of metadata requirements to meet our import threshold.
* Establish a baseline metric so we can measure import progress over time.
  * The above graph is a start
  * We need better visibility on how much is being imported on an ongoing basis, i.e. each month so we can measure improvements. The ability to located what has been recently imported will add discovery of specific import issues.
* Provide confidence in our imports and import process.

Wiki topic page for this project: https://github.com/internetarchive/openlibrary/wiki/Open-Library-Importing
And current developer's guide for importing: https://github.com/internetarchive/openlibrary/wiki/Developer's-Guide-to-Data-Importing

We have an opportunity to leverage book data from our partner Better World Books (BWB). We have access to metadata from their current and past book inventories which we can use to increase out book coverage.
**BWB sources:** 
* list of 'seen' ISBNs `ISBN, title, date`
* API access for checking and retrieving metadata, w/ cover image access

**Epic sub-parts:**
* Identify import candidates
* Bring non-MARC import path in line with MARC imports
  * [ ] Import preview feature #2205 
  * Document (JSON schema) the generic pre-import  data format used here https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/importapi/import_edition_builder.py 
  * [x] Add non-MARC import conversion / handling features. Title formatting (#2311), Author name format, can we determine subject, &c
* Once mechanisms exist to import from non-MARC sources, provide ongoing input using automated tools

**Comment by tfmorris** [comment] 2019-08-23 06:00
Is the presumption that the BWB data meets the `quality books` metric, or is that still TBD?

**Comment by hornc** [comment] 2019-08-23 12:25
To be clarified, agreed upon, and documented. The current bar is pretty low according to https://openlibrary.org/books/add  I think we should be able to do a bit better for our automated imports, but there aren't any good guidelines written down anywhere to evaluate how the current import system is doing, or to give us something to aim towards.

**Comment by mekarpeles** [comment] 2019-11-05 20:30
This and #2204 can likely be closed. We now have an ongoing import pipeline (cron) and we've taken a good stab at importing modern materials. @hornc can you update this thread with our results and recommend next steps re: using LoC v. Bowker v. BWB in an automated/continuous way?

**Comment by mekarpeles** [comment] 2021-01-23 09:01
Closing as duplicate of #2034

**Closed by mekarpeles** 2021-01-23 09:01 UTC
Labels: Affects: Data, Lead: @mekarpeles, Module: Import, Priority: 2, Type: Epic
