### ISSUE TITLE
Index normalized author name in solr

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#178] opened 2013-03-26 10:18 UTC
Imagine the case where the author name author name has special accent characters like "Ghaṭṭi Añjanēyaśarma". Most of the time, the user won't be able to enter the accent characters and autocomplete will fail. 

The search engine should index the accent-stripped version of the author name along with the real name to avoid such issues.

**Comment by tfmorris** [comment] 2016-01-30 16:26
@gio I know you made some Solr changes recently. Was diacritic folding and/or unicode normalization part of that work or is this still open?

**Comment by LeadSongDog** [comment] 2016-07-11 19:14
@anandology there still seem to be two very similar records at https://openlibrary.org/search?q=Gha%E1%B9%AD%E1%B9%ADi&author_key=OL6A and at https://openlibrary.org/search?q=Gha%E1%B9%AD%E1%B9%ADi&author_key=OL6A 
Neither of them is found yet by an author search for "Ghatti Anjaneyasarma"

**Comment by tfmorris** [comment] 2016-07-11 21:41
@LeadSongDog Anand (anandology) isn't involved any more. As I understand it, Gio (@gdamdam) is the current dev. Unfortunately when I attempted to ping him for status back in January, I inadvertently used the wrong username. 

@gdamdam Any update on Solr diacritic folding?

**Comment by bfalling** [comment] 2016-09-22 17:54
We've moved the full-text search engine to an Internet-Archive-based Elastic Search cluster. A decision needs to be made about the OL metadata search engine. Keep SOLR? Also move to Elastic Search?

**Comment by tfmorris** [comment] 2016-10-05 06:28
I don't think it makes sense to have two different search technologies, but
then it didn't make sense to move to ES just because that's what IA wanted.

We know the last transition broke things which depended on the search query
language, so a little more due diligence, public notice, and discussion
should be done this time to at least notify users that their apps are about
to break, well in advance of any migration.

**Comment by bfalling** [comment] 2016-10-05 06:53
A little context on the move to Elastic Search: The SOLR used for searching inside books was found to be continuously corrupting. Repaired data re-corrupted after a few weeks for no ascertainable reason. We weighed between upgrading SOLR and moving to ES, which has much more support within the Archive. We chose the latter.

**Comment by tfmorris** [comment] 2016-10-06 05:05
All true, but the most relevant things for me were the lack of advance
notice, public discussion, or any input from the community.

It could have been entirely the correct decision, but arrived at in
completely the wrong way.

I'm suggesting not repeating the mistake.

**Comment by tfmorris** [comment] 2017-04-05 01:41
@bfalling If a switch to Elasticsearch is a blocker for this task, has any progress been made on advertising the potential change (e.g. to ol-tech or ol-discuss), soliciting feedback, preparing downstream consumers for the change?

This bug represents a significant usability issue and was first reported in 2010. It'd be nice to make some progress on it.

**Comment by mekarpeles** [comment] 2017-10-18 02:24
@tfmorris one thing we've started to do is write back openlibrary_work and openlibrary_edition IDs into their corresponding archive.org items. This allows us to do more querying against Internet Archive Elastic Search. OL still need solr (or its own ES) in the interim because there are many works and editions for which there are no corresponding archive.org items and IA isn't reluctant to store metadata in ES for works/editions which are not digitized.

One of the current challenges is solr takes a while to update and its becoming increasingly difficult to keep our tiny solr instance sync'd with IA's borrow availability data. We've been switching Open Library to use a special Archive.org availability API to get this info (instead of trying to write back to solr). One downside is we can't easily query Open Library for available works.

In the next year or so I'd like to see tighter integration between IA and OL in terms of moving metadata away from OL's postgres and solr instance into some official shared infrastructure which both services can agree upon. This direction is a very early stage idea, but it's worth bringing up in case there are strong opinions which may help us avoid "gotchas".

**Comment by tfmorris** [comment] 2017-11-08 23:19
As pointed out in #599, the ICU Normalizer, mentioned in my Aug 2013 note, isn't powerful enough and we actually want ICU Folding.

**Comment by mekarpeles** [comment] 2018-03-13 07:27
@cdrini is this related to #599?

**Comment by tfmorris** [comment] 2019-08-04 21:10
I've confirmed that the `ICUFolderingFilter` correctly handles this case and for
`q=type:author AND name:Ghatti Anjaneyasarma` returns both records:

```
      {
        "name":["Ghaṭṭi Añjanēyaśarma"],
        "key":"/authors/OL6A"},
      {
        "name":["Ghaṭṭi Āñjanēyaśarma"],
        "key":"/authors/OL179948A"}]
```

One nuance is that the giant concatenated `text` field doesn't use `ICUFoldingFilter` because it's a mishmash of different types of text, but I think we probably want to move away from it anyway because it doubles the amount of data that we need to index.

**Comment by LeadSongDog** [comment] 2019-10-25 17:52
Searching finds each of those two keys individually, with no indication of the other. Surely we would want to display some indication of the nearly-identical spelling's existence to facilitate their merger.

**Comment by tfmorris** [comment] 2019-10-28 01:33
> Searching finds each of those two keys individually, with no indication of the other. Surely we would want to display some indication of the nearly-identical spelling's existence to facilitate their merger.

You've just restated the original request.

**Comment by guyjeangilles** [comment] 2019-11-12 20:58
Making this a sub-task of #789

**Comment by tfmorris** [comment] 2019-11-12 22:18
> Making this a sub-task of #789

Why? They have nothing to do with each other. This requires a change to the indexing schema while #789 is about update frequency and accuracy.

**Comment by guyjeangilles** [comment] 2019-11-12 22:23
Mostly because #789 refers to
> ...missing expected data fields

and I would expect an normalized author name to be in Solr. But I can remove the sub-task if you feel it's inappropriate.

**Comment by guyjeangilles** [comment] 2019-11-14 02:07
No longer a sub-task #789

**Comment by LeadSongDog** [comment] 2019-12-09 16:03
#11 was closed in favour of this. Consider that
https://openlibrary.org/search?q=%22tiananmen%22&mode=everything finds 447 hits, but 
https://openlibrary.org/search?q=%22tian%27anmen%22&mode=everything finds only 45 and
https://openlibrary.org/search?q=%22tiananmin%22&mode=everything finds zero.
Some sort of soundex or metaphone normalization has to be indexed

**Comment by tfmorris** [comment] 2019-12-17 21:10
> Some sort of soundex or metaphone normalization has to be indexed

@LeadSongDog That's a different feature request. Let's keep the discussion here focused on the original request ie diacritic folding and Unicode normalization.

**Comment by tfmorris** [comment] 2020-04-30 21:34
The fix for this is in https://github.com/tfmorris/openlibrary/commit/c7026ff67680e8848cd14130fb32b37fe6be08a0 and is straightforward, but it requires a Solr config change by OL staff which is unlikely to ever happen so unassigning myself.

**Closed** 2021-09-15 05:00 UTC
Labels: Type: Feature Request, Theme: Search, Module: Solr, Theme: Internationalization, Priority: 2, Lead: @cdrini, Theme: Unicode
