### ISSUE TITLE
Stats on the home page is not working (stats.html)

### ISSUE THREAD

**Issue by Hardcore-fs** [internetarchive/openlibrary#146] opened 2012-05-23 08:23 UTC
When there are no stats the 'total' in the following line is set to  0

   $ percent = lambda v: sprintf("%.2f%%", (100.0 \* v)/total)

either there needs to be a check for total being zero or a 'quick fix'
(total+0.000001)

But once this is fixed the stats page comes up correctly, without causing an error

**Comment by mekarpeles** [comment] 2017-11-28 18:53
Similar to #656

**Comment by rohitjain00** [comment] 2019-03-22 21:49
`0.0.0.0:8080/libraries/stats` page redirects to homepage also 
`0.0.0.0:8080/libraries` is disabled feature. I think there should be a way to reproduce this error or this should be closed

**Comment by brad2014** [comment] 2019-05-03 22:14
@mekarpeles : Since #656 was closed as stale, should this one also be?

**Comment by tfmorris** [comment] 2019-05-05 05:24
Simple question - does the stats page on the developer instance work currently if the total is zero?

**Comment by tfmorris** [comment] 2019-05-06 01:47
Actually this was already addressed in the Mar 22 comment. This page doesn't exist in the current system. Closing.

Apologies to the OP for ignoring it for so long.

**Closed by tfmorris** 2019-05-06 01:47 UTC
Labels: Type: Bug
