### ISSUE TITLE
Frequent "Oops, try again later" reported by patrons

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7967] opened 2023-06-13 07:57 UTC
Several patrons have reported errors when trying to edit records. I see no obvious reason for these particular records to throw errors nor do I see any reason for the specific accounts to have issues. My own edits do not produce the error, but I was able to reproduce by using one of the patron's accounts.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by jimchamp** [comment] 2023-06-13 23:26
Edits were failing to pass our spam word checks, which use regex to determine if any designated spam words are present in the record being edited (check occurs [here](https://github.com/internetarchive/openlibrary/blob/500e98998231b3a0d4882b166810741a45276cae/openlibrary/plugins/upstream/spamcheck.py#L59)).  Each spam word is passed, unmodified, as the `pattern` to `re.search()`.  Many of our spam words contain at least one unescaped `.` character, which is treated as any single non-newline character when matching.

Closing this as I've updated our spam word list, escaping all `.` characters.  @seabelis, please re-open this if the issue is still occurring.

**Closed by jimchamp** 2023-06-13 23:26 UTC
Labels: Type: Bug, Needs: Triage, Affects: Librarians, Needs: Lead
