### ISSUE TITLE
author search has weird indentation for some authors

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8996] opened 2024-03-30 23:07 UTC
#### Evidence / Screenshot
![Screenshot_20240331-000441](https://github.com/internetarchive/openlibrary/assets/921217/cef5f721-0256-4051-9872-b3da66f9cb80)

#### Relevant URL(s)
https://openlibrary.org/search/authors?q=pokemon

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

@cdrini

**Comment by scottbarnes** [comment] 2024-03-31 05:19
See https://github.com/internetarchive/openlibrary/commit/29208c70acafe439f1ec0a3f153cc747beed56da.

**Comment by Noronha01** [comment] 2024-04-03 20:12
Hello! I am a CS student wanting to start contributing to an open source project, can I try to solve this issue?

**Comment by scottbarnes** [comment] 2024-04-04 01:18
@Noronha01, thanks for your interest in this issue. I have assigned it to you.

If you've not yet done so, you'll want to check out [CONTRIBUTING.md](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md), with particular emphasis on:

- the [Docker installation README.md](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md)
- [How we use git](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet) (AKA the Git Cheat Sheet")
- [Loading Production Book Data](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data) to copy, for example, Works, Editions, and Authors to your local environment (if needed).

Then for this issue specifically, you'll want to look at the [Frontend Guide](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide) to see how to rebuild the CSS in particular, as you'll need to do that for this task.

Next you'll want to reproduce the bug yourself. Then, check out 29208c70acafe439f1ec0a3f153cc747beed56da, which I suspect is where the problem was introduced. You can verify that with `git bisect`.

Please ask any questions that you might have.

**Comment by kpan02** [comment] 2024-04-08 04:13
Hello! I am looking for open source projects to contribute to as homework for my Principles of SWE course. Is there any chance I can work on this issue as well?

**Comment by scottbarnes** [comment] 2024-04-08 13:03
@kpan02, thanks for looking to help out. This issue is pretty small and might be a bit hard to break up to have multiple people working on different parts, unless @Noronha01 happens to be too busy to work on it. How are things going, @Noronha01? Do you have any questions?

@kpan02, if you you haven't checked this query, it's always worth looking for issues labeled [Good First Issue without a linked PR](https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22+no%3Aassignee+-linked%3Apr).

**Comment by Noronha01** [comment] 2024-04-11 12:03
Hey, @scottbarnes, sorry, I have been busy, but I will open a PR today.

**Closed** 2024-04-23 20:12 UTC
Labels: Type: Bug, Theme: Search, Priority: 3, Good First Issue, Lead: @scottbarnes
