### ISSUE TITLE
better spacing on /stats page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3270] opened 2020-03-26 16:37 UTC
![image](https://user-images.githubusercontent.com/55302685/77671841-63710800-6f45-11ea-90cc-88c49fbf805e.png)
where the red line is

**Comment by ritwikchakraborty123** [comment] 2020-03-31 06:24
can you please help me to find the particular page or the path of file where we have to make change.

**Comment by BrittanyBunk** [comment] 2020-03-31 14:06
@ritwikchakraborty123 https://openlibrary.org/stats the spacing doesn't look like an issue today, but that's because the numbers are smaller than in this picture. The numbers could be better spaced out.

**Comment by RayBB** [comment] 2024-03-21 18:53
Not sure what was going on back in 2020 but I can't reproduce this issue anymore even with numbers of the same size.
Closing for now.

**Closed by RayBB** 2024-03-21 18:53 UTC
Labels: Type: Bug, Theme: CSS, Affects: UI, Priority: 4, Lead: @jdlrobson
