### ISSUE TITLE
Cannot save changes to work-less editions

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1891] opened 2019-02-15 20:13 UTC
## Description

Trying to save changes to a work-less edition results in a failure, but no error message.

## Evidence 

> Relevant url?

https://openlibrary.org/books/OL24195925M/Sarah's_Key

> Screenshot (if possible):
![fullscreen capture 2152019 91028 pm bmp](https://user-images.githubusercontent.com/17739465/52881958-7ae89980-3166-11e9-840d-99f820f2a573.jpg)

## Details

> Logged in (Y/N)? 

Yes

> Browser type/version? 

Chrome Version 71.0.3578.98 (Official Build) (64-bit)

> Operating system? 

Windows 7 pro

**Comment by mekarpeles** [comment] 2019-02-15 22:20
@hornc can I please entrust this one to you? Thank you!!

**Comment by LeadSongDog** [comment] 2019-02-20 18:11
@seabelis, @mekarpeles @hornc I had no problem adding that edition once I populated the publisher, date, and location fields. There was an existing work which I linked in. Without these, it is probably a good thing not to create an edition record distinguished solely by an ISBN. Commonly a single edition has more than one ISBN: we should not presume otherwise. 

I was using Chrome 71.0.3578.80 (Official Build) (32-bit) on Win 7 Pro at the time.

**Comment by seabelis** [comment] 2019-02-20 18:18
Where I've run into these issues, the edition record already exists; I'm just trying to consolidate under one work. I will see if I can edit any of the other problematic editions.

**Comment by seabelis** [comment] 2019-02-20 18:24
On this one, for example, all edits fail. I tried earlier to move it to OL40886W but it bounced and ended up an orphan. Now I cannot edit any of the work or edition information, nor can I move it to the appropriate work. https://openlibrary.org/books/OL26067435M/La_Route_Roman

**Comment by cdrini** [comment] 2019-02-20 19:23
@mekarpeles @jdlrobson I think this might be related to #1831. I think we have bring back `errors.html` cause it was being

**Comment by cdrini** [comment] 2019-02-20 19:25
(whoops! Pressed the wrong button)

**Comment by LeadSongDog** [comment] 2019-02-22 18:54
Hmm, the same problem on https://openlibrary.org/books/OL23877809M/The_road
Neither would it allow the link to https://openlibrary.org/works/OL40886W nor the addition of an author. 
Looking closer, it appears that when @seabelis made this edit: https://openlibrary.org/books/OL26067435M/La_Route_Roman?b=4&a=3&_compare=Compare&m=diff
the link to /works/OL17481152W was deleted but not replaced with /works/OL40886W
I suspect that recent changes have borked the error display: Like you I just see a pale yellow ribbon with no message on it, just the red triangle.

**Comment by hornc** [comment] 2019-02-27 02:21
I can reproduce this with the https://openlibrary.org/books/OL23877809M/The_road book, but I'm not sure it is entirely due to the book being an orphan --  it looks like there is supposed to be an error message that is not being presented. Hence the yellow bar and warning exclamation mark in the screenshot.

I tried looking for the error message content in cookies etc, but could not find anything.

**Comment by tfmorris** [comment] 2019-02-27 05:21
These messages have victims of the CSS refactoring multiple times. Recently the post-author-merge messages disappeared as well (something to the effect of "Your merge is in progress, refresh the page to see the results.")

**Comment by seabelis** [comment] 2019-04-10 08:35
I've been maintaining a list of broken records: https://openlibrary.org/people/seabelis/lists/OL129155L/broken. I will sometimes revisit and try to move editions to their corresponding works. Sometimes this is successful, but the trouble is that when they fail they create a new orphaned work. Sometimes these resolve after an author merge; not always.

**Comment by hornc** [comment] 2019-04-24 04:40
Another example: https://openlibrary.org/books/OL25430105M/Drumul?m=history

The Change Work field actually _created_ an orphan after I reverted it to the old duplicate work. My edit just reproduced @seabelis 's edit. 

The issue with the error messaging needs to be fixed as I can't tell if there is some other specific problem with the data that is causing it to lose the new Work id, or whether it happens in all cases.

**Comment by cdrini** [comment] 2019-04-25 02:03
Using the debugger I'm going to introduce soon (shameless plug), 

![image](https://user-images.githubusercontent.com/6251786/56704717-39cbb300-66dc-11e9-9507-2f14902fc3be.png)
![image](https://user-images.githubusercontent.com/6251786/56704740-4ea84680-66dc-11e9-8551-a6370956dc31.png)

Which makes this errors, where it's saying the edition's work's key is not found make sense (since 
![image](https://user-images.githubusercontent.com/6251786/56704803-8adba700-66dc-11e9-8dac-048a9419dac5.png)

Any thoughts on what might be causing this? Cause by this logic, _no_ orphaned edition should be editable. Does anyone have an example of an orphan that _can_ be edited?

**Comment by seabelis** [comment] 2019-04-25 07:54
I've encountered plenty of editable orphans, but I've since associated them with their respective work records. I believe this was one of them prior to my migrating it: https://openlibrary.org/books/OL7432665M/Dear_Mr._Henshaw_(rpkg)_(HarperClassics)

**Comment by seabelis** [comment] 2019-04-25 10:07
Actually, I think that's a bad example. I only moved it; didn't edit it.

This list has orphans that I was previously able to edit, but unable to move. What would happen is when edited, they would create a work, but when trying to move them, they would go back to being an orphaned edition. I think that is no longer the case as what happens now is the editions cannot be moved or saved. https://openlibrary.org/people/seabelis/lists/OL119930L/stuck

**Comment by LeadSongDog** [comment] 2019-04-26 20:34
https://openlibrary.org/books/OL8586641M/The_Art_of_War_by_Baron_De_Jomini?b=10&a=9&_compare=Compare&m=diff was supposed to correct dimensions on the edition record and link it under OL15202586W but it deleted the old work ID _without_ replacing it. This created an orphan which now will not permit correction.

**Comment by LeadSongDog** [comment] 2019-05-13 15:45
@seabelis 
Looking down one of your list: https://openlibrary.org/search?q=title%3A+%22at+home%22+author%3A+%22Bill+Bryson%22&sort=old&mode=everything shows many instances where orphan editions are duplicates of non-orphan editions. For one instance, OL24050119M is duplicated by OL24478391M. 

@cdrini 
The problem here is that we are not seeing a useful diagnostic when that duplication is detected, just the red triangle with exclamation mark and no save of the edit. What should probably happen is to cue up an edition merge that results in a redirect.

**Comment by cdrini** [comment] 2019-05-14 15:22
@LeadSongDog moving to [OL15202586W](https://openlibrary.org/works/OL15202586W/Pre%CC%81cis_de_l'art_de_la_guerre) created an orphan because the work has a subtitle. It'll be fixed once we have a deploy (this Thursday) and #2112 goes to production.

**Closed** 2019-05-15 15:32 UTC
Labels: Affects: Librarians, Editing, Editions, Orphaned Editions, Type: Bug
