### ISSUE TITLE
Sync DAISY coverage across OL and IA

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#751] opened 2018-01-15 23:20 UTC
see https://github.com/internetarchive/openlibrary/issues/749#issuecomment-357560684

**Comment by mekarpeles** [comment] 2018-01-15 23:20
related: #732

**Comment by hornc** [comment] 2019-04-22 00:50
@mekarpeles is this an exact duplicate of #1047 or is there some other work required for this issue?

**Closed** 2019-06-24 03:14 UTC
Labels: CH: sync-ia-ol, DAISY, Needs: Detail, metadata
