### ISSUE TITLE
Checkbox near dropdown button in top navigation bar

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#4738] opened 2021-03-05 16:05 UTC
Presence of checkbox in the top navigation bar near `Browse`, `More` and user avatar (When logged in) on dev.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/73437497/110138154-f6f7bd80-7dd1-11eb-8c28-3347c2031ded.png)

### Steps to Reproduce

* Actual: Visible checkbox
* Expected: None or hidden checkbox

### Details

- **Logged in (Y/N)?** Both
- **Browser type/version?** Firefox 86.0 (64 bits)
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** dev

**Comment by mekarpeles** [comment] 2021-03-22 19:12
@lephemere is this issue still occurring for you? If not, can we close it? If it is, I'm making `Priority: 1`

**Comment by navneetsaluja** [comment] 2021-03-23 07:53
@/mek 
Pretty sure this is the cache issue, duplicate of #4789. @/lephemere run `make css`

**Comment by cdrini** [comment] 2021-03-24 21:27
Ahhh, I missed as this was on the local environment. Marking as closed; a `docker-compose run --rm home make css` should fix it :+1:

**Closed by cdrini** 2021-03-24 21:27 UTC
Labels: Lead: @cdrini, Needs: Triage, Priority: 1, Type: Bug
