### ISSUE TITLE
Internationalizing the openlibrary UI

### ISSUE THREAD

**Issue by brad2014** [internetarchive/openlibrary#2190] opened 2019-06-11 20:12 UTC
This is an epic that covers subissues related to both 
- moving the server onto a translation maintenance pipeline (Weblate? Pootle? Zanata?) 
- refactoring the user interface so that foreign language users see the UI in their language 
- creating and maintaining UI translations

The UI will be polylingual, presenting label elements in the user language and content elements in the content language.  (With exceptions: e.g.  if a data field of a work is its ISO-639 language, that datum would be presented in the user's language.  FR  would be presented as French or Français or Französich, etc).

I expect this epic to cover issues of UI handling non-roman (e.g. hindi, nepali) and non-LTR languages (e.g. arabic, hebrew).

**Comment by brad2014** [comment] 2019-06-11 20:21
Also dropping here @nemobis suggestion from #791 to leverage the folks at https://translatewiki.net/wiki/Translating:New_project

**Comment by tfmorris** [comment] 2019-08-02 01:27
This seems like a duplicate of #791 (which has much more history).

The UI doesn't really need to be "refactored" - we "just" need to fix the bit rot caused by developers editing and adding things without considering translation. Unfortunately, these things are some of the most immediately visible elements such as the home page carousels.

The first item to be completed is #971.

**Comment by LeadSongDog** [comment] 2019-11-09 20:44
See too #791

**Comment by guyjeangilles** [comment] 2019-11-15 00:39
Related: #871 , #1855 , #1040 

We shouldn't keep this and #791 open. #791 is older, but this issue has actionable items and is thus closable. Also there are more issues referencing this issue than #791.

**Comment by tfmorris** [comment] 2019-11-25 01:21
> Also there are more issues referencing this issue than #791.

That's because this duplicate was created and then a bunch of references to it were inserted in various places. We could do the same thing with the original ticket #791 to pull it back into the lead if that's how we're going to decide things.

**Comment by guyjeangilles** [comment] 2019-11-25 21:36
I was more laying out the pros and cons for keeping each than making a decision. Closing this as a duplicate of #791

**Closed by guyjeangilles** 2019-11-25 21:36 UTC
Labels: Affects: UI, Needs: Breakdown, Needs: Help, Priority 3: Normal, State: Work In Progress, Theme: Internationalization, Type: Epic
