### ISSUE TITLE
Edit history should provide direct link to author-merge detail

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#7038] opened 2022-09-30 21:13 UTC
### Describe the problem that you'd like solved
The edit history should provide an easy way to get to the details of an author merge. For example, 
https://openlibrary.org/authors/OL117575A/Joseph_H._Barrett?m=history
should provide a link to
https://openlibrary.org/recentchanges/2022/09/30/merge-authors/97278924

This would both allow for quick verification of the source records for the merge as well as a direct link to undo it if necessary.

**Comment by mekarpeles** [comment] 2022-10-04 18:49
@cdrini + @mheiman do I recall you saying that creating links between merges is somewhat challenging? And recommendations on if/how this could be done?

**Comment by mheiman** [comment] 2022-10-05 00:20
What Tom is suggesting is actually the expected behavior.  It's working on my development instance running the current build:

<img width="887" alt="Screen Shot 2022-10-04 at 6 58 37 PM" src="https://user-images.githubusercontent.com/886889/193951919-d3991443-6f42-40fa-bc67-d1f9a22e045c.png">

Notice the details link, which takes you to the merge description. I don't know why it would be different in production.

**Comment by cdrini** [comment] 2022-10-05 02:32
I believe this is linked to usergroup. I vaguely recall reading some ancient comment somewhere about there being performance issues preventing it from being enabled for everyone. We should make sure it's enabled for librarians. I believe this is managed by the openlibrary.yml file.

**Comment by cdrini** [comment] 2022-10-05 02:36
I believe it's this one, `history_v2`. Could you confirm @mheiman ? I can update the production config file if so.
![Screenshot_20221004-223519](https://user-images.githubusercontent.com/6251786/193968745-08982bee-f7ec-4a9f-9819-1771c2fe5f25.png)

**Comment by mheiman** [comment] 2022-10-05 14:57
Good memory! Yes, that feature is the relevant one. It's applied a couple of steps upstream from where the message is defined, so it wasn't obvious looking at the code. Enabling it for librarians should do the trick.

**Comment by tfmorris** [comment] 2022-10-05 16:28
The payload for https://openlibrary.org/authors/OL117575A.json?m=history includes the date and the edit ID, so I'm not sure I understand where the heavy performance burden comes from. Is it not as simple as

`link_url = f"https://openlibrary.org/recentchanges/{year}/{month}/{day}/merge-authors/{merge-id}"`

I think it's useful for everyone to understand the provenance of the metadata, not just librarians.

**Comment by cdrini** [comment] 2022-10-06 00:31
Ok the expansion to librarians has been merged, will go out in next deploy. Leaving this issue open in case someone wants to investigate the perf associated with making it fully public!

**Comment by bicolino34** [comment] 2022-10-07 18:01
I think, this is a duplicate of #40 from 2011. Should I close the older one?

**Comment by tfmorris** [comment] 2022-10-08 23:51
@bicolino34 Good catch! Sorry I missed that this issue had already been reported over a decade ago.

Normal practice is to retain the oldest issue. That way all the history and context is kept.

**Comment by mekarpeles** [comment] 2022-10-10 18:21
Thanks @bicolino34 + @tfmorris will close and make sure the other issue is tagged correctly

**Closed** 2022-10-10 19:05 UTC
Labels: Type: Feature Request, Module: Merging, Priority: 3, Module: Authors, Lead: @mheiman
