### ISSUE TITLE
z-index issue --- search results display UNDER work menu

### ISSUE THREAD

**Issue by spamspambaconspam** [internetarchive/openlibrary#3588] opened 2020-07-16 03:29 UTC
Search results display on a layer UNDER the work menu

### Evidence / Screenshot (if possible)

![z level](https://user-images.githubusercontent.com/9367321/87622363-f8646080-c6f0-11ea-8c7b-df2f10ff4a83.png)

### Relevant url?
Looks like its just the pages with the work menu (IOW, the work/book pages)

### Steps to Reproduce
1. On any work/book URL, type something in the search field but don't activate a search; just allow the results to populate as a drop down.   Be sure to search for something that will return at least 6 hits... "abc" or "best" are good test strings. 

### Details

- **Logged in (Y/N)?** Yayus. 
- **Browser type/version?**  Edge Version 83.0.478.64 (Official build) (64-bit)
- **Operating system?** Win 10 Eval copy 20161.rs prerelease.200627-1754
- **Environment (prod/dev/local)?** prod

**Comment by shucon** [comment] 2020-07-19 18:40
Can't reproduce the issue:
![Screenshot from 2020-07-20 00-09-51](https://user-images.githubusercontent.com/22860775/87882397-607eb380-ca1d-11ea-9bd2-24ea440e406b.png)

cc: @mekarpeles

**Comment by spamspambaconspam** [comment] 2020-07-19 19:39
Using your exact parameters, I can reproduce it in prod.
I'm thinking it's likely caused by an issue that has been modified in dev and therefore won't be a problem in the next release. (she hopes! :))

I'd close this out, but I don't think it's my place to decide what to keep open or close out.  So, please feel free to close out, if you'd like to.

![image](https://user-images.githubusercontent.com/9367321/87883366-dca0d900-c9d4-11ea-8f40-2b963533dbdf.png)

**Comment by guyjeangilles** [comment] 2020-07-21 03:45
I can actually duplicate this on dev and prod now.
![ol_3588](https://user-images.githubusercontent.com/7256157/88010460-72875180-cb04-11ea-9e53-3c7d35326b7e.png)

**Comment by cdrini** [comment] 2020-09-15 22:51
Closed by #3801

**Closed by cdrini** 2020-09-15 22:51 UTC
Labels: Affects: UI, Lead: @jdlrobson, Needs: Investigation, Priority: 3, Type: Bug
