### ISSUE TITLE
Markdown help button does not do anything

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2624] opened 2019-11-12 17:26 UTC
Help button doesn't do anything

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/68694696-794dd580-052e-11ea-95ca-bd73fa150dd7.png)

### Relevant url?
e.g. https://openlibrary.org/books/OL25934687M/P.S._I_Still_Love_You/edit

### Expectation
It should serve some purpose

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF69
- **Operating system?** Win10

**Comment by mekarpeles** [comment] 2019-12-10 18:28
If it doesn't do anything, we should investigate whether it once did something (i.e. is this a regression?). Once this is done, we should document our findings here and make a decision between fixing the regression or removing the element.

**Comment by tfmorris** [comment] 2019-12-10 19:18
Since there's a contained element:

`<a href="/help/markdown" target="_new" title="Formatting Help"></a>`

I'm guessing that's what it's supposed to do.

**Comment by JordanDysart** [comment] 2019-12-11 05:56
The options bar for this markdown editor is initialized in `jquery.wmd.js` [line 1574](https://github.com/internetarchive/wmd/blob/55904c7aa0ec75981713ef0813e2c85530755574/jquery.wmd.js#L1574). It also looks like the button is treated differently when run through `function setupButton(button, isEnabled)` on [line 1468](https://github.com/internetarchive/wmd/blob/55904c7aa0ec75981713ef0813e2c85530755574/jquery.wmd.js#L1468). 

After this initialization this leaves the help button with no function assigned to the onclick event, and a massless (unclickable) <a> tag as a child.

... I think. 

Also, the href does take us to a markdown help page.

**Comment by aashimgarg** [comment] 2020-01-31 19:58
Hey @mekarpeles @tfmorris can i add this link  https://fs.blog/2013/11/taking-notes-while-reading/ .
As this link will help the users to write the notes about the book which they like.

**Comment by tfmorris** [comment] 2020-01-31 20:37
@JordanDysart Sounds like you did some investigation. Are you preparing a fix or should @aashimgarg work on it?

**Comment by JordanDysart** [comment] 2020-02-01 18:46
Hey @tfmorris, I hadn't heard anything back (_I also didn't follow up_), about how we would fix this. From what I found in the forked markdown editor code, is the child tag is not given a width or height so you can't click it. This button looks like it was always planned to open up the md help page, but it was just never tested. 

I haven't put anything together to fix it, so @aashimgarg feel free to work on the issue.

**Comment by Abhishek856** [comment] 2020-03-11 14:32
hello everyone , my self Abhishek mishra , i want to work on this issue . so can i work on this issue.

**Comment by tabshaikh** [comment] 2020-03-11 14:36
@Abhishek856 ya sure go ahead

**Comment by mightysood** [comment] 2020-03-12 09:31
Hey @JordanDysart @tfmorris 
This issue is still open and no one has looked into it!
Can I work on this issue?

**Comment by JordanDysart** [comment] 2020-03-15 23:18
Hey @mightysood, I would suggest putting your fix together and just submitting it. It's going to be a good experience regardless. I'm not currently working on it.

**Comment by mightysood** [comment] 2020-03-17 17:03
Hi @JordanDysart @tfmorris 
I have root caused this issue. There is a library called wmd used with <textarea> tag to give it extra functionalities, Help button has <a> tag which has height and width of 0 X 0 so when we click the help button then anchor tag is not getting clicked. 
If I add below CSS on the anchor tag, this issue is fixed. should I raise a PR?
{
    position: absolute;
    height: inherit;
    width: inherit;
}

**Comment by cdrini** [comment] 2020-03-17 17:22
Good find @mightysood ! Please do; then we can test it to make sure it's working :+1:

**Comment by mightysood** [comment] 2020-03-17 18:32
Hi @cdrini @JordanDysart  @tfmorris 
I have raised a PR. please look into it and revert back.

**Comment by mightysood** [comment] 2020-03-17 18:43
Hi @cdrini @JordanDysart 
I raised a PR and didn't change much code and I am not sure why Travis CI build failed.

**Closed** 2020-03-18 23:59 UTC
Labels: Affects: UI, Good First Issue, Needs: Triage, Priority: 3, Theme: Editing, Type: Bug
