### ISSUE TITLE
Navbar `More` drop-down menu overlaps with the search bar

### ISSUE THREAD

**Issue by homewardgamer** [internetarchive/openlibrary#5911] opened 2021-11-28 04:18 UTC
### Evidence / Screenshot (if possible)
<img width="1440" alt="Screenshot 2021-11-28 at 9 45 15 AM" src="https://user-images.githubusercontent.com/73935799/143729342-fde57b10-4a91-4a80-87ff-a5accec88a56.png">

### Relevant url?
https://openlibrary.org/

### Steps to Reproduce

1. Go to ... https://openlibrary.og/
2. Do ...     open up the More drop-down menu
3.  See if it overlaps with the Seach bar

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**N
- **Browser type/version?**Chrome Version 96.0.4664.55
- **Operating system?** MacOSX
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

I think we should increase the `z-index` of the drop-down menu so that it comes *over* the search bar and not below it. This way it will look much better.

### Stakeholders

If possible I would like to work on this.

**Comment by pulkit-30** [comment] 2021-11-28 07:19
Hey @homewardgamer ,
Can I work on this issue?

**Comment by jimchamp** [comment] 2021-12-08 18:48
Closing as this is a duplicate of #5194

**Closed by jimchamp** 2021-12-08 18:48 UTC
Labels: Type: Bug, Close: Duplicate, Priority: 2, Lead: @jimchamp
