### ISSUE TITLE
Canonical URLs should not include version url param

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3341] opened 2020-04-10 15:07 UTC
The first result on google when searching for [how to borrow openlibrary](https://www.google.com/search?client=firefox-b-d&q=how+to+borrow+openlibrary) links to https://openlibrary.org/help/faq?v=102 ; which is ~7 years older than the current page!

### Steps to Reproduce

1. Go to https://openlibrary.org/help/faq?v=102 and inspect the source

* Actual: `<link rel="canonical" href="https://openlibrary.org/help/faq?v=102" />`
* Expected: `<link rel="canonical" href="https://openlibrary.org/help/faq" />`

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF74
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles @tabshaikh

**Comment by tfmorris** [comment] 2020-04-10 18:09
This is addressed by the pending canonical URL PR.

**Comment by guyjeangilles** [comment] 2020-04-15 00:54
The specific PR is #3306

**Comment by SouthGoingZax** [comment] 2020-10-28 14:58
That PR is closed now.  This looks like a subset (and thus dupe) of #2864 (see the last comment for a larger set of parameters to exclude).

**Comment by SouthGoingZax** [comment] 2020-11-07 03:29
Closing this as a dupe of #2864

**Closed by SouthGoingZax** 2020-11-07 03:29 UTC
Labels: Lead: @jdlrobson, Priority: 3, Theme: SEO, Type: Bug
