### ISSUE TITLE
Fix missing widget on mobile

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#2146] opened 2019-05-24 01:20 UTC
## Description

The arrow widgets for increment/decrement of numeric values are missing on mobile but present on desktop. 

## Details

- **Logged in (Y/N)?** yes
- **Browser type/version?** chrome
- **Operating system?**  iOS

**Comment by mekarpeles** [comment] 2019-05-29 14:58
@LeadSongDog can you please provide a screenshot, a url, or additional information on reproducing the issue? It's unclear what page this is for, how it looks, and how it's supposed to look.

I don't see `Arrow Widgets` referenced anywhere in our https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide

@koderjoker -- once @LeadSongDog clarifies what's broken, could you make sure it's documented as a component on our Front-end guide?

Thank you!

**Comment by jdlrobson** [comment] 2019-05-30 12:28
I'm pretty sure this is browser specific and these do not show on mobile and there is nothing we can do here. The arrows are provided by the browser when hints are present.

Suggested "Close: Will not fix"

**Comment by LeadSongDog** [comment] 2019-05-31 16:19
@jdlrobson 
1. What does "when hints are present" mean? Is there something OL is not telling the browser?
2. Those widgets aren't just missing in one browser: both Safari and Chrome show the same problem on iOS. I'm not sure what Android users see, but it's likely the same. The Firefox and Chrome browsers do present the widgets on Win7 Pro, but IE does not.
3. How are mobile users supposed to edit these fields? If they can't do so, then the values should not be shown in what look like edit boxes at all, but really we want the user to have the same capability on any supported browser or platform.

**Comment by cdrini** [comment] 2019-05-31 16:56
@LeadSongDog They can be edited by clicking on them and using the keyboard? Does the keyboard not appear when you tap on the input box?

This is controlled by the OS. On desktop operating systems, the up/down buttons appear. On e.g. Android, those buttons would be too small to press, so instead the OS opens the keyboard in number-pad mode:

<img src="https://user-images.githubusercontent.com/6251786/58721635-68a40b80-83a3-11e9-868d-a6e9a478ab7c.png" width="300">

**Comment by LeadSongDog** [comment] 2019-05-31 17:15
Chrome on iOS gives a general keyboard when the user clicks in the box. If the user gives extra digits, such as 19.01 cm, it shows the easily-missed error bubble “Enter a valid value” without saying what is wrong. The invalid number error prevents saving the page.

**Comment by cdrini** [comment] 2019-05-31 18:17
Ah, that error is because of #2095 . The fix for that should be on production after our Thursday deploy.
Unfortunately there isn't much we can do to force Chrome to display the numpad when we specify `type="number"` :/

**Comment by LeadSongDog** [comment] 2019-05-31 19:12
@cdrini I still see the error on dev too, but if the code is fixed and in the queue, that's great. Thank you for clarifying.

**Comment by cdrini** [comment] 2019-06-08 02:51
#2095 is now fixed on production! I'll close this issue as won't fix I guess, cause we can't make Chrome display the widgets, and since the field no longer errors when trying to use a decimal number.

**Closed** 2019-06-08 02:53 UTC
Labels: Affects: Mobile/Responsive, Close: Will Not Fix, Editing, Regression
