### ISSUE TITLE
Publishers API results only shows 1 record, when UI shows many more

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2249] opened 2019-07-31 02:01 UTC
I am trying to explore all items by a particular publisher using the API for removing non-book items, and resolving orphaned editions. I was hoping this endpoint could return all results, but it looks like it is broken.

### Reproduction Steps
1. Go to https://openlibrary.org/publishers/John_Bartholomew_&_Son and observe there are ~128 results
2. Go to https://openlibrary.org/publishers/John_Bartholomew_&_Son.json

* Expectation: The same number of results should be present in both
* Actual: Only 1 result is returned.

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** FF70
- **Operating system?** Win10

### Related Files
- The class managing this endpoint https://github.com/internetarchive/openlibrary/blob/e1b826761942b02d315055e4323724e7b094bb56/openlibrary/plugins/worksearch/publishers.py#L31-L42
- The class it inherits from https://github.com/internetarchive/openlibrary/blob/bc59b7c942c6eef29e76eb82c585c59d1d240d81/openlibrary/plugins/worksearch/subjects.py#L89

**Comment by tfmorris** [comment] 2019-07-31 04:19
My guess is that "ebook" filtering is being applied somewhere in the chain. It sucks that this is getting baked into so many parts of Open Library.

**Comment by guyjeangilles** [comment] 2019-11-18 23:51
Still only showing one work. Assigning @hornc per slack discussions since this is metadata related

**Comment by cdrini** [comment] 2019-11-19 18:10
It looks like this removes the filter: 
https://openlibrary.org/publishers/John_Bartholomew_&_Son.json?has_fulltext=false

This might also affect the subjects API, since these API share most of their code. Updated description to match template.

**Comment by tfmorris** [comment] 2019-11-24 19:37
> This might also affect the subjects API, since these API share most of their code. Updated description to match template.

I've confirmed that the subjects API is broken as well. My July 31 comment still holds.

**Comment by tfmorris** [comment] 2020-01-28 22:24
So https://openlibrary.org/publishers/John_Bartholomew_&_Son.json now shows an `ebook_count` of 127 which is the same as the `work_count`.

That doesn't seem right. Was that the desired outcome? Adding ?fulltext=false changes both counts to 1.

**Comment by LeadSongDog** [comment] 2020-01-29 20:02
I suspect the ampersand is mangling things:
https://openlibrary.org/publishers/John_Bartholomew
and 
https://openlibrary.org/publishers/John_Bartholomew.json
agree on 23 works.

**Comment by hornc** [comment] 2020-01-30 05:23
@tfmorris this look like pre-existing code that sets the counts to the same value:

https://github.com/internetarchive/openlibrary/blob/457e6d6cbd12d79d1b1ac1fad16d2dea0a857190/openlibrary/plugins/worksearch/subjects.py#L132-L134

What uses `ebook_count`? I'd consider this to be a separate issue.

**Comment by tfmorris** [comment] 2020-01-30 18:58
OK. Looks like that was added by @mekarpeles in 2ee4a7cf9a4d00055e97a95f68e6bb38a1db5eee. Perhaps he can explain the purpose. It seems misleading/wrong to me, but I'll close this.

**Closed by tfmorris** 2020-01-30 18:58 UTC
Labels: Affects: Data, Affects: Server, Lead: @hornc, Needs: Investigation, Priority: 3, Theme: Public-APIs, Type: Bug
