### ISSUE TITLE
Revert button styling on Edition pages shows link which should be hidden

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2282] opened 2019-08-07 00:00 UTC
### Description

For Admins and (now very recently) Librarians who have access to revision revert buttons, the button styling on Edition pages looks like this:

![image](https://user-images.githubusercontent.com/905545/62584597-6e6d1e80-b909-11e9-9eca-0863d21fba70.png)

The problem is the unstyled button, and the duplicated link below it.

On Works and Author pages the expected result is:
![image](https://user-images.githubusercontent.com/905545/62584648-9c526300-b909-11e9-9c41-048523fd8000.png)

Inspecting the element in browser shows me the div=revertLink correctly gets its display=none from:
https://github.com/internetarchive/openlibrary/blob/f0514f9492a08edfca9e6f8e064cdfebcb5bfca8/static/css/page-user.less#L83
For works and authors.

For editions, the styling of that link looks like it is coming from page-book.css

I'm not exactly sure what the fix is -- it looks like the non-displayed duplicate link is deliberate, and the styling needs to be made consistent.

I'm hoping @jdlrobson you'll recognise what to do here :)

### Relevant url?

https://openlibrary.org/books/OL5063689M/Max_Ernst?v=7 for a broken example on an edition

https://openlibrary.org/works/OL2248600W/Max_Ernst?v=1 for the 'good' example on a work

Seeing and fixing this is going to be complicated by usergroups. See the recently added instructions here for instructions on how to test as different users in local dev:
https://github.com/internetarchive/openlibrary/wiki/Getting-Started#creating-users

### Details

- **Logged in (Y/N)?**  Y, As admin or librarian usergroup members

### Stakeholders

@jdlrobson 

### Review checklist

Added by @jdlrobson and needed to consider this DONE.

- [ ] Use the `hidden` class to hide the revert link in places it is not supposed to be seen. Remove any CSS that tries to hide it in a different manner.
- [ ] All the #revertLink rules (and related styles) from static/css/page-form.less, static/css/page-user.less static/css/page-edit.less into a new component that represents the revert function. The component should live in static/css/components/revertLink.less
- [ ] The component should be documented in the [Design pattern library](https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library)
- [ ] The new component will be loaded in static/css/page--for-admin-users.less that generates a stylesheet static/build/page--for-admin-users.css that is loaded by admins on all pages.

## Aspirational design

Ideally, we'd extend the admin-bar (naming it something generic like "advanced-options" (weak conviction on the naming here) and include `revert` which has appropriate librarian permissions/scoping. Details at @scottbarnes's discretion.

<img width="479" alt="Screenshot 2024-03-15 at 9 15 59 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/68bc4b53-8c1c-4a1c-ae09-7f3cace8ece3">

**Comment by tapaswenipathak** [comment] 2019-08-08 08:26
Hi @hornc, @jdlrobson: if you don't mind, I will take the issue on my head.

@hornc can you please label the priority of the ticket, if urgent I can PR today, otherwise I do on Monday.

**Comment by jdlrobson** [comment] 2019-08-10 17:04
I don't have librarian/admin access on OpenLibrary so can't easily check what the problem is. On my localhost I get "Recaptcha solution was incorrect" when I try to edit so I can't actually get to a revertable revision right now :-S

I've guessed what the problem is here and tried to spec out the fix I'd like to see as review checklist.

If the button just needs to be hidden, using the hidden class should suffice (with JS to remove it where necessary). I'd also like to use this opportunity to ensure the component styles only load where needed (in an admin specific stylesheet)

The styling for admin and librarian pages has been purposely neglected so far given the smaller audience. If this issue only impacts librarians/admins I'd be tempted to drop this to priority low.

**Comment by hornc** [comment] 2019-08-13 02:32
Thanks for adding the checklist @jdlrobson! That might be enough to enable me to fix it, because I do run into the issue frequently.

I'd like to get us to a point where it is easier for devs to test using different users, I've recently updated https://github.com/internetarchive/openlibrary/wiki/Getting-Started#creating-users to help with viewing the site as different users in local environments.

I agree with your assessment that this is lower priority though. @tapaswenipathak it might me more useful for you to focus on some standard user facing issues that are easier to confirm work?

**Comment by tapaswenipathak** [comment] 2019-08-13 03:58
Feel free taking the ticket if you feel like. I might give the ticket few hours today.  :)

**Comment by jdlrobson** [comment] 2019-08-16 16:54
@hornc lemme know if there's anything left to do on this (Please reassign me if so) or if this can be closed!

**Comment by hornc** [comment] 2023-09-10 21:02
Still an issue https://openlibrary.org/books/OL5063689M/Max_Ernst?v=7 (original reported example)
Removing my lead tag as I am not working on UI aspects of OL, and have never been UI lead.

**Comment by Realmbird** [comment] 2024-03-08 21:01
Can I attempt this "assign me"

**Comment by Realmbird** [comment] 2024-03-08 21:03
I see where the css file is located where is the html and javascript located for this page

**Comment by Realmbird** [comment] 2024-03-13 02:36
I have been looking at the site but, how do I find this revert button on the open library if it is only for admins how do I test or debug if my solution works

**Comment by Realmbird** [comment] 2024-03-13 02:57
![Uploading Edit Book didn't edit tried finding revert button.PNG…]()

**Comment by Realmbird** [comment] 2024-03-13 02:57
![Edit Book didn't edit tried finding revert button](https://github.com/internetarchive/openlibrary/assets/56459277/b2ba6f0f-75d6-4b38-8bb8-a78c3cf6886a)

**Comment by Realmbird** [comment] 2024-03-13 03:04
looked at how there was 

Relevant url?

https://openlibrary.org/books/OL5063689M/Max_Ernst?v=7 for a broken example on an edition

https://openlibrary.org/works/OL2248600W/Max_Ernst?v=1 for the 'good' example on a work

So if I understand correctly since I visited these pages and didn't find the revert button, I need to create a user using the source another person gave me?
I am kinda new to docker so I will post again if I have problems creating user with admin perms in my local docker
https://github.com/internetarchive/openlibrary/wiki/Getting-Started#creating-users

**Comment by scottbarnes** [comment] 2024-03-13 13:41
My apologies, @Realmbird. I had written which files you might want to look at and how I found them, and I don't know if I failed to submit the comment, or what, but I certainly don't see it here. That's a bit depressing.

With respect to not seeing the 'revert' button, you'll want to do all of this on your local development instance in Docker, while logged in as the default `admin` user, so getting that running is the first step. See https://github.com/internetarchive/openlibrary/tree/master/docker#readme for that.

Next, you'll want to look at how to make changes to CSS and JS such that the appropriate files are built: https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#css-js-and-html

In terms of which files to edit, I did `git grep "Revert to this revision"` to find that `openlibrary/templates/viewpage.html` looked like the HTML page you will want to edit. I may be mistaken, but I don't think you'll need to edit JS for this, as this looks to simply do a POST via `<form>`. So I think you may just need to update HTML and CSS.

**Comment by Realmbird** [comment] 2024-03-13 15:09
Thanks I will be working on this immediately

**Comment by Realmbird** [comment] 2024-03-14 01:02
@scottbarnes 
![Screenshot from 2024-03-13 17-58-51](https://github.com/internetarchive/openlibrary/assets/56459277/31f68c8d-2657-4674-9c86-ddf34663e774)
![Screenshot from 2024-03-13 17-59-02](https://github.com/internetarchive/openlibrary/assets/56459277/daedba1d-74a7-497f-9022-4c44ff44bc59)
I got the docker to work I will now be reading the front end guide. I got a picture of the development environment book but, what do I need to do to see the revert button. Also when I looked at the view template why not just delete the button and keep the revert in the form, is there a reason two buttons to same request. So I think removing "<div id="revertLink"><a rel="nofollow" href="$changequery(m='revert')">$_("Revert to this revision")</a>?</div>" solves the problem but, how do I check the result I don't know how to cause the revert button to appear I tried making edit and adding comment nothing but, not sure how I can see revert button

**Comment by Realmbird** [comment] 2024-03-14 01:02
My idea
![Screenshot from 2024-03-13 18-01-34](https://github.com/internetarchive/openlibrary/assets/56459277/71e27701-42d6-417e-aabb-3e95c4181c79)

**Comment by Realmbird** [comment] 2024-03-14 01:03
The code has two buttons that sends same request so just removed the one that I assume is not desired which is the link as in his ideal version there is only the button

**Comment by scottbarnes** [comment] 2024-03-14 02:00
I'm also not sure why there are two links for reverting, but removing one makes sense as a test. The issue summary speculates it may be intentional, so it would be great if you can figure out why that might be there. But if you remove it and everything works properly, perhaps the reason for the duplication will remain a mystery.

In terms of getting the revert button to display, you'll need to make an edit to an edition, as you mentioned doing, and _then_ view the history (the link to view the history on the upper right of the edition page, next to the "Edit" button), and then select a prior version. From that page you should be able to see and use the revert button.

**Comment by Realmbird** [comment] 2024-03-14 15:39
Removing that one line fixes it

**Comment by Realmbird** [comment] 2024-03-14 15:40
![Screenshot from 2024-03-14 08-39-57](https://github.com/internetarchive/openlibrary/assets/56459277/0f8c3529-8b88-4ebc-872f-d1461afd9ca2)
![Screenshot from 2024-03-14 08-40-15](https://github.com/internetarchive/openlibrary/assets/56459277/e4115178-2961-4d5b-939e-a7647a4ea17d)

**Comment by Realmbird** [comment] 2024-03-14 15:43
Funny removing one line fixed the bug

**Comment by Realmbird** [comment] 2024-03-14 15:54
Think error caused wrong css file used on html how do I check this

**Comment by Realmbird** [comment] 2024-03-14 16:32
![Screenshot from 2024-03-14 09-30-33](https://github.com/internetarchive/openlibrary/assets/56459277/f927014b-9eca-4a19-8028-a1c9b82a8c61)
I noticed only css files added are page-book and page-dev css only

**Comment by scottbarnes** [comment] 2024-03-14 17:32
If you edit a `.less` file, you'll need to rebuild CSS by following the front end guide: https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#css-js-and-html.

In this case, I am not sure of the best place to put the styling, but perhaps it makes sense to try:
1. changing `viewpage.html` so that the `div id="revertLink"...>` line is gone; and
2. adding the following to one of the `less` files loaded when viewing that page:
```css
// openlibrary/templates/viewpage.html
div#revertNotice {
  padding: 5px;
  background-color: @dark-green;
  form {
    display: inline-block;
  }
  text-align: center;
}
```
I am not entirely sure if this should go in one of the existing `.less` files or a new one. For now perhaps just put it in `work.less` and we can figure out where it goes once everything looks good. At this point you just want to try to get the styling right so it matches our reference image as posted in the image description.

I think the next step is to probably open a PR as it will be easier to comment on code changes that way.

Finally, you'll probably want to change the button styling for the revert button in `viewpage.html` so that it matches those buttons in the admin bar, even though that means the revert button won't perfectly match the reference image.

**Comment by Realmbird** [comment] 2024-03-14 18:53
Not sure what you mean for everything but, what I understand is
Sure:
1. Try changes in work.less file
2.  change viewpage.html
Not sure: 
1. What does PR mean
2. "you'll probably want to change the button styling for the revert button in viewpage.html so that it matches those buttons in the admin bar, even though that means the revert button won't perfectly match the reference image." What do you mean matches button in admin bar so instead of reference make button look like other buttons

**Comment by scottbarnes** [comment] 2024-03-14 22:35
I apologize for using acronyms. :) A "PR" is a pull request, which is a mechanism by which you can contribute code to another repository. Open Library has some directions about [creating a pull request](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#creating-a-pull-request), and it shouldn't be too hard to find supplemental information if you need it.

In terms of (4), the styling of the revert button in `viewpage.html`, the buttons in the admin bar, as shown here (`Add to Staff Picks`, etc.), have a particular styling, and I was thinking it might be good to have the styling of the revert button match:
![image](https://github.com/internetarchive/openlibrary/assets/26524678/a1ed2fb3-a1fb-4b5f-a26d-b80e3bcf0b25)

For now, let's focus on getting your changes into a pull request that (1) makes it so there is one revert button, and (2) that one revert button looks like the one shown in the summary at the top of this issue. Then we can worry about the exact styling of the revert button vis-a-vis the other buttons nearby. 

Eventually we will probably want to create a new component, perhaps `revertButton.less` or something, and then ensure it shows up on every page that has a history that can be edited, but let's not worry about that yet. I am just writing that down now to help us remember.

**Comment by Realmbird** [comment] 2024-03-15 00:28
Ok thanks for your help I am a beginner so I am enjoying this process of learning

**Comment by Realmbird** [comment] 2024-03-15 00:29
If I understand I just first make pull request to make one revert button then I make a another one to make it look better will do this when I get back home

**Comment by scottbarnes** [comment] 2024-03-15 00:52
I am happy to help, and I am happy you are helping Open Library. In terms of the pull requests, let's just start with one, and perhaps it will turn out everything can be done within the same pull request. :)

**Comment by Realmbird** [comment] 2024-03-15 07:18
What did I do wrong I tried making branch
![Screenshot from 2024-03-15 00-16-29](https://github.com/internetarchive/openlibrary/assets/56459277/34158d1d-0229-492d-9d00-5c49d03b0d21)

![Screenshot from 2024-03-15 00-18-09](https://github.com/internetarchive/openlibrary/assets/56459277/6309e14b-4192-408b-95ab-8fd170737116)
Tried making first pull request got this error what did I did wrong I made a new branch but, I can't push it

**Comment by cdrini** [comment] 2024-03-15 08:52
Ah your remote is incorrect you will have to pull from your fork. See the beginning of the documentation here on how to make a fork: https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet . Make sure to set your GitHub USERNAME when you clone your fork!

**Comment by Realmbird** [comment] 2024-03-15 16:41
@scottbarnes @cdrini 
Have done the fork now it works, currently working on making pull request 
![Screenshot from 2024-03-15 09-39-26](https://github.com/internetarchive/openlibrary/assets/56459277/b847c81d-6417-40ef-9f6d-b37ce137809c)
![Screenshot from 2024-03-15 09-40-03](https://github.com/internetarchive/openlibrary/assets/56459277/fd5a3d83-817f-48f5-8bb8-72a350b658ae)
### Not sure why docker compose exec web make test didn't work

**Comment by Realmbird** [comment] 2024-03-15 16:48
Sent pull request https://github.com/internetarchive/openlibrary/pull/8908

**Comment by Realmbird** [comment] 2024-03-15 16:50
Made mistake did git add . not git add file doing pull request again

**Comment by Realmbird** [comment] 2024-03-15 17:15
@QuantuM410  how do run "docker compose run web make test" as I keep got error host variable not set for first time after I did git add .. Not sure after I removed my previous file for repo and re m
![Screenshot from 2024-03-15 10-15-11](https://github.com/internetarchive/openlibrary/assets/56459277/f7ded60c-230b-4230-b6cc-0873d7b4778a)
ade a new fork and did changes again "docker compose run web make test" worked not sure why 
![Screenshot from 2024-03-15 10-14-31](https://github.com/internetarchive/openlibrary/assets/56459277/7df869d8-1be5-4580-9842-19be3ff0d704)

**Comment by QuantuM410** [comment] 2024-03-15 17:30
> @QuantuM410  how do run "docker compose run web make test" as I keep got error host variable not set for first time after I did "git add .". Not sure after I removed my previous folder for repo and deleted the previous fork repo and made new fork and made changes to it and just "git add openlibrary/templates/viewpage.html" The testing worked?
> ![Screenshot from 2024-03-15 10-15-11](https://github.com/internetarchive/openlibrary/assets/56459277/f7ded60c-230b-4230-b6cc-0873d7b4778a)
> ade a new fork and did changes again "docker compose run web make test" worked not sure why 
> ![Screenshot from 2024-03-15 10-14-31](https://github.com/internetarchive/openlibrary/assets/56459277/7df869d8-1be5-4580-9842-19be3ff0d704)
> 
> 
> 
> 

The host variable error is common for all so that's not an issue. Your web container should be running to perform those tests. Also it would be easier for you to setup ```precommit```. It runs the tests and linting whenever u try to commit the changes.

**Comment by scottbarnes** [comment] 2024-03-16 00:51
@Realmbird, as @QuantuM410 mentioned, if you use `docker compose exec` the container needs to be running:
```
❯ docker compose exec --help       

Usage:  docker compose exec [OPTIONS] SERVICE COMMAND [ARGS...]

Execute a command in a running container
```

However, if your containers are not running you can also use `docker compose run home make test`, and that will run all the tests using the `home` container:
```
❯ docker compose run --help                                       

Usage:  docker compose run [OPTIONS] SERVICE [COMMAND] [ARGS...]

Run a one-off command on a service
```
For what it's worth, the `web` container would work too, but it depends on other containers, so they need to start to run the tests, whereas `home` just needs itself.

If you get hung up trying to remove all the files from your previous commit, it may be easiest to simply make a new branch and then create a new commit there that includes only the change(s) you want.

**Comment by Realmbird** [comment] 2024-03-16 00:54
I made new branch and redid commit

**Closed** 2024-03-16 01:32 UTC
Labels: Type: Bug, Module: JavaScript, Priority: 3, Good First Issue, Affects: UI, Theme: Design, Affects: Librarians, reCaptcha, Lead: @scottbarnes

**Comment by Realmbird** [comment] 2024-03-16 01:48
@scottbarnes  should I make another issue to make the revert button look like the images you said maybe calling it "making revert button consistent with other buttons"

**Comment by Realmbird** [comment] 2024-03-16 01:51
Also if I finish this issue what should I do after the first issue

**Comment by scottbarnes** [comment] 2024-03-16 02:28
@Realmbird, I opened #8911 to address unifying the admin bar and revert button. That said, I am not sure if we should proceed at the moment, as it's going to be more involved than I had thought.

**Comment by Realmbird** [comment] 2024-03-16 05:12
@scottbarnes Ok also what should I do after I finished this first commit is there a new level or do I just get any issue I think I could possibly do
