### ISSUE TITLE
Lists should follow redirects when rendering

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4563] opened 2021-02-09 19:23 UTC
### Evidence

![image](https://user-images.githubusercontent.com/6251786/107540363-f9c90f00-6b93-11eb-9250-bc181effe536.png)

### Relevant url?
e.g. https://openlibrary.org/people/seabelis/lists/OL140479L/Duplicate_Work?page=16 (at the bottom)

* Actual: Redirects appear broken
* Expected: Redirects should be followed, and appear as normal books

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF85
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@seabelis

**Comment by seabelis** [comment] 2021-02-18 09:14
Is this a duplicate of https://github.com/internetarchive/openlibrary/issues/501 ?

**Closed** 2021-03-04 14:15 UTC
Labels: Lead: @mekarpeles, Priority: 2, Type: Bug
