### ISSUE TITLE
 Update Twitter icon in the footer to the X icon

### ISSUE THREAD

**Issue by NayanshiSingh** [internetarchive/openlibrary#9676] opened 2024-08-01 21:52 UTC
### Problem

![Screenshot 2024-08-02 031459](https://github.com/user-attachments/assets/856af7ee-39b8-4f52-b887-3a8aa36c5878)

The Twitter icon in the footer should be updated to the new X icon to reflect the rebranding.

### Reproducing the bug

To Reproduce:
 

1. Go to the footer of any page.
2. Locate the Twitter icon.

Expected behavior:
A clear and concise description of what you expected to happen:
The Twitter icon should be replaced with the new X icon.

### Context

- Browser (Chrome, Safari, Firefox, etc): Crome
- OS (Windows, Mac, etc): Windows
- Logged in (Y/N): Y
- Environment (prod, dev, local): local

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by ayush2743** [comment] 2024-08-02 01:27
@cdrini @mekarpeles @jimchamp 
Hi, I would like to work in this issue. Can you assign it to me please?

**Comment by NayanshiSingh** [comment] 2024-08-02 02:10
@mekarpeles , @cdrini , @jimchamp, @scottbarnes can you please assign this issue to me I would love to work on this issue!!

**Comment by scottbarnes** [comment] 2024-08-02 02:17
Alas, @NayanshiSingh, this was just addressed. See the footer here: https://testing.openlibrary.org/
 
Duplicate of #9572, closed by #9573.

**Closed by scottbarnes** 2024-08-02 02:17 UTC
Labels: Type: Bug, Needs: Triage, Needs: Lead
