### ISSUE TITLE
Increase expiry date / maximum age for static resources to 1 day

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1367] opened 2018-10-18 15:45 UTC
In #1264 we talk about potential performance improvements. One that is very actionable is setting longer expiry dates for static resources.

"Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network."

Note: all expiry dates suggested are just guidelines - feel free to cache longer if it makes sense!

- [ ] Add expiry date header (currently 10mins, at least 24hrs seems appropriate) for covers e.g. https://covers.openlibrary.org/b/olid/OL14034633M-M.jpg
- [ ] Add expiry date header for all files in static folder (currently 60 minutes, at least 24hrs seems appropriate) e.g.  https://openlibrary.org/static/images/categories/art.svg, https://openlibrary.org/static/images/down-arrow.png 
- [ ] Add expiry date header (currently 6hrs, at least 24hrs seems appropriate) for archive.org resources (e.g. https://archive.org/services/img/TargetingE_00_Nich)
- [ ] Add expiry date header for analytics.archive.org resource  (currently 6hrs, at least 24hrs seems appropriate) (e.g. https://analytics.archive.org/…1=25.6px&ga_cd2=2.625&version=2&count=10)

**Comment by brad2014** [comment] 2019-05-10 07:39
Note: analytics.archive.org link is 404 Not Found.  Did it move?

**Comment by brad2014** [comment] 2019-05-10 07:43
Note: Log analysis (fetches of static from same IP within 6-24 hour window) would show if this would have an effect on performance, and perhaps give an idea what rational settings would be, if one wanted to improve on the 24h number.

**Comment by brad2014** [comment] 2019-05-10 07:46
(note for labelers:  if this were in response to a user complaint, it would be `Type: Bug`.  if it were in response to server overload, it would be `Type: Refactor/Clean-up`.  Since the issue is focused on improving user experience, its a `Type: Feature`)

**Comment by jdlrobson** [comment] 2019-05-11 07:20
I think this one lies more in the realms of sys admin.

Would Charles know what needs to be done here?

**Comment by brad2014** [comment] 2019-05-11 13:48
@mekarpeles  or @hornc, should one of you own this?

**Comment by guyjeangilles** [comment] 2019-11-20 21:11
@mekarpeles What's stopping progress on this issue?

**Comment by RayBB** [comment] 2023-10-06 20:27
I looked briefly into how we might cache covers.
A small heads up on that, the nginx service that runs in prod (where we might set cache headers) doesn't run in the local environment by default.

**Comment by RayBB** [comment] 2024-05-22 18:12
We can close this now that this pr has been merged.
It drastically improve the caching and handles all the cases mentioned.
https://github.com/internetarchive/openlibrary/pull/8930

**Closed by RayBB** 2024-05-22 18:12 UTC
Labels: Type: Feature Request, Module: Memcache, Theme: Performance, Affects: UI, Priority: 2, Lead: @RayBB
