### ISSUE TITLE
ISNI field does not strip whitespace from values

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5696] opened 2021-09-27 08:02 UTC
From a patron:
_the ISNI field does not strip whitespace from values so the url generation is not enforced for valid links - example: http://www.isni.org/0000%200001%202130%209873 was generated due to the ISNI field contained - "0000 200001 202130 209873" if the field removed whitespace to be "0000200001202130209873" the url correctly will format._

### Relevant url?

https://openlibrary.org/authors/OL1643202A
http://www.isni.org/0000%200001%202130%209873
### Steps to Reproduce

1. Go to ...an author page
2. Do ...add ISNI with spaces, "0000 200001 202130 209873" 

* Actual: invalid url
* Expected: white spaces should be stripped so url is generated properly

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by bencomp** [comment] 2022-08-05 14:23
I just noticed this behaviour (and updated the ISNI manually). The merged pull request #5697 does not solve this, because it only removes (leading and) trailing spaces, not spaces within the identifier. It may work differently for different types of identifiers too, so removing all whitespace in all identifiers is probably not the solution. #6423 is strongly related to (or a duplicate of) this issue.

**Closed** 2022-08-07 18:20 UTC
Labels: Type: Bug, Priority: 3, Affects: Data, Lead: @seabelis, Affects: Experience
