### ISSUE TITLE
Update alt text for history/edit buttons

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9012] opened 2024-04-02 19:12 UTC
### Problem

Alt text currently refers to the pages as "template" but that is wrong and probably a bit confusing for anyone relying on the alt text.

It should probably "page" instead of template.

Happens on works/authors and probably other places too.

#### Evidence / Screenshot
<img width="1150" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/fb9ee479-72f9-416b-86a0-1136f9ab26b3">
<img width="1135" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/e8ebba6e-cc25-40cf-9edf-4d3789b4033d">

#### Relevant URL(s)
- https://openlibrary.org/works/OL20012930W/

### Reproducing the bug

1. Go to https://openlibrary.org/works/OL20012930W/
2. Hover over the edit/history buttons as in screenshots
3. Seen the wrong alt text

#### Proposal & constraints

If you would like to work on this please just comment saying so and start right away. I'll assign you shortly after 👍

**Comment by Spedi** [comment] 2024-04-02 21:46
Hi there!
I'm a freshman Applied Math student who's currently learning Python, and I'm trying to find easy issues to tackle in order to start contributing to Open Source projects.
Is there any chance that I can help you with this issue?

**Comment by RayBB** [comment] 2024-04-02 21:52
@Spedi absolutely welcome aboard! Go ahead and follow the getting started guide and try to make the change.
How did you find this project and ticket?
Also, please let us know if/how the getting started docs could be improved!

**Comment by Spedi** [comment] 2024-04-02 22:15
I found this project because I'm planning to try to enter GSoC next year, and so I'm starting to approach the OSS world and the various organizations.
Plus I often use the Internet Archive website, so it is really a pleasure to contribute to it!

**Comment by RayBB** [comment] 2024-04-02 22:16
So you were looking at a list of orgs hosting GSoC for next year? Can you share the particular link to where you found Open Library? I am just curious, if you don't remember it isn't important. @Spedi

**Comment by Spedi** [comment] 2024-04-02 22:25
Yep, not for the 2024 edition though (it's too late and I'm still learning the basics of Python, so I wouldn't be prepared enough to tackle big projects).
This is the link: https://summerofcode.withgoogle.com/programs/2024/organizations/internet-archive.

**Comment by RayBB** [comment] 2024-04-02 22:36
@Spedi well if you stick around I'm sure you could have a great proposal for next year!

**Comment by Spedi** [comment] 2024-04-02 23:06
I hope so, I'm looking forward to contribute to the project often hopefully!
I finished doing my PR, but Docker isn't working well so I didn't manage to get a screenshot of the changes, is it a problem or should I commit the changes anyway?

**Comment by RayBB** [comment] 2024-04-03 08:47
@Spedi 
Go ahead and open your PR without the screenshots for now.
What is the issue you're facing with your Docker setup?

**Comment by Spedi** [comment] 2024-04-03 09:24
I've never used Docker before, so I just followed the guide that's on the Wiki to install it and use it.
The problem is that when I try to do `docker compose up`, I always get the **FATAL: role "openlibrary" does not exist** error, even though I tried resolving it with the steps written on the Wiki.

**Comment by RayBB** [comment] 2024-04-03 10:24
@Spedi what happens when you follow [these](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md#an-error-similar-to-fatal-role-openlibrary-does-not-exist) steps in the wiki?

**Comment by Spedi** [comment] 2024-04-03 10:42
@RayBB Those are the steps that I've been following, unfortunately with no success.
This is the error that I get on the localhost page: **/openlibrary/openlibrary/templates/home/index.html: error in processing template: OperationalError: connection to server at "db" (172.19.0.2), port 5432 failed: FATAL: role "openlibrary" does not exist (falling back to default template)**.
Is there any software/dependencies/ecc that I need to have to make docker run correctly?

**Comment by RayBB** [comment] 2024-04-03 10:44
@Spedi can you please share the exact commands you ran and what the output was. If you are in Slack it would be great to post it there so others can help. If not, you can join by filling out the volunteer form on the website.

**Comment by Spedi** [comment] 2024-04-03 10:51
@RayBB Sure! I'm going to post it on Slack, thank you for your help and patience!

**Comment by scottbarnes** [comment] 2024-04-03 13:29
I didn't see the thread on Slack, but have you also followed these steps (ensuring the `Administrator` account is used when necessary), @Spedi? https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#fix-line-endings-symlinks-and-git-submodules-only-for-windows-users-not-using-a-linux-vm

The other question I have is whether you're using WSL, which because of the error, I think you may not be? If not, it may be worth checking out: https://learn.microsoft.com/en-us/windows/wsl/install.

Though not a Windows user, I wrote most of the Windows-specific help to get the project running, and using WSL seems to avoid a lot of the problems.

**Comment by Anchellon** [comment] 2024-04-04 07:22
Hi @Spedi @RayBB 
I was also looking into this issue and would be Happy to help with an extra pair of eyes on this! 
I have applied for gsoc 2024 and I was hoping to start contributing to the Internet archive !

**Comment by kpan02** [comment] 2024-04-08 04:08
Hello! I am interested in working on this issue as well.

**Closed** 2024-04-08 20:00 UTC
Labels: Type: Bug, Good First Issue, Lead: @RayBB, Needs: Staff / Internal
