### ISSUE TITLE
Searching for books in other languages very hard

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#643] opened 2017-11-11 20:49 UTC
If I search for only public domain + borrowable books in spanish, I get a list of works containing a spanish book, but there is no sane way for me to identify the spanish edition or to see whether it's available. Instead, the availability tells me if any copy of the book is available (not necessarily the spanish version).

This is another case which could be solved by searching against Archive.org using the /browse UI proposed in #602 

https://openlibrary.org/search?q=subject%3Ain_library+OR+subject%3Aaccessible_book&mode=ebooks&language=spa&has_fulltext=true

**Comment by LeadSongDog** [comment] 2017-11-17 19:43
This is because we get the work rather than the edition as the search result. It should be a user option radio button.

**Comment by tfmorris** [comment] 2018-03-24 19:20
This sounds like a duplicate of #448

**Comment by LeadSongDog** [comment] 2018-08-03 19:38
It isn't really a search issue, so much as a problem with the way that search results are shown to the user. Even for a search on an ISBN the user is shown the entire work result, if not a list of works:
https://openlibrary.org/search?q=0199120099&mode=everything
This should send the user directly to https://openlibrary.org/books/OL7402600M/Aristophanes

**Comment by LeadSongDog** [comment] 2018-10-25 21:30
@mekarpeles perhaps correct the issue title to “Show matching edition” as a start?

**Comment by mekarpeles** [comment] 2018-10-25 21:49
@LeadSongDog one of the reasons we currently search by work is, a search for Moby Dick would give you several hundred results for the same work.

I am not convinced (based on the calls we've had) that the right answer *is* to to exclusively show edition results. This isn't what goodreads does, for instance. But their search *is* robust to language. I think we'd be losing a lot if we (in a binary sense) completely switched from `work` search to `edition` search. I think some sort of hybrid approach is necessary (which groups by work but shows the relevant/matching edition).

We do have an endpoint exclusively for edition searches https://openlibrary.org/search/editions but I'm not sure that it works -- this does seem like a good place to start (i.e. at least provide the option). Still this would fundamentally require us to change how all our works (and or editions) are indexed in our search engine which should be the subject of a community call (/ is not something to be taken/done lightly)

**Comment by mekarpeles** [comment] 2018-10-25 21:51
#342 seems like a good first place to start.

**Comment by guyjeangilles** [comment] 2019-11-04 01:31
Agreed with Tom, this is a duplicate of #448. Closing

**Closed by guyjeangilles** 2019-11-04 01:31 UTC
Labels: Theme: Search, Type: Bug, languages
