### ISSUE TITLE
All create/update/delete operations broken

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7920] opened 2023-06-01 09:08 UTC
Since about nine hours ago, no edits have been made to Open Library. If I attempt to make an edit I see the following error:
`b'<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n'
`
### Evidence / Screenshot (if possible)
<img width="1180" alt="Screenshot 2023-06-01 at 09 23 20" src="https://github.com/internetarchive/openlibrary/assets/17739465/013a6b3b-db3f-4066-9bcd-1f2859c3bae3">

### Relevant url?
https://openlibrary.org/...

### Steps to Reproduce

1. Go to ...openlibrary.org
2. Do ...try to edit something.

* Actual: error as noted above.
* Expected: edit successfully saved.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp @cclauss @scottbarnes

**Comment by LeadSongDog** [comment] 2023-06-01 11:53
Seems to have started about 18:48 EDT (“12 hours ago” became “13 hours ago” about 07:48.

**Comment by cclauss** [comment] 2023-06-01 12:38
https://sentry.archive.org/organizations/ia-ux/issues/357925 is an example of this error.

I suspect that turning off `ol-home` might be the cause of this.  Step 3 of #5143

**Comment by cclauss** [comment] 2023-06-01 13:55
I undid step 3 of #5143

**Comment by LeadSongDog** [comment] 2023-06-01 14:11
@cclauss That seems to have cured it for now. Edits are happening again. https://openlibrary.org/recentchanges/edit-book

**Comment by cclauss** [comment] 2023-06-01 14:17
I am glad to hear it!

**Comment by cdrini** [comment] 2023-06-01 19:24
Marking as resolved. Great quick response @cclauss !

**Closed by cdrini** 2023-06-01 19:24 UTC
Labels: Type: Bug, Priority: 0, Needs: Triage, Affects: Librarians, Affects: Experience, Needs: Lead
