### ISSUE TITLE
Author autocomplete shows death=birth

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#745] opened 2018-01-13 02:51 UTC
Compare these:

![image](https://user-images.githubusercontent.com/11435431/34902095-618eae28-f80c-11e7-8f0f-034bbdda6e48.jpeg)
![image](https://user-images.githubusercontent.com/11435431/34902096-61b0ad84-f80c-11e7-8486-8868ac23d9ba.jpeg)

**Comment by cdrini** [comment] 2018-01-13 04:14
Whoops! Me again, from #660 ; here's where the issue is:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/edit.html#L123

**Comment by kaarora123** [comment] 2018-01-17 10:01
Hi! Can I work on this or is this already fixed?

**Comment by mekarpeles** [comment] 2018-01-17 10:28
@kaarora123 go for it! Should be a fairly straightforward one; if you get stuck @cdrini and I can point you in the right direction.

Just merged in two changed which fix our local dev environment so please make sure your repo is up to date and let us know if you have any questions :)

**Comment by kaarora123** [comment] 2018-01-17 10:59
Thank you! This is my first contribution, so if I did anything wrong please let me know.

**Closed** 2018-01-18 01:51 UTC
Labels: Editing, authors, bug, easy
