### ISSUE TITLE
Subject names with "/" in them break

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#727] opened 2018-01-05 10:25 UTC
If one does a subject search for https://openlibrary.org/search/subjects?q=fiction+%2F+thriller and then clicks on "FICTION / Thrillers", the resulting subject page (i.e. https://openlibrary.org/subjects/fiction_/_thrillers) breaks.

reported via https://twitter.com/bucksci/status/948318580826918912

**Comment by LeadSongDog** [comment] 2018-01-05 18:24
Found at https://openlibrary.org/subjects/fiction__thrillers
Just need to cull the slash from the slug.

**Comment by LeadSongDog** [comment] 2018-01-05 18:59
Looking at the very first example, LC Bot seems to have faithfully pulled in that subject on 22 October 2011  from https://lccn.loc.gov/2011035738 via https://openlibrary.org/show-records/marc_loc_updates/v39.i38.records.utf8:10298944:3580
That was some months before the first edition's publication date, but close enough that it would have been in pre-press. The LoC shows "FICTION / Thrillers." as one of the "BISAC Subject Headings", not a LoC Subject Heading. However, http://bisg.org/page/BISACSubjectCodes only lists it with further sub-qualifiers such as 
FIC031000      FICTION / Thrillers / General 
or 
FIC031090      FICTION / Thrillers / Terrorism
However, since OL just treats that as free text anyhow, I'm sure it doesn't matter here.

**Comment by LeadSongDog** [comment] 2018-10-19 16:52
Compare:
https://openlibrary.org/subjects/fiction_:_thrillers 
https://openlibrary.org/subjects/fiction__thrillers
https://openlibrary.org/subjects/fiction_thrillers
https://openlibrary.org/subjects/fiction_/_thrillers
https://openlibrary.org/subjects/fiction_%2F_thrillers
https://openlibrary.org/subjects/fiction+/+thrillers
https://openlibrary.org/subjects/fiction+%2F+thrillers

**Comment by mekarpeles** [comment] 2019-03-29 22:12
@JeffKaplan

**Comment by tfmorris** [comment] 2019-04-11 21:24
This is a duplicate of #333 from @bfalling 2 1/2 years ago.

re @jdlrobson's question:
> So should https://openlibrary.org/subjects/fiction_/_thrillers actually be linking to https://openlibrary.org/subjects/fiction__thrillers ?

Yes, I believe it should. That would be a quick fix to the 404s while we work on a more long term solution.

**Comment by hornc** [comment] 2019-05-05 09:57
Also, the works page links in the subjects heading are not escaped: e.g. https://openlibrary.org/works/OL149210W/Thinner

However the "related subjects" on a subjects page are: https://openlibrary.org/subjects/fiction__thrillers

**Comment by tfmorris** [comment] 2019-05-06 01:11
Closing as a duplicate of #333.

The problem that @hornc just reported:

> Also, the works page links in the subjects heading are not escaped: e.g.  https://openlibrary.org/works/OL149210W/Thinner

Should get its own separate issue.

**Closed** 2019-05-06 01:11 UTC
Labels: Close: Duplicate
