### ISSUE TITLE
Log In + Sign Up link styling broken on Book pages

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4933] opened 2021-03-29 19:05 UTC
@Yashs911 reported 14 days ago:
CSS for Log In and Sign Up seems to be missing from the Books Page (http://staging.openlibrary.org/works/OL6384123W/Self-knowledge and now on production https://openlibrary.org/works/OL6384123W/Self-knowledge)

### Evidence / Screenshot (if possible)
![openlibrary org_works_OL6384123W_Self-knowledge](https://user-images.githubusercontent.com/978325/112886514-e3650d00-9086-11eb-99dc-a5dd5ef06620.png)

### Relevant url?

https://openlibrary.org/works/OL6384123W/Self-knowledge

### Steps to Reproduce

1. Go to ... https://openlibrary.org/works/OL6384123W/Self-knowledge) incognito

### Details

- **Logged in (Y/N)?**  N
- **Browser type/version?** chrome 
- **Operating system?**  linux
- **Environment (prod/dev/local)?** prod + staging

### Stakeholders

@cdrini @jamesachamp @jdlrobson j

**Comment by jdlrobson** [comment] 2021-03-29 19:22
The problem is `components/buttonsAndLinks.less` and the file `components/buttonBtn.less` which it imports have both been marked as legacy CSS (by inclusion inside static/css/legacy.less), yet it's now needed on a page which is not using legacy CSS (books page)

The following should be added to static/css/page-book.less :

 `@import "components/buttonBtn.less";`

Longer-term, let's remember not to rely on any styles inside static/css/legacy.less. Setting up a storybook for documenting CSS should be a higher priority IMO to avoid this.

**Comment by cdrini** [comment] 2021-03-29 20:12
Dipping priority since we've evaluated it and it looks impact is constrained to these buttons.

**Closed** 2021-06-05 03:05 UTC
Labels: Affects: Experience, Good First Issue, Lead: @jamesachamp, Priority: 2, Regression, Team: Front-end, Type: Bug
