### ISSUE TITLE
No results for authors with a hyphen in their name

### ISSUE THREAD

**Issue by HamsterDeveloper** [internetarchive/openlibrary#6088] opened 2022-01-31 01:16 UTC
Hyphens seem to break the search of the author field when adding a new book.

1. Go to [Add a Book](https://openlibrary.org/books/add)
2. Enter a name with hyphens into the author field (example: Agnieszka Lingas-Łoniewska)

* Actual: No results; only "create a new record for ..." is offered.
* Expected: Listing existing author entries to choose from.

**Comment by cdrini** [comment] 2022-04-11 18:52
Here is the relevant code:

https://github.com/internetarchive/openlibrary/blob/8b983898879a48d2386610e790814145e783c17d/openlibrary/plugins/upstream/addbook.py#L1074-L1115

Not sure why this isn't working.

**Comment by tfmorris** [comment] 2022-04-12 00:28
This is an exact duplicate of #4800 which was opened 13 months ago and related to #790 from 2018.

**Comment by mekarpeles** [comment] 2022-12-20 00:04
Seems to be resolved on /addbook for Jean-Paul Sartre
And also search https://openlibrary.org/search/authors?q=Jean-Baptise+

**Closed by mekarpeles** 2022-12-20 00:04 UTC
Labels: Type: Bug, Theme: Search, Module: Authors, Priority: 2, Lead: @cdrini

**Comment by tfmorris** [comment] 2023-02-01 14:59
This is still broken. I've added the example from the original issue (Agnieszka Lingas-Łoniewska) to #790.
