### ISSUE TITLE
"Unable to render this page" - https://openlibrary.org/books/OL11562694M

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#4224] opened 2020-12-06 20:00 UTC
I'm not sure if this got broken by the large garish ad that takes up the majority of the screen or something else.

### Evidence / Screenshot (if possible)
![Screen Shot 2020-12-06 at 2 56 22 PM](https://user-images.githubusercontent.com/82178/101290982-7d9cfe80-37d3-11eb-93f1-44e6f29b736a.png)

### Relevant url?

https://openlibrary.org/books/OL11562694M/Chainsaws_as_a_Tool_for_Conservation_%28Rural_Development_Forestry_Network_Paper%29?edition=

### Steps to Reproduce

1. Go to ... the url above
2. Do ...

* Actual: large garish ad taking up most of the screen and no book information
* Expected: book info with no ad

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment] 2020-12-08 18:39
Dupe of #4052

**Closed by mekarpeles** 2020-12-08 18:39 UTC
Labels: Needs: Triage, Type: Bug

**Comment by tfmorris** [comment] 2020-12-08 22:28
Actually a dupe of #3760 from over 3 months ago (and #4051). #4052 is a PR which is supposed to fix this, but has been stuck in review for a full month.
