### ISSUE TITLE
Reuse `ShareModal` macro on "My Books" pages

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8854] opened 2024-02-29 23:19 UTC
### Describe the problem that you'd like solved

The share link on "My Books" pages, when clicked, displays a prompt containing the page's link which the patron must manually copy.  This is pretty inconvenient, and provides an experience which is much different from clicking the share link on a book page.

### Proposal & Constraints

Reuse the book page share links on "My Books" pages.  Each social share link should link back to the current page.  The embed link should be removed altogether for "My Book" pages, but still appear on book pages, as there is no handler for embedded "My Books" pages today.

### Additional context

The share modal template can be found here: https://github.com/internetarchive/openlibrary/blob/9915746638edfab5f9eee950bcdc8fc58928094e/openlibrary/macros/ShareModal.html

Here's an example of how our share links are being used today: https://github.com/internetarchive/openlibrary/blob/9915746638edfab5f9eee950bcdc8fc58928094e/openlibrary/templates/type/edition/modal_links.html#L26-L29

**Comment by noobCoderVP** [comment] 2024-03-02 09:36
Hey there, I would like to work on this issue. I understood the issue and now going through the codebase to make changes, can you assign it to me?

**Comment by jimchamp** [comment] 2024-03-02 13:09
Thanks, @noobCoderVP!  Let me know if you have any questions.

**Comment by noobCoderVP** [comment] 2024-03-02 13:20
Thanks for that, I will reach out to you in case of any questions, I am going through the contribution guidelines and codebase as of now because I am a new contributor. You can help me with the reproducing steps (even the browser url of My Books page in local is enough). Thanks again!!

**Comment by jimchamp** [comment] 2024-03-02 14:34
When logged in, you can use http://localhost:8080/account/books to view the My Books page.

**Comment by noobCoderVP** [comment] 2024-03-02 18:19
I have figured out the issue

### Current Workflow
![image](https://github.com/internetarchive/openlibrary/assets/98279986/891b1650-85dd-48e3-8334-d7e1c7777c7a)

### Target Workflow
![image](https://github.com/internetarchive/openlibrary/assets/98279986/b5566265-c8eb-4ec2-a28f-e4644fba2d38)

I am working on it, Let me know if any changes are required, thanks for the guidance @jimchamp

**Comment by noobCoderVP** [comment] 2024-03-03 05:59
Hey there, I am developing on VScode with docker, My dependencies are not getting resolved in VScode (there are no errors, I just want to remove the warnings), may I know is there a way to fix this? Do you have any idea how to open VScode such that all dependencies get resolved?

![image](https://github.com/internetarchive/openlibrary/assets/98279986/91bc0433-adc9-49d3-9eae-b10790be41e5)

**Comment by noobCoderVP** [comment] 2024-03-04 05:29
Hey @jimchamp I have almost fixed the issue,
![image](https://github.com/internetarchive/openlibrary/assets/98279986/c6255c1d-02d7-4690-bab2-8e2b5d0aebe4)

There are some questions that I have:
1. Should I change the share Icon HTML similar to existing one? share Icon of book page is very small with small text, for My Books page we can have bigger one.
2. Do I need to remove embbed option?

May I know if you have any suggestions, thanks!!

**Comment by jimchamp** [comment] 2024-03-04 23:37
Thanks, @noobCoderVP!

Be sure to use the same share icon that is already in use on the "My Books" page.  The "embed" option will need to be removed on the "My Books" page.  Adding some `show_embed` flag to the `ShareModel.html` template would be an easy way to achieve this.

**Comment by jimchamp** [comment] 2024-03-05 18:51
@noobCoderVP push your feature branch to your repo and post the branch name here, and I'll check it out.

**Comment by noobCoderVP** [comment] 2024-03-05 19:05
https://github.com/noobCoderVP/openlibrary/tree/8854/feature/add-share-modal-on-my-books-page is my feature branch, I have just pushed it, one more thing needs to be fixed, I couldn't find a way to insert page_url in the shareModal args, it must be done from views 

add the argument of page instead of None from the corresponding view
![image](https://github.com/internetarchive/openlibrary/assets/98279986/ad9d46ce-1680-45cc-864d-e15cf96b7c37)

currently I am passing request.home as the page_url
![image](https://github.com/internetarchive/openlibrary/assets/98279986/de4e2957-0b60-4de6-b8b7-f8fda3967c40)

(similar use of page_url)
![image](https://github.com/internetarchive/openlibrary/assets/98279986/dc4bb6c4-a7b9-4fe0-8b62-a1a64fb701bc)

Thank you so much for the help @jimchamp ...

**Comment by jimchamp** [comment] 2024-03-05 22:04
Thanks @noobCoderVP!
I think that the "Copy URL" link is not working because your Javascript has not been compiled.  There are some notes about that [here](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#building-css-and-js).

Anyway, things seemed to work properly when I tested your changes on my machine.  Go ahead and open a PR, and I'll properly review your changes.  Be sure not to include your `.gitignore` changes in the PR.  Thanks again!

**Comment by noobCoderVP** [comment] 2024-03-06 18:46
I am grateful to you @jimchamp, it was my first significant open source contribution, you made my experience great!! would like to collaborate again with you for any contribution...🙂

**Comment by Realmbird** [comment] 2024-03-08 01:51
@jimchamp  I would like to work on this would this be possible

**Comment by noobCoderVP** [comment] 2024-03-13 16:58
Hey @jimchamp, can you review this PR and close the issue?

**Comment by noobCoderVP** [comment] 2024-03-19 17:34
I have made review changes according to your suggestions @jimchamp, merge the PR whenever you get some time. I actually have developed a draft proposal for GSOC 2024, would you please help me out with any reviews? [my GSOC proposal](https://docs.google.com/document/d/182ps6_69JAyDkAmoJQd2SM50YGKBRF0kc1Bg4q7lQUc )

**Closed** 2024-03-20 17:35 UTC
Labels: Type: Feature Request, Priority: 3, Good First Issue, Lead: @jimchamp, Theme: My Books
