### ISSUE TITLE
Merge Books

### ISSUE THREAD

**Issue by awebdeveloper** [internetarchive/openlibrary#4310] opened 2020-12-19 09:03 UTC
Look at this link you will find multiple books by the same author with same name. 
https://openlibrary.org/authors/OL1398754A/Malcolm_Gladwell

### Describe the problem that you'd like solved
Provide a user facing way to merge two books. If name and author is same the volunteers can merge it.

### Proposal & Constraints
Goodreads does this really well through their discussion forums and volunteers

**Comment by seabelis** [comment] 2020-12-21 13:16
Duplicate of #805.

**Closed by seabelis** 2020-12-21 13:16 UTC
Labels: Needs: Triage
