### ISSUE TITLE
Merge & delete all "please see" authors

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#482] opened 2017-04-27 00:05 UTC
https://openlibrary.org/search/authors?q=please+see

**Comment by LeadSongDog** [comment] 2017-04-27 05:21
Many if not all these were my doing, after manually author-merging by changing each of the works' author fields.  There are some prolific authors I haven't completed. Some of the results, such as https://openlibrary.org/authors/OL3609510A/please_see_D._S._Fletcher still 'seem' to have works against them, but on closer examination, https://openlibrary.org/works/OL12247832M/The_Generic_Names_of_Moths_of_the_World and https://openlibrary.org/works/OL12247830M/The_Generic_Names_of_Moths_of_the_World now show a different author record: https://openlibrary.org/authors/OL894610A/D._S._Fletcher

**Comment by tfmorris** [comment] 2017-04-27 05:39
OK, that's a different story then. If these aren't original library catalog records, we should:
- merge author records & coalesce works
- revert the names to their original forms
- dedupe the names and add them to the AKAs

**Comment by hornc** [comment] 2017-04-27 08:00
I have been looking at these recently and am planning to merge the authors.
I also found these, which seem to require a few more changes + fixes: https://openlibrary.org/search?q=Author%3Adelete

@LeadSongDog, can you provide some insight on what should happen to these deletes? Most of them look like they should be at least redirects, and a few look like potentially valid authors to be reinstated?

**Comment by LeadSongDog** [comment] 2017-04-27 15:38
@tfmorris, the point was to address multiple author records for a single person (deduplication) and  single records for multiple people (deconflation). What you are suggesting would simply re-mingle what has been deconflated. The real answer is to get on with adopting controlled author records (VIAF or similar) then adding a structure for addressing errors found in those formal records.
@hornc, the "please see" entries are, in effect, soft redirects that could be replaced by hard ones. The "delete" authors were largely bogus to begin with, erroneously created (mostly by bots). While a double-check would be good to do, I don't think there's much valid, useful information to be found in their histories. Mostly they were the leftover record after correcting work records to show their proper authors.

**Comment by hornc** [comment] 2017-05-08 11:50
see also comment on #150 :

Well, https://openlibrary.org/search/authors?q=Gilbert+Abbott+Beckett shows many variations on handling the issue, but we need to assist author merging these. That is why standardized authority records were invented, after all. We really need a pre-merge search that finds the near-misses: similar titles from similarly named authors; for instance. In this case I just omitted the letter with the diacritic, but wild carding would be more flexible.

**Comment by LeadSongDog** [comment] 2017-05-08 16:23
One aggravating factor in adopting standards is that OL wants the nonstandard direct form John Quincy Adams while LCAuth, VIAF etc will have the inverted form Adams, John Quincy, 1767-1848 with two commas. We really need to capture both if not all variations in the author record.

**Comment by hornc** [comment] 2018-01-11 02:51
Current status:
`egrep '"name": ".*please see.*"' ol_dump_authors_2017-12-31.txt`
shows 174 author records with 'please see' in the name.

How to we want to resolve this? I can put the list somewhere for others to help merge to the correct main author record. Alternatively I can help someone else use the OL client to do this in an automated fashion.

**Comment by hornc** [comment] 2018-01-11 03:06
I think we could call this blocked by SOLR issues. The following author
https://openlibrary.org/authors/OL6564319A/please_see_Walter_E._Scott
appears to have no works, yet I found (with some ingenuity,, via the VIAF)  https://openlibrary.org/works/OL13715332W/Death_Valley_Scotty_rides_again

This 'please see' record appears to be the only valid version of the author, but without a reliable index it is hard to tell what is going on.

A trick to check an author's works which seems to bypass SOLR is to append 'works.json' after the author OLID:
https://openlibrary.org/authors/OL6564319A/works.json

**Comment by hornc** [comment] 2018-03-19 21:39
@salman-bhai unfortunately this is still an issue, there are still 168 'please see' authors in the Feb 2018 Authors DB dump. There are also many 'delete' authors that have the same issue. Further work on this is blocked by #628 as it is impossible to tell which have already been removed and which are outstanding.

**Comment by salman-bhai** [comment] 2018-03-20 04:08
@hornc anything that I can do to help?

**Comment by hornc** [comment] 2018-04-09 23:46
Some progress has been made, solr has caught up and now there are only 57 authors remaining that need to be merged:  https://openlibrary.org/search/authors?q=please+see

**Comment by tfmorris** [comment] 2018-04-10 05:48
Under 50 now, but each author which is merged also needs to be hand edited to remove the bogus "Please see" name from the AKAs (now that indexing alternate names works for search).

**Comment by hornc** [comment] 2018-06-06 00:34
All cleared, finally! 
Thanks @tfmorris for getting many of the last remaining ones, caused by alternate names. I noticed many were fixed, but still appearing in Solr results, I think because of the caching issue https://github.com/internetarchive/openlibrary/issues/927
I have fixed and  reindexed the remainder, so now 

https://openlibrary.org/search/authors?q=please+see

gives 0 results

**Closed by hornc** 2018-06-06 00:34 UTC
Labels: merging, solr

**Comment by LeadSongDog** [comment] 2018-06-06 14:37
@hornc @tfmorris Thank you for clearing that up. There still needs to be a "right" way for regular users to dedupe and deconflate author records, short of hitting "help" dozens of times a day.
