### ISSUE TITLE
Orphaned editions error

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3760] opened 2020-09-01 19:07 UTC
```
/opt/openlibrary/deploys/openlibrary/9afb5a2/openlibrary/templates/type/edition/view.html: error in processing template: IndexError: list index out of range (falling back to default template)
```

### Relevant url?
- https://openlibrary.org/books/OL9773440M/Muertos_Incomodos?v=1
- https://openlibrary.org/books/OL9773440M/Muertos_Incomodos?v=1&debug=true

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF79
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment] 2020-12-08 18:42
Dupe of #4052

**Closed** 2020-12-17 09:00 UTC
Labels: Lead: @mekarpeles, Priority: 2, Type: Bug
