### ISSUE TITLE
This book fails to render

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3695] opened 2020-08-13 05:25 UTC
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/90097408-d2d47200-dd03-11ea-882c-fa63e8f6930c.png)

### Relevant url?
https://openlibrary.org/works/OL17364096W/Hikayat_Iskandar_Zulkarnain

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF79
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

**Comment by aasifkhan7** [comment] 2020-08-17 13:29
@cdrini this book doesn't exist in my local OL instance - how can I import it in the local DB?

**Comment by SouthGoingZax** [comment] 2020-10-17 23:29
@aasifkhan7 you can import items by using the script outlined here:  https://github.com/internetarchive/openlibrary/wiki/Getting-Started#importing-test-data

It looks like the problem is that the author of the work, which you can find by looking at the json output for this work (https://openlibrary.org/works/OL17364096W.json), has no name.  You can see that by looking at the json output for the author entity for that work (https://openlibrary.org/authors/OL7292325A.json).  Compare that to a well-defined author entity, which has a name (https://openlibrary.org/authors/OL34184A.json).

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html#L61 assumes all author entities have names.  This issue could be fixed by adding a check to the list comprehension to see if a.name exists.

**Comment by SouthGoingZax** [comment] 2020-10-17 23:42
It also looks like there is more code that assumes every author entity has a name.  For example, searching for this same book's title results in a broken search page:  https://openlibrary.org/search?q=title%3A+%22Hikayat+Iskandar+Zulkarnain%22&mode=everything&debug=true

And the edit template too:  https://openlibrary.org/works/OL17364096W/Hikayat_Iskandar_Zulkarnain/edit?debug=true

In addition to fixing those, perhaps this book should have a new author.  https://openlibrary.org/authors/OL5631454A/No_name is a well-formed placeholder author entity for cases like this.

**Comment by mekarpeles** [comment] 2020-10-19 05:28
> Aaron says @ 8:29 PM, 2020-10-17
> `@charles` [i.e. @hornc] or anyone else that has an opinion, it looks like author entities that don't have names break the site in a few places (see my last two comments in https://github.com/internetarchive/openlibrary/issues/3695).  A quick search through the repository yields several more places that assume that author entities have names.  Should they all be adjusted to verify that assumption, or should this be considered a data problem and not a code problem, or should both the data and code be corrected?  On the issue I alluded to the solution as being both, but I wanted to double-check.

My thoughts:
I think it's both -- but I think it starts with the principle "no dead ends".
The system should not break if a field is missing. Next we should make sure the system can't create new edge cases. Finally, we should retroactively fix the data (preferably as/when other bot updates are occurring on the same record)

**Closed** 2020-11-17 07:53 UTC
Labels: Lead: @mekarpeles, Priority: 3, Type: Bug
