### ISSUE TITLE
Availability consistently appears wrong for some works in search results

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2141] opened 2019-05-22 03:39 UTC
## Description
Regardless of refresh, the works always show "No ebook available" when in the search results, but viewing them directly shows they are publicly available or borrowable.

## Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/58140304-af0fa280-7c0c-11e9-9846-66c2eb000480.png)

## Relevant url?
- https://openlibrary.org/works/OL16312108W (use the search https://openlibrary.org/search?q=wind+in+the+willows&mode=everything)
- https://openlibrary.org/works/OL476641W
- https://openlibrary.org/works/OL115074W

## Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 66.0.5
- **Operating system?** Windows 10 Home

## Stakeholders

**Comment by ericnam** [comment] 2019-06-04 12:48
I'm unable to reproduce the errors via the links provided - is there a specific book in the list that is displaying the incorrect availability?

**Comment by brad2014** [comment] 2019-06-06 22:55
I'm marking this `affects: server` on the assumption that the server is reporting incorrectly that no ebooks are available.

**Comment by brad2014** [comment] 2019-06-07 00:53
Is this related to #1929?

**Comment by cdrini** [comment] 2019-06-07 02:07
@ericnam You have to search for one of the works. For example, https://openlibrary.org/search?q=wind+in+the+willows&mode=everything

@brad2014 possibly related? I'm not too sure. I might assess this, but not any time soon, so someone else can take a crack at it if they like :P

**Comment by LeadSongDog** [comment] 2019-06-07 15:33
Compare:
![willow0](https://user-images.githubusercontent.com/11435431/59114488-42d3b500-8915-11e9-9b14-0c8d6fbc41b5.jpg)

![willow2](https://user-images.githubusercontent.com/11435431/59114509-4cf5b380-8915-11e9-9c3a-71c1132e508b.jpg)

![willow3](https://user-images.githubusercontent.com/11435431/59114975-52073280-8916-11e9-8e0b-889c390b9072.jpg)

Edition OL26343700M was moved 
from https://openlibrary.org/works/OL16312108W/The_Wind_in_the_Willows
to https://openlibrary.org/works/OL17745575W

After all editions have been merged from one work record to another, the last edition stays listed on the (properly voided) work as a sort of ghost edition. The merged-from work shows zero editions, but it still appears on a title search, with the borrow button for the moved-away edition.

**Comment by tfmorris** [comment] 2019-10-25 02:46
I've edited the original problem report to include the search url that's needed to reproduce the problem. With that, I think it's adequately described. There are three different types of buttons: 1) Borrow, 2) Join Waitlist, and 3) Unavailable, but the last seems to be used much too often. I suspect it's being used for both the "Read" and "Unavailable" cases, so that's probably where someone should start with the investigation.

Medium priority.

**Comment by mekarpeles** [comment] 2019-10-30 02:21
Here's an example of a solr doc for the work https://openlibrary.org/works/OL16312108W (in the results above)
http://archive.org/~mek/solr_example.xml

It lists the following archive.org IDs. When we run availability across them, we do indeed get positive matches of availability: 

```
https://archive.org/services/availability?identifier=windwillowschild00grah,windinwillows00grah,windinwillows01grah,windinwillows00grah2,cu31924028200172,windinwillows000grah,windi\nwillows00mich_0,windinwillowsban00kenn,windinwillowschi00kenn,windinwillows00mich,windinwillows00grah_z2x,windinwillows00trol,\windinwillowstho00kenn,windinwillows00grah_x1n,windinwillowscla0000grah,windinwillowsgra00grah,windinwillows1980grah,windinwill\owswor00kenn,windinwillows100grah,windinwillows00grah_10,windinwillows00grah_8,windinwillows00grah_9,riverbankfromken0000carr,w\indinwillows00grah_0,windinwillows00grah_1,windinwillows00grah_3,windinwillows00grah_7,windinwillowsken00grah,windinwillows0000\grah_c1x7,windinwillows00kenn,riverbankfromwin00grah
```

See:
```
{
success: true,
responses: {
windwillowschild00grah: {
status: "error",
error_message: "not found"
},
windinwillows00grah: {
status: "open",
identifier: "windinwillows00grah",
isbn: null,
oclc: null,
openlibrary_work: "OL16312108W",
openlibrary_edition: "OL7153762M",
last_loan_date: null,
num_waitlist: null,
last_waitlist_date: null,
collection: "newyorkpubliclibrary,bannedbooks,americana,fav-tonyluzano,fav-miki1975,fav-seeprudenceplay,fav-sorrento,fav-tugba_tekben,fav-martybraz,fav-noahgrey,fav-wassi_chamsy_homeschooling,fav-melissa_baxa,fav-austen17,fav-lalounalovely,fav-selena01018,fav-stoney_knob_farm,fav-altomentis,fav-alan_machin,fav-essie_yesterday,fav-goodeve,fav-kimkat_106,fav-coppletank,fav-negorro,fav-1770beethoven1826,fav-pixiecake1,fav-kathoarn,fav-sherah,fav-monophelia,fav-peng_sheng,fav-bunnybonbon,fav-amiraal,fav-melissa_roman,fav-lelystra,fav-nokhufunekho,fav-yoshiyamadeep"
},
windinwillows01grah: {
status: "open",
identifier: "windinwillows01grah",
isbn: null,
oclc: null,
openlibrary_work: "OL16312108W",
openlibrary_edition: "OL7001197M",
last_loan_date: null,
num_waitlist: null,
last_waitlist_date: null,
collection: "uconn_libraries,blc,americana,fav-in2artlife,fav-kurt3246"
},
...
```

The challenge here is that we have up to 20 works, which each have some number of full_text editions, and we need to find a way to ask archive.org/services/availability?identifier= which one's are available (possibly short circuiting when we find one).

**Comment by tfmorris** [comment] 2019-10-30 15:21
The very first ID in that response has

```
windwillowschild00grah: {
    status: "error",
    error_message: "not found"
},
```

which I could easily see making some suitably fragile code unhappy.

Having said that, the current API design requires wasted work for this use case. All that's really needed is True/False for availability of a digital edition for any one of a given set of IDs.

**Closed** 2020-03-11 22:03 UTC
Labels: Affects: Server, Lead: @cdrini, Needs: Breakdown, Priority: 1, State: Backlogged, Theme: Search, Type: Bug
