### ISSUE TITLE
Importbot overwrites history

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6778] opened 2022-07-23 15:20 UTC
When Importbot imports new data, the existing history of the original imported record is overwritten. 
### Relevant url?

https://openlibrary.org/books/OL24262078M/The_Thirteen_Problems?m=history
### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL24262078M/The_Thirteen_Problems?m=history
2. Do ...view first entry which states the record was originally imported from Betterworldbooks. However, look at the date from 2010; BWB was not a source at the time.

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp @hornc

**Comment by cdrini** [comment] 2022-07-25 21:06
My guess would be this is a rendering issue. The line that says "Imported from better world books" likely checks the `source_records` field. v=1 of this record only had one source record: a Marc file. Current version also has 2 bwb source records. I guess it should use the first element in the list of source records, but maybe uses the last? The history at least doesn't appear to be corrupted, thankfully!

**Comment by hornc** [comment] 2022-08-18 05:43
same issue / duplicate of #2643

**Comment by hornc** [comment] 2022-08-18 05:54
also reported in #1381

**Comment by mekarpeles** [comment] 2022-08-22 17:42
Closing as duplicate of https://github.com/internetarchive/openlibrary/issues/2643

**Comment by mekarpeles** [comment] 2022-08-22 17:43
Closing as duplicate of https://github.com/internetarchive/openlibrary/issues/2643

**Closed by mekarpeles** 2022-08-22 17:43 UTC
Labels: Type: Bug, Priority: 2, Lead: @mekarpeles
