### ISSUE TITLE
Searching for Subject terms with diacritics fails

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#317] opened 2016-09-22 20:38 UTC
From a user... Subject queries for terms with diacritics in the name fail. E.g. the following both return zero results:
- Yogācāra (Buddhism) 117 books, subject
- Theravāda Buddhism 105 books, subject

At: https://openlibrary.org/search/subjects?q=buddhism&search=
Clicked: https://openlibrary.org/contact?path=/subjects/therav%C4%81da_buddhism

If I manually edit the URL to remove the ā's, Yogacara returns 3 results and Theravada returns 22 – different from the subject listing. It appears that there's perhaps something funny with your subject database's character collation, or some other fluke that causes the queries to be dissociated from the actual results. (I certainly should hope you've got that many titles on both on the record!)

May be directly related to Unicode issues in #178

**Comment by LeadSongDog** [comment] 2016-09-27 15:26
This may be partly user or browser issues, but there is certainly a misfunction going on. 

For me, https://openlibrary.org/search?q=Yog%C4%81c%C4%81ra returned 122 hits (a mix of work and edition records) while https://openlibrary.org/search?q=Yog%C4%81c%C4%81ra+%28Buddhism%29 reduced that to 119 and removing diacritics https://openlibrary.org/search?q=Yogacara+%28Buddhism%29 brought it down to just 9. 

Similarly, https://openlibrary.org/search?q=Therav%C4%81da returned 149 while https://openlibrary.org/search?q=Therav%C4%81da+Buddhism reduced that to 129 and removing diacritics https://openlibrary.org/search?q=Theravada+Buddhism brought that down to 78.

It seems (without detailed examination) that the set of non-diacritic results is disjoint from the diacritic results. The search should be fuzzy enough to include all the diacritic variations, not just the ones exactly as entered by the user.

**Comment by bfalling** [comment] 2016-10-09 07:46
Related issue reported: In some cases, internal URLs are generated containing accented characters, which, if followed, show a 404 page. In some cases, if you replace the accented characters with unaccented versions, the pages are found.

e.g.
https://openlibrary.org/subjects/person:joan_miró_%281893-1983%29 (fails)
https://openlibrary.org/subjects/person:joan_miro_%281893-1983%29 (works)
https://openlibrary.org/subjects/person:miró_joan_(1893-) (fails)

The broken links appear on such pages as:
https://openlibrary.org/search/subjects?q=joan+miro
https://openlibrary.org/subjects

On the other hand, this page works:
https://openlibrary.org/works/OL12673415W/Joan_Miró

Another example: https://openlibrary.org/subjects/place:québec_(province)

**Comment by LeadSongDog** [comment] 2016-10-12 20:06
Oddly, a subject search with the person: prefix puked on the "ó" character (u'\xf3') :
https://openlibrary.org/search/subjects?q=person%3Ajoan+mir%C3%B3+%281893-1983%29
  with the message:`
"/opt/openlibrary/deploys/openlibrary/96466a6/openlibrary/templates/search/subjects.html: error in processing template: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 16: ordinal not in range(128) (falling back to default template)"

On the other hand a general search with the same prefix:
https://openlibrary.org/search?q=person%3Ajoan+mir%C3%B3+%281893-1983%29
seems to work just fine.  It`s just the subject search that`s apparently borked.

**Comment by tfmorris** [comment] 2017-05-08 19:32
This looks like a duplicate of #178, #11, and some even older bug reports in earlier bug reporting systems. It was first reported at least as early as 2010.

**Comment by hornc** [comment] 2017-05-12 23:40
I'm looking into this at the moment:
https://openlibrary.org/search?subject=therav%C4%81da+buddhism Correctly returns 106 results, which is 1 off what the https://openlibrary.org/search/subjects?q=buddhism page shows as the result count for that subject.

The issue seems to be that the https://openlibrary.org/subjects/therav%C4%81da_buddhism page uses a different mechanism to get results and finds nothing.

An example of a work that has subject:theravāda buddhism
https://openlibrary.org/works/OL7820790W

**Comment by hornc** [comment] 2017-05-13 11:29
The subject search is failing to find results because in this code here, which POSTs data to solr
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/utils/solr.py#L86

the subject paramters are being urlencoded to %C4&81 in the POST body when they need to be left alone to return results.

**Closed** 2017-05-17 04:22 UTC
Labels: search, unicode

**Comment by mekarpeles** [comment] 2018-12-21 20:45
I think this is related:

```
[2018-12-21 20:43:35 +0000] [25339] [ERROR] Error handling request /subjects/place:sacsahuam_site_(peru)
Traceback (most recent call last):
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/httpserver.py", line 212, in __call__
    return self.app(environ, start_response)
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/core/middleware.py", line 42, in __call__
    data = self.app(environ, new_start_response)
  File "/opt/openlibrary/openlibrary/scripts/openlibrary-server", line 118, in wrapper
    return app(environ, start_response)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/application.py", line 273, in wsgi
    self.load(env)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/application.py", line 372, in load
    ctx[k] = safeunicode(v)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/web/utils.py", line 237, in safeunicode
    return obj.decode(encoding)
  File "/opt/openlibrary/venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 25: invalid continuation byte
```

**Comment by LeadSongDog** [comment] 2018-12-22 03:35
So in 
https://openlibrary.org/subjects/place:sacsahuam%C3%A1n_site_(peru)
The position 25 is the accented character %C3%A1  (á) in “Sacsahuamán Site (Peru)”
Note that query shows six books but none have covers, even placeholder covers.

**Comment by tfmorris** [comment] 2018-12-26 21:43
@mekarpeles Did that request get logged correctly? The logged string "/subjects/place:sacsahuam_site_(peru)" doesn't contain any utf-8 characters that I can see.

Did you want to reopen this issue? I recommend either doing that or creating a new issue if you want someone to investigate this. Otherwise it's likely to get overlooked.
