### ISSUE TITLE
Regression: mobile search button takes you to search page rather than revealing an input

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1961] opened 2019-03-08 02:30 UTC
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

Advanced search is much slower than the autocomplete search.

Previously clicking search revealed a search input that allowed you to search without leaving the page 

## Evidence 
Visit any page on a mobile device and hit search icon.

> Relevant url?
`https://openlibrary.org/...`

> Screenshot (if possible):

![screenshot_20190307-182846_chrome](https://user-images.githubusercontent.com/148752/54003471-30c05b80-4107-11e9-84a0-4d6fd4469d34.jpg)

## Expectation
> What should by happening? What will it look like / how will it behave?

I shouldn't be navigated to the advanced search page 

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by jdlrobson** [comment] 2019-03-08 02:33
No JS errors so I am guessing this may relate to those recent `live` changes. The event handler is not running.

**Comment by mekarpeles** [comment] 2019-03-08 19:16
When the screen is very small, the main search box turns into a magnifying lens icon.

It used to be the case that when a user clicked this lens (in the small-screen mode) it would expand so that there was also an input area you could type in.
But a regression has occurred where instead of expanding, clicking the icon instead redirects you to /search (which is not what we want)
So the task is to look through ol.js and find the rule which is responsible for this "search expand" behavior (see `searchExpansionActivated` in ol.js) and debug why it's not working correctly :slightly_smiling_face:
If it's done right, it may only be 1 or 2 lines of code which need to be changed

**Comment by mekarpeles** [comment] 2019-03-08 19:19
Assigning to @ShreyashApp

**Comment by jdlrobson** [comment] 2019-03-09 00:27
I've tracked this regression down to a commit. This was broken in 7e79a9376b816181d2dbb14ed41bef9357d857e0 - that will provide the clue to how to fix this :)

**Comment by ShreyashApp** [comment] 2019-03-09 09:59
I found that changing the code to this worked.
$(document).live('submit','.trigger', function(e) {
Is there some possibility to check it.  Thank you.

**Comment by rohitjain00** [comment] 2019-03-17 18:05
Is there any follow-up for this issue? I would like to work on fixing this.

**Comment by mekarpeles** [comment] 2019-03-17 18:31
@rohitjain00 go for it -- willing to review solutions from either you or @ShreyashApp (who previously submitted a fix though I don't believe it's resolved the issue yet)

**Comment by ShreyashApp** [comment] 2019-03-17 19:27
Hi,
@mekarpeles I checked it on my local host and it seems to work fine. Could you tell me some steps to recreate the issue.

**Comment by mekarpeles** [comment] 2019-03-17 20:27
@ShreyashApp's solution (merged) works great -- something happened between time of merge and now which is resulting on the changes not appearing in master. 

`git blame` on `ol.js` shows:

`3d2711b2 (Rohit Jain          2019-03-17 23:41:17 +0530 261)     $('.trigger').on('submit', function(e) {`

so it's possible a merge conflict occurred and the wrong code was accepted.

@ShreyashApp may I ask you to re-submit the same PR so I can ensure you get your due credit? Sorry for the inconvenience, my fault!

**Closed** 2019-03-17 20:47 UTC
Labels: Regression, priority, search

**Comment by rohitjain00** [comment] 2019-03-25 19:03
Sorry for the inconvenience caused by my PR I was not aware of the wrong code. I sincerely apologize for my mistake.

**Comment by jdlrobson** [comment] 2019-03-26 01:06
No need to apologise! I brought down the entire wikipedia site for 5 minutes once! 🤣
Part of being a developer is breaking stuff and usually when stuff breaks it's due to badly organised code not an individual. We are working with some very fragile frontend code so this kind of thing is unfortunately going to be common until we put more checks in place.

**Comment by mekarpeles** [comment] 2019-03-26 14:59
@rohitjain00 you're doing great. :+1:
