### ISSUE TITLE
Fix home page performance / speed

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1264] opened 2018-10-06 14:11 UTC
The OpenLibrary home page ranks in the bottom third of all web pages on the internet in performance.

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fopenlibrary.org%2F

#1171 deals with one specific piece of the home page speed, but it's not the only issue. We need to:

1. Improve the load times for this page
2. Put in place tooling which allows us to track this over time and spot regressions

Some of the things the suggestions that seem easy to deal with include:
- turn on compression of served assets
- inline or otherwise eliminate page-home.css which is requiring an extra round trip latency before rendering can start
- add cache expiry dates to many resources. Things like cover images can have pretty long life times (longer than Google recommends)

There's probably other low hanging fruit, but the main thing we need to do is be systematic about improving the current terrible performance.

**Comment by jdlrobson** [comment] 2018-10-06 17:57
That report actually looks good to me.

Performance and mobile are my main focus right now and but the homepage is much better than other pages so it would be good to pull out some actionables from here. The css is only 4kb. That's tiny. i don't think anything needs to be done there.

I think the main issue here is the server latency, compression (see my other issue about compressing covers) and #1171 (which is not yet deployed). Let's see what impact #1171 has first. That many request can flood the client and slow down important downloads such as html and css so I am confident that will make a big difference. If it doesn't we should consider content delivery networks, setting expiry headers and, gzipping images.

That report is actually a lot lot better than when i ran it before. Note other pages far much worse - e.g. subjects:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fopenlibrary.org%2Fsubjects%2Fart%23sort%3Dedition_count%26ebooks%3Dtrue
Switching all those pages to v2 is the best thing we can do.

**Comment by jdlrobson** [comment] 2018-10-07 03:42
According to https://www.webpagetest.org/result/181006_X1_756d2f7f89d51129857514ad33f7b8d7/
first byte time is 5.395s of the 6.3s first paint.

This points to server side. Have we considered adding a level of caching to the backend before? The homepage doesn't need to change on every page load yet unless I am mistaken every time we seem to generate it from scratch via python.

**Comment by jdlrobson** [comment] 2018-10-18 15:38
Do we have any caching/profiling in place on the backend?

**Comment by mekarpeles** [comment] 2019-04-02 20:51
Closing as duplicate of #1553

**Closed by mekarpeles** 2019-04-02 20:51 UTC
Labels: performance
