### ISSUE TITLE
BookImportError: Too Many Requests on amazon.com/paapi5/getitems

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3967] opened 2020-10-28 16:04 UTC
How can we avoid being rate limited on Amazon paapi5 requests?

#4220

httplib | POST https://webservices.amazon.com/paapi5/getitems [429]
-- | --
reason | Too Many Requests

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

#4150 demonstrated that increasing the wait times has no effect other than slowing things down.  This is because different workers compete for access to Amazon API in an uncoordinated way.  Multiple callers create a bottleneck because their wait times are not coordinated and as a result, the Amazon API blocks.

The proposed solution is to create a singleton which is the only access to the Amazon API.  This would mean that all requests
across multiple workers would route through that Singleton. This would allow all delays to be correct and will effectively throttle all transactions such that there is fair access for all callers. The results should be that cached so that repeated calls for the same information are short-circuited to avoid creating further bottlenecks.

__Options:__
1. Create a single `Amazon_API` object and allow different workers to hold a pointer to that object to make calls on.
2. Create a dockerized web service that exposes a web API similar to the Amazon API but only serving local callers.

If we go with the singleton, would Gunicorn allow multiple workers to share a common singleton?
If we go with the web service, should we use web.py or use something more modern like https://www.flaskapi.org or https://fastapi.tiangolo.com?

**Comment by mekarpeles** [comment] 2020-12-17 20:37
Resolving as duplicate of #4220

**Closed by mekarpeles** 2020-12-17 20:37 UTC
Labels: AmazonAPI, Lead: @cclauss, Needs: Investigation, Priority: 2, Type: Bug
