### ISSUE TITLE
Missing Alt Value for Footer Archive Logo Img

### ISSUE THREAD

**Issue by dwaipayan05** [internetarchive/openlibrary#4584] opened 2021-02-12 16:13 UTC
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/53687927/107791986-9b11ba00-6d7a-11eb-8e6c-3d9ffa332344.png)

### Steps to Reproduce

1. Go to Footer of openlibrary.org
2. Check the alt value of footer using Inspect Element Feature

* Actual: alt = ""
* Expected: Some Alt Value

### Details

- **Logged in (Y/N)?**  N
- **Browser type/version?** Chrome
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Add an Alt Value to the Img

### Related files

[nav_foot.html](https://github.com/internetarchive/openlibrary/blob/a61250b4ade345430e406d99eb04ae102713899a/openlibrary/templates/lib/nav_foot.html)

**Comment by Yashs911** [comment] 2021-02-12 16:51
Hi @dwaipayan05 this issue is a duplicate of https://github.com/internetarchive/openlibrary/issues/4521#issuecomment-772398033
And according to the discussion https://github.com/internetarchive/openlibrary/issues/4521#issuecomment-772730099 `alt=""` is appropriate for the Archive logo.

**Comment by Yashs911** [comment] 2021-02-12 16:52
If you are interested in solving issues related to Image Accessibility. Go to https://github.com/internetarchive/openlibrary/issues/4521 and pick one file.

**Comment by dwaipayan05** [comment] 2021-02-12 16:54
Thanks mate.

**Closed** 2021-02-12 17:41 UTC
Labels: Needs: Lead, Needs: Triage, Type: Bug
