### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by airbee7337** [internetarchive/openlibrary#2592] opened 2019-10-31 13:36 UTC
Currently:
Each time a new page is saved to the Archive, all the js,css,images,etc are re-downloaded. 

Example:
I archive page 1 of openlibrary.org, all css,images,js,elements are downloaded. 

I go to page 2 on openlibrary.org, all css.images,js,elements,etc (EXACT same MD5) are Re-Downloaded. 

Would it be possible for a MD5 checking system before elements (css,images,scripts,etc) are re-downloaded. 

This could save bandwidth and increase loading speeds.
Just like the caching system works on firefox.

All CSS,JS,IMG,etc files are checked for MD5 before fetching a 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by cdrini** [comment] 2019-11-12 05:03
Hi @airbee7337 ! Thanks for the bug report. Could you please follow the bug report template? It makes it much easier for us to process incoming issues. For this, I'd especially like to know what browser/os you're using. I can't reproduce this on FF69/Win10. I've re-added the bug template to make it easier to fill in. Let me know if you have any questions!

**Comment by guyjeangilles** [comment] 2019-11-25 22:15
Gonna close this since this since @cdrini wasn't able to reproduce. We can reopen if @airbee7337 can provide more details about this bug.

**Closed by guyjeangilles** 2019-11-25 22:15 UTC
Labels: Close: Not Reproducible, Type: Bug
