### ISSUE TITLE
Broken Page

### ISSUE THREAD

**Issue by awebdeveloper** [internetarchive/openlibrary#4309] opened 2020-12-19 08:49 UTC
### Evidence / Screenshot (if possible)

<img width="1074" alt="Screenshot 2020-12-19 at 12 53 04 PM" src="https://user-images.githubusercontent.com/1593429/102683736-33674480-41f9-11eb-9327-00e8f8f55faa.png">

### Relevant url?
https://openlibrary.org/books/OL8853506M/iCon_Steve_Jobs_the_Greatest_Second_Act_in_the_History_of_Business

* Actual:  Page Opens without error
* Expected: Page has errors

### Details

- **Logged in (Y/N)?**  Y
- **Browser type/version?**   Safari 
- **Operating system?**  macOS Catalina 
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment] 2020-12-19 09:49
@awebdeveloper adding `?debug=true` to the failing URL's end will give you more information about the error.

![ol](https://user-images.githubusercontent.com/64412143/102686156-bee9d100-420b-11eb-9c4c-2ac314dc34fd.JPG)

And on dev.openlibrary.org, this issue might have been solved partially.
![Capture](https://user-images.githubusercontent.com/64412143/102686375-5f8cc080-420d-11eb-8d14-0e7a05ea3763.JPG)

**Comment by SouthGoingZax** [comment] 2020-12-19 16:36
Duplicate of #4051

**Closed by SouthGoingZax** 2020-12-19 16:36 UTC
Labels: Needs: Triage, Type: Bug

**Comment by tfmorris** [comment] 2020-12-20 02:53
Actually a dupe of #3760 and #4224 as well as #4051, but they're all marked as closed and, as of a few minutes ago, the URL above still errors on the production server, so I could easily see @awebdeveloper wondering what the actual status is.

**Comment by SouthGoingZax** [comment] 2020-12-20 04:35
Yeah, I agree the state is not clear to people less familiar with the release practices.  The issues get closed when the PRs are merged, but [deployments usually happen once a week](https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#introduction).  I believe the fix should go out with the next release.
