### ISSUE TITLE
503 on dev device - "No server is available to handle this request."

### ISSUE THREAD

**Issue by jollygreenegiant** [internetarchive/openlibrary#6804] opened 2022-07-29 20:06 UTC
### Question
I've started getting 503 errors on my dev device with the message "No server is available to handle this request."

I'm not noticing this on the OpenLibrary website or when using a different IP address on my dev device, so I suspect this is a rate limiting issue - I know the Covers API has a limit of 100 requests/5 min, but is there a similar limit for the other API endpoints?  In this case it's `/search`

It's probably unlikely that an actual user would ever hit the rate limit, but I'd like to handle that case, to be sure.

**Comment by mekarpeles** [comment] 2022-08-01 22:19
It's possible that at the time the servers (or more particularly our search engine) were was just getting overloaded by heavy traffic. Please re-open if you repeatedly are seeing this problem and @cdrini can investigate.

Are there certain searches you're trying to do? At what frequency are you hitting the APIs?

**Comment by jollygreenegiant** [comment] 2022-08-09 13:54
I haven't run into this since originally opening the issue, so it may have been a one-off thing, or high-traffic issue, like you mentioned.  It was just me using the API for development, so I shouldn't have been hitting the API more than 10-20 times in a minute at most (if loading a list of books for example).  Seems to be okay since though 👍

**Comment by cdrini** [comment] 2022-08-09 14:46
Can you give an example of the request you were making, @jollygreenegiant ? Maybe we can find a more performant way for you to get what you need :)

I'll close this in the mean time since it seems the issue is resolved!

**Closed by cdrini** 2022-08-09 14:46 UTC
Labels: Needs: Triage, Needs: Community Discussion, Type: Question, Lead: @cdrini
