### ISSUE TITLE
Host Open Library i18n on web-based translation platform

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#7746] opened 2023-03-30 07:08 UTC
Currently, translation process of Open Library is quite convoluted and inconvenient for users. This can possibly be fixed by hosting our translation on one of web services. I have found two possible options: [Weblate](https://weblate.org/en/) and [Crowdin](https://crowdin.com/page/open-source-project-setup-request). Both of them offer free plans for ope-source projects upon request.
# Weblate
![image](https://user-images.githubusercontent.com/58372007/228753673-a01a48a0-bb9a-4965-9242-53a9963ac2f3.png)
The projects has to meet following criteria:
1. Translated content has to be released under a license [approved by OSI](https://opensource.org/licenses) or [recognized as libre by FSF](https://www.gnu.org/licenses/license-list.html).
2. All the source code has to be publicly available in a supported version control system.
3. Translations have to be in the same repository as the source code, or under the same project/organization as the source code repository.
4. Using Weblate has been approved by the upstream project.
5. Mention you use Weblate for translations in the README. It’ll attract new translators and also help Weblate to be free for more projects.
6. The project has had active development for at least three months.
7. You will have 14 days to set up your project.
8. Please request project approval once you finish the setup.
9. Unapproved projects will be removed.
10. There is no guarantee of service availability, nor quality for Libre hosting.
# Crowdin
Crowdin seems to have no limitations on number of strings and languages, but they have the following criteria to make a request:
1. You have created a translation project in Crowdin.
2. The project is licensed under an approved license from an open-source initiative.
3. Your project's source code is publicly available for download.
4. You do not have any commercial products related to the open-source project you are requesting a license for.
5. You are the project lead.
6. You have been working on your open-source project for at least three months.
7. You have an active community of collaborators.
8. You keep the "News" section of your website up to date.
9. You release updated builds on a regular basis.

Note: As an Open Source project maintainer by submitting the form you agree to:
- join Crowdin beta group and try Crowdin's latest features,
- contribute your project translations to Crowdin Global TM and gain access to Crowdin Neural Machine Translator.

The requirements do not apply to paid customers.

---

Links to request forms:
Weblate https://hosted.weblate.org/hosting/
Crowdin https://crowdin.com/page/open-source-project-setup-request

Transifex also seems as a viable option https://www.transifex.com/open-source/

**Comment by tfmorris** [comment] 2023-03-30 15:47
I think this is a duplicate of #3328 from a few years ago.

**Closed** 2023-03-30 16:16 UTC
Labels: Type: Feature Request, Theme: Internationalization, Needs: Triage, Needs: Lead
