### ISSUE TITLE
Moving a Work-less edition to a Work doesn't seem to work

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#730] opened 2018-01-07 11:07 UTC
@cdrini -- when I try to move this work-less edition https://dev.openlibrary.org/books/OL9732224M/Glut to a work https://dev.openlibrary.org/works/OL15861476W/Glut it doesn't appear to do anything.

**Comment by tfmorris** [comment] 2018-01-07 18:45
Were you doing this move using the API, a tool, or some openlibrary.org affordance?

It appears that the workless edition used to point to this, now deleted, work:
https://dev.openlibrary.org//works/OL5846151W?m=history

Shouldn't that be a redirect to the "winning" work that it got merged into?

Independent of what happens now, it seems pretty clear that that answer should be that it should be possible to add Work-less editions to Works.

**Comment by mekarpeles** [comment] 2018-01-07 21:12
And there should be a ui to convert a deleted work  to a redirect for an admin

I was using @cdrini's new librarian mode edit UI

**Comment by LeadSongDog** [comment] 2018-01-07 22:45
Yes the redirect is helpful to minimize dead links in from other sites

**Comment by cdrini** [comment] 2018-01-07 23:30
Hmmm... Investigating.

**Comment by cdrini** [comment] 2018-01-07 23:45
Super weird. It's working as expected on my local instance...

**Comment by cdrini** [comment] 2018-01-07 23:48
Ok, even weirder. I think the issue is with the work. I was able to move it to another work, but when I tried to move it to https://dev.openlibrary.org/works/OL15861476W/Glut , it became work-less again.

**Comment by cdrini** [comment] 2018-01-08 00:11
Ok, I think the issue is that searching by key isn't working correctly in the work autocompleter (for some reason). Keeping the Chrome devtools open, it looks like as soon as I select "Glut" from the suggestions, the hidden input element with name `edition--works--0--key` gets updated to get value "/works/OL15861476W" (as it should). HOWEVER, after I click away from the input, the value is reset to empty.

**Comment by cdrini** [comment] 2018-01-08 00:17
Nope, nevermind, it seems to be a problem *exclusively* with `/works/OL15861476W`...

**Comment by LeadSongDog** [comment] 2018-01-18 20:50
Related oddity:
![edition or work](https://user-images.githubusercontent.com/11435431/35120762-2cb3e970-fc67-11e7-8ff7-f97d944750a8.png)

**Comment by cdrini** [comment] 2018-01-19 06:03
@LeadSongDog Great find! That's definitely an issue, but unrelated to this one :) "Dummy" works are created in solr for orphaned editions so that they can still be found in search. We've got to filter those out in this search box, because we want works exclusively. Could you create a new issue for it?

**Comment by LeadSongDog** [comment] 2018-01-19 16:03
Done, as #761

**Comment by hornc** [comment] 2018-11-13 02:39
closing per @LeadSongDog 's comment above, thanks!

**Comment by LeadSongDog** [comment] 2019-01-18 15:58
Ah, @hornc, my "Done" from Jan 19, 2018 was in reference to the immediately previous @cdrini request "Could you create a new issue for it?". It did not mean that this issue #730 was done and could be closed. I'll try to be more clear. Please reopen.

**Comment by tfmorris** [comment] 2019-04-11 21:30
Reopening per @LeadSongDog's request.

**Closed** 2019-05-15 15:32 UTC
Labels: Affects: Admin/Maintenance, Editing, Editions, Orphaned Editions, Type: Bug, Works, merging
