### ISSUE TITLE
"Add Author Photo" broken on Author page

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9473] opened 2024-06-23 15:08 UTC
### Problem

The link to "Add Author Photo" is broken on the Author page.

#### Evidence / Screenshot
![image](https://github.com/internetarchive/openlibrary/assets/26524678/4066b0c0-24b2-4c38-805a-985d4be03a02)

### Reproducing the bug

1. Go to an author page, e.g. http://localhost:8080/authors/OL20585A/Edwin_Abbott_Abbott
2. Do click on the "Add Author Photo" link by mousing over the author photo box in the upper right.

* Expected behavior: it's possible to upload an image.
* Actual behavior: it's not possible to upload an image.

#### Related files

It looks as a change in 17538fd7255a16ef0a7e9ff69095619fb18cfd55 may be causing this.

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by deysandip301** [comment] 2024-07-06 07:09
Hey @scottbarnes I would like to work on this issue.
can you please assign it to me ??

**Comment by scottbarnes** [comment] 2024-07-06 13:06
I went ahead and assigned it to you, @deysandip301. Please let me know if you have any questions.

**Comment by deysandip301** [comment] 2024-07-08 07:39
Hey @scottbarnes , I reproduced the bug locally and identified that the issue is caused by two conflicting <span> elements in infobox.html. Commenting out one resolves the issue. To fix this, we should separate the functionality of the two spans. 
can you suggest me what could be the best practice in which I should implement to solve this bug ?? 

![image](https://github.com/internetarchive/openlibrary/assets/116277357/e2b62dd8-b5eb-4f97-8181-6f7e1eec2a5c)

![image](https://github.com/internetarchive/openlibrary/assets/116277357/9c97b33e-a012-4582-b926-3a3fc40b2f5c)

![image](https://github.com/internetarchive/openlibrary/assets/116277357/e3929b02-b47b-4d5b-b543-fe459ae6b597)

**Comment by deysandip301** [comment] 2024-07-12 18:46
Hey @scottbarnes I am thinking of adding a new javascript file which would render the mobile and desktop items conditionally based on the window size of the user device and will add event listener based on window size 
is it a good approach to solve this problem or is there a bettter way to implement this ??

**Comment by scottbarnes** [comment] 2024-07-13 03:59
@deysandip301, identifying the fact that duplicating the call to `$:render_template("authors/infobox", page)` breaks things is a really good start.

I _think_ the problem _may_ relate to the way that the code, e.g. in https://github.com/internetarchive/openlibrary/blob/9f7257d6db25c39614a5aadf23e580cd6ceb3846/openlibrary/templates/covers/change.html#L45-L46, operates on `#imagesAdd` the `add_frame()` call in https://github.com/internetarchive/openlibrary/blob/9f7257d6db25c39614a5aadf23e580cd6ceb3846/openlibrary/plugins/openlibrary/js/covers.js#L30-L32.

Of course, I could be completely wrong about this, so please don't limit yourself to exploring this line of thinking.

That said, the reason I am focused on `add_frame()` is because `#id` values [should be unique](https://api.jquery.com/id-selector/) in jQuery, and the changes in https://github.com/internetarchive/openlibrary/commit/17538fd7255a16ef0a7e9ff69095619fb18cfd55 ultimately result in `#imagesAdd` (and `#imagesManage`) being added to two elements, even though one has `display: none`. So it's interesting that that ID is doubled up, the code stops working.

In terms of how we fix this, I think we should probably stick with modifying the existing files, and the first step would be to verify whether there is a way to slightly modify, say, `add_frame()` to use a CSS class rather than an ID.

You may have found this already, but when editing JavaScript, `docker-compose exec web npm run watch-css` can be helpful to automate rebuilding. See the [Building CSS and JS](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#building-css-and-js) section of the Frontend Guide for more.

**Comment by deysandip301** [comment] 2024-07-13 05:08
well I got that @scottbarnes
I will surely work on that..

**Comment by scottbarnes** [comment] 2024-07-13 14:03
@deysandip301, great, thanks! I also saw that I linked the wrong part of `change.html`. Hopefully it was obvious I meant the `id` values, but I updated the code link above so it reflects what I was saying.

**Comment by deysandip301** [comment] 2024-07-13 20:53
Hey @scottbarnes I finally got that and able to solve the issue 
it was fun and a great learning experience as I went and read documentation on jquery to work on this issue 
looking forward to contribute more and keep learning
thank you for all the help...

**Closed** 2024-07-22 05:36 UTC
Labels: Type: Bug, Module: Authors, Priority: 2, Lead: @scottbarnes
