### ISSUE TITLE
Books with No Subjects

### ISSUE THREAD

**Issue by bananalifeonthepalouse** [internetarchive/openlibrary#8200] opened 2023-08-17 15:13 UTC
### Question

Is there an easy way to grab a report of all books that don't have any subjects?

**Comment by davidscotson** [comment] 2023-08-19 10:21
If you mean Editions then I have a suggestion. It's perhaps not the best way, but what I'd do with the download of the editions data would be:

```zgrep --invert-match '"subject' ol_dump_editions_2023-04-30.txt.gz | cut -f2```

Or in english: Without having to unzip it search the large file, find any line that doesn't have "subject (note the initial ", this should match "subjects", "subject_people", "subject_place", "subject_time", you could spell these out for slightly improved accuracy) then just report the edition key by cutting it from the second column of the returned line of data.

With that slightly outdated data dump it returns slightly over 20 million entries.

You might be looking for Works with no subjects (i.e. none of the linked editions have any subjects), which would need a few extra hoops jumped, though I feel it would likely be swamped by duplicate works with editions that have yet to be merged to the main entry which may have subjects and so might be misleading, depending on what you aim to do with the data.

**Comment by tfmorris** [comment] 2023-08-19 18:21
@bananalifeonthepalouse What are you trying to do? If you take a step back and describe your goal, people can probably offer you a better solution.

The solution proposed by @davidscotson will technically work, but it doesn't actually match the user experience since subjects are maintained on works, not editions, with them defaulting the to union of all subjects on attached editions. The works which match subject searches can then have editions attached have no subjects assigned to them.

The duplicate unmerged works issue he mentions is real, but there's not really anything you can do about it. Poor data quality is a fact of life with OpenLibrary. Depending on what your actual goal is, there may be ways to work around it.

**Comment by cdrini** [comment] 2023-08-20 05:42
It seems like there are a lot! 😬 https://openlibrary.org/search.json?q=-subject%3A*&mode=everything&fields=key,title,subtitle,author_name,subjects

**Comment by tfmorris** [comment] 2023-08-21 20:38
That's ~52% of the current 33.2M works. I'm guessing that 17.2M works would be considered too many to attempt to query via the Search API, but you can tweak @davidscotson 's bash 1-liner to do the same thing:

```
zgrep -v '"subject' ol_dump_works_2023-07-31.txt.gz | cut -f 2 | cut -d/ -f3 | gzip > ol_works_no_subjects_2023-07-31.txt.gz
```

for some reason, this returns 15.8M works without subjects as compared to the 17.2M quoted by the Solr API. Not sure what the cause of the difference is?

```
zgrep -v '"subject' ol_dump_works_2023-07-31.txt.gz | cut -f 2 | cut -d/ -f3 | wc -l
15817735
```

**Comment by cdrini** [comment] 2023-08-21 21:23
Hmm your query would also exclude eg `subject_people` ; updating the solr to be equivalent: https://openlibrary.org/search.json?q=-subject%3A*+-person%3A*+-place%3A*+-time%3A*&mode=everything&fields=key%2Ctitle%2Csubtitle%2Cauthor_name%2Csubjects

Yields 16,755,037

A little closer but still off by 1mil! The age of the data dump would account for some of it, but seems like too much for it to just be that. Could also be the world `"subject` appears inside descriptions or something? causing a false positive? Not sure!

**Comment by tfmorris** [comment] 2023-08-21 23:29
> The age of the data dump would account for some of it

I'm using the 31 July dump, so it's less than a month old.

> Could also be the word "subject appears inside descriptions or something? causing a false positive?

```
zgrep -E -v '"subjects":|"subject_people":|"subject_places":|"subject_times":' ol_dump_works_2023-07-31.txt.gz | grep '"subject' | wc -l
7
```
which brings the count up to 15817742, but still not very close. Here's the updated command line:

```
zgrep -E -v '"subjects":|"subject_people":|"subject_places":|"subject_times":' ol_dump_works_2023-07-31.txt.gz | cut -f2 | cut -d/ -f3 | gzip > ol_books_no_subjects_2023-07-31.txt.gz
```

**Comment by cdrini** [comment] 2023-08-28 19:07
Are these options giving you what you need, @bananalifeonthepalouse ? If not please re-open, and we'll be happy to help! Closing for now since there's nothing else we can do.

**Closed by cdrini** 2023-08-28 19:07 UTC
Labels: Priority: 3, Type: Question, Lead: @cdrini
