### ISSUE TITLE
Minor CSS issue with lists in the edition specific description

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#4495] opened 2021-01-26 19:38 UTC
Ordered and unordered lists in the edition description are not poperly aligned with the text. Instead of beeing indented to the right they are indented to the left overlapping with other elements.

### Evidence / Screenshot (if possible)
![grafik](https://user-images.githubusercontent.com/2772669/105895164-7812a680-6015-11eb-8e38-e97fc417c26e.png)

### Relevant url?

You can see the probelm in these editions:

- [OL28816021M](https://openlibrary.org/books/OL28816021M/)
- [OL28817180M](https://openlibrary.org/books/OL28817180M/)
- [OL28814276M](https://openlibrary.org/books/OL28814276M/)
- [OL28814727M](https://openlibrary.org/books/OL28814727M/)
- [OL28571653M](https://openlibrary.org/books/OL28571653M/)
- [OL28819107M](https://openlibrary.org/books/OL28819107M/)

### Details

- **Logged in (Y/N)?** both
- **Browser type/version?** Firefox, Chrome, Safari 
- **Operating system?**  OSX
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment] 2021-01-27 03:57
Duplicate of #3611?

**Comment by Yashs911** [comment] 2021-01-27 04:39
@bitnapper I would like to work on this issue

**Closed** 2021-02-12 08:31 UTC
Labels: Lead: @jdlrobson, Needs: Triage, Priority: 3, Type: Bug
