### ISSUE TITLE
ImportBot duplicating Author creation

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#756] opened 2018-01-16 21:19 UTC
Either:
* It creates duplicate author records by default
or
* It performs a simple text comparison and will conflate different authors under the same ID (similar to: https://openlibrary.org/authors/OL2624944A/Smith_(undifferentiated) )
**edit** or
* It fails to match existing authors and leaves 'Author Unknown' (see example in comments below)

I'll be happy to be proved wrong, but either way isn't ideal.

We should at least be clear what the algorithm is so it can be improved, and so problems with existing data can be identified and fixed. 

**Motivation for the suspicion:** I have identified a class of problem records where editions-without-works also have no associated author in OL, but have Author names in the source Internet Archive records. Many have unlinked Author records on OL. I want a way to connect editions with existing authors without creating new ones.

**Example:**

Edition without work and author: https://dev.openlibrary.org/books/OL23519479M
The source IA record, with author: https://archive.org/details/azegyesbirsgire00halmgoog
The unlinked Author record that already exists on OL: https://openlibrary.org/authors/OL6683705A

**Comment by LeadSongDog** [comment] 2018-01-19 19:33
Is this what you're looking for?
https://github.com/internetarchive/openlibrary/blob/f1f7e01bb118e10787bd135a064ca7e4220dbece/openlibrary/catalog/add_book/load_book.py#L118

**Comment by hornc** [comment] 2018-01-29 22:32
See https://openlibrary.org/works/OL17785789W for a recently imported book (Sep 2017) which has ended up with no author, even though the author does exists in OL: https://openlibrary.org/authors/OL6991748A/Mick_McCarthy

**Comment by tfmorris** [comment] 2018-01-29 23:14
Does ImportBot write logs? Are they public? Can we review them to see what
happened here (and in other similar cases)? Adding some logging (if
necessary) might be the first step in figuring out what's going on.

**Comment by LeadSongDog** [comment] 2018-02-08 20:08
@hornc That example had already existed since 2011 as https://openlibrary.org/works/OL16133460W/In_search_of_the_missing for the same ISBN13. Of course the 2017 record https://openlibrary.org/works/OL17785789W  showed a borked isbn_9781856356916 as the OCAID (without showing an ISBN), so that might be connected with the problem.  Are there many of these?

**Comment by hornc** [comment] 2018-03-06 09:31
Author names with titles seem to get many duplicates, according to Wikidata entries with OLIDs. Is this due to some part of the matching algorithm stripping / rearranging titles and not finding matches?
Examples of wikidata authot names to investigate further:
```
John Morley, 1st Viscount Morley of Blackburn
Fulke Greville, 1st Baron Brooke
John Hobhouse, 1st Baron Broughton
Bahá'u'lláh
Jagadish Chandra Bose
Edward of Norwich, 2nd Duke of York
John Fane, 11th Earl of Westmorland
Albert, 4th duc de Broglie
Thomas West, 3rd Baron De La Warr
Christopher Addison, 1st Viscount Addison
Henry Somerset, 8th Duke of Beaufort
Auguste-Théodore-Paul de Broglie
John Paul II
Alexander Lindsay, 25th Earl of Crawford
Stafford Northcote, 1st Earl of Iddesleigh
Colin Lindsay, 3rd Earl of Balcarres
Natalʹja M. Pirumova
```

**Comment by LeadSongDog** [comment] 2018-03-06 19:32
Looking at the last one first, several records had been merged and redirected to OL796597A. Searching for the latinized "Pirumova" found four. Searching for the original "Пирумова" did not. I expanded the alternative names list to include the Cyrilic spelling, but theres a missing link: alternative names don't seem to be included in the author name matching.  OL has no equivalent to Wikipedia's disambiguation pages: a structured way to handle multiple distinct targets matched with the same search string. Instead, we just _hope_ the one we want comes near enough to the top of the list to be seen. 

One coping strategy is simply to add the disambiguation to the bio field of the most prolfic. In this case, I added "Distinguish from Natal'â Iosifovna Pirumova." 

----

Searching for "Earl Balcarres" found several OLIDs for the same author, some but not all redirected to OL4480811A. There are several other earls Balcarres, but none with the same name. There are also several other "Colin Lindsay"s but none with the same lifespan.

**Comment by LeadSongDog** [comment] 2018-03-06 20:54
@hornc At
https://github.com/internetarchive/openlibrary/blob/3559919180b5e43678f90ff3bd721a9c3b92d76c/openlibrary/plugins/worksearch/code.py#L658
 shouldn't "alternate" read "alternative" as elsewhere in that module?

**Comment by hornc** [comment] 2018-03-06 21:31
@LeadSongDog Possibly for consistency with books, and solr, but `alternate_names` is the correct name for the field as currently stored by OL against the author record.

In SOLR `author_alternative_name` is used, see https://github.com/internetarchive/openlibrary/blob/f8092840a77c7479a352fd83fd068d340f97d3e3/conf/solr/conf/schema.xml#L482

Thanks for the **alternative names don't seem to be included in the author name matching** insight, I think that is key! I plan to dig into this further once I have tidied up my i18n PR, and make sure we are using alt names for matching.

**Comment by tfmorris** [comment] 2018-03-07 00:10
Yes, I agree that alternate names are not searchable. Fixing that would help (some) with the can't search for diacritic folded names (at least for cases which have already been merged).

**Comment by LeadSongDog** [comment] 2018-03-12 20:19
It seems that 
https://github.com/internetarchive/openlibrary/commit/8f4a46b87bebaae83ff12e5cebac6af32a0884c5
deliberately introduced the sole instance of "Alternative names" in the code, as a  section heading. @anandology must have had some reason to do so, but I can't see what it was.

**Comment by tfmorris** [comment] 2018-03-13 00:10
"Alternative names" in the UI has no impact on the use of (and correctness of) `alternate_names` in the code. @hornc Note that `author_alternative_names` is a search field for works, not authors. Each work gets indexed by not only its metadata, but also significant bits of metadata from a) its editions and b) its authors.

Not being able to search on alternate names is a good clue, but I don't think the answer is as simple as "alternative" vs "alternate."

**Comment by tfmorris** [comment] 2018-03-25 07:21
My PR #882 which fixes #848 will help address searching the AKAs, but I suspect the problem goes much deeper.

**Comment by LeadSongDog** [comment] 2018-03-26 16:17
For info, there's some interesting work going on at Wikidata on deduping items about individual humans. There's a daily report of items with the same birth and death dates, fed into a deduping process:
https://www.wikidata.org/wiki/Wikidata:Database_reports/identical_birth_and_death_dates
Also available formatted as:
https://www.wikidata.org/wiki/Wikidata:Database_reports/identical_birth_and_death_dates/1

**Comment by LeadSongDog** [comment] 2018-03-27 17:17
Not sure if it is still used, but there is marc import code for author names around https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/works/from_sample.py#91

It seems to address parsing initials for given names in some cases, but it is far from complete.  Really the various initial forms should be listed under the alternative names, as one or another cataloguer somewhere or other may use any form possible. 
Hence "Adams, John Quincy" will show up in marc records with any of the inverted forms:
Adams, John Q.
Adams, John Q
Adams, John
Adams, J. Q.
Adams, J. Q
Adams, J Q
Adams, J.
Adams, J
Adams
Then there will be the allcaps equivalents, the surname-only allcaps equivalents, and the disinverted forms of everything aforementioned. Sometimes the inversion-indicating comma has been omitted by the cataloguer, making it even more confusing. 

While only a few forms will be widely used, many of them will show up in the VIAF record as either "Preferred forms" or "Alternate name forms": https://viaf.org/viaf/36980021 

There are clearly too many to list them all, so some organizing principle ought to be elucidated and brought to bear. The question then is how to choose such a principle.  I would suggest in the meantime that making searches treat the periods as whitespace would be an easy win, vastly reducing the number of variants. Storing only the disinverted forms is similarly easy. If a complete given name (e.g. "Quincy")  is listed, and if the search can be made to match it on the fly, there would be no merit in also storing the initial, except where this is the best-recognized form.

**Comment by LeadSongDog** [comment] 2018-05-11 15:43
@hornc Here's a glaring case: https://openlibrary.org/authors/OL7408198A/Jack_(_Higgins?m=history
missed finding "Jack Higgins" 
One might think it was because of the embedded stray "(" but https://openlibrary.org/search/authors?q=%22Jack+%28+Higgins%22&mode=everything does find it, so I remain unconvinced.
Looking at the MARC https://openlibrary.org/show-records/ia:isbn_9780425165423 
It appears that the 100 $d subfield was not properly parsed by ImportBot.

**Comment by tfmorris** [comment] 2018-05-13 22:41
I don't think that MARC record is correct. It should be `100 $aHiggins, Jack$d1929-`. The fact that it's `100 1  $aHiggins, Jack ($d1929- )` means that the name ended up as Jack ( Higgins and the death date as ')'. The matcher could be made taught to ignore the extra noise, but it doesn't seem like a particularly egregious miss.

**Comment by LeadSongDog** [comment] 2018-05-14 02:36
The MARc record is clearly wrong, but if such trivial typos caused creation of redundant author records, how many such are there?

**Comment by guyjeangilles** [comment] 2019-11-12 22:16
#2180 created the tests that @tfmorris advised. @hornc has there been progress on the "author matcher" as describe above? 

I suggest changing the title of the issue so it more accurate describes the work that needs to be done.

**Comment by agmckee** [comment] 2021-08-02 16:48
Not sure if this issue is being actively worked on, I came across it because I found an example of the second described issue from the OP (It performs a simple text comparison and will conflate different authors under the same ID) and I was researching how it might have happened.

As a software developer myself I know that good cases are useful in debugging so here's the MARC record:

https://openlibrary.org/show-records/talis_openlibrary_contribution/talis-openlibrary-contribution.mrc:2732017825:392

Several books, e.g. https://openlibrary.org/works/OL21884337W/30-Day_Vegetarian_Diet, are now associated with the associated author record, https://openlibrary.org/authors/OL5629119A/Gail_Johnson,  that aren't anything to do with the author. These associations have been made by the ImportBot.

**Comment by agmckee** [comment] 2021-08-02 21:48
@LeadSongDog thanks for cleaning up the Gail Johnson records however I could have done that myself, I thought it was more advisable to determine why ImportBot had got it wrong first.

**Comment by LeadSongDog** [comment] 2021-08-03 02:16
Not much mystery. The bot used low-fidelity info from AMZ without checking elsewhere. AMZ doesn’t even try to distinguish similarly-named authors. For some reason the bot is still being allowed to do this.

**Comment by LeadSongDog** [comment] 2021-11-04 21:14
@cclauss 
Who is it that runs Import Bot? Clearly nothing has been done to fix this. 

Just now, https://openlibrary.org/recentchanges/2021/11/04/add-book/88210045 created yet another duplicate author. Simply checking the world at entry for this isbn finds the book, with the first name rather than just the initial. 

Had this been checked, the bot would not have needed to create https://openlibrary.org/authors/OL9939497A  
which is redundant to https://openlibrary.org/authors/OL572017A and to https://openlibrary.org/authors/OL5692659A.

**Comment by mekarpeles** [comment] 2022-02-02 00:06
I believe this is an issue at the core of our import process, not with e.g. amz. It's prioritized under next proposed milestone

**Comment by hornc** [comment] 2022-02-02 00:54
This is an old issue, and obviously got lost in the pile. Since 2018, I have got a better idea of how author matching algorithm is supposed to work.

Possibly missing some of the detail, and I'd have to dig into the code again after a long while, but in general:

 An Author with dates in the source metadata will _never_ match an existing author without dates.

This appears to be a deliberate early design decision, and from what I remember the design tends to be conservative about not conflating authors where extra data exists. 

This means that if an undated John Smith is imported, and a user adds dates, or the author is merged into one with dates, the next undated John Smith import will create a new record. This seems to be the cause of some of the author import complaints. I'm not sure what a better alternative is using automated matching with the data available.

Some of these early reports of missing author matches which the code _should_ have found were due to gaps in indexing, where some of the 'fuzzier' name matches relied on an up-to-date search index. It has made it notoriously hard to improve, because even the existing code which is not perfect couldn't function correctly in all cases because up-to-date data wasn't available.

Import bot (the main source of new imports) changes weren't being indexed until https://github.com/internetarchive/openlibrary/pull/5617 was deployed ... which was literally yesterday, so I think that will have an impact.

**Comment by LeadSongDog** [comment] 2022-02-03 19:08
@hornc Are you referring literally to importing author records (as from Wikidata, ISNI or VIAF), or rather creating author records anew, linked from newly created (not imported) work records for newly imported editions? I expect the latter, which may be closer to the root of the problem. Creating author records without linkage to an established external identifier should always be the last resort. If we must attribute a work to an undifferentiated John Smith, we should be explicit in doing so: we should show "John Smith undifferentiated" until a specific John Smith is identified.

**Comment by hornc** [comment] 2022-02-04 03:08
@LeadSongDog Authors are only created when new book editions are imported. When I talk about 'author imports' I mean the author creation that occurs on those imports. The code for adding new editions, works, and authors is here https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/add_book/__init__.py  , and the main endpoint which uses this code is the /api/import endpoint.

I guess the terminology is a bit confusing. We import book data into Open Library, and that causes editions, works, and new authors to be created.    Authors are not imported separately from the books they authored.

**Comment by LeadSongDog** [comment] 2022-02-04 06:25
@hornc Yes, that’s as I thought. You do understand why it’s wrong to let the tail wag the dog? This is the very reason we have such an obscene duplication of records on authors. We can’t rationally expect that every catalogued edition MARC record imported will choose to spell an author’s name consistently and distinctly. That is why ISNI and VIAF exist: to provide curated metadata.

**Comment by mekarpeles** [comment] 2023-10-18 16:30
Is this broadly a duplicate of #7349? Author resolution for imports is/was a goal for 2023, so we should track accordingly.

**Comment by scottbarnes** [comment] 2024-07-19 01:13
With #7349 merged, can this issue be closed? I understand there is still author duplication sometimes, but to what extent does this issue accurately reflect the current problem(s)?

**Closed** 2024-08-12 03:58 UTC
Labels: Type: Bug, Module: Import, Priority: 2, Affects: Data, Theme: Unicode, Lead: @scottbarnes, Can it be closed?
