### ISSUE TITLE
Use Invisible ReCaptcha

### ISSUE THREAD

**Issue by beccat123** [internetarchive/openlibrary#7695] opened 2023-03-21 14:19 UTC
Minimal design effort needed: simply remove the currently visible reCaptcha box.

Engineers to investigate into the possibility of using the latest version of reCaptcha, which no longer utilizes a visible checkbox box reading "I'm not a robot" before the user could click on the button to view and complete the graph quiz window and then proceed to the next step. Instead, the newest reCaptcha generates the graph quiz window automatically after the user clicks on the button to proceed to the next step.

Belongs to the epic below:
#7694

**Comment by bottercode** [comment] 2023-03-24 07:29
Can you assign this issue to me? I would like to work.

**Comment by jimchamp** [comment] 2023-07-19 20:58
Closing this issue, which seems to be a duplicate of #7674.  I've updated epic #7694 to reference #7674.

**Closed by jimchamp** 2023-07-19 20:58 UTC
Labels: Type: Feature Request, registration, Good First Issue, Priority: 2, Needs: Investigation, Lead: @beccat123
