### ISSUE TITLE
Librarian Merge Queue user experience improvements.

### ISSUE THREAD

**Issue by Eds-Dbug** [internetarchive/openlibrary#8654] opened 2023-12-20 22:01 UTC
## Relevant Documentation

https://docs.google.com/document/d/1VdEAIFNb7Y-woVPp7KzaHCraak6bJXJthT3f7tgoAD8/edit?usp=sharing

## Main Stakeholders: 
Mek, Onno, Jim Champ, Jenee W, David Scotson, Lisa, Marla, Thorston

## Main Problems:
1. Merge btn loads before the rest of the page loads resulting in potential misclicks from which accidental merges occur.

## Priority of Problems:
1. Problem #1 may have a potential solution see PR #8669

## Related Sub Issues
#8655

## Description, Patron Story

**What is the design change?**
Multiple UI/UX improvements for Librarians and Open Library Personnel on the Merge Queue page and Merge Link pages. 

**Why is this design change necessary?**
To improve the user experience for Librarian Merge Queue and Merge Links which will potentially add to productivity and more user friendly environment.

**Who is it for?**
Librarians and anyone who uses the Merge Queue.

**Constraints or considerations?**
Requires further librarian input to discuss improvements.

## Relevant Designs

**No designs necessary yet**

## Feedback Questions

**Thoughts/reactions/feelings**
Suggestions from @onnotasler: 

1.) First proposed change is to ensure that the "merge" in the in Merge Link pages button doesn't load before the rest of the page loads to avoid misclicks which will result in accidental merges.

**visual design & aesthetics**
The proposed changes thus far do not seem to affect the overall visuals of the Merge Queue or Merge Link pages respectively.
 
### Stakeholders

@openlibrary @Mek @onnotasler @jimchamp @bitnapper

**Comment by Eds-Dbug** [comment] 2023-12-24 21:42
Update to #8655: 

Vir-8 has a solution!

See PR #8669

**Comment by jimchamp** [comment] 2024-02-27 19:09
This seems to be a duplicate of #8655.

**Closed by jimchamp** 2024-02-27 19:09 UTC
Labels: Priority: 3, Type: Epic, Theme: Design, Lead: @jimchamp, Needs: Designs, Type: Design Proposal
