### ISSUE TITLE
Search breaks when you have one " (double quote)

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8416] opened 2023-10-14 15:53 UTC
### Evidence / Screenshot (if possible)
<img width="1113" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/2ccb8a2a-fdcc-4c4c-8fdb-500b0486ba5e">

Search breaks when you have one `"` (double quote)
Does not happen for one `'` (single quote)

### Relevant url?

https://openlibrary.org/search?q=%22This+Was+Logging

### Steps to Reproduce

1. Go to the home page
2. Search for `"This Was Logging`
3. See this error `/openlibrary/openlibrary/templates/work_search.html: error in processing template: TypeError: 'NoneType' object is not subscriptable (falling back to default template)`

* Actual: Gives an error
* Expected: Doesn't give an error

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

We should at least gracefully handle the error. At best, figure out how to deal with that one `"` character.

### Stakeholders

@cdrini

**Comment by cdrini** [comment] 2023-10-14 21:09
Note this seems to only error if `has_fulltext=true` is in the url https://openlibrary.org/search?q=%22This+Was+Logging&has_fulltext=true

**Comment by mansip2002** [comment] 2023-11-24 20:42
Hi, I was wondering if I could take on this issue?

**Comment by RayBB** [comment] 2023-11-25 09:52
@mansip2002 you're welcome to look if you like but this probably requires some understanding of Solr. I'd recommend looking at open issues labeled "good first issue" for something easier.

**Comment by mekarpeles** [comment] 2023-11-27 20:36
@mansip2002 feel free to give it a shot -- do you have any questions about getting started?

**Comment by parmishh** [comment] 2023-12-08 07:33
Hi @RayBB  I tried to reproduce the issue but it seems to work fine for me. Is there any steps I am missing to reproduce let me know.
<img width="960" alt="Screenshot 2023-12-08 130144" src="https://github.com/internetarchive/openlibrary/assets/91942072/1cb6b973-eccc-486e-9c7e-43ce7a4b92da">

**Comment by RayBB** [comment] 2023-12-08 11:27
Looks like the error message is gone which I guess is progress. But it should give search results instead of having zero. Try searching without the quote and see what it shows

**Comment by parmishh** [comment] 2023-12-15 16:45
Hi @RayBB Yes you are right the issue is resolved. But if " is added it should still give some results but gives 0 results. I think I can make this correct. 
Please assign this issue to me

**Comment by mekarpeles** [comment] 2023-12-18 19:38
I agree @RayBB, better results would be nice: @cdrini maybe we can add single quote as a test case in our spreadsheet. In terms of the error, marking the issue itself as closed.

**Closed by mekarpeles** 2023-12-18 19:38 UTC
Labels: Type: Bug, Theme: Search, Needs: Triage, Lead: @cdrini
