### ISSUE TITLE
Fix templates to wrap translatable strings in `$_( ... )`

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1146] opened 2018-09-19 07:07 UTC
There are quite a few old but prominent pages / templates that have missed out on having this added

- [ ] Identify the templates which do not have the strings wrapped in `$_( ... )`
- [ ] Fix all the templates 
- [ ]  add $_( ... ) to the items in the footer 
- [ ] Test the changes

**Comment by tabshaikh** [comment] 2018-10-01 13:33
@mekarpeles can you tell how to see the translated openlibrary page

**Comment by aditya81070** [comment] 2018-10-15 06:41
@salman-bhai Can I take this issue?

**Comment by mekarpeles** [comment] 2018-10-15 06:52
@aditya81070 I don't know if this will be the easiest issue to work on because it requires some background knowledge of our internationalization system. If you feel confident in what the `$_(...)` syntax is doing and when to use it, go for it! Otherwise, we're happy to help you find a good first issue :)

**Comment by aditya81070** [comment] 2018-10-15 06:56
Okay, I think first I should setup docker container and after that, I
should look for issues. I would like to work on first issue to learn things.

**Comment by tabshaikh** [comment] 2018-10-15 07:45
This issue is almost solved in my local repo, will open a pull request soon :)

**Comment by guyjeangilles** [comment] 2019-11-15 00:14
I've added the tasks from @tabshaikh's comment into the original issue. @tabshaikh Was a pull request every made on the work you did?

**Comment by tabshaikh** [comment] 2019-11-19 17:29
No, I think it is in my local fork

**Comment by guyjeangilles** [comment] 2019-11-19 21:49
@tabshaikh Is there anything blocking you from making a PR?

**Comment by tfmorris** [comment] 2019-11-24 19:46
This overlaps with PR #2442

**Comment by mekarpeles** [comment] 2019-12-18 07:58
@tabshaikh which templates are being worked on? Can you please update the issue so it's clear what the scope is? Then you can remove the `Needs: Detail` label

Also, please push the code you have and cite here so someone else can help push it over the finish line (if it's incomplete, that's fine :))

**Comment by tabshaikh** [comment] 2019-12-19 05:46
I have pushed the pr, Initially, when I had opened the issue it was just intended for the footer but the change required is in multiple files for which @tfmorris also has a draft pr

**Comment by tfmorris** [comment] 2020-03-12 19:05
I'm closing this as a duplicate of #973. PR #2442 has the initial pass at internationalizing everything and we have issue #2998 to review and clean up the i18n.

**Closed by tfmorris** 2020-03-12 19:05 UTC
Labels: Close: Duplicate, Lead: @tabshaikh, Priority: 3, Theme: Internationalization, Type: Bug
