### ISSUE TITLE
Edit form is ignoring some options

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2210] opened 2019-07-07 19:57 UTC
### Description

Selecting the "Yes, its a translation" option when editing https://openlibrary.org/books/OL27083670M/The_Black_Tulip is ignored.

### Relevant url?

https://openlibrary.org/books/OL27083670M/The_Black_Tulip

### Details
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:67.0) Gecko/20100101 Firefox/67.0

Reported by kevin61

**Comment by LeadSongDog** [comment] 2019-07-09 21:09
Well, there are several issues with edit forms that need to be addressed, some _very_ longstanding:
#228 #352 #610 #853 #1716 #2033 #2073 
@mekarples Perhaps librarianship and editing issues don't feel as important to devs as cosmetics?

**Comment by seabelis** [comment] 2019-07-10 10:23
Duplicate of #1892

**Comment by cdrini** [comment] 2019-07-19 14:16
Closing as duplicate of #1892

**Closed by cdrini** 2019-07-19 14:17 UTC
Labels: Close: Duplicate, Editing, Priority 1: High, Type: Bug
