### ISSUE TITLE
Strange error on simple author search

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#5595] opened 2021-08-30 16:24 UTC
When I search for the author "lucy bikle", I get an (untranslated) error message saying "Error parsing empty search engine response" which doesn't really make any sense. I know that there are authors matching this search pattern, so I'm not sure why the search engine response is empty or what I should do about it.

### Evidence / Screenshot (if possible)

![Screen Shot 2021-08-30 at 12 16 50 PM](https://user-images.githubusercontent.com/82178/131371071-0d277f33-ec2e-4019-9a61-db8ca604df25.png)

### Steps to Reproduce

1. Go to the search box
2. Do the author name entry

* Actual: Error
* Expected: List of authors which match the search pattern

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by sadn1ck** [comment] 2021-08-30 17:55
I'm unable to reproduce on Chome Version 92.0.4515.159


![image](https://user-images.githubusercontent.com/16396161/131382710-979c0e8c-32b2-4703-8b5b-718bae4f25c4.png)

**Comment by cdrini** [comment] 2021-08-30 21:06
I think this is the result of #5343 ; during a typical "episode" the solr server won't respond, and OL displays an error.

**Comment by LeadSongDog** [comment] 2021-09-02 05:40
Diacritic search symptoms here too. Compare https://openlibrary.org/search/authors?q=Lucy+leffingwell

**Comment by cdrini** [comment] 2021-09-20 20:24
@LeadSongDog I believe that's unrelated to this specific issue.

Closing in favour of #5343

**Closed by cdrini** 2021-09-20 20:24 UTC
Labels: Type: Bug, Needs: Triage, Lead: @cdrini
