### ISSUE TITLE
Fix dangerous author merge UI behavior

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#668] opened 2017-12-09 00:48 UTC
The current author merge UI invites the user to make mistakes by having the first author selected by default and not updating selections appropriately when the user makes changes.

Additionally, the "Are you sure" dialog doesn't include any information that the user could usefully use to confirm they're doing what they intended to.

Proposed changes:

* Remove the default selection when the list is displayed so the user has to explicitly select what they want
* deselecting an author for merge also deselects the "Master" radio button
* confirmation dialog includes information on the author records to be merged

**Comment by tfmorris** [comment] 2017-12-29 21:39
I don't know of the behavior tracks the appearance, but unselecting "Merge" for the first item leaves "Master" selected, which could be triggering this behavior.

Another dangerous behavior occurs when returning to a merge list using the browser Back button. It leaves the previous items selected for merge, but because the contents of the list are changed, the selections are in the wrong place. If a user wants to do a second merge from the same list and isn't extremely careful, they'll end up merging unintended and incorrect items.

**Comment by tfmorris** [comment] 2018-02-28 17:02
Can we repurpose / expand this to fix all the bad / dangerous UI behavior?

Proposed changes:
- Remove the default selection when the list is displayed so the user has to explicitly select what they want
- deselecting an author for merge also deselects the "Master" radio button
- confirmation dialog includes information on the author records to be merged

**Comment by LeadSongDog** [comment] 2018-04-25 20:57
Yes, I just fell victim to it myself:
https://openlibrary.org/authors/OL160727A/Bernard_le_Bovier_de_Fontenelle?b=6&a=5&_compare=Compare&m=diff
I inadvertently left the first line autoselected.

**Comment by LeadSongDog** [comment] 2018-09-05 18:50
Consider what happens when, following an author merge, a user hits their back button. They are presented with the same (perhaps cached) query, listing all the author records, but they are shown only _some of_ the same author records: those just _merged from_ have now disappeared off the list. Are they deselected, or just invisible?

**Comment by guyjeangilles** [comment] 2019-10-31 23:52
Assigning jdlrobson (not tagging per request) since this is front-end related.

**Comment by jdlrobson** [comment] 2019-11-01 01:30
For this one I'll need a better description of the problem,  preferably summarized in the description to be willing to be the assignee.

**Comment by tfmorris** [comment] 2019-11-01 01:46
Do you need more than [this](https://github.com/internetarchive/openlibrary/issues/668#issuecomment-369307926)?

> Can we repurpose / expand this to fix all the bad / dangerous UI behavior?
> 
> Proposed changes:
> 
> * Remove the default selection when the list is displayed so the user has to explicitly select what they want
> * deselecting an author for merge also deselects the "Master" radio button
> * confirmation dialog includes information on the author records to be merged

**Comment by jdlrobson** [comment] 2019-11-01 23:53
This task is too broad to be actionable by me right now. In addition to this I can't get the merge feature working locally or use it in production so am not really sure what's being talked about, so no that's not enough for me (but may be for someone like @mekarpeles). Screenshots, urls and replication steps (written for me as if i am 5 years old) would help me personally.

**Comment by tfmorris** [comment] 2020-05-16 23:50
Part of @jdlrobson's object seemed to be that my proposed changes were in a comment, not the main body of the issue, so I've copied them there.

@seabelis please feel free to edit/update with your thoughts or material from #3469.

**Comment by seabelis** [comment] 2020-05-17 08:31
Thanks, @tfmorris and @LeadSongDog . I knew this issue existed somewhere but couldn't remember what it was called.

**Comment by seabelis** [comment] 2020-05-17 08:36
By automatically selecting  the first listed author by default, the chances of accidental incorrect merges are high. To avoid merging the first listed author, one must double opt out by changing the merge target AND removing the selected check box.

### Evidence / Screenshot (if possible)
I searched Sandra Brown for merging. Janet Daily is selected by default.
<img width="776" alt="Screenshot 2020-05-16 at 19 01 32" src="https://user-images.githubusercontent.com/17739465/82125664-b4fc7d00-97a7-11ea-9c36-a0c3f21edab3.png">

### Steps to Reproduce

1. Search an author.
2. Click merge authors.


* Actual: First listed author is selected by default.
* Expected: Nothing should be selected by default. Only the user should choose which profiles to merge.

@jdlrobson Are these steps and issue clear?

**Comment by LeadSongDog** [comment] 2020-05-17 22:41
Considering the havoc that could result if someone were to search on Smith or Jones this should perhaps be more than priority 3

**Comment by LeadSongDog** [comment] 2020-05-24 17:22
If I read it correctly (that’s a long shot) then the most important part of the problem lies at: 
https://github.com/internetarchive/openlibrary/blob/12c05a664a0e0bb96a4d4594b2c5b1d708ebaf31/openlibrary/templates/merge/authors.html#L17

**Comment by mekarpeles** [comment] 2020-09-29 19:20
Decision:
* Sticky primary
* When primary changes, un-select merge
* Highlight all rows in merge

**Comment by jamesachamp** [comment] 2020-09-30 23:46
Team, the current pull request has the undesired behavior of reordering the author list when a new primary is chosen.  Please review the following updated behavior and let me know if you have any notes:

![sticky_top](https://user-images.githubusercontent.com/28732543/94750736-cc9e6180-0354-11eb-9aff-c067d06d034f.gif)

If this is acceptable, I'll update the PR. Thanks!

**Closed** 2020-10-19 21:11 UTC
Labels: Affects: UI, Module: JavaScript, Needs: Detail, Needs: Lead, Priority: 2, Type: Bug, authors, merging
