### ISSUE TITLE
Malformed subject person query

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#764] opened 2018-01-23 19:01 UTC
On the page https://openlibrary.org/works/OL17512137W/The_Evliya_C%CC%A7elebi_Way there is a link listed under "PEOPLE" to
https://openlibrary.org/subjects/person:evliya_c%CC%A7elebi_(1611?-1682?)

As the dates (1611?-1682?) are not URL encoded, Chrome (and likely other browsers) cannot find the target, and instead one gets:

> Subjects /
> person:evliya çelebi (1611
> We couldn't find any books about person:evliya çelebi (1611.
> 
> Try something else?

**Comment by LeadSongDog** [comment] 2018-01-24 17:13
I suspect this issue originates with the ad-hoc partial url encoding at https://github.com/internetarchive/openlibrary/blob/046ecbec3edf4b749cf758543edb5039dabb972e/openlibrary/templates/subjects.html#L509 
Similar treatment is done at 
https://github.com/internetarchive/openlibrary/blob/046ecbec3edf4b749cf758543edb5039dabb972e/openlibrary/templates/subjects.html#L568
which may have similar effects.

**Comment by tfmorris** [comment] 2018-01-24 17:20
Good catch. URL encoding should be done on the entire thing using a standard library function.

**Comment by hornc** [comment] 2018-03-13 21:15
:+1:  I think there are numerous locations where ad-hoc partial encoding is happening, I was looking at another similar one earlier, https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/models.py#L414

That looks to be HTML encoding, but since they are partial it is hard to figure out why a particular substitution is made. There should be standard safe-encoding functions + libraries we can use consistently. I'll look for existing full encoding functions in the codebase and update here.

**Comment by hornc** [comment] 2018-03-13 21:47
It took a while to create a link that does the right thing here:
https://openlibrary.org/subjects/person:evliya_%C3%A7elebi_(1611%3f-1682%3f)

The `?`s are throwing the url off, as in this similar example:
From https://openlibrary.org/works/OL5507491W/America  any Subject person with a '?' in their dates does not get `?` encoded to `%3d`

 https://openlibrary.org/subjects/person:walter_raleigh_sir_(1552?-1618)
should be
 https://openlibrary.org/subjects/person:walter_raleigh_sir_(1552%3f-1618)

Additionally the Evliya Çelebi example has trouble with the c-cedilla, it looks like the link is using a compose character of c followed by a cedilla, while the subject page expects there to be a combined character.
 
URL encoding is needed for '?' characters (lets use a standard lib that does everything).
The unicode cahr issue might need some more investigation for a fix.

**Comment by hornc** [comment] 2018-03-13 23:38
Common escaping code appears to live here: https://github.com/internetarchive/openlibrary/blob/ad4ab0b61755d010775692facaf5bff989648473/openlibrary/core/helpers.py

**Comment by tfmorris** [comment] 2018-03-14 05:34
Back at the dawn of time it may (**MAY**) have made sense to roll one's own, but today we should just use the standard escaping mechanisms of the URL library or HTML library.

**Comment by kd2718** [comment] 2018-10-21 02:36
it looks like this is still an issue. I can take a look

**Comment by YBthebest** [comment] 2018-11-19 23:20
If nobody's doing this yet, I'll be starting work on this issue, as it seems @kd2718 hasn't pursued !

**Comment by YBthebest** [comment] 2018-11-26 02:33
Hi, could anyone help me with a couple of questions I have regarding the usage of links in the project. I have a tough time understanding some of the functioning. 
To start off, very basic, but how does this URL: 
https://openlibrary.org/subjects/person:daniel_defoe_(1661-1731)
result in this title: Daniel Defoe (1661?-1731)
i.e, where is this logic handled? There are a lot of encoding issues here and it seems like the ?'s are arbitrarily taken out of the URL. They should clearly be encoded instead, but this breaks the ability of the page to retrieve the correct subject here.

**Comment by LeadSongDog** [comment] 2018-11-26 17:06
@YBthebest, It is a mess. Under https://openlibrary.org/authors/OL18283A/Daniel_Defoe there are different "people" versions of that name, as well as many author AKAs listed: Daniel Defoe (1661?-1731), Daniel Defoe, Daniel Defoe (1660 or 1-1731) are all there. Of the "people", only "Daniel Defoe" sans dates is among the AKAs. 

At some stage, it would seem that a highly automated cleanup should add the "people" variations to the  AKAs, then consolidate the "people" variations to the best-completed of the author name. Ideally at some point the "people" should all link to OL18283A rather strings. Eventually, the "people" and AKAs entries should each link to an authority record that supports their being for that author; VIAF, ISNI, or Wikidata could all work. Of course for people who were not authors a different approach is needed. 

This should likely be discussed and turned into a set of issues for openlibrary-client.

**Comment by YBthebest** [comment] 2018-11-26 19:19
Yes, it seems like linking to OL18283A-like strings would be the easiest solution. I would be glad to try to solve some of the arising issues, but I'm not familiar enough with the platform yet to fully understand how it is all managed currently (between authors, subjects, persons, and so on).

**Comment by kd2718** [comment] 2018-11-26 19:39
@YBthebest, this is what scared me away. I was hoping to grab any URLs from sent from the backend and make sure they are properly html escaped or handled in a different way. However, I was unable to figure out what was going on. I am not familiar with web.py and had a hard time understanding how it all worked. 

I began to suspect that there were dead paths in the codebase, but didn't want to say to much as this was my first time working with this repo. However, now that it seems you are falling into the same pits I did, I thought I would chime in.

At one point i found where the text for the links was determined on the frontend code, but was not able to find where the url was returned from the database. We should really escape all strings that will be used in URLs before they are saved to the DB, but I think your idea of using the unique identifier is a better idea.

**Comment by YBthebest** [comment] 2018-11-26 19:41
@kd2718 Great to hear back from you. Yes, it seems that URL's are handled in multiple different ways and this really leads to a bunch of deadlinks on different pages. I can't seem to understand exactly how it works yet, so was hoping for a more active contributor to help clarify a bit. I think that switching to unique identifiers would be much better than the rest, but it might not be as easy to achieve as we think.

**Comment by YBthebest** [comment] 2018-11-28 17:59
@LeadSongDog Would you have any idea of one of the sub-tasks that I could try to get fixed at this moment in time, or do we need to carefully carve out the other issues first?

**Comment by LeadSongDog** [comment] 2018-11-28 18:22
@YBthebest Probably the first thing to do is decide on how urlencoding _ought_ to be consistently implemented. See the Mar 13-14 discussion above between @hornc and @tfmorris for hints. After that, survey where we have other sorts of implementations that needs to be changed.

**Comment by kd2718** [comment] 2018-11-29 19:59
@LeadSongDog urlencoding ought to be implemented with the standard libarary, like in the example [here](https://stackoverflow.com/a/9345102/4788717). The issue is that @YBthebest and I have not been able to figure out where all urls are built on the backend. The comment by @hornc on [March 13th](https://github.com/internetarchive/openlibrary/issues/764#issuecomment-372821117) looks like it has one location, but is that where all of them are created?

**Comment by YBthebest** [comment] 2018-11-29 22:49
@kd2718 Yes, good summary. To add to that, I can't seem to entirely understand how the backend works in regards to the link -- what is stored in the DB, what is dynamically generated, and so forth. A couple of the issues seem to arise from this.

**Comment by tfmorris** [comment] 2018-11-30 07:17
I've visited this a few times recently, but always run out of time before reaching a satisfactory conclusion, so this time I'm just going to answer as much as I have time for.

> To start off, very basic, but how does this URL:
> https://openlibrary.org/subjects/person:daniel_defoe_(1661-1731)
> result in this title: Daniel Defoe (1661?-1731)
> i.e, where is this logic handled? 

No idea, but I'm not sure it matters. In case it helps with other cases like this, a good "cheat" is to tack `.json` on the end to see the raw data: https://openlibrary.org/subjects/person:daniel_defoe_(1661-1731).json

In this case, I don't see anything obvious, so my guesses are: 1) stale cache somewhere, 2) obscure code somewhere which uses indirection through works & authors, but the canonical author record *also* doesn't match, so perhaps more stale cache.  But, as I said, I don't think it matters. 

> Under https://openlibrary.org/authors/OL18283A/Daniel_Defoe there are different "people" versions of that name, as well as many author AKAs listed: Daniel Defoe (1661?-1731), Daniel Defoe, Daniel Defoe (1660 or 1-1731) are all there. Of the "people", only "Daniel Defoe" sans dates is among the AKAs.

I think that list is a includes all "subjects" for all works by the given author. OpenLibrary manages subjects as strings, not things (ie objects), so the multiplicity of choices is a natural consequence. Again, I don't think it matters for the problem at hand.

The problem, as I understand it, is to translate a subject containing characters which require escaping translated into a URL which will target the correct subject. For the most recent example, the top person subject for Daniel Defoe's work is "Daniel Defoe (1661?-1731)" which links to:

   https://openlibrary.org/subjects/person:daniel_defoe_(1661?-1731)

which doesn't resolve, but the correctly encoded version does:

   https://openlibrary.org/subjects/person:daniel_defoe_(1661%3f-1731)

so, the task is to get either the back end of the front end to do the correct encoding. Since I see:

    <a href="/subjects/person:daniel_defoe_(1661?-1731)">Daniel Defoe (1661?-1731)</a>

in the HTML, it looks like it's the backend that's failing to do the correct encoding.

A quick inspection of the HTML, followed by a search of the source tree gives:
https://github.com/internetarchive/openlibrary/blob/b67ec90a470d230f3ba7cae3ac0f2c734ffb1aed/openlibrary/templates/type/author/view.html#L194
as the likely culprit.

Unfortunately, there also appear to be a number of other copies of `render_subjects()` so perhaps an opportunity to DRY.

Timing out... Hope that's enough to get started!

**Comment by tfmorris** [comment] 2018-12-01 17:16
> I want to point out that, [in this link](https://openlibrary.org/works/OL16109211W/Fortunes_and_misfortunes_of_the_famous_Moll_Flanders), the url under people is malformed (as the `?` in the birth date) and is built by the template engine, not returned as json.

That's why I wrote:

> Since I see:
>
>     <a href="/subjects/person:daniel_defoe_(1661?-1731)">Daniel Defoe (1661?-1731)</a>
> in the HTML, it looks like it's the backend that's failing to do the correct encoding.

and posted links to the template code.

**Comment by mekarpeles** [comment] 2019-07-03 19:53
This seems to be fixed with the latest upgrade of web.py from 0.33 to 0.39

**Closed by mekarpeles** 2019-07-03 19:53 UTC
Labels: Good First Issue
