### ISSUE TITLE
"More by author" doesn't list books by the actual author

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1016] opened 2018-07-06 14:18 UTC
https://github.com/internetarchive/openlibrary/blob/173bbe52694445639bf3e5e5e3bc4a5bb41650ad/openlibrary/macros/RelatedWorksCarousel.html#L8

is generating unrelated content such as:
https://archive.org/search.php?query=openlibrary_work:(*)%20AND%20collection:(inlibrary)%20AND%20loans__status__status:AVAILABLE%20AND%20(creator:%22Smith,%20John%22%20OR%20creator:%22John,Smith,%22)%20AND%20!openlibrary_work:(OL217077W)

simply because of the superficial similarity of many authors' names to https://openlibrary.org/authors/OL2440391A/Smith_John

**Comment by jdlrobson** [comment] 2018-12-14 23:47
@LeadSongDog not sure I understand this bug. Can you please update the description to make it clearer. I don't see any carousel on https://openlibrary.org/authors/OL2440391A/Smith_John...

**Comment by LeadSongDog** [comment] 2018-12-15 01:58
I just used John Smith as an illustration. Any common name has the same behaviour. Look at a book by one Helen Young and books by other Helen Young’s  show up in the carousel. Often these are from different centuries. It still happens even on mobile.

**Comment by jdlrobson** [comment] 2018-12-15 02:14
Are you referring to the fact that   on https://openlibrary.org/works/OL217077W/The_art_of_painting_in_oyl "more by john smith" shows books that are by different john smiths?

**Comment by LeadSongDog** [comment] 2018-12-15 03:10
Exactly. It should instead show just the _same_ olid’s works by 
https://openlibrary.org/authors/OL2440391A/John_Smith

**Comment by tfmorris** [comment] 2019-02-18 23:48
This appears to be fundamentally wrong. I don't understand why this:

* isn't using OpenLibrary metadata
* is using generic string matching when we have strong identifiers
* isn't using a standard "works by author" query which is already built and in use all over the place

When looking at this Carl Zimmer work https://openlibrary.org/works/OL13699253W/Soul_made_flesh
the recommendation is for "Modern Style" by Lawrence Grow with no hint of a Zimmer in sight. 

This recommendation is so completely wacky it makes OpenLibrary look brain dead. Clicking on the "More by" hyperlink takes you away from OpenLibrary, which is another poor design choice.

This list should be constructed using the same query as is used to create the list on the author page
https://openlibrary.org/authors/OL394581A/Carl_Zimmer. Ideally it should be deduped and sorted by similarity or popularity, but getting the basics fixed first is more important.

**Comment by tfmorris** [comment] 2019-02-18 23:57
It looks like where this went wrong was by being based on `custom_ia_carousel` but I can't tell if that was intentional or just a historical design accident/flaw.

@mekarpeles it looks like you did a bunch of refactoring on RelatedWorksCarousel/WorksCarousel, but can't tell if you were involved in its creation. Do you know if there's a reason that this doesn't use the obvious pattern of using OL metadata?

**Comment by jdlrobson** [comment] 2019-02-19 00:16
Not on computer at moment but are there an JS errors in the developer console? That would be my first guess.

**Comment by brad2014** [comment] 2019-05-14 08:23
@mekarpeles I'm going to assign this to you on the hypothesis that it's related to your carousel work, but feel free to reassign as appropriate.

**Comment by RayBB** [comment] 2023-10-07 12:18
This is fixed now.
The john smith mentioned in original issue doesn't have works to borrow and no carousel shows up.
But with a work like this https://openlibrary.org/works/OL5734718W/Little_Brother
The carousel shows up just fine and only shows works by the exact same author (by ID)
<img width="1104" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/1aea6138-49c1-4a9e-8ae7-82aec81ac80e">

**Closed by RayBB** 2023-10-07 12:18 UTC
Labels: Type: Bug, Module: Carousels, Priority: 3, Affects: Server, Lead: @mekarpeles

**Comment by tfmorris** [comment] 2023-10-09 18:42
Cory Doctorow isn't a very good example since his name is unique, but I've confirmed that the Carl Zimmer example that I gave above now works correctly. The fix was in 03d0ab845906c937429c54c0fb73bcb669269bd7
