### ISSUE TITLE
Home page won't load after following docker setup instructions

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#4954] opened 2021-04-01 04:00 UTC
I followed the docker setup instructions, they were pretty easy.

However, after actually starting everything the home page won't load (though things like search do work).

The error I'm getting is this:

```
web_1           |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/xml/etree/ElementPath.py", line 354, in iterfind
web_1           |     selector = _cache[cache_key]
web_1           | KeyError: ('//item',)
web_1           | 
web_1           | During handling of the above exception, another exception occurred:
web_1           | 
web_1           | Traceback (most recent call last):
web_1           |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 280, in process
web_1           |     return self.handle()
web_1           |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 271, in handle
web_1           |     return self._delegate(fn, self.fvars, args)
web_1           |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 517, in _delegate
web_1           |     return handle_class(cls)
web_1           |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 495, in handle_class
web_1           |     return tocall(*args)
web_1           |   File "/openlibrary/infogami/utils/app.py", line 187, in <lambda>
web_1           |     HEAD = GET = POST = PUT = DELETE = lambda self: delegate()
web_1           |   File "/openlibrary/infogami/utils/app.py", line 206, in delegate
web_1           |     return getattr(cls(), method)(*args)
web_1           |   File "/openlibrary/openlibrary/plugins/openlibrary/home.py", line 81, in GET
web_1           |     cached_homepage = get_cached_homepage()
web_1           |   File "/openlibrary/openlibrary/plugins/openlibrary/home.py", line 74, in get_cached_homepage
web_1           |     return cache.memcache_memoize(
web_1           |   File "/openlibrary/openlibrary/core/cache.py", line 112, in __call__
web_1           |     value, t = self.update(*args, **kw)
web_1           |   File "/openlibrary/openlibrary/core/cache.py", line 153, in update
web_1           |     value = self.f(*args, **kw)
web_1           |   File "/openlibrary/openlibrary/plugins/openlibrary/home.py", line 39, in get_homepage
web_1           |     blog_posts = get_blog_feeds()
web_1           |   File "/openlibrary/openlibrary/plugins/upstream/utils.py", line 786, in get_blog_feeds
web_1           |     return [process(post) for post in _get_blog_feeds()]
web_1           |   File "/openlibrary/openlibrary/core/cache.py", line 112, in __call__
web_1           |     value, t = self.update(*args, **kw)
web_1           |   File "/openlibrary/openlibrary/core/cache.py", line 153, in update
web_1           |     value = self.f(*args, **kw)
web_1           |   File "/openlibrary/openlibrary/plugins/upstream/utils.py", line 748, in _get_blog_feeds
web_1           |     return [parse_item(item) for item in tree.findall("//item")]
web_1           |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/xml/etree/ElementPath.py", line 395, in findall
web_1           |     return list(iterfind(elem, path, namespaces))
web_1           |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/xml/etree/ElementPath.py", line 359, in iterfind
web_1           |     raise SyntaxError("cannot use absolute path on element")
web_1           |   File "<string>", line None
web_1           | SyntaxError: cannot use absolute path on element
web_1           | 
web_1           | error saved to /var/log/openlibrary/ol-errors/2021-04-01/034100742902.html
```

On the home page the error is simply:
```
Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2021-04-01/034515694914 and will look into it as soon as possible. Head for home?
```

Here is the related error html file: https://jsfiddle.net/c6rpdsa3/

### Steps to Reproduce

1. Follow docker setup instructions
2. Go to homepage of open library after running

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** FF/Chrome
- **Operating system?** Mac
- **Environment (prod/dev/local)?** local

**Comment by cdrini** [comment] 2021-04-01 04:17
Thanks for the report @RayBB ! Looks like a duplicate of #4942 . I just merged @drakene 's fix, so let me know if it's working now!

**Closed by cdrini** 2021-04-01 04:17 UTC
Labels: Needs: Lead, Needs: Triage, Type: Bug
