### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by montorodiaz** [internetarchive/openlibrary#4674] opened 2021-02-25 13:53 UTC
Hello:

We are recently having trouble with the OpenLibrary covers on our website.

We use the cover calls in an img tag:

`<img src="https://covers.openlibrary.org/b/isbn/8435005836-M.jpg" />`

If we do:

- requests with correct ISBN but not in openLibrary
- requests with incorrect ISBN

The response from the server is:

"internal server error"

Previously, in the case of non-existent covers, the server returned a notfound response.

### Evidence

Correct example:

https://covers.openlibrary.org/b/isbn/8435005836-M.jpg

Incorrect ISBN example:

https://covers.openlibrary.org/b/isbn/84350s05836-M.jpg (internal server error)

Example of the image that would correspond to a correct ISBN but does not have:https://covers.openlibrary.org/b/isbn/8422659026-M.jpg (internal server error)

Example of a request that includes an incorrect ISBN:
https://covers.openlibrary.org/b/isbn/8422659027-M.jpg  (internal server error)

##workaourn

Due to this error, we process the image by javascript, and if we get error from the openlibrary server, we discard the image.

Thanks

**Comment by jamesachamp** [comment] 2021-03-02 18:32
This may be a duplicate of #4680 (or vice versa).  If so, it should be fixed after the next deployment.

**Comment by montorodiaz** [comment] 2021-03-03 08:25
Hello:

Yes, it appears to be a duplicate of https://github.com/internetarchive/openlibrary/issues/4680, which is now resolved.

We will wait for the next deployment to check it.

Greetings and thank you.

**Comment by montorodiaz** [comment] 2021-03-03 08:30
Duplicate of https://github.com/internetarchive/openlibrary/issues/4680, which is now resolved.

**Closed** 2021-03-03 08:30 UTC
Labels: Lead: @cclauss, Needs: Lead, Needs: Triage, Type: Bug

**Comment by cclauss** [comment] 2021-03-03 08:31
Cool @montorodiaz I should do the next [deployment](https://github.com/internetarchive/openlibrary/releases) today so please recheck this in ~24 hours
