### ISSUE TITLE
Experiment: Resolve top 100K OpenAlex Books to ISBN 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8623] opened 2023-12-13 17:56 UTC
### Describe the problem that you'd like solved

OpenAlex (mostly journals) has a list of books with some metadata:

https://openalex.org/works?sort=cited_by_count%3Adesc&column=display_name,publication_year,type,open_access.is_oa,cited_by_count&page=1&filter=type%3Abook

Can we try to match the top 100K most cited books from OpenAlex to Open Library works? The Open Library Book Search API (https://openlibrary.org/search.json) may be a good place to run a few experiments to see what type of matches we get. Ask questions & document your findings on this issue!

**Comment by nick2432** [comment] 2023-12-17 02:20
can i work on this?

**Comment by shivam200446** [comment] 2023-12-19 12:37
@mekarpeles Hey sir, I would like to work on it.

**Comment by scottbarnes** [comment] 2023-12-19 21:15
@nick2432, I have assigned this to you. Sorry for the delay and please let me know if you have any questions.

@shivam200446, maybe one of these might be a good fit? https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+label%3A%22Good+First+Issue%22+no%3Aassignee.

**Comment by Billa05** [comment] 2024-01-07 16:00
Hey, @nick2432, are you working on this? If not, I can help with this issue.

**Comment by Billa05** [comment] 2024-01-08 16:22
Hi @scottbarnes, I did some research and it seems that our task is to verify whether the first 100,000 most cited books from Opnealex are available in the ol or not. The parameters that I have used for this task are title, author, and publish_year. Do you think there are any other parameters that should be taken into consideration? I have written a Python script to record all the missing books in a file.

**Comment by Billa05** [comment] 2024-01-08 18:58
I ran the program for the first 10,000 books and discovered the following:
1. Out of the 10,000 books, 2,194 had no results in the OL search.
2. There are issues with decoding JSON which is causing failures in many cases
3. Including the 2nd case, and some Connection aborted errors. A total of 663 books didn't get processed due to these errors.

Once I receive @scottbarnes  inputs, I'll try to fix the errors and run the program for all the books.

**Comment by scottbarnes** [comment] 2024-01-10 04:28
@Billa05, I followed up on Slack. :)

**Comment by Billa05** [comment] 2024-01-11 19:05
Hey @scottbarnes , I've shared the link to the code on Slack.

**Comment by scottbarnes** [comment] 2024-01-11 20:17
@Billa05, I ran the code on a few hundred items, but didn't get any errors. However, I left some feedback on the gist you shared that may help explain where the errors are coming from.

**Comment by Billa05** [comment] 2024-01-12 20:23
Yeah @scottbarnes, I did the same and it's working perfectly. Maybe I was having network problems that day. what would be the next step towards this issue?

**Comment by scottbarnes** [comment] 2024-01-12 21:27
@Billa05, I think the next step is to simply report what kind of matches turn up. For example, perhaps see how many matches there are when you try searching with whatever information is available (e.g. if there is no author, still trying a search and seeing if there is a match). Then trying again but requiring both an author and a title. And finally maybe requiring all three match.

What else sounds like it might be interesting to see?

**Comment by Billa05** [comment] 2024-01-13 10:13
Hey @scottbarnes, I can think of 4 cases: 
1) only title
2) title and author
3) title and publish date
4) all three parameters.

For now, I will only take the first 300 books. Once done, I will share the record in Google Docs.

**Comment by Billa05** [comment] 2024-01-19 18:24
hey @scottbarnes I experimented and here's what I got :

number of books found in OL (out of first 300 books):

- Only title: 272 books
- Title & publish_date: 272 books
- Title & author: 241 books
- All three parameters: 241 books

It appears that the first two and the last two yield identical outcomes.

**Comment by scottbarnes** [comment] 2024-01-25 14:35
Hi, @Billa05. Thanks for this. I will talk with @mekarpeles about how to proceed.

One thing I realize I may not have been clear about is I was wondering, for example, how many _only_ had a title, and how many _only_ had a title and publish_date. I know it could be a coincidence that they're the same, as are the other two, just to make sure, there are 272 with _only_ a title, correct, and a different 272 with _only_ a title and publish_date?

**Comment by mekarpeles** [comment] 2024-01-29 16:52
Open Alex has metadata, including ISBN, we want to find e.g. the top 100k (or 10k) books w/ ISBN.

We want to look for these 10k or 100k isbns in e.g. Open Library data dump or search (in batches of ~100) and see which Open Library records exist v. are missing.

Compile a list of all of the hits (e.g. `openalex_id`, `isbn`, `openlibrary_edition`) and keep track of misses (e.g. `openalex_id`, `isbn`).

**Next steps:**
Eventually, we want (a) import any missing record, (b) add `openalex` identifiers for any existing record, (c) give the openalex folks a query so they can see all Open Library records with `openalex` identifiers and also `ocaids` (meaning they have previews or are readable/borrowable.

**Comment by Billa05** [comment] 2024-02-04 09:47
> Hi, @Billa05. Thanks for this. I will talk with @mekarpeles about how to proceed.
> 
> One thing I realize I may not have been clear about is I was wondering, for example, how many _only_ had a title, and how many _only_ had a title and publish_date. I know it could be a coincidence that they're the same, as are the other two, just to make sure, there are 272 with _only_ a title, correct, and a different 272 with _only_ a title and publish_date?

When searched with only title as a parameter, and when searched with title and publish date, it returns the same results. I have cross-checked it, and the same applies to the other two.

**Comment by Billa05** [comment] 2024-02-04 09:52
> Open Alex has metadata, including ISBN, we want to find e.g. the top 100k (or 10k) books w/ ISBN.
> 
> We want to look for these 10k or 100k isbns in e.g. Open Library data dump or search (in batches of ~100) and see which Open Library records exist v. are missing.
> 
> Compile a list of all of the hits (e.g. `openalex_id`, `isbn`, `openlibrary_edition`) and keep track of misses (e.g. `openalex_id`, `isbn`).
> 
> **Next steps:** Eventually, we want (a) import any missing record, (b) add `openalex` identifiers for any existing record, (c) give the openalex folks a query so they can see all Open Library records with `openalex` identifiers and also `ocaids` (meaning they have previews or are readable/borrowable.

I have been very busy lately. Once I have some free time, I will start on this and share my findings.

**Comment by mekarpeles** [comment] 2024-02-26 20:26
Hi @Billa05 I know you're quite busy at the moment, I just wanted to see if you're able to share the code that you do have so that we can help and continue your efforts -- that would be a big help! Thank you

**Comment by Billa05** [comment] 2024-02-27 06:24
> Hi @Billa05 I know you're quite busy at the moment, I just wanted to see if you're able to share the code that you do have so that we can help and continue your efforts -- that would be a big help! Thank you

Hey @mekarpeles , I apologize for my inactivity for the past two weeks. I was busy with exams, followed by a hackathon and a personal project. I'm also working on ML. I assure you that I will start working on it this week. you can find the code [here](https://gist.github.com/Billa05/8a931badf0ca15dc8d59add660db69bb).

**Comment by Billa05** [comment] 2024-02-28 17:44
Hey @mekarpeles , I'm afraid that OpenAlex doesn't provide ISBNs in their metadata.
that is why I was trying the combination of parameters like:

1. only title
2. title and author
3. title and publish date
4. all three parameters.

**Comment by scottbarnes** [comment] 2024-02-28 21:13
We _might_ be able to get some ISBN data out of some of the records. I am not sure how reliable this is, but in looking at the records for a few books, the DOI field has a URL which contains either an ISBN 10 or 13. See, e.g. https://api.openalex.org/works/W2752384816 and https://api.openalex.org/works/W4299689471.

The ISBNs seem to be for digital editions, which may be worth noting. But I would suggest trying to extract the ISBN out of the DOI field. E.g. using https://api.openalex.org/works/W2752384816 with the [isbnlib](https://github.com/xlcnd/isbnlib) library:
```
In [7]: from isbnlib import is_isbn13

In [8]: is_isbn13("https://doi.org/10.4159/9780674369542".split("/")[-1])
Out[8]: True
```

You'll need to count the length of the element after the last `/` to know whether to run `is_isbn10` or `is_isbn13`, but it should be pretty easy to see if the end of the DOI is a valid ISBN.

**Comment by Billa05** [comment] 2024-02-29 17:04
Thank you @scottbarnes, Most books have the ISBN in the DOI field. it's just that they are in different formats like 
978-94-009-3027-8
1.9781611970777
cbo9780511488856

**Comment by scottbarnes** [comment] 2024-03-01 14:34
I realize you may already be planning this, but just to error on the side of caution, how about doing something like, for example:
```python
>>> from isbnlib import canonical
>>> maybe_isbns = ['978-94-009-3027-8', '1.9781611970777', 'cbo9780511488856']
>>> isbns = [get_canonical_isbn(maybe_isbn) for maybe_isbn in maybe_isbns]
>>> isbns
['9789400930278', '9781611970777', '9780511488856']
```

**Comment by Billa05** [comment] 2024-03-01 19:36
Hey @scottbarnes, I have shared my findings on this [repo](https://github.com/Billa05/OpenAlex_experiment) for the first 200 books. Could you please check it out?

**Comment by scottbarnes** [comment] 2024-03-01 19:55
This looks great, @Billa05. Thanks so much for your hard work.

@mekarpeles had mentioned either (1) querying `search.json` in batches of 100, or (2) parsing a [data dump](https://openlibrary.org/developers/dumps) (presumably the editions dump).

One way to break these tasks apart would be to run the query against the 100K most cited books from OpenAlex and write those ISBNs to a file, without querying Open Library as part of this step.

Then, once you've got all the ISBNs parsed out of the top 100k cited books on OpenAlex and saved to a file, you can either (1) query `search.json` in batches of 100, or (2) parse a data dump by reading from that file.

How does that sound?

**Comment by Billa05** [comment] 2024-03-02 07:05
@scottbarnes sounds good to me. I will go ahead and move forward with the query search. Please confirm if `openlibrary_edition` means the `key` in this format => `/works/OL25713116W` or it's the list of `edition_key`?

**Comment by scottbarnes** [comment] 2024-03-02 14:54
I am not quite following, but does this answer the question: If this question is arising in the context of parsing a data dump, @mekarpeles mentioned we want to resolve the top 100k most cited OpenAlex books to Open Library Works by their ISBN, and on Open Library the ISBN is stored on the edition, so if parsing the data dumps you'd want to:
- check the lists in the `isbn_10` and `isbn_13` field of each edition;
- if an ISBN from one of the 100k most-cited OpenAlex books is present then you'd want to store the `/works/OL...W` value from that edition's `works` key; and
- save the ISBN 13 (let's save them all as ISBN 13), the Open Library Work key, and the Open Library Edition key (see below).

Note, because it's possible OpenAlex has, for example, an ISBN 13 representation of an ISBN 10, and Open Library may only have an ISBN 10 for that same ISBN, it probably makes sense to convert both the ISBNs from OpenAlex and any ISBNs in an Open Library edition's `isbn_10` list to ISBN 13 before comparing to see if the OpenAlex ISBN is present in an Open Library edition.

Also, even though @mekarpeles mentioned resolving the top 100k most-cited OpenAlex books to Open Library works, if parsing the data dumps, please record the Open Library edition (the `key` field that looks like `/books/OL...M`) also. Perhaps it would be interesting to see if there is a significant difference between the editions cited and the Works in Open Library, versus the Editions.

So putting this all together, for `9780511812507`, which I saw from your prior work is an ISBN 13 from Open Alex that's present in Open Library, you'd want to record both `/works/OL25713116W` from the `works` key, and `/books/OL34556568M` from the `key` field.

I am unsure of the best format, but absent a better idea, perhaps write these all to a CSV or JSONL file, such as:
```csv
9780511812507,/works/OL25713116W,/books/OL34556568M
````
Or:
```jsonl
{"ISBN_13": "9780511812507", "work": "/works/OL25713116W", "edition": "/books/OL34556568M"}
```

I realize this may be slightly misleading since we're doing all the ISBN comparison by converting to ISBN 13, and perhaps the Open Library Edition only has the ISBN 10, but we'll just have to remember we did all the comparisons as ISBN 13.

Having written all of this, I *think* parsing the data dump has the potential to be quite slow, as you may have already realized, though it is likely what I would do to try avoid hammering the Open Library server -- though doing it in batches of 100 is probably fine. But if you want to parse the data dump for fun and profit, you'll probably want to do something such as put all the ISBNs from Open Alex in a Python `set`, assuming they fit in memory. Then for each line of the editions dump, check the `isbn_10` and `isbn_13` field to see if the ISBN 13 (or converted ISBN 10 -> ISBN 13) is present `in` the `set`, and then record the relevant data in a `CSV` or `JSONL` format file as mentioned above. 

I hope that wall of text makes sense.

**Comment by scottbarnes** [comment] 2024-03-02 17:45
@Billa05, I updated my comment above as I think I understood the confusion. Please let me know if everything makes sense now.

**Comment by Billa05** [comment] 2024-03-03 10:58
> @Billa05, I updated my comment above as I think I understood the confusion. Please let me know if everything makes sense now.

@scottbarnes, it is now completely clear.

**Comment by Billa05** [comment] 2024-03-11 14:03
Hi, @scottbarnes, I tried using ol_dump for a task, but unfortunately, it is causing errors due to invalid JSON. Please take a look at the [using_OlDumb.py](https://github.com/Billa05/OpenAlex_experiment/blob/master/using_OlDumb.py) file. Before running the file, ensure you have the `ol_dump.txt` file. 

I have come up with another solution. I tried searching for ISBN13 in the `search.json`. If it's not found, I attempted to search with ISBN10. Unfortunately, the API rate limit is causing a 503 error, which is preventing this method from working.

you can find the repo [here](https://github.com/Billa05/OpenAlex_experiment/tree/master)

**Comment by scottbarnes** [comment] 2024-03-12 01:34
@Billa05, thanks for your hard work on this.

With respect to the error you encountered when trying to use the editions dump, can you explain more about it? I cloned the repository, put the editions dump in `using ol_dump/`, and ran:
```sh
❯ time python using\ ol_dump/new.py
python using\ ol_dump/new.py  1033.34s user 44.64s system 97% cpu 18:25.33 total
```
As show above, that completed successfully. Can you explain more about what you ran when you got an error, and share the error message?

I checked the first ISBN 13 (and its ISBN 10 equivalent) in `using ol_dump/Not_Found.jsonl`, and indeed, it wasn't in the editions dump:
```
❯ rg "9783838585758|3838585755" ~/Downloads/ol_dump_editions_2024-02-29.txt

```
The first ISBN in `using ol_dump/Hits.jsonl` is indeed in the editions dump, however:
```
❯ rg "0198202059|9780198202059" ~/Downloads/ol_dump_editions_2024-02-29.txt
22619:/type/edition     /books/OL1532028M       10      2023-01-15T16:44:18.816020      {"notes": {"type": "/type/text", "value": "Includes bibliographical references (p. [317]-329) and index.\nSeries statement from jacket."}, "identifiers": {"goodreads": ["1225276"], "librarything": ["9181797"]}, "title": "Greece and the inter-war economic crisis", "authors": [{"key": "/authors/OL223352A"}], "publish_date": "1991", "publishers": ["Clarendon Press", "Oxford University Press"], "isbn_10": ["0198202059"], "subject_place": ["Greece"], "covers": [1132073], "lc_classifications": ["HC295 .M38 1991", "HC295.M38 1991"], "publish_places": ["Oxford [England]", "New York"], "subject_time": ["1918-1974.", "1917-1935."], "pagination": "xii, 334 p. ;", "source_records": ["bwb:9780198202059", "marc:marc_loc_2016/BooksAll.2016.part21.utf8:706266:979", "ia:greeceinterwarec0000mazo", "promise:bwb_daily_pallets_2020-08-06"], "dewey_decimal_class": ["330.9495/07"], "languages": [{"key": "/languages/eng"}], "lccn": ["91009620"], "subjects": ["Greece -- Economic conditions -- 1918-1974.", "Greece -- Politics and government -- 1917-1935."], "publish_country": "enk", "series": ["[Oxford historical monographs]"], "by_statement": "Mark Mazower.", "type": {"key": "/type/edition"}, "ocaid": "greeceinterwarec0000mazo", "key": "/books/OL1532028M", "number_of_pages": 334, "works": [{"key": "/works/OL1865898W"}], "local_id": ["urn:bwbsku:W3-BMA-015"], "latest_revision": 10, "revision": 10, "created": {"type": "/type/datetime", "value": "2008-04-01T03:28:50.625462"}, "last_modified": {"type": "/type/datetime", "value": "2023-01-15T16:44:18.816020"}}
```
So at a high level the script appears to be doing what it should. It's entirely possible this got us all that we needed, but I'd like to know more about the error you're encountering.

**Comment by Billa05** [comment] 2024-03-12 06:58
@scottbarnes The issue is that we are missing some ISBNs due to invalid JSON. Check the console to identify the line with invalid JSON.
```py
 for line in file:
        try:
            json_str = line.split("\t")[-1]
            json_data = json.loads(json_str)
        except:
            print(line)
            continue
```

**Comment by Billa05** [comment] 2024-03-12 10:14
@scottbarnes It seems that I didn't extract the file correctly earlier. However, I have resolved the issue now, and it works perfectly fine. So, I believe that one part of the task is completed. What would be the next step?

Also, there was a bug that caused some ISBNs to be processed twice. But I have fixed that as well.

**Comment by scottbarnes** [comment] 2024-03-12 14:12
Great, thanks for fixing that, @Billa05!

@mekarpeles mentioned the following as next steps:
> **Next steps:** Eventually, we want (a) import any missing record, (b) add `openalex` identifiers for any existing record, (c) give the openalex folks a query so they can see all Open Library records with `openalex` identifiers and also `ocaids` (meaning they have previews or are readable/borrowable.

It looks as if there are at most around 24.7k 'misses' (and maybe less if de-duping lowers the number by a lot); I am unsure whether we'll want to use the batch importer for that, but that needs more documentation so it's easier for others to use, so for now, please focus on writing a script to do (b). 

You'll want to test this locally, not on production, so please see [Loading Production Book Data](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data), use `copydocs.py` to copy some records over from `Hits.jsonl`, and then write a script that will read a file in the format of `Hits.jsonl`, and for each Edition edit it to add the OpenAlex identifier, and to make a comment that the edit adds an OpenAlex identifier. You can see an example of the identifier usage here: https://openlibrary.org/books/OL3969869M.json. Please also update your OpenAlex repository with the new script for accomplishing (b).

**Comment by mekarpeles** [comment] 2024-03-18 16:38
@Billa05 can you also possibly add a very short README.md showing how you're using this code and detailing the process?

https://github.com/Billa05/OpenAlex_experiment/tree/master

**Comment by Billa05** [comment] 2024-03-18 19:46
> @Billa05 can you also possibly add a very short README.md showing how you're using this code and detailing the process?
> 
> https://github.com/Billa05/OpenAlex_experiment/tree/master

Hey @mekarpeles, I added a short readme file. If it's not explanatory enough, I can write a more detailed one. This week, I will proceed further with this issue.

**Comment by Billa05** [comment] 2024-03-20 20:31
> You'll want to test this locally, not on production, so please see [Loading Production Book Data](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data), use `copydocs.py` to copy some records over from `Hits.jsonl`, and then write a script that will read a file in the format of `Hits.jsonl`, and for each Edition edit it to add the OpenAlex identifier, and to make a comment that the edit adds an OpenAlex identifier. You can see an example of the identifier usage here: https://openlibrary.org/books/OL3969869M.json. Please also update your OpenAlex repository with the new script for accomplishing (b).

hey @scottbarnes , could you please explain how and specifically what to edit?

**Comment by scottbarnes** [comment] 2024-03-21 13:45
I don't think there are any files you will need to edit in the Open Library repository, and instead you will be editing a script you create to modify the records. To edit the editions to update the identifiers it is probably easiest to use [openlibrary-client](https://github.com/internetarchive/openlibrary-client/blob/master/README.md).

Using openlibrary-client, you will want a script to retrieve each edition in `Hits.jsonl`, and then you will want to update the identifier field.

Again, you'll want to do this locally when testing, so please see the information on `copydocs.py` so you can copy over some editions in `Hits.jsonl`. The `openlibrary-client` has an example of how you can [update an edition](https://github.com/internetarchive/openlibrary-client/blob/master/README.md#editions).

Please let me know whether that clears up any confusion.

**Comment by Billa05** [comment] 2024-03-21 18:30
Thank you, @scottbarnes, for explaining. I was able to produce this output
Here is the [code](https://github.com/Billa05/openlibrary-client/tree/master/adding%20identifiers). If this is the correct approach, what should be the next step?

![Screenshot from 2024-03-21 23-49-55](https://github.com/internetarchive/openlibrary/assets/90760974/d3a1a9be-4c38-46e6-9ea1-feabec07bd36)

**Comment by scottbarnes** [comment] 2024-03-21 18:43
Great. I need to think a bit about the best way to test the next step in the local development environment.

For the record, the next step will involve creating script to import these the misses from `Not_Found.jsonl`. We'll want that to happen on the local development server for testing, likely using the `/isbn` API (which I need to give you documentation to use), and then after each edition is imported, we'll want to update the identifiers for that edition to add the Open Alex identifier.

In the mean time, can you update the `README` to explain how the new script works, which files it needs, etc. You may also want to change the name from `test.py` to something more descriptive.

**Comment by scottbarnes** [comment] 2024-03-21 21:49
@Billa05, I thought about this a bit more, and with respect to step (a) that @mekarpeles mentioned (importing the missing records), please do the following:
- Write a script to iterate through each line in `Not_Found.jsonl`.
- For each ISBN, call `ol.session.get("http://localhost/isbn/<isbn here>.json`. (To get `ol.session`, use the same setup as here: https://github.com/Billa05/openlibrary-client/blob/115599ece0e39f0325d5b3ff5e840e1d6d3afea9/adding%20identifiers/add_identifiers.py#L3-L6).
- From each response to your `ol.session.get()`, parse the response to get the `key`, and then update the identifier for that edition in the same way you've already done to add the OpenAlex ID.

To make `/isbn` function locally, you'll need to first add some ISBNs to editions in your local development environment. Therefore, pick a few ISBN 13s/rows from `Not_Found.jsonl` to use for testing. Then edit some editions (it doesn't matter which ones) in your local development environment to add the ISBN 13s. Then, when you visit http://localhost:8080/isbn/some_isbn.json, you should see the metadata for the edition.

Some thoughts:
- This code should all be part of the same repository (e.g. OpenAlex_experiment).
- Please create a `requirements.txt` listing the dependencies (such as `openlibrary-client` for your script.
- Please update the documentation to reflect the new features.
- It's not necessary, but for bonus points you could look into [argparse](https://docs.python.org/3/library/argparse.html) or another CLI library to create a CLI to make these tools a bit easier to use. That way it would be possible to run an entrypoint script (e.g. `main.py`) with various options to generate `Hits.jsonl` and `Not_Found.jsonl`, have it update identifiers for `Hits.jsonl`, and do the import +  update the identifier for `Not_Found.jsonl`.
- Rather than hard code in the URLs, paths, filenames, etc. everywhere, for more bonus points you could have them read from a single file where all the configuration options are set. That way it's a bit easier to change filenames/paths and switch between the production and local development server as well. This is not necessary though.
- Because updating the identifier after calling `/isbn` will use the same logic as you used to update the identifiers for `Hits.jsonl`, you could simply call the same function, though you'd need to integrate the tools a bit more first.

Finally, here's what 'success' looks like when calling the ISBN endpoint here:
```python
>>> r = ol.session.get("http://localhost:8080/isbn/9780203850107.json")
>>> r.json()
{'publishers': ['Roberts brothers'],
 'key': '/books/OL20431791M',
 'title': 'Flatland: A Romance of Many Dimensions',
 'publish_date': '1885',
 'works': [{'key': '/works/OL118420W'}],
 'type': {'key': '/type/edition'},
 'identifiers': {'amazon': ['B0123456789']},
 'classifications': {},
 'description': 'blaaaaaaaah.',
 'ocaid': 'flatlandaromanc01abbogoog',
 'isbn_13': ['9780203850107'],
 'latest_revision': 10,
 'revision': 10,
 'created': {'type': '/type/datetime', 'value': '2013-03-28T07:50:50.124308'},
 'last_modified': {'type': '/type/datetime',
  'value': '2024-03-21T21:06:35.605471'}}
```

You can see I use Flatland as test item. In this example, you'd then take the `key` in the `.json()` output and update the identifier for `OL20431791M` to include the OpenAlex ID.

You may wonder why I haven't mentioned imports. The [/isbn endpoint](https://github.com/internetarchive/openlibrary/wiki/Developer's-Guide-to-Data-Importing#import-by-isbn) can also import items. So you won't need to do anything for that part. We may or may not need to call `/isbn` with an additional argument, but that's to be determined and if needed will be a one line change to the script.

How's all this sound?

**Comment by Billa05** [comment] 2024-03-22 13:50
Hello @scottbarnes, thank you for the detailed explanation. I was able to complete the task, but I wanted to confirm if
 [this](https://github.com/Billa05/OpenAlex_experiment/blob/master/import_and_add.py) is what we needed or not. As you requested, the file will do both jobs. If it looks good to you, I will proceed with making it CLI-based and do all that is required to make it perfect.

**Comment by scottbarnes** [comment] 2024-03-22 14:28
@Billa05, this looks great, both in terms of what it does and the updated documentation.

I may have missed it, but please make sure this script also has the ability to update the identifiers for all the items in `Hits.jsonl`.

In `add_identifiers()` in `import_and_add.py`, it looks as if a [`break` used for testing got committed](https://github.com/Billa05/OpenAlex_experiment/blob/c759870e567a11a8da925addaa90d36b84202b33/import_and_add.py#L23). I think it makes sense to remove that from the committed code, though it may make sense to comment it out, add a comment that uncommenting will run just run on one item, or something like that. I am not sure what the 'best' practice is here, and I think reasonable people can reasonably disagree on whether things like that should be committed. I'll leave to you the decision to remove the `break` or comment it out and leave a note about what it's for. :)

To make it a bit easier to understand when someone looks at this in the future, it may be worth renaming, for example, the default output file in `OpenAlex.py` from `output2.jsonl` to `OpenAlex_isbn.jsonl` so it's both more descriptive and matches what's in `find.py`. It may also be helpful to restructure things a bit (or simply document a bit more) so either the input files and output files 'match' insofar as things don't need to be renamed or moved, or perhaps to both document and restructure. I know right now it's very obvious what the steps are and which files go with what, but it may be less obvious to someone who has never seen the code before and just wants to generate an updated list of OpenAlex Id <-> ISBN candidates, to update any 'hits' with new identifiers, and to import + update the 'misses'.

On the topic of making it painfully obvious to people what to do, please update the documentation to add a sample set of steps for how to run this start to finish, assuming one is starting with nothing other than having cloned the repository and been told, "A great contributor named @Billa05 wrote a script to see what's in OpenAlex, what's in Open Library, and to update Open Library based on those things. Please go run that."

**Comment by Billa05** [comment] 2024-03-22 16:01
> I may have missed it, but please make sure this script also has the ability to update the identifiers for all the items in `Hits.jsonl`.

yes this case is also covered in the function, we just have to pass the file path of the `Hits.jsonl`
```py
def main():
    isbn_dict = import_isbns("using ol_dump/Hits.jsonl")
    add_identifiers(isbn_dict)
```
It seems like the [/isbn endpoint](https://github.com/internetarchive/openlibrary/wiki/Developer's-Guide-to-Data-Importing#import-by-isbn) documentation states that First, the Open Library database is searched for the provided ISBN, and if there's a match, it returns the corresponding edition. So, based on that information, everything is working perfectly fine. 

and, I apologize for including the break statement and output2.jsonl in the commit. It was only for testing purposes, and I forgot to double-check everything before pushing. Once I finish the CLI part, I will surely update the file structure, add comments, and update the readme for better code understanding.

**Comment by Billa05** [comment] 2024-04-03 15:49
Hey @scottbarnes, sorry for the delay. Could you please review the [CLI ](https://github.com/Billa05/OpenAlex_experiment)functionality? I'm currently held up with college exams.

**Comment by scottbarnes** [comment] 2024-04-03 19:18
@Billa05, this looks good! I will talk with @mekarpeles about the next steps hopefully tomorrow Pacific time and get back to you about how we want to proceed.

**Closed** 2024-04-22 19:37 UTC
Labels: Type: Feature Request, metadata, Priority: 3, Good First Issue, Theme: Identifiers, Module: Import, Lead: @scottbarnes
