### ISSUE TITLE
Graphs broken on homepage

### ISSUE THREAD

**Issue by navneetsaluja** [internetarchive/openlibrary#5022] opened 2021-04-09 21:12 UTC
### Evidence / Screenshot (if possible)
![graph3](https://user-images.githubusercontent.com/54721958/114241054-2fc51c80-99a6-11eb-8590-4a3a2549b972.png)

### Relevant url?
https://openlibrary.org/

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 87.0
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by dwaipayan05** [comment] 2021-04-10 05:30
Duplicate of #3924

**Comment by STAMATIOSL** [comment] 2021-04-10 10:39
Hi, I am a new contributor. I downloaded the Docker and I want to contribute to an open issue. What's the process for this?

**Comment by dwaipayan05** [comment] 2021-04-11 11:22
@STAMATIOSL Please go through this [document](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md).

**Comment by STAMATIOSL** [comment] 2021-04-11 13:12
@dwaipayan05 I read it but I can't connect the Docker with the OpenLibrary. As I understood, I must do this in order to see the changes in the OpenLibrary. Am I right?

**Comment by dwaipayan05** [comment] 2021-04-11 13:38
If you're talking about setting up docker environment for OL Installation, here's a proper [video tutorial](https://archive.org/embed/openlibrary-developer-docs/openlibrary-docker-set-up.mp4). 

If you're stuck at any specific phase of the docker installation, you can ask for clarifications with proper error outputs, screenshots on [gitter](https://gitter.im/theopenlibrary/Lobby)

**Comment by mekarpeles** [comment] 2021-04-12 17:57
I don't believe this is a duplicate of:
https://github.com/internetarchive/openlibrary/issues/5022#issuecomment-817082160

I think this issue is occurring because staff recently changed our backend stats cron-jobs from python2 on `ol-home` + `ol-www1` to python3 `ol-home0` + `ol-www0`

**Comment by mekarpeles** [comment] 2021-04-17 01:16
Before resolving, also followup here: https://news.ycombinator.com/item?id=26840794

**Comment by mekarpeles** [comment] 2021-05-05 22:58
https://github.com/internetarchive/openlibrary/issues/2481#issuecomment-833100823

**Comment by RayBB** [comment] 2021-06-23 22:21
Looks like graph is broken again as of June 23

<img width="934" alt="image" src="https://user-images.githubusercontent.com/921217/123175467-8a0a4100-d41d-11eb-91b3-0e7f0792c804.png">

**Comment by mekarpeles** [comment] 2021-06-23 22:36
This is cached fortunately cached, if you add ?lang=something to the end of the url, it should show that as of yesterday or so, our crons are back operational

**Comment by mekarpeles** [comment] 2021-06-23 22:54
just restarted memcached on prod and confirmed data is coming in.

**Closed by mekarpeles** 2021-06-23 22:54 UTC
Labels: Lead: @cdrini, Priority: 2, Type: Bug
