### ISSUE TITLE
Upgrade Reading Log: add "Check-ins"

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5088] opened 2021-04-22 18:53 UTC
### Describe the problem that you'd like solved

Add a readinglog_checkins table with a Reading Log ID foreign key, a page number, and a date... Or, store this information in the Reading Log table as json (probably better as it avoids joins)

**Comment by bicolino34** [comment] 2022-10-12 16:32
This is a duplicate of #6662

**Closed by bicolino34** 2022-10-12 16:32 UTC
Labels: Type: Feature Request, Priority: 3, Theme: Reading Log, Lead: @mekarpeles
