### ISSUE TITLE
MARC importer shouldn't use invalid/cancelled LCCN from 010$z

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8188] opened 2023-08-15 14:10 UTC
The MARC importer appears to have used the value 90015509 from the MARC subfield 010$z of this [record](https://ia803207.us.archive.org/fetchmarc.php?path=/7/items/jenacampaign180600maud/jenacampaign180600maud_marc.xml) causing a bad match with this [edition](https://openlibrary.org/books/OL1861359M/Fundamentals_of_adhesion), but the MARC [specification](https://www.loc.gov/marc/authority/ad010.html) says:

> $z - Canceled/invalid LC control number
> Canceled or invalid LC control number, including invalid NUCMC numbers.

Only LC control numbers from 010$a should be used for matching.

### Relevant url?
Conflated edition https://openlibrary.org/books/OL1861359M/Fundamentals_of_adhesion
MARC record https://ia803207.us.archive.org/fetchmarc.php?path=/7/items/jenacampaign180600maud/jenacampaign180600maud_marc.xml

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: invalid LCCN used for matching
* Expected: 010$z subfield contents are ignored

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders
@hornc

**Comment by tfmorris** [comment] 2023-08-17 19:16
Actually, the OpenLibrary code looks correct, so perhaps the screwup is someplace in Internet Archive code, but I don't understand how scans get matched up with OpenLibrary records or where it sources its MARC records.

https://github.com/internetarchive/openlibrary/blob/9b3a80f1d82c3c2455b207370d7d7de9c40e86ed/openlibrary/catalog/marc/parse.py#L105-L108

**Comment by hornc** [comment] 2023-09-12 20:36
I have looked into this and corrected the specific metadata -- removing invalid LCCN from archive.org and removing the incorrect archive.org identifier from OL.

I believe @tfmorris is correct, OL is doing the correct thing by only looking at `$a` LCCNs and not writing `$z` . The problem is that archive.org is promoting invalid LCCNs in `$z` to its metadata, which is causing the conflated editions. It's likely causing other problems on the archive.org side too.

I'll need to take a look at the archive.org MARC ingestion process before closing this issue. I should be able to fix it.

**Comment by hornc** [comment] 2023-12-05 21:02
After further investigation I found that archive.org code is only importing `010$a` also, so both IA and OL are already ignoring invalid LCCNs.  The problem with this particular item is that there is a source MARC record on the archive.org item with the wrong LCCN in the `010$a` field, which is what caused this particular conflation, and why I couldn't find any other wrong examples:  https://archive.org/download/jenacampaign180600maud/jenacampaign180600maud_marc.xml

```
<datafield tag="010" ind1=" " ind2=" ">
<subfield code="a">90015509</subfield>
</datafield>
```

On a hunch I swapped the first two digits of the entered LCCN, and it found the correct work:

https://lccn.loc.gov/09015509

It's a typo in the original MARC.

**Closed by hornc** 2023-12-05 21:02 UTC
Labels: Type: Bug, Theme: MARC records, Needs: Triage, Lead: @hornc
