### ISSUE TITLE
Subject search breaks when keyword "new" present

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#322] opened 2016-09-26 17:57 UTC
e.g. http://openlibrary.org/search/subjects?q=New%20York

**Comment by hornc** [comment] 2016-09-30 07:15
This might be an issue specific to 'New York' , other searches with spaces do give results, e.g. "North York", "West Africa", "vacuum tubes" (for something non-geographical).

Strangely every book I can find about New York has an 'NY' or 'N.Y.' as part of subject, as if it has been standardised. The canonical New York subject seems to be https://openlibrary.org/subjects/place:ny

Is there a standard the prefers 'NY' to 'New York'? It does seem odd that the entire OL db has every reference to New York stored as NY.

**Comment by jessamynwest** [comment] 2016-09-30 13:58
@hornc @bfalling Interesting observation. I see it with some two word searches and not for all.

New Mexico fails
New Jersey fails
New Delhi fails
(trying to find a two word phrase starting with NEW that doesn't fail, maybe it's a stop word?)
Atlantic City succeeds
George Clinton succeeds
Bill Clinton succeeds

If there was some standardization done around the state names, itwas before my time.

**Comment by LeadSongDog** [comment] 2016-09-30 18:19
Subject searching on "New" as a single word finds zero hits: https://openlibrary.org/search/subjects?q=New
Title searching for the same single word gets 116,292 hits: https://openlibrary.org/search?q=New
Title search for "New York" finds 36,163: https://openlibrary.org/search?q=New+York

**Comment by hornc** [comment] 2016-10-01 07:34
@jessamynwest, following up on the 'New' subject, I found a book that has 'New Order (Group)' as a subject https://openlibrary.org/works/OL4311941W/24_Hour_Party_People . It doesn't show up in a subject search. Using the format of the New Order subject page: https://openlibrary.org/subjects/new_order_(group) , I found the elusive 'New York' subject page: https://openlibrary.org/subjects/new_york

It exists, and there are 106 works that have 'New York'  as a subject, and there are numerous other New York related subjects. They just don't show up on a subject search.

I'll take a look at the code to see if there is anything that treats subjects searches with 'New' in them differently.

**Comment by jessamynwest** [comment] 2016-10-04 19:46
That is my presumption, or a reserved word.

**Comment by mekarpeles** [comment] 2017-03-23 08:19
https://github.com/internetarchive/openlibrary/issues/65

**Comment by tfmorris** [comment] 2019-07-05 22:52
Based on the results of this search: http://server.openjournal.foundation:8984/solr/select/?q=type%3Asubject+AND+%22new%22%0D%0A&version=2.2&start=0&rows=10&indent=on
I suspect that there's nothing in Solr with the word "new" in it to be found, so the problem is in (historical) indexing code.

**Comment by guyjeangilles** [comment] 2019-11-15 19:27
It sounds like #2246 should fix this problem. Let's leave open until it's merged.

**Closed** 2021-01-22 02:30 UTC
Labels: Lead: @cdrini, Module: Solr, Priority: 3, Theme: Search, Type: Bug

**Comment by tfmorris** [comment] 2021-01-22 06:20
The last comment by @xayhewalo (sic) says that #2246 will fix this, but that is unmerged (and abandoned).

@mekarpeles Could you please provide some rationale for to help followers understand why this is being closed? Since @bfalling has been waiting over 4 years for this, I'm sure he'd appreciate it as well.
