### ISSUE TITLE
Bot suggestions

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2387] opened 2019-09-14 01:39 UTC
From the Internet Archive:
- Table of Contents
- Description

From Book Finder (BF):
- If there's only an ISBN 10, add the ISBN 13 from BF and vice versa

**Comment by cdrini** [comment] 2019-09-16 16:58
@hornc @mekarpeles Should we create issues for these on the bot repo, or is here ok?

**Comment by LeadSongDog** [comment] 2019-09-17 15:44
Wherever the issue is done, the bot should also verify there's a real, published edition, not just a number. That means checking for availability in stores and/or libraries.

**Comment by BrittanyBunk** [comment] 2019-09-18 16:37
I'm not sure that's possible for the bot to do. I mean, I bet the bot can do 90% of the groundwork and people can double check in stores/libraries for the other 10%

**Comment by seabelis** [comment] 2019-09-18 17:32
Agreed with @LeadSongDog . We don't want to import phantom editions; same as has been discussed with Amazon imports.

**Comment by BrittanyBunk** [comment] 2019-09-18 17:38
Idk what a phantom edition is.

**Comment by LeadSongDog** [comment] 2019-09-18 21:37
@BrittanyBunk prospective publishers don't get individual ISBNs, they buy whole blocks of them (100, 1000, 10 000, etc.) from national registrars such as Bowker. Before they start to market a book they assign it an ISBN from their block. They'll at some point submit bibliographic data for cataloguing under that number and set a nominal publication date.  If for some reason the book never actually publishes, the ISBN is for a "phantom" edition. The number should never be reassigned to a different book, even though that does sometimes happen at small publishers. We do not want these to show up in OL, as nobody can ever obtain and read them.

This is particularly a problem with a large number of Amazon imports from 2008, where bogus records described books that were clearly never published.

**Comment by BrittanyBunk** [comment] 2019-09-20 14:46
I get it now. I think it'll be ok to use bookfinder to find the missing complementary isbn for books that already exist on Open Library and then have it double check afterwards on the wikipedia site you brought up.

**Comment by mekarpeles** [comment] 2019-10-29 02:40
I don't have the time to create new issues for these specifically -- if the proposal is for a description bot and a table of contents bot, let's document them clearly as separate issues please :)

**Closed by mekarpeles** 2019-10-29 02:40 UTC
Labels: Type: Feature

**Comment by BrittanyBunk** [comment] 2020-04-09 03:31
ISBN 13 can be used to find an ISBN 10, but not vice versa. So people should only enter ISBN 13 for it to auto-generate an ISBN on the OL site to use and search with. That will make the data dump more complete and easy to work with instead of using software to find it.

**Comment by tfmorris** [comment] 2020-04-09 18:03
> ISBN 13 can be used to find an ISBN 10, but not vice versa. 

That's not true.

**Comment by BrittanyBunk** [comment] 2020-04-09 18:06
@tfmorris I'll delete then. That's what I figured.
