### ISSUE TITLE
Python 3: KeyError on 'hit' in plugins/openlibrary/stats.py

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4023] opened 2020-11-05 16:41 UTC
### Evidence / Screenshot (if possible)
https://sentry.archive.org/sentry/ol-web/issues/3862

<type 'exceptions.KeyError'> at /works/OL6037022W
'hit'
Python | /opt/openlibrary/deploys/openlibrary/824a904/openlibrary/plugins/openlibrary/stats.py in stats_hook, line 84
-- | --
GET https://openlibrary.org/works/OL6037022W

![Screenshot 2020-11-05 at 17 40 04](https://user-images.githubusercontent.com/3709715/98269503-18fd4280-1f8e-11eb-8452-3f7fee8da777.png)

### Relevant url?

https://openlibrary.org/works/OL6037022W

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by SouthGoingZax** [comment] 2020-11-07 19:55
@cclauss it seems like there are at least  a couple things here: 1) figure out why 'hit' is missing in py3, and 2) make it so that if 'hit' is ever missing in the future, it doesn't result in a user-facing error.  Sound right?  Anything else?

**Comment by cclauss** [comment] 2020-11-07 20:39
Let's worry about 1 first.  After we know what the problem is and where it comes from, we can determine how it should be raise.

**Comment by Yashs911** [comment] 2021-01-14 15:30
@cclauss I cannot reproduce this error. I guess we can close this issue.

**Comment by mekarpeles** [comment] 2021-01-25 15:30
I agree, I think this has been resolved?

**Closed by mekarpeles** 2021-01-25 15:30 UTC
Labels: Lead: @cclauss, Module: Memcache, Priority: 2, Type: Bug
