### ISSUE TITLE
Internal Server Error - Add Book with Unicode characters

### ISSUE THREAD

**Issue by TheBestPessimist** [internetarchive/openlibrary#4869] opened 2021-03-21 10:30 UTC
### Evidence / Screenshot (if possible)
![add a book -   Internal Server Error](https://user-images.githubusercontent.com/4482210/111901357-48de4b80-8a40-11eb-8a76-05efea119b25.gif)

### Relevant url?
https://openlibrary.org/books/add

### Steps to Reproduce
Try to ad d the following book:
- title: `Doi galoşi`
- author: `Camelia Leonte`
- publisher: `Junimea`
- Published: `1988`
- isbn: none
- goodreads record: https://www.goodreads.com/book/show/26099487-doi-galo-i?from_search=true&from_srp=true&qid=EgtiGgQoB7&rank=1

* Actual: Internal Server Error - status code 500
* Expected: Book is successfully added

### Details

- **Logged in (Y/N)?**  Yes
- **Browser type/version?** Vivaldi 3.7.2218.45 (Stable channel) (64-bit)
- **Operating system?** Windows 10 OS Version 2009 (Build 19042.844)
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Not sure.

###### Piggyback

I'm migrating my collection from Goodreads to Openlibrary, due to the removal of API.

1. It would be nice to also add a picture to the book record directly in that form
2. It would be nice that on the import goodreads CSV (https://openlibrary.org/account/import/goodreads) to give the option to create all of those titles which could not be imported due to lack of ISBN , even though they don't have the isbn and afterwards ask me to edit them.

![image](https://user-images.githubusercontent.com/4482210/111901542-898a9480-8a41-11eb-995e-d8f82e389134.png)

**Comment by cclauss** [comment] 2021-03-22 00:00
Dup of #4311

**Comment by mekarpeles** [comment] 2021-12-22 17:53
@cclauss noted this as a dupe of #4311 which has been closed

**Closed by mekarpeles** 2021-12-22 17:53 UTC
Labels: Type: Bug, Module: Import, Priority: 2, Lead: @mekarpeles, Lead: @hornc, Theme: Unicode

**Comment by TheBestPessimist** [comment] 2021-12-24 14:19
@mekarpeles  what about the 2 suggestions besides the bug?
