### ISSUE TITLE
Multiple editions with same IA identifier

### ISSUE THREAD

**Issue by mangtronix** [internetarchive/openlibrary#81] opened 2011-11-09 19:42 UTC
We are still seeing multiple borrowable editions that have the same IA identifier.  When multiple editions with the same IA id get borrowed it causes problems with the loan system ("too many loan records found").

Here's an example that came in through the help system:
http://openlibrary.org/books/OL24768898M/Art_in_action
http://openlibrary.org/books/OL15355691M/Art_in_action

**Comment by hornc** [comment] 2017-07-01 03:09
@mekarpeles  I _think_ this is resolved now with the new availability checks... I have borrowed the example above and both editions are correctly shown as being checked out, which I think is the main issue in this report.

My current understanding is that duplicate ocaids in editions are fine (at least for now)
Duplicate ocaids across works is bad, and these should be merged together.

**Comment by hornc** [comment] 2017-11-01 01:42
@mekarpeles can we close this now as resolved, or are there still residual issues that you are aware of?

**Comment by LeadSongDog** [comment] 2017-11-01 21:22
@hornc Would you mind explaining why it is that "duplicate ocaids in editions are fine"? It seems to me that they should be for one edition only, just like an ISBN (although occasionally multiple ISBNs will apply to a single edition).

**Comment by mekarpeles** [comment] 2017-11-15 00:12
I'm not aware than any editions should have the same ocaids -- if so, they likely are candidates for merge cc @hornc

**Comment by salman-bhai** [comment] 2018-04-13 10:41
Is this Issue still open or can we can close this?

**Comment by tfmorris** [comment] 2018-04-13 14:49
@salman-bhai I don't see a resolution to the issue. Why should it be closed?

@hornc I agree with @LeadSongDog and @mekarpeles. An ocaid represents a scan of a single physical volume. This by definition can only be a single edition.

Possible solutions are to delete the duplicate ocaids (if they're attached to incorrect editions) or to merge the multiple edition records. Do we have a sense for how widespread the problem is?

In this case, since the two edition records were created from **exactly the same** Western Washington University MARC record, the appropriate solution would seem to be to merge the two records (and figure out why we ended up with two in the first place from exactly the same source data).

**Comment by salman-bhai** [comment] 2018-04-13 15:33
@tfmorris I wasn't sure about it and since there were no comments on this since a long time, I just wanted to confirm. 
Cheers!

**Comment by mekarpeles** [comment] 2018-10-11 19:57
@hornc does our updated import system check for this? (I believe it does) :)

**Comment by hornc** [comment] 2018-10-11 20:46
The updated import does check for existing ocaid s , however I think there may be existing data where ocaid s are duplicated on different editions of the same work, so we need to be careful about books blindly merging editions with the same ocaid. I think some of the matching on the archive.org side that associates the archive.org `openlibrary` value is less strict on matching editions that the `_works` and `_editions`

That needs more investigation, and could be a separate, clearer issue? The original problem with dupes was concerning loan issues, which is resolved.

**Comment by hornc** [comment] 2019-04-09 23:11
covered by #1045

**Comment by hornc** [comment] 2019-04-22 00:45
closing in favour of #1045

**Closed by hornc** 2019-04-22 00:45 UTC
Labels: merging, sync-ia-ol
