### ISSUE TITLE
Edition form allows each edition to have only one language

### ISSUE THREAD

**Issue by sandbergja** [internetarchive/openlibrary#677] opened 2017-12-18 13:09 UTC
This is troublesome for entering bilingual books (including dictionaries) and other multilingual materials.  Thanks for looking into this!

**Comment by LeadSongDog** [comment] 2017-12-18 16:06
@sandbergja It works fine for me, in Librarian mode, using Chrome on Windows 7. It is a bit simplistic, but the basic function is there. https://openlibrary.org/books/OL13503633M/Andria?b=5&a=4&_compare=Compare&m=diff

**Comment by sandbergja** [comment] 2017-12-18 16:26
Ahhh, thanks!  I didn't think of checking Librarian mode.

**Comment by tfmorris** [comment] 2017-12-29 21:30
@sandbergja If you're satisfied that this is not a bug, could you please close the issue? Thanks!

**Closed** 2017-12-30 19:20 UTC
