### ISSUE TITLE
Randomize the 'Authors Alliance & MIT Press' carousel

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2642] opened 2019-11-14 01:16 UTC
Shows up with the same books everyday

**Comment by guyjeangilles** [comment] 2019-11-15 18:19
Maybe related to #2628 @cdrini @jdlrobson thoughts?

**Comment by cdrini** [comment] 2019-11-15 19:39
Could you post a screenshot, @BrittanyBunk @guyjeangilles ? This is what it looks for me:
![image](https://user-images.githubusercontent.com/6251786/68970578-9942fa80-07b5-11ea-93d7-dd3ea8d32a65.png)

I notice it changing every ~day or so, I think.

**Comment by cdrini** [comment] 2019-11-15 19:39
I'll post another screenshot tomorrow as well to see if it's changed

**Comment by guyjeangilles** [comment] 2019-11-15 19:43
![mit_pub](https://user-images.githubusercontent.com/7256157/68970829-184d2880-07e0-11ea-969b-a54be223fd30.png)

**Comment by BrittanyBunk** [comment] 2019-11-15 21:45
It's the same

![](https://user-images.githubusercontent.com/7256157/68970829-184d2880-07e0-11ea-969b-a54be223fd30.png)

**Comment by tfmorris** [comment] 2019-11-16 02:16
We could save the effort of fixing it by removing it. It's always seemed weird to me that we highlight offerings from one random publisher.

**Comment by BrittanyBunk** [comment] 2019-11-16 15:37
Me too. I'd rather see another genre put in there, like recipes or something.

**Comment by cdrini** [comment] 2019-11-19 03:57
Forgot to update this, but it does look like it's changing (here it is today). I'm closing this specific issue; feel free to open a new one for adding a new type of carousel :+1:
![image](https://user-images.githubusercontent.com/6251786/69115484-b813ec00-0a56-11ea-8875-e7799f464187.png)

**Closed by cdrini** 2019-11-19 03:57 UTC
Labels: Needs: Assessment, Priority 3: Normal, State: Backlogged, Type: Feature

**Comment by tfmorris** [comment] 2019-11-19 07:00
Do we have a root cause or a link to the fix?

**Comment by cdrini** [comment] 2019-11-19 07:02
The issue was that the carousel was not randomizing; the picture above indicates that it _is_ randomizing; so closing this as can't repro.

**Comment by BrittanyBunk** [comment] 2019-12-27 06:12
@cdrini Thanks. I do notice that it is now randomizing. I'll start a new issue for new carousels. Thanks for helping this in the right direction.
