### ISSUE TITLE
Subtitles should appear in autocomplete search results

### ISSUE THREAD

**Issue by popcar2** [internetarchive/openlibrary#6462] opened 2022-04-20 16:35 UTC
There are a lot of books (specifically those in a series) that heavily depend on subtitles to form a complete title. The issue is that when searching for a title of a book, the subtitle does not appear. This leads to many different works having the same title or being misleading. Anything after a colon would also not appear in the search preview, as that would be considered a subtitle.

For example: _Diary of a Wimpy Kid_, _Diary of a Wimpy Kid: Rodrick Rules_, and _Diary of a Wimpy Kid: Dog Days_ would all just appear as _Diary of a Wimpy Kid_ in the search preview.

![image](https://user-images.githubusercontent.com/16920817/164277920-7599db5b-5309-4121-9697-65a1b056719b.png)

Another example:

![image](https://user-images.githubusercontent.com/16920817/164278588-8b6b9577-2487-4c24-83e6-e3a1b3f6de4b.png)

### Proposal
I suggest showing subtitles in search previews by default. They're usually important context to a title and can help differentiate works in a series.

**Comment by seabelis** [comment] 2022-04-21 07:14
Duplicate of #2355 ?

**Comment by cdrini** [comment] 2022-04-21 17:01
Oh this is just for the UI piece of making the titles appear in the drop down; #2355 was about also querying `subtitle` when a user searches with `title:`.

**Comment by mekarpeles** [comment] 2022-04-21 17:29
@furugoorin how do you feel about trying this one?

We might try adding a middle line w/ subtitle (similar to what we do on our books page) like:

**Title**
_Subtitle_
by Author

**Comment by constantinazouni** [comment] 2022-04-29 12:43
Is anyone working on that?

**Comment by mekarpeles** [comment] 2022-05-02 16:49
@constantinazouni all yours if you'd like to try it!

**Closed** 2022-05-09 20:22 UTC
Labels: Theme: Search, Priority: 3, Good First Issue, Needs: Help, Lead: @mekarpeles, Affects: Experience
