### ISSUE TITLE
When adding in an author for a new book, the author doesn't show up on the next page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2750] opened 2019-12-17 15:25 UTC
"Add a Book" asks for the author, but when I submit it, the author doesn't appear on the next page, which is the "Add a little more?" page. Before, the author used to appear. Now it shows a blank in the author field.

**Comment by tfmorris** [comment] 2019-12-17 18:26
Duplicate of #1716

**Closed by tfmorris** 2019-12-17 18:26 UTC
Labels: Type: Bug
