### ISSUE TITLE
Contact form is failing on submission

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10088] opened 2024-11-26 19:48 UTC
### Problem

```
Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2024-11-26/194721574288 and will look into it as soon as possible. Head for [home](https://openlibrary.org/)?
```

<img width="821" alt="image" src="https://github.com/user-attachments/assets/c28a7d55-9d3e-4c6e-b97d-7f597411c167">

### Reproducing the bug

1. Go to https://openlibrary.org/contact?path=%2Fauthors%2FOL1491464A
2. Submit form

* Expected behavior: Success
* Actual behavior: Failure

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Mac
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

* @seabelis 
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by jimchamp** [comment] 2024-11-26 22:07
Duplicate of #10030

**Closed by jimchamp** 2024-11-26 22:07 UTC
Labels: Type: Bug, Needs: Breakdown, Needs: Triage, Needs: Lead
