### ISSUE TITLE
Request guidance on IAUX for GSOC 2021

### ISSUE THREAD

**Issue by Swapnil-2001** [internetarchive/openlibrary#4859] opened 2021-03-17 19:18 UTC
Hello, 

My apologies if this is not the right place, but I would be very grateful for some assistance with this year's [GSOC project ideas](https://docs.google.com/document/d/1qt1dfk6rNE3yzMJXbriDjpeDrn6LQeiXviREvnXP6bE/edit#heading=h.5qhlrygrim5x). 

I've tried to reach out to potential mentors via the emails provided but haven't received a reply yet. I've also sent in a few PRs and opened issues in the relevant Github repositories, but with no luck. Any help would be appreciated.

Thank you

**Comment by cclauss** [comment] 2021-03-18 20:55
Can you please be clear about what guidance you are interested in?

Also please provide links to your previous PRs and issues because
https://github.com/internetarchive/openlibrary/pulls?q=author%3ASwapnil-2001 shows no PRs and
https://github.com/internetarchive/openlibrary/issues?q=author%3ASwapnil-2001 shows only this issue.

**Comment by Swapnil-2001** [comment] 2021-03-19 14:58
I would like to work on the **Archive.org Front-end Web Components (IAUX)** project as listed in the [ideas](https://docs.google.com/document/d/1qt1dfk6rNE3yzMJXbriDjpeDrn6LQeiXviREvnXP6bE/edit#) page. I understand that the relevant repository is [iaux](https://github.com/internetarchive/iaux) and I've created a few PRs and issues there. 

Issues:
[Selected quick search entry doesn't show up in input field after search is cleared](https://github.com/internetarchive/iaux/issues/528)
[Error when demoing scrubber-bar with storybook](https://github.com/internetarchive/iaux/issues/529)
[Error when running 'yarn storybook' from expandable-search-bar](https://github.com/internetarchive/iaux/issues/534)

PRs: 
[Remove redundant imports and correct file path in index.stories.js](https://github.com/internetarchive/iaux/pull/535)
[Fix error in import method in scrubber-bar/stories](https://github.com/internetarchive/iaux/pull/530)
[Minor UI fixes](https://github.com/internetarchive/iaux/pull/527)

It would be very helpful if I can get in touch with a mentor and better understand the requirements of the project, and hopefully, get started on it soon.

**Comment by mekarpeles** [comment] 2021-04-21 17:35
Duplicate of https://github.com/internetarchive/iaux/issues/543

**Closed** 2021-04-21 17:35 UTC
