### ISSUE TITLE
Search of 'Book' results in an error. 

### ISSUE THREAD

**Issue by benbdeitch** [internetarchive/openlibrary#9441] opened 2024-06-16 15:43 UTC
### Problem

When looking up the word 'book', off of the searchbar on the openlibrary main page, the search times out. This is probably not a particularly important issue, but given that it's consistent, I figured it was worth noting. 

#### Evidence / Screenshot
![image](https://github.com/internetarchive/openlibrary/assets/131627264/9745bdd3-2a18-4c95-ad6f-e03e459dfc0e)
![image](https://github.com/internetarchive/openlibrary/assets/131627264/051b4987-6d7f-4e7e-b142-20425e6001d1)

#### Relevant URL(s)
[Relevant search](https://openlibrary.org/search?q=book&mode=everything&debug=true)

### Reproducing the bug

1. Go to the openlibrary webpage, and search the word 'book'. 

* Expected behavior: It would pull up a proper search for the word 'book'.
* Actual behavior: The search instead times out. 

### Context

- Browser (Chrome, Safari, Firefox, etc): Chrome
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by mekarpeles** [comment] 2024-06-17 19:10
Closing as a duplicate of #5480, this happens with many common words related to #7271 the current search page flow which synchronously fetches search results **and** facets (which we are trying to tease apart into 2 separate stages -- search results that load synchronously and facets that load async.

**Closed** 2024-06-17 19:10 UTC
Labels: Type: Bug, Theme: Search, Priority: 3, Lead: @cdrini
