### ISSUE TITLE
Incorrect works listing on author's page after changes

### ISSUE THREAD

**Issue by highandmighty** [internetarchive/openlibrary#7473] opened 2023-01-30 11:58 UTC
For almost about a month I see incorrect information about works on the author's page which usually happens after works merge or changes in data. At the same time on the level of the work the information is correct. For example, author's page still shows 2 different works which lead to the one work page (because they were merged a long ago). Or author's page show works which are not attributed to this author anymore.

At first I thought that it is a delay in updating database, but it persists for weeks or even months after last edits.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/25966313/215468860-89bf0cd1-d4cd-4677-b5ab-c707b62ce855.png)
![image](https://user-images.githubusercontent.com/25966313/215468955-4cec2c1d-a17b-4b1e-b04d-05f68c4cf5e5.png)

### Relevant url?
- Merged works still showed unmerged:
  - https://openlibrary.org/authors/OL4716706A/Kevin_Lynch?q=Site (both lead to OL4477206W)
  - https://openlibrary.org/authors/OL235078A/John_N._Summerson?q=Sheldonian (both lead to OL1958655W)
- Work is still attributed to wrong author: https://openlibrary.org/authors/OL11545776A/Kevin_A._Lynch (this one work should be attributed only to OL579064A)

### Steps to Reproduce

1. Go to given URLs

* Actual: information on author's page is not in sync with information on work's page
* Expected: information on author's page is in sync with information on work's page

### Details
- Y (Logged)
- https://www.whatsmybrowser.org/b/R1RCA
- prod

### Proposal & Constraints

—

### Related files

—

### Stakeholders

—

**Comment by tfmorris** [comment] 2023-01-31 17:23
This is a symptom of a stale search index / failed index update. Many of the displays on the site are created using search results, so if they're wrong you get the results you see.

If you click through to https://openlibrary.org/works/OL17979434W you can see that the database is correct, but that's not what's used to build the works listing on the author page.

You can see a similar effect at https://openlibrary.org/search/authors?q=john+n+summerson where the search results indicate 39 works for the author, while the author's page shows 49.

**Comment by cdrini** [comment] 2023-11-20 16:49
Duplicate of #7348 .

**Closed by cdrini** 2023-11-20 16:49 UTC
Labels: Type: Bug, Priority: 2, Needs: Investigation, Lead: @cdrini, Module: Solr Updater, Theme: Redirects
