### ISSUE TITLE
Public Reading Log links broken on people Account page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3050] opened 2020-02-17 04:29 UTC
https://openlibrary.org/people/mekBot links to reading log pages are broken (possibly because of internationalization).

### Evidence / Screenshot (if possible)

Click on `already read` link on /people/mekBot and get navigated to:
`https://openlibrary.org/people/$(page.key)/books/already-read`

### Relevant url?

https://openlibrary.org/people/mekBot

### Related files

Somewhere around openlibrary/templates/account/

**Comment by tfmorris** [comment] 2020-02-17 16:34
Yes, that's definitely internationalization. Also, the French translation has no links in it at all.

**Comment by cdrini** [comment] 2020-02-17 22:47
Duplicate of #3025; closing and moving info to that

**Closed by cdrini** 2020-02-17 22:47 UTC
Labels: Good First Issue, Lead: @mekarpeles, Priority: 2, Theme: Internationalization, Type: Bug
