### ISSUE TITLE
Ongoing process to identify recent good books for import

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2333] opened 2019-08-23 02:38 UTC
As part of the epic #2332 , Investigate an ongoing source of current / modern / popular books to feed into the non-MARC modern book pipeline [`modern-import-bot`](https://github.com/internetarchive/openlibrary-bots/tree/master/modern-import-bot)

### Describe the solution you'd like

* An automated bot to identify suitable import candidates by ISBN on an ongoing basis
#### Outputs from this task:
* a piece of stand-alone software that can be triggered (via a cron job) to output a list of recently published ISBNs which can be fed into the existing non-MARC import process.
* It does not need to exclude items we already have -- the import process can do this. It only needs to identify good candidates.
* It **should** exclude things like notebooks, calendars, other stationery items, DVDs, CDs and other non-book items which may have book like identifiers.
* As part of the task, identify any areas of difficulty or data reliability issues.

**Comment by hornc** [comment] 2019-08-27 05:44
@rahul-kumi feel free to make a start on this, and ask if you have any questions!

**Comment by BrittanyBunk** [comment] 2019-09-15 20:51
I would use https://www.bookfinder.com/ to look at open library books that only have one isbn # and fill in the missing one (like add an isbn 13 to a book with only an isbn 10 and vice versa).

**Comment by guyjeangilles** [comment] 2019-11-22 00:36
@hornc has been working on this so I'm assigning him per slack discussions

**Comment by mekarpeles** [comment] 2021-01-23 13:49
Closing as duplicate of #2034

**Closed by mekarpeles** 2021-01-23 13:49 UTC
Labels: Affects: Data, Lead: @hornc, Module: Import, Priority: 2, State: Work In Progress, Type: Feature Request
