### ISSUE TITLE
Adding non-Latin character book failing 500:  "UnicodeEncodeError: 'ascii' codec can't encode characters"

### ISSUE THREAD

**Issue by dector** [internetarchive/openlibrary#4311] opened 2020-12-19 09:34 UTC
### Evidence / Screenshot (if possible)

![Screenshot_2020-12-19_13-30-48](https://user-images.githubusercontent.com/265872/102686055-7841aa00-41fe-11eb-8b4d-a50c70a6f9e3.png)

### Relevant url?
https://openlibrary.org/books/add

### Steps to Reproduce
1. Log-in with account
2. More -> Add Book
3. Enter title: `Справа Василя Стуса. Збірка документів з архіву колишнього КДБ УРСР`
4. Enter unknown author: `Вахтанг Кіпіані` (Click "create new record for")
5. Enter publisher: `Віват`
6. Enter published date: `2019`
7. Enter USBN13: `9789669429278`
8. Press "Add"

* Actual: Error 500
* Expected: Book added to system

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox latest
- **Operating system?** Debian Linux 10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
I'm using cyrillic symbols for book and author name. Might be the issue?

**Comment by SouthGoingZax** [comment] 2020-12-19 16:47
Thanks for the report, @dector.  Can you update the Steps To Reproduce with the text you're using for the book and author name?

**Comment by dector** [comment] 2020-12-19 16:57
@SouthGoingZax Sure! My second suggestion is that it's happening because of new author.

Title: `Справа Василя Стуса. Збірка документів з архіву колишнього КДБ УРСР`
Author: `Вахтанг Кіпіані` (Click "create new record for")
Publisher: `Віват`
Publish year: `2019`
ISBN13: `9789669429278`

**Comment by SouthGoingZax** [comment] 2020-12-21 23:58
Thanks.

I can reproduce it.  The error from my local dev environment is:

```
solr_1       | INFO: [] webapp=/solr path=/select params={wt=json&q.op=AND&q=title:"??????+??????+?????.+??????+??????????+?+??????+??????????+???+????"+AND+author_key:"OL5A"+AND+publisher:"?????"+AND+publish_date:"2019"+AND+isbn:"9789669429278"&start=0} hits=1 status=0 QTime=7 
web_1        | [2020-12-21 20:20:56 +0000] [218] [ERROR] Error handling request /books/add?debug=true
web_1        | Traceback (most recent call last):
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 135, in handle
web_1        |     self.handle_request(listener, req, client, addr)
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
web_1        |     resp.write(item)
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 333, in write
web_1        |     self.send_headers()
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 329, in send_headers
web_1        |     util.write(self.sock, util.to_bytestring(header_str, "ascii"))
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gunicorn/util.py", line 507, in to_bytestring
web_1        |     return value.encode(encoding)
web_1        | UnicodeEncodeError: 'ascii' codec can't encode characters in position 201-206: ordinal not in range(128)
```

It looks like gunicorn is trying to encode response headers as ascii, which triggers the error.

Looking at the headers of a successful book addition attempt, this request results in an HTTP 303 and redirects to the edit page for the added book so the user can continue adding additional metadata.  The edit page in the Location header of the 303 response contains the title of the added book, which could be the problem when using non-ascii characters:

![image](https://user-images.githubusercontent.com/72705998/102830185-9a256300-439d-11eb-86e1-5c68dc339ac2.png)

The version of gunicorn being used is 2.5 years old.  It looks like that encoding was changed in a later version ([commit](https://github.com/benoitc/gunicorn/commit/879651bb6f873631725cc31cbda783349fdf9dc3)).  Maybe upgrading gunicorn could help.  If the above theory is correct, a work-around could also be to not redirect the user to the edit page automatically if non-ascii characters are in the book title, but instead return a page with a link to the edit page for the user to click on. @cdrini, what are your thoughts on how to proceed? 

Also, it looks like the [book addition succeeded](https://openlibrary.org/works/OL24096573W).

**Comment by dector** [comment] 2020-12-22 16:10
@SouthGoingZax Awesome, thanks! Can I remove duplicates somehow?

**Comment by SouthGoingZax** [comment] 2020-12-22 17:36
You can request that duplicates be merged using the [contact form](https://openlibrary.org/contact).  It's an ability limited to people designated as admins and librarians.

**Comment by dector** [comment] 2020-12-22 19:19
Got it, thanks a lot.

**Comment by cdrini** [comment] 2021-02-22 22:36
@SouthGoingZax Is this still an issue? A number of our utf8 issues were fixed in the last few months during the py2/3 migration. If the issue is still there, upgrading gunicorn to see if that fixes it seems reasonable :+1:

**Comment by cdrini** [comment] 2021-02-22 22:39
@cclauss This issue seems vaguely familiar; was there another issue very similar to this? I thought we might've already tried updating gunicorn.

**Comment by cclauss** [comment] 2021-02-22 22:57
Like #4225 Internal Server Error attempting to merge authors with Unicode names which we were to discuss on today's call.

**Comment by cclauss** [comment] 2021-02-23 18:39
We are running current gunicorn https://github.com/internetarchive/openlibrary/blob/8203f8c262b01250e52cf386c9fdc5fe2e3b7e1e/requirements_common.txt#L11 vs. https://pypi.org/project/gunicorn

**Comment by hornc** [comment] 2021-03-25 20:24
The error messages look like the issue I fixed on borrow redirects in #4861 -- that PR does not fix this, but somewhere a redirect is occurring with a non-URL-encoded URL with Unicode characters in the redirect header `location:` field  -- gunicorn does not like that.

**Comment by cdrini** [comment] 2021-06-14 19:28
@dhruvmanila  would you by any chance be able to help out with this one? It's causing a lot of our non-English users grip :( If you have the time, would love to jump on a call to explain this.

**Closed** 2021-06-26 00:47 UTC
Labels: Lead: @cdrini, Priority: 2, Theme: Unicode, Type: Bug

**Comment by cdrini** [comment] 2021-06-28 21:47
@dector This should now be fixed on openlibrary.org ! Please let us know if you're still having issues :+1:
