### ISSUE TITLE
Add to staff picks fails if any dark item associated with Work ID

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8473] opened 2023-10-28 14:21 UTC
<class 'internetarchive.exceptions.ItemLocateError'> at /admin/staffpicks
Item cannot be located because it is dark or does not exist.

### Evidence / Screenshot (if possible)
<img width="1141" alt="Screenshot 2023-10-28 at 16 19 59" src="https://github.com/internetarchive/openlibrary/assets/17739465/6927a5e6-81ad-425f-9f7d-34f62466aeaa">

### Relevant url?

https://openlibrary.org/admin/staffpicks?debug=true

### Steps to Reproduce

1. Go to ...https://openlibrary.org/admin/staffpicks?debug=true
2. Do ...add OL1807144W

* Actual: Error noted above. 
* Expected: Editions should be added to staff picks.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by ClementineAccount** [comment] 2023-11-21 04:21
@jimchamp @mekarpeles 
Can I be assigned this issue so I can attempt it?
I also need to know if 'Editions should be added to staff picks' is the correct fix.

**Comment by jimchamp** [comment] 2023-11-30 21:34
@seabelis are you still experiencing this issue?  I was unable to reproduce this with OL1807144W (which is now a staff pick).  I also tried with a recently published book and didn't see an error page.

@ClementineAccount if this bug is still occurring, I'll assign you and help to find a solution.

**Comment by seabelis** [comment] 2023-12-07 15:40
It's hard to say as I've been removing the dark item links and I only add to staff picks every now and then. I will see if I can find an appropriate test work.

**Comment by seabelis** [comment] 2023-12-19 16:43
Found an example. https://openlibrary.org/works/OL2950942W/The_Demon-Haunted_World

**Comment by jimchamp** [comment] 2023-12-21 22:40
Thanks @seabelis!  What happens when the button works?  From what I can gather from the code, it looks like some JSON response is displayed.  That seems inconvenient if it's true...

@ClementineAccount, are you still interested in working on this?  I think that wrapping [this call](https://github.com/internetarchive/openlibrary/blob/e7404e7f15df39fdc11a0e45f86be3988540f102/openlibrary/plugins/admin/code.py#L205) in a `try` block would work.  If there's an exception, return some JSON that contains an error message.

**Comment by ClementineAccount** [comment] 2023-12-22 03:12
> Thanks @seabelis! What happens when the button works? From what I can gather from the code, it looks like some JSON response is displayed. That seems inconvenient if it's true...
> 
> @ClementineAccount, are you still interested in working on this? I think that wrapping [this call](https://github.com/internetarchive/openlibrary/blob/e7404e7f15df39fdc11a0e45f86be3988540f102/openlibrary/plugins/admin/code.py#L205-L207) in a `try` block would work. If there's an exception, return some JSON that contains an error message.

Yes I am interested. Once assigned I can start attempting the suggestion of wrapping the call and trying it out.

**Comment by jimchamp** [comment] 2023-12-22 03:13
Thanks @ClementineAccount!

**Comment by seabelis** [comment] 2023-12-22 09:06
Yes, when there's an eligible edition a json success message is returned. If no eligible edition exists (for example, all already have the tag) a json failure message is returned. When there's a dark item no json is returned. I believe the code just doesn't execute at all when it hits a dark item.

**Comment by seabelis** [comment] 2023-12-22 09:07
If possible, it should just skip over the dark item and still find the eligible items.

**Comment by jimchamp** [comment] 2023-12-22 19:00
> If possible, it should just skip over the dark item and still find the eligible items.

This is correct ----  @ClementineAccount, instead of returning immediately if an error is encountered, continue processing all of the `ocaids`.  Sorry for the bad instructions earlier...

@seabelis, would it be useful if the failed `ocaids` were returned after the button was pressed, or maybe some kind of `n/m items added to staff picks` message?

**Comment by ClementineAccount** [comment] 2024-01-08 08:08
@jimchamp I have started work on this properly today now that the holiday period is over. Will let you know if I encounter blocks or have questions.

**Comment by ClementineAccount** [comment] 2024-01-15 03:57
> @jimchamp I have started work on this properly today now that the holiday period is over. Will let you know if I encounter blocks or have questions.

Just realized that something happened on that day and I wasn't able to start it. I apologize for that. I will now reply to this post again once I have started working on it and reproducing the bug.

**Comment by seabelis** [comment] 2024-01-25 14:12
@jimchamp It would be helpful if the edition ID is returned.

**Comment by jimchamp** [comment] 2024-01-25 22:16
Alright, that should be easy enough.  When we are iterating through the `ocaid`s, we can store any `ocaid` that failed in a list.  Once the `ocaid`s have been processed, we can include the list in the JSON response.

**Closed** 2024-03-15 19:32 UTC
Labels: Type: Bug, Priority: 3, Lead: @jimchamp
