### ISSUE TITLE
Improve Search Results Experience when 0 results 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1001] opened 2018-06-26 19:49 UTC
If the user is in `mode=ebooks` mode for search, but there are no results, we should fall back to search `mode=everything` and/or at least show the user some other options + a useful message which doesn't feel like a dead-end

**Comment by mekarpeles** [comment] 2018-07-13 01:14
We're going to fall back to the next `/search/inside` full-text search! cc: @brewsterkahle

**Comment by mekarpeles** [comment] 2023-03-12 22:06
**History**

1. Some searches return non results -- this is not a great experience
2. We had implemented a fallback to full text search in #1025
this was expensive and could be confusing so we rolled back the change in #3288

We still don't want dead ends. The revised proposal is to:
* show no results w/ warning message <img width="845" alt="Screenshot 2023-03-12 at 3 01 44 PM" src="https://user-images.githubusercontent.com/978325/224576337-1007260f-ce94-4fe0-8211-7ef89ccf3a9a.png">
* Instead of showing the text, "Search for books containing the phrase [...]" as a link, change it to the text, "Showing books containing the phrase [...]" and asynchronously load up to 5 fulltext search results w/ a link to switch to "see more" which goes to the /search/inside tab

**Comment by tfmorris** [comment] 2023-03-14 01:55
I recommend looking at this through a different lens. Dead ends are unsatisfying, but the best solution is to avoid them in the first place, not to send the user on a detour down a *different* dead end.

I recently copied the book title, "Cornell ’77: The Music, the Myth and the Magnificence of the Grateful Dead Show at Barton Hall," from an [article](https://news.cornell.edu/stories/2023/03/dead-co-play-benefit-barton-hall-honoring-legendary-77-show) and pasted it into the OpenLibrary search box resulting in exactly zero matches. Searching "All" instead of "Title" also returned zero matches. Switching to full-text search resulted in ... zero matches. Can you spot the one word (out of sixteen) that the article author transcribe wrong for _[Cornell '77: the music, the myth, and the magnificence of the Grateful Dead's concert at Barton Hall](https://openlibrary.org/works/OL20055171W)_?

If search returned results which were close (I consider 15 of 16 words close), there would be many fewer dead ends to worry about. This applies to single letter transpositions, small typos, and all the other things the Google & Duck Duck Go handle effortlessly, but completely stump OL Search.

**Comment by Ashisaphnx** [comment] 2023-11-01 17:23
Would it be possible for the search function to look for each word, and display the results in order of most similar words?

**Comment by Ultare1717** [comment] 2023-11-20 03:50
Hello, I am a student from the University Of Toronto. Would it be possible for me and my group to work on this in case this issue is still open?

**Comment by mekarpeles** [comment] 2024-03-07 20:19
Related to #8740

**Comment by merwhite11** [comment] 2024-05-03 19:29
@mekarpeles Hello Mek, I'd love to take this issue on.

**Comment by merwhite11** [comment] 2024-05-06 19:23
@mekarpeles 
Reading through these comments again and actually not sure what the issue is. Is the goal to implement @tfmorris 's [suggestion](https://github.com/internetarchive/openlibrary/issues/1001#issuecomment-1467224890) :  ? 

I see noted that the issue was fixed by #1025 ..but when I search for a result with a typo, it's still turning up 0 results: 
![Screenshot 2024-05-06 at 12 22 43 PM](https://github.com/internetarchive/openlibrary/assets/79802377/7140201a-0206-4f71-963b-2b255cfd9a34)

Please clarify the reqs for this and happy to get to work on it.

**Comment by mekarpeles** [comment] 2024-05-07 14:22
@tfmorris, @benbdeitch has been working on an fuzzy search effort #8873 to address #6923. An issue exists for this, a PR-in progress exists for this.

@merwhite11 This issue is calling for something different, which is --

If you are on the `All` or `Books` tab and you perform a search and there are 0 results found through regular search, before showing "No results found" use javascript to perform a Full Text Search using the https://openlibrary.org/search/inside.json API and, if there are any results, show a card with up to the first e.g. 3 matches as described in #8884  

See the design here for inspiration: https://github.com/internetarchive/openlibrary/issues/8884#issuecomment-1988970459

We also want to do this in a way where (when possible) we're keeping the design of the different search pages consistent, see: #8891

**Comment by merwhite11** [comment] 2024-05-07 19:46
@mekarpeles @jimchamp 
Reiterating what we went over in today's meeting. Thank you for all the guidance :) -- 

**Context:**

When search returns 0 results, current UI displays a <No Results> widget and a link to <Search for books containing the phrase..>

**Goal:**
On browsers that support JS, the link needs to be replaced by a suggestions card aka Full Text Search Results Preview Box outlined here: https://github.com/internetarchive/openlibrary/issues/8884#issuecomment-1988970459

**Process:**

1. User enters search → [search controller](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/worksearch/code.py#L379-L510) renders [template](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/work_search.html) displaying results
2. Add a check in template that checks if there are 0 results (aka SOLR_EDITIONS?)
3. If there are 0 results, make a JS call from template to a [Partial](https://github.com/internetarchive/openlibrary/blob/37db01e97fafaeec1f36951050b06f836442ca71/openlibrary/plugins/openlibrary/code.py#L1020)
4. Partial will return Full Text Search Results Preview Box HTML 
5. The preview box will be a template or a macro that will be inserted into the original work_search template. 

**Questions:**

1. Is JS function going to be written in a separate file (eg. plugins/openlibrary/js/preview-box) and called from work_search.html template?

**Future Issues / Out of scope:**

1. Apply preview box to Search Inside search results: #8884 
2. Apply preview box feature to Authors, Subjects, Lists and Advanced Search when 0 results
3. Include preview box feature to all search results (regardless of how many results returned)

**References:**

Similar Partials use-case: https://github.com/internetarchive/openlibrary/blob/37db01e97fafaeec1f36951050b06f836442ca71/openlibrary/plugins/openlibrary/js/affiliate-links.js

Partials docs (to be added to!): https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#partials

Separate but possibly overlapping issue of unifying UI for <No Results> widget being worked on here: https://github.com/internetarchive/openlibrary/issues/8891

**Comment by merwhite11** [comment] 2024-06-01 00:46
Progress report --
- All data coming in and linking to correct pages on clicks
- First draft of formatting for md & lg screens complete

Still to do --
- Format card for small screens / responsive
- Add browse icon in header
- Add loading indicator

<img width="1021" alt="Screenshot 2024-05-31 at 5 42 08 PM" src="https://github.com/internetarchive/openlibrary/assets/79802377/6bf482d8-107f-4642-b2e7-13efb7133218">

**Comment by merwhite11** [comment] 2024-06-08 00:54
Another progress report 6/7/24:

Completed:
- Responsive styling
- Title and author truncated for mobile
- Quotes around text
- Error message display before 

Still to do:
- Blue link default for title and author in mobile
- Try different fonts for quotes to make it stand out more obviously as a quote
- Determine how many book results should be displayed for mobile and desktop
- Determine if <Search Inside> header should go on bottom of card
- Add loading indicator
- Update Partials info in docs

<img width="366" alt="Screenshot 2024-06-07 at 5 53 38 PM" src="https://github.com/internetarchive/openlibrary/assets/79802377/17200b06-95fa-4b53-b163-ed54e5b5ac68">

<img width="996" alt="Screenshot 2024-06-07 at 5 54 05 PM" src="https://github.com/internetarchive/openlibrary/assets/79802377/463da863-755b-4f0a-944b-0437635c9695">

**Comment by jimchamp** [comment] 2024-06-10 13:41
Thanks @merwhite11!  Just in case you didn't know, we have a [loading indicator macro](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/LoadingIndicator.html) that can probably be used as a placeholder here.

**Comment by merwhite11** [comment] 2024-06-20 19:22
@mekarpeles 
Opened the pull request and draft of Partials docs revision:
https://docs.google.com/document/d/1Ays0kw1tcYSj4IuMIthSS_jw0TbrxHmDuqCoVyoqet0/edit

**Comment by mekarpeles** [comment] 2024-07-12 03:26
Maybe show 3 results instead of 5
![image](https://github.com/user-attachments/assets/409c3f5d-6653-4b9d-a22a-b82cc7b61fe1)

We may want to change "No results found" to match whatever tab they are... Because it's weird we say "no results found" and then we show them results!
![image](https://github.com/user-attachments/assets/07d0e6bb-d615-42e4-a9b6-4f8d83d4daf5)

![image](https://github.com/user-attachments/assets/fd54ba24-0cef-410a-aa4b-a1306ddeb699)

Instead of "Loading Search Inside Suggestions" let's change that to:
"Checking for Search Inside matches"

<img width="290" alt="Screenshot 2024-07-11 at 8 26 05 PM" src="https://github.com/user-attachments/assets/2f5d0661-55ea-4807-b1ef-5cb02591bb83">

**Closed** 2024-08-20 19:18 UTC
Labels: Good First Issue, Priority: 2, Lead: @mekarpeles, Affects: Experience, Team: Front-end, Needs: Designs
