### ISSUE TITLE
Possible to create 5 identical lists?

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#48] opened 2011-07-29 17:12 UTC
http://openlibrary.org/people/Tuli/lists

**Comment by hornc** [comment] 2016-01-19 09:58
looks like a duplicate of #227 ?

**Comment by hornc** [comment] 2016-03-31 02:44
Fixed with tested and merged PR https://github.com/internetarchive/openlibrary/pull/252
@gdamdam can you please close this issue, thanks!

**Comment by salman-bhai** [comment] 2018-03-21 16:13
@mekarpeles @hornc would it be okay if we can close this Issue!

**Closed** 2018-03-21 18:58 UTC
Labels: bug
