### ISSUE TITLE
API search by ISBN returns different results from website search

### ISSUE THREAD

**Issue by LuccoJ** [internetarchive/openlibrary#290] opened 2016-03-20 15:20 UTC
Compare
https://openlibrary.org/search?isbn=9780198612711
with
https://openlibrary.org/search.json?isbn=9780198612711

The latter doesn't return any hit for me, but the ISBN is valid and found by the web search.
The same happens with the 10-digit version.

**Comment by tfmorris** [comment] 2016-03-25 15:25
Not ideal, but you can get the information from alternate APIs:

https://openlibrary.org/isbn/9780198612711.json
https://openlibrary.org/api/books?bibkeys=ISBN:9780198612711&format=json&jscmd=data

The ISBN search term is a surrogate that gets expanded to isbn_10 OR isbn_13 in some places and I think IA has been messing with the search syntax, so they may have broken this aspect. I'm not aware of any place that they make advance announcements about deployments which have the potential to break apps.

**Comment by hornc** [comment] 2016-04-10 09:40
Hi @LuccoJ, I had a look into this to check there wasn't a code issue with isbn searches, and I couldn't find anything wrong with isbn searches in general.  This particular work appears to not have been fully indexed, after a manual re-index the API search now returns the expected result:
https://openlibrary.org/search.json?isbn=9780198612711

I'll dig further to try to understand how the first search differs from the API search as there seems to be quite separate code that performs the two searches.

**Comment by bfalling** [comment] 2016-08-08 19:43
Hey, @hornc! Just curious if you had a chance to compare the two pieces of search code and see whether there are discrepancies and/or a chance to unite them.

**Comment by LeadSongDog** [comment] 2017-10-26 15:48
Of all those searches, only one returns a distinct edition record. 
OL1037080M is found by: https://openlibrary.org/api/books?bibkeys=ISBN:9780198612711&format=json&jscmd=data  and I note that edition record does not link to the work record.
All the others find OL7401624M which is linked to OL6562308W. 

I note also that https://openlibrary.org/search.json?isbn=9780198612711 works while https://openlibrary.org/search.json?ISBN=9780198612711 does not. Not sure if this is an intended case sensitivity.

**Comment by guyjeangilles** [comment] 2019-10-22 23:49
The specific ISBN links in the this thread seem to be working minus the one mentioned by @LeadSongDog. @hornc Has there been any progress on the different search methods on the site and the API?

Also, @hornc are you willing to be assignee for this issue? Note: the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels based on context: let me know your thoughts

**Comment by tfmorris** [comment] 2020-02-18 22:32
As @hornc reported in April 2016, this was an indexing failure which has since been fixed, so I think this can be closed. @cdrini do you agree? (since you're the current assignee)

As far as investigation and refactoring of search to reduce redundancy, I propose that that task gets a ticket of its own (if it's really important enough to pursue).

@LeadSongDog re:
> I note also that https://openlibrary.org/search.json?isbn=9780198612711 works while https://openlibrary.org/search.json?ISBN=9780198612711 does not. Not sure if this is an intended case sensitivity.

Yes, the API is case sensitive.

**Comment by cdrini** [comment] 2020-11-24 03:02
This is the code that /search.json uses:

https://github.com/internetarchive/openlibrary/blob/22d73ee2ec9b4ac3940c225d8a89ef3fb5ceec71/openlibrary/plugins/worksearch/code.py#L945-L977

And this the code /search uses:

https://github.com/internetarchive/openlibrary/blob/22d73ee2ec9b4ac3940c225d8a89ef3fb5ceec71/openlibrary/plugins/worksearch/code.py#L592-L634

These are almost entirely different code paths :/ ; a quick look doesn't reveal if they even intersect at any point. I think the root cause of this issue wasn't the that the record was mis-indexed, but that these two endpoint had inconsistent logic. If the record had been missing from both, it would have been perfectly ok.

**Comment by RayBB** [comment] 2023-10-07 03:19
There doesn't appear to be any further problem here so I'll close this for now.
Feel free to re-open if anyone feels otherwise.

**Closed by RayBB** 2023-10-07 03:19 UTC
Labels: Type: Bug, Theme: Search, Theme: Public APIs, Priority: 3, Needs: Investigation, Lead: @cdrini

**Comment by tfmorris** [comment] 2023-10-07 13:36
Is it desirable that these two very similar requests use entirely different
sets of code to do their work?
