### ISSUE TITLE
Editing an edition with-no-work no longer creates a work on save

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#760] opened 2018-01-18 23:46 UTC
Previously I was able to create works from an orphaned edition using the UI by making a no-op edit, see https://openlibrary.org/recentchanges/2017/10/25/edit-book/53157052 for an example.

This no longer works.

I believed the code that added the work was here: https://github.com/internetarchive/openlibrary/blob/f1f7e01bb118e10787bd135a064ca7e4220dbece/openlibrary/plugins/upstream/addbook.py#L615

but we also have this, in the same file:
https://github.com/internetarchive/openlibrary/blob/f1f7e01bb118e10787bd135a064ca7e4220dbece/openlibrary/plugins/upstream/addbook.py#L412

Which looks like it is trying to do the same thing. Both are old code, and neither are working now.

There should only be one version, it should work, and let's not label it a hack in the comments :wink: 

I'm pretty sure the L615 code was triggered previously as I added a line there to copy subjects to the newly created work, which had not been happening. My edit above shows the Work had subjects added. I have only recently noticed the L412 code.

@cdrini  , FYI

**Comment by cdrini** [comment] 2018-01-19 05:51
Oh boy, the new works *are* getting created, they're just not getting linked. A new work was created every time "Save" was hit :/
See: https://openlibrary.org/works/OL17830042W/A_Home_Ein_Heim_Ett_Hem https://openlibrary.org/works/OL17830044W/A_Home_Ein_Heim_Ett_Hem
https://openlibrary.org/works/OL17830045W/A_Home_Ein_Heim_Ett_Hem
https://openlibrary.org/works/OL17830046W/A_Home_Ein_Heim_Ett_Hem
https://openlibrary.org/works/OL17830047W/A_Home_Ein_Heim_Ett_Hem


Editing the edition creates a dummy work populated with data from the edition https://github.com/internetarchive/openlibrary/blob/f1f7e01bb118e10787bd135a064ca7e4220dbece/openlibrary/plugins/upstream/addbook.py#L615-L624

However, this work isn't persisted to the database until the edition is saved, here:
https://github.com/internetarchive/openlibrary/blob/f1f7e01bb118e10787bd135a064ca7e4220dbece/openlibrary/plugins/upstream/addbook.py#L411-L416
This uses its own logic to create the work from the edition, then updates it with the changes from the UI (which was created using different logic).

Note that `work_data` is the updated work to be saved, and `self.work` is the work associated with the edition (as stored in the db). i.e. `self.work` is definitely `None` for orphans.

This is a regression from #700 . Because that change sets `edition.works[0].key` to an empty string, if one doesn't exist. When the `edition.update` is run (which happens after the above snippet), I think it *erases* the `edition.works` set in the above snippet, causing the edition to remain an orphan.

**Comment by mekarpeles** [comment] 2018-01-19 09:57
note: https://github.com/internetarchive/openlibrary/pull/700 just got merged in really recently (I think 2 days ago) -- see https://github.com/internetarchive/openlibrary/pull/700#issuecomment-358432226
For a while the feature was running without this code

**Comment by LeadSongDog** [comment] 2018-01-19 16:51
Well that explains this mess. 
In the process of moving and editing editions :
https://openlibrary.org/books/OL7407202M/Kinematics_and_Dynamics_of_Machinery
https://openlibrary.org/books/OL9657377M/Kinematics_and_dynamics_of_machinery

under:
https://openlibrary.org/works/OL3285161W/Kinematics_and_dynamics_of_machinery

I inadvertently created:
https://openlibrary.org/works/OL17830054W/Kinematics_and_Dynamics_of_Machinery
https://openlibrary.org/works/OL17830053W/KINEMATICS_AND_DYNAMICS_OF_MACHINERY
https://openlibrary.org/works/OL17830052W/Kinematics_and_Dynamics_of_Machinery
https://openlibrary.org/works/OL17830051W/KINEMATICS_AND_DYNAMICS_OF_MACHINERY
https://openlibrary.org/works/OL17830050W/KINEMATICS_AND_DYNAMICS_OF_MACHINERY

These now-childless (there's gotta be a word for that) works should all redirect to the merged work: OL3285161W but I don't think there's a way for that to happen short of resorting to the "Problem" reporting mechanism.

**Comment by cdrini** [comment] 2018-01-20 03:01
@mekarpeles whoops, I mean #661 , not #700 ; my bad!

**Comment by hornc** [comment] 2018-01-20 03:19
@LeadSongDog I have [merged those works](https://openlibrary.org/recentchanges/2018/01/20/bulk_update/53412622) using the [ol-client](https://github.com/internetarchive/openlibrary-client). For my, and others', future reference the code (Python) to do this sort of thing is: 

```
from olclient.openlibrary import OpenLibrary
ol = OpenLibrary()
dupes = ['OL17830054W', 'OL17830053W', 'OL17830052W', 'OL17830051W', 'OL17830050W']
master = 'OL3285161W'

redirects = [ ol.Redirect(f=d, t=master) for d in dupes]
ol.save_many(redirects, "merge duplicate works")
```

I am happy to do more of these sort of bulk redirects and edition moves using the client if you provide me with lists of ids.

**Comment by LeadSongDog** [comment] 2018-01-20 06:20
@hornc Thank you, as an interim measure that is very welcome, but in the longer term I trust it will be unnecessary.

**Comment by LeadSongDog** [comment] 2018-01-26 15:02
Generically these are edition-less works created since 15 January 2018. The new work title will be the same as the now-relinked edition's historic title was at the time the new work was created. These new empty works may either be redirected to that work targeted by the edition's new link or simply deleted.

**Comment by hornc** [comment] 2018-01-29 05:07
Required for #153

**Closed** 2018-01-29 05:58 UTC

**Comment by LeadSongDog** [comment] 2018-03-03 19:17
@hornc @mekarpeles @cdrini Still a problem. https://openlibrary.org/books/OL21551234M/Heike_monogatari?m=history Shows two edits where I pasted the very same work OLID. The first link was oddly misrecorded by 1000 as a newly created work record. The second corrected the error in the edition record, but the new orphan work is still there.
