### ISSUE TITLE
Arrow missing from add to list dropdown on author pages

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9065] opened 2024-04-10 17:53 UTC
### Problem

It probably should have a down arrow like we have on the want to read button for books?
<img width="209" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/eebce5a6-bd47-4363-b14b-22050580af11">

#### Evidence / Screenshot
<img width="1080" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/0cc2cffe-c921-42c7-8abd-80677fb25961">

#### Relevant URL(s)
https://openlibrary.org/authors/OL12180252A/Adriana_Churampi_Ram%C3%ADrez

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by Spedi** [comment] 2024-04-10 19:32
Hi there!
I suppose I can tackle this issue, is there any chance that I can work on it?

**Comment by RayBB** [comment] 2024-04-10 19:38
@Spedi you're assigned! :)

**Comment by Spedi** [comment] 2024-04-10 19:57
Perfect!
Could you give me more info on the issue, please? What are the files that I should investigate in order to get the expected result?

**Comment by RayBB** [comment] 2024-04-10 20:06
@Spedi this be in the authors/view.html file.

If you're not sure about navigating the codebase yet I recommend watching some of the overview videos in our docs.

**Comment by Spedi** [comment] 2024-04-11 09:37
Thank you for the info and the advice, I'll make sure that I watch the video ASAP.

**Comment by Spedi** [comment] 2024-04-14 19:21
I may underrated the difficulty of this issue (at least for me :) ), if it is a urgent one you may want to assign it to someone more prepared.
Otherwise, if it's ok for you, would you like to help me tackle this?
In the _Want to Read_ dropdown we have the arrow because of the `include_dropper=True` in `$:macros.SearchResultsWork(doc, show_librarian_extras=show_librarian_extras, include_dropper=True)` or the two things are not related?

**Comment by Spedi** [comment] 2024-04-14 19:24
Plus, I was trying to understand the code via the _Inspect_ function of the browser, is this a good strategy in your opinion?

**Comment by RayBB** [comment] 2024-04-17 09:33
@Spedi it isn't urgent so you can take your time looking into it.
`include_dropper=True` seems related to me.
Starting with the browser inspect function to see what classes are on files to search for them on the codebase is always a good way to start!

I'd recommend checking out these files and seeing what you find. https://github.com/search?q=repo%3Ainternetarchive%2Fopenlibrary%20%22template(%27my_books%22&type=code

**Comment by azadDsync** [comment] 2024-04-22 19:01
Hello ,
I have figure out the issue ,may I allowed to work on this?

**Comment by Spedi** [comment] 2024-04-22 20:19
Hi there! @RayBB 
I suppose I solved the problem, the testing seems to give good results, but once I try to push the code on git I get this error: ` ! [rejected]            fix-frontend -> fix-frontend (fetch first)
error: failed to push some refs to 'github.com:Spedi/openlibrary.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.`
Do you know what that means?

**Comment by RayBB** [comment] 2024-04-23 09:52
It is a little hard to explain but it means your code on github is ahead of your code on local.
I think the easiest thing to do is `git pull` and then git push but that probably won't work if you already committed locally. You can`git push --force` but you should generally be very careful doing that (especially when it's not your branch).

Alternatively, you can make a new branch and push it there.
@Spedi

**Comment by RayBB** [comment] 2024-04-23 09:52
@azadDsync as you can see, this issue is already assigned to someone else. Please check the good first issues that aren't assigned to anyone and ask to be assigned before opening a PR. Thanks!

**Closed** 2024-05-09 16:46 UTC
Labels: Type: Bug, Good First Issue, Priority: 4, Affects: Experience, Team: Front-end, Lead: @RayBB, Needs: Response
