### ISSUE TITLE
Translation not working 

### ISSUE THREAD

**Issue by Tzinapapadopoulou** [internetarchive/openlibrary#9101] opened 2024-04-17 08:10 UTC
#### Evidence / Screenshot
<img width="894" alt="open" src="https://github.com/internetarchive/openlibrary/assets/117903616/f735b9d8-9b27-4e5e-ad6b-a27238f036ee">
<img width="863" alt="op" src="https://github.com/internetarchive/openlibrary/assets/117903616/623f97ad-905a-44e1-801e-db65c8f1db9e">

#### Relevant URL(s)
https://openlibrary.org/ when changing into any other language than English 

### Reproducing the bug

1. Go to the initial openlibrary page 
2. Change language and notice that the "Set a Yearly Reading Goal" box does not change.

* Expected behavior: "Set a Yearly Reading Goal" box should change language each time.
* Actual behavior: pictures above

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Proposal & constraints

I noticed that in folder i18n, all translation files include this box. However, for some reason it does not actually change. 

#### Related files

openlibrary/openlibrary/templates/home/welcome.htlm
openlibrary/openlibrary/i18n

**Comment by Tzinapapadopoulou** [comment] 2024-04-17 08:23
I would like to work on this and I am searching. If anyone has an idea of where the root of the problem might be, please let me know! :)

**Comment by rebecca-shoptaw** [comment] 2024-04-17 13:09
Hello! It's not a bug (exactly), it's just that that text was recently added to the site and translation files, so many of the translators likely haven't gotten to it yet. :) I can double-check to see if there's a way to notify people re: all the recently added text to be translated.

**Comment by mekarpeles** [comment] 2024-04-22 11:55
@rebecca-shoptaw is correct! Closing this as not an engineering issue -- the translation simply needs to be added and there are instructions here:

https://github.com/internetarchive/openlibrary/wiki#internationalization

**Closed by mekarpeles** 2024-04-22 11:55 UTC
Labels: Type: Bug, Needs: Triage, Needs: Lead
