### ISSUE TITLE
Replace `docker-compose` with `docker compose`

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7594] opened 2023-03-03 16:47 UTC
We are looking for a contributor to help us update our scripts to use `docker compose` instead of the legacy `docker-compose` which is about to be EOL (end of life).

__Related issues and pull requests:__
* [x] #7548
* [x] #7621 -->
    * [x] #7708
* [x] #7676 -->
    * [x] #7700
* [ ] #7626
    * [ ] #7706

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by Parth-Agarwal216** [comment] 2023-03-03 17:32
Hello, may I contribute to this issue?

**Comment by cclauss** [comment] 2023-03-03 18:33
Sure!...  My conversation with ChatGPT...

Q:
> what is required to upgrade a repository from `docker-compose` to `docker compose`?  Are there any websites that describe this?

A:
> To upgrade a repository from docker-compose to docker compose, there are a few things that need to be considered:

> Make sure you have the latest version of Docker installed on your system.

> Update your docker-compose.yml file to use the new syntax. This includes changing the version number to "3.0" or higher, and modifying any service definitions that use the old syntax.

> Remove any references to the docker-compose command in your build and deployment scripts, and replace them with the new docker compose command.

> Update any CI/CD pipelines or other automation tools that use docker-compose to use the new syntax and command.

> There are several websites that provide detailed instructions on how to upgrade from docker-compose to docker compose, including:

> Docker's official documentation: https://docs.docker.com/compose/reference/
> DigitalOcean's tutorial: https://www.digitalocean.com/community/tutorials/how-to-migrate-from-docker-compose-to-the-new-docker-compose-cli
> Medium's guide: https://medium.com/@kevinsimper/how-to-migrate-to-the-new-docker-compose-34530b29c7f1

> It's important to note that the new docker compose command is still evolving, so it's a good idea to check the official documentation and release notes for any changes or updates before upgrading your repository.

### So...
How should we get started?

**Comment by scottbarnes** [comment] 2023-03-03 23:48
> Unfortunately, I am unable to remove errors of the type "exec docker/ol-web-start.sh: no such file or directory" even after following the mentioned steps. Hence, sorry for the inconvenience as I may not be able to help.

@Parth-Agarwal216, I am just speculating, but it's possible that the repository got CRLF line endings during cloning. 

I know you mentioned following the steps, but just to be safe, did you try the steps listed in [Fix line endings, symlinks and git submodules](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#fix-line-endings-symlinks-and-git-submodules-only-for-windows-users-not-using-a-linux-vm) from the [Git Cheat Sheet](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet)?

The OL Docker [README.md](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md) may also have some potentially relevant information.

**Comment by cclauss** [comment] 2023-03-04 06:11
Can you `ls docker` and `ls docker/ol-web-start.sh` ?

**Comment by Parth-Agarwal216** [comment] 2023-03-04 09:36
Yep, I did try the steps listed in Git Cheat Sheet. I use Windows, yet have to learn Linux as am just starting out.

**Comment by scottbarnes** [comment] 2023-03-04 09:50
@Parth-Agarwal216, if you're still interested in this issue, we can help you try to diagnose the docker problem. If together we can solve the problem, that would help us better understand challenges people run into as well and we can update the documentation to reflect what we've learned.

The first step would be to share the output of `ls docker` and `ls docker/ol-web-start.sh` as @cclauss mentioned.

If you could also share the line endings `docker-compose.yml` is using (i.e.`CRLF` or `LF`), that would help as well. See [On windows, how would I detect the line ending of a file?](https://stackoverflow.com/questions/32255747/on-windows-how-would-i-detect-the-line-ending-of-a-file) for help with that if you're not sure -- if you're using an IDE there is a fair chance the line endings for open files will show up somewhere in the lower right of the window.

**Comment by Parth-Agarwal216** [comment] 2023-03-04 10:33
![Screenshot (15)](https://user-images.githubusercontent.com/118837763/222894820-a91b51f4-d0ed-4339-a651-bf9ded3b5261.png)
![Screenshot (17)](https://user-images.githubusercontent.com/118837763/222894829-453492f1-d1a4-4608-af5d-ba1c507bb00a.png)

**Comment by scottbarnes** [comment] 2023-03-04 10:36
Well, that has me puzzled! I was fairly certain the line endings would be `CRLF`. 

What about trying `docker compose build --no-cache` and then `docker compose up` once more, and then pasting the output up to and including an errors?

Also, I am about to go to sleep, so any further replies for me may be slightly delayed. :)

**Comment by cclauss** [comment] 2023-03-04 10:55
https://www.mingw-w64.org ;-)
$ `docker --version`
$ `docker-compose --version`

**Comment by Parth-Agarwal216** [comment] 2023-03-04 13:28
I think that I might have figured the issue. I cloned the repo using https and then modified it with the steps :
![Screenshot (19)](https://user-images.githubusercontent.com/118837763/222904434-032c5584-e143-4484-bf75-6c3d408875ff.png)
However upon running docker compose up, I still find:
![Screenshot (21)](https://user-images.githubusercontent.com/118837763/222904493-b5a2e5ca-3bac-42cc-ab1c-36dc746ed72f.png)

**Comment by DebbieSan** [comment] 2023-03-04 15:01
Hey @Parth-Agarwal216, you need to download the module for infogami. 

You can read more about infogami here 

https://openlibrary.org/dev/docs/infogami#anchor17

**Comment by scottbarnes** [comment] 2023-03-04 15:15
@Parth-Agarwal216, this looks like a step in the right direction. :)

I know you may have already done this, but just to be on the safe side, can you do:
```
git rm --cached -r .
git reset --hard
```

That last command will remove any changes you have made that aren't committed, but I am guessing you have not yet made any changes so that shouldn't be an issue.

Also to note, `git reset --hard` is likely to have some errors if not done as an Administrator, so be sure to closely check every line of the output.

I know you ran `git submodule init; git submodule sync; git submodule update` already, but maybe also run that again and double check you didn't any errors while running it, as that _may_ need to be run as Administrator in Windows, but I am not sure about that.

**Comment by Parth-Agarwal216** [comment] 2023-03-04 16:47
Just cloned the git repo again, following exact same steps but it works now lol :)

**Comment by cclauss** [comment] 2023-03-04 16:51
Please provide the output of these commands:
$ `docker --version`
$ `docker-compose --version`
$ `docker compose --help`

**Comment by Parth-Agarwal216** [comment] 2023-03-04 17:01
![Screenshot (24)](https://user-images.githubusercontent.com/118837763/222919010-11e6d044-486e-463f-9748-8abe65a9afc3.png)
![Screenshot (25)](https://user-images.githubusercontent.com/118837763/222919015-1ad48369-2124-473d-b84d-c41def7eef6c.png)

**Comment by gobbledy-gook** [comment] 2023-03-06 15:25
Hello !

Is this issue still active ? Actually I cloned the repo, installed docker on my machine and was easily able to do ```docker compose up```. I am not sure if the problem still persists.

Thanks !

**Comment by scottbarnes** [comment] 2023-03-06 16:15
@gobbledy-gook, it has not yet been addressed, but I believe @Parth-Agarwal216 is working on it. `docker compose` is meant to be a [drop-in replacement](https://docs.docker.com/compose/compose-v2/#differences-between-compose-v1-and-compose-v2) for `docker-compose`, and as such it supports the `docker-compose` options. So running `docker compose` on this repository works.

However, some files, such as [openlibrary/scripts/deployment/restart_servers.sh](https://github.com/internetarchive/openlibrary/blob/98432f1e5db85e0e906f7ef4e0231cce82910f25/scripts/deployment/restart_servers.sh#L27) have `docker-compose` in them rather than `docker compose`, and this is what needs updating.

**Comment by cclauss** [comment] 2023-03-06 16:24
% `git grep docker-compose`
```
Makefile:       docker-compose build
Makefile:       docker-compose up
Makefile:       docker-compose stop
Makefile:       docker-compose up runserver
Makefile:       docker-compose run -e SHELL=/bin/bash --rm shell pipenv update --clear
Makefile:       docker-compose run -e SHELL=/bin/bash --rm shell pipenv run pytest --create-db -vvv -x --pdb
Makefile:       docker-compose run -e SHELL=/bin/bash --rm shell pipenv run pytest -m smoketest -vvv -x --pdb
Makefile:       docker-compose run -e SHELL=/bin/bash --rm shell pipenv run pytest --create-db
Makefile:       docker-compose run -e SHELL=/bin/bash --rm shell pipenv run pytest -m smoketest
Makefile:       docker-compose run -e SHELL=/bin/bash --rm shell pipenv shell
Makefile:       docker-compose run -e SHELL=/bin/bash --rm shell pipenv run python manage.py compilestatic --delete-stale-files
Makefile:       docker-compose build --no-cache
README.WithoutDocker.md:- Copy `docker-compose.linux.yml` to `docker-compose.override.yml`
README.md:# Setup v2.5 using docker-compose
```

**Comment by Parth-Agarwal216** [comment] 2023-03-06 20:10
@scottbarnes , I had been working on the issue but am running into some problems. I think that I may be unable to solve the issue so you may assign it someone else.

**Comment by scottbarnes** [comment] 2023-03-06 21:46
Thanks for having a go, @Parth-Agarwal216.:)

@gobbledy-gook, any interest in this one? @cclauss laid out how you can find the files that (potentially) need updating. Some of the changes may be a bit hard to test (e.g. things involving Jenkins and deployment), but in theory they should 'just work' with the appropriate things installed, so don't stress about trying to test them.

**Comment by gobbledy-gook** [comment] 2023-03-08 16:45
Honestly, I am new to docker yet ! But I would like to try it. I will keep you updated with any progress. @cclauss @scottbarnes thanks for the initial direction !

**Comment by gobbledy-gook** [comment] 2023-03-09 05:01
I followed the suggested step. I changed all possible ```docker-compose``` to ```docker compose``` except the places where it appeared as file name. Below image is of the remaining files where all the remaining ```docker-compose``` text is with a file name.

![Screenshot 2023-03-09 at 10 28 12 AM](https://user-images.githubusercontent.com/96362727/223923378-77196ab8-6820-4753-9546-393f9d68aff4.png)

**Comment by scottbarnes** [comment] 2023-03-09 05:42
This is looking like good progress.

In `scripts/tests/test_affiliate_server.py` I think change the comment from `docker-compose run --rm home pytest scripts/tests/test_affiliate_server.py` to `docker compose run --rm home pytest scripts/tests/test_affiliate_server.py` so that it reflects the most current versions of `docker compose`. (If you run that test with `docker compose`, you'll see it works and the tests pass.)

The other thing that I think may need to be updated is `scripts/solr_builder/Dockerfile` to reflect a newer version of `docker-compose`, as well as the comments in the related files that say `docker-compose`. Though https://docs.docker.com/compose/install/linux/#install-the-plugin-manually may help, the change to the `Dockerfile` looks related to Jenkins and perhaps should be a separate issue. What do you think, @cclauss?

Good call on checking with ChatGPT. I would double check some of what it says, though. E.g. I read https://docs.docker.com/compose/compose-file/#compose-file as giving slightly different guidance on the compose file name. @cclauss, what do you think using `compose.yaml` as that page suggests?

@gobbledy-gook, I think you are probably at a stage where you can create a PR and mark it as a draft so we can take a look at it.

**Comment by cclauss** [comment] 2023-03-09 06:07
In the diff above, we should not modify instances `docker-compose` is immediately followed by a dot `.` but we will need to modify instances without the dot such as /usr/local/bin/docker-compose.
Let’s drop `docker.` from the names of the .yaml files as the docs recommend.
Let’s keep a single PR.
+1 on creating a PR that we can all study.
Nice progress!

**Comment by gobbledy-gook** [comment] 2023-03-09 09:29
@cclauss Agreed ! I have made the necessary changes according to me and am ready to make a PR but I don't see a branch for this issue. So to which branch should I make a PR to ?

**Comment by cclauss** [comment] 2023-03-09 10:02
`git checkout -b docker-compose_to_docker_compose`

**Comment by jamstack-elise** [comment] 2023-03-22 21:21
Hello! 
Windows user who followed sources available on the main website for getting a dev environment set up sans mentor (...but would happily appreciate a go-to mentor where available to allow for more work achievements). 

I've reproduced this two-day process (roughly ~2 hours each) and here is a summary of these results--

1. Day 1: [Volunteer Page from IA](https://archive.org/about/volunteerpositions.php) | Result: I followed the "Getting Started with our GitHub link.
2. Day 1: [Volunteer GitHub Page](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md) | Result: Went through Quick Tour, Orientation, Orientation supplemental Doc, Technical Walkthrough, Installing Open Library. I experienced information overload for Day 1 and needed to retrace and note some things to do for the following day.
3. Day 2: [Docker instructions](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md)  |  Result: Most up-to-date in troubleshooting and setting up a dev environment. I kept running into home-1 and web-1 containers exiting on Docker.
4. Day 2: [Git Cheat Sheet](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#fix-line-endings-symlinks-and-git-submodules-only-for-windows-users-not-using-a-linux-vm) | Result: I repeatedly ran into an infogami error, even with syncing up my submodules. I also noticed a dir does not exist for the codebox listed in the [troubleshooting instructions for infogami](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md/#no-module-named-infogami). So my workaround was to review filepaths manually.
5. Day 2: [Video Tutorial](https://archive.org/embed/openlibrary-developer-docs/openlibrary-docker-set-up.mp4) | Result: I realized I had watched this before and it was outdated from the instructions given in the Docker instructions, so it's recommended that it should be deprecated.

Some action items
I'm happy to help update the ["Getting Started" page](https://github.com/internetarchive/openlibrary/wiki/Getting-Started) so that  ```docker-compose``` is updated to ```docker compose```. Please give a go-ahead to follow through 🏹. Thanks!

**Comment by scottbarnes** [comment] 2023-03-22 22:29
> Some action items I'm happy to help update the ["Getting Started" page](https://github.com/internetarchive/openlibrary/wiki/Getting-Started) so that `docker-compose` is updated to `docker compose`. Please give a go-ahead to follow through bow_and_arrow. Thanks!

@jamstack-elise, Thanks for raising this issue about the wiki references to `docker-compose`. I made an issue for this: #7708. Any interest in it? Thanks too for bringing up the video being out of date. I will take a look at that.

Additionally, I'm sorry that the Docker documentation we have didn't quite get the job done without issue. We'd like to improve that, so if you have suggestions on how the documentation can be improved for onboarding new volunteers, please make an issue and we can see how we can make it better. :)

**Comment by jamstack-elise** [comment] 2023-03-23 14:39
> > Some action items I'm happy to help update the ["Getting Started" page](https://github.com/internetarchive/openlibrary/wiki/Getting-Started) so that `docker-compose` is updated to `docker compose`. Please give a go-ahead to follow through bow_and_arrow. Thanks!
> 
> @jamstack-elise, Thanks for raising this issue about the wiki references to `docker-compose`. I made an issue for this: #7708. Any interest in it? Thanks too for bringing up the video being out of date. I will take a look at that.
> 
> Additionally, I'm sorry that the Docker documentation we have didn't quite get the job done without issue. We'd like to improve that, so if you have suggestions on how the documentation can be improved for onboarding new volunteers, please make an issue and we can see how we can make it better. :)

No worries, we're all here to help make Open Library the best in-class! Thanks for guiding me through the issue and steps to complete-- on it! :) 💯

**Closed** 2023-05-17 17:21 UTC
Labels: Type: Bug, Priority: 3, Theme: Provisioning, Module: Docker, Needs: Review, Lead: @cclauss, Needs: Special Deploy
