### ISSUE TITLE
Subject isn't shown in search results

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6268] opened 2022-03-09 12:04 UTC
I was trying to search for subject "Словники" but there are 0 hits in search. I know that it exists because I had created this subject before, and currently it has 6 works ([link](https://openlibrary.org/subjects/%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%B8)). It should at least show 4 hits, in my opinion because there are also subjects [Англійсько-українські словники](https://openlibrary.org/subjects/%D0%B0%D0%BD%D0%B3%D0%BB%D1%96%D0%B9%D1%81%D1%8C%D0%BA%D0%BE-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D1%96_%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%B8), [Японсько-українські словники](https://openlibrary.org/subjects/%D1%8F%D0%BF%D0%BE%D0%BD%D1%81%D1%8C%D0%BA%D0%BE-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D1%96_%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%B8), [Українсько-японські словники](https://openlibrary.org/subjects/%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE-%D1%8F%D0%BF%D0%BE%D0%BD%D1%81%D1%8C%D0%BA%D1%96_%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%B8)

### Evidence / Screenshot (if possible)
Search results:
![image](https://user-images.githubusercontent.com/58372007/157437506-d17c9b03-65dc-4e2e-94ff-211057c20cb3.png)
Subject page:
![image](https://user-images.githubusercontent.com/58372007/157437596-f7b902f8-2f8c-4864-a35a-bdcf673cfa04.png)

### Relevant url?
Subject: https://openlibrary.org/subjects/%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%B8
Search results: https://openlibrary.org/search/subjects?q=%D0%A1%D0%BB%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D0%B8&mode=everything

**Comment by cdrini** [comment] 2022-03-09 22:26
Hi! Subjects search isn't indexed for live edits, unfortunately. They only get updated during a full reindex (eg #5827)

Closing as a duplicate of #1896

**Closed by cdrini** 2022-03-09 22:26 UTC
Labels: Type: Bug, Needs: Triage, Needs: Lead
