### ISSUE TITLE
Sliders should autoplay

### ISSUE THREAD

**Issue by Gopimanojvuyyuru** [internetarchive/openlibrary#1927] opened 2019-02-25 06:54 UTC
## Description

The Classic Book , Books we love sliders  and all others are not changing. It is better if we can add code to change randomly so that users can get known to all the books in the slider else he have to click the arrow forward and backward all the times manually.

## Expectation

If the issue is solved the user can easily see the sliders without keep on pressing forward and rewind buttons manually. 

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

**Comment by jdlrobson** [comment] 2019-02-25 16:51
Are you talking about shuffling or providing new content?

Shuffling or providing new content on the server would impact caching and thus performance.

Shuffling on the client would be jarring especially on a slow connection. 

Curious to understand the problem more and find a compromise.

What is the time to live in cache for the existing homepage? Would shortening it to say an hour help with this? Would the proposals to make these carousels load books infinitely as you scroll help?

**Comment by mekarpeles** [comment] 2019-02-25 16:56
We should lazy load and perhaps show more results at a time (perhaps a 2
row option) and offer additional faceting options.

it sounds like the problem is we are only showing the user around 10 books
on subject pages

**Comment by tfmorris** [comment] 2019-02-25 17:23
My guess is that what's being requested is for the carousels to auto cycle on a timer basis - you know, the kind that whisks away the thing you were going to click on just as you are about to click ;-)

But, as @jdlrobson said, you should clarify and then we'll need to consider tradeoffs for different possible implementations.

**Comment by Gopimanojvuyyuru** [comment] 2019-02-26 06:49
What my point is in our site the images are not moving on fixed intervals which makes users always to keep on clicking so here is small example.
https://www.w3schools.com/howto/howto_js_slideshow.asp
So if we can make slides movable it will be easier.

**Comment by mekarpeles** [comment] 2019-02-26 18:11
I think this is the type of issue is for a proposed enhancement (not a bug) and is best addressed through community consensus (e.g. on one of our calls). Marking as enhancement for now.

**Comment by jdlrobson** [comment] 2019-02-27 01:30
Slick has an autoplay mode > http://kenwheeler.github.io/slick/ which I think is what is being asked for here!

**Comment by mekarpeles** [comment] 2019-04-02 20:38
Anyone else think we should be autoplaying carousels? I think it's probably distracting. Closing for now unless there's more interest

**Closed by mekarpeles** 2019-04-02 20:38 UTC
Labels: carousels, enhancement

**Comment by jdlrobson** [comment] 2019-04-03 02:55
I think we should be moving away from carousels. I don't like them and I'm not alone. I'd much prefer a wall of covers

https://twitter.com/SaraSoueidan/status/1111937665484623872?s=19
