### ISSUE TITLE
When creating a new list in a book's page, the list does not appear in the "Want to Read" drop-down menu

### ISSUE THREAD

**Issue by Yonial** [internetarchive/openlibrary#828] opened 2018-03-05 23:18 UTC
Reproduce:

1. Find a book and click on "Want to Read". (https://dev.openlibrary.org/books/OL1419317M/Quiltmaking_tips_and_techniques)
2. Click on the drop-down button and "Create a new list".
3. Create the new list.
4. Open the drop-down menu - the new list is not displayed in the "My Reading Lists".

Tested in both DEV and PROD environments

![image](https://user-images.githubusercontent.com/10077523/37005239-47b2873c-2088-11e8-8262-b18a918d67fb.png)

**Comment by Yonial** [comment] 2018-03-05 23:28
Related to #729

**Comment by rohitjain00** [comment] 2019-03-24 12:27
SImilar issue #729 is closed so does this issue still exists? or it is also resolved in #1325 ?

**Comment by guyjeangilles** [comment] 2019-11-14 01:13
I can reproduce the bug.

This is a weird one. Some notes:
- If I go to my lists, I see the list and the book I added.
- If I go to another page and click the drop down, I see the list.
- If I navigate back to the original page where I created the list, _I still can't see the list_ from the "Want to Read" dropdown.

**Comment by jamesachamp** [comment] 2020-12-16 19:58
Additional notes:
- When using Firefox, the list will appear in the "Want to Read" dropdown if the browser's back button is used to navigate to the original page.  This isn't the case when using Chrome.
- Lists appear to be listed in the dropdown from newest to oldest.  Whenever a new list is created using the dropdown, it appears at the bottom of the list of lists (this may or may not be helpful in finding the root cause).

**Comment by bicolino34** [comment] 2022-11-19 10:18
@mekarpeles not sure if this should be kept. As for now, when you create new list, it automatically adds work to the newly created list. So, I don't think this is a problem anymore

**Closed** 2022-11-21 20:08 UTC
Labels: Type: Bug, Theme: Lists, Module: JavaScript, Priority: 3, Theme: Reading Log, Affects: UI, Lead: @mekarpeles
