### ISSUE TITLE
Fix Invalid Availability Button: Fix Bulk Availability API to not erroneously return `private` for records without `lending___status`

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#4379] opened 2021-01-07 20:32 UTC
Edition pages for editions that are available show Not in library in the edition list even though there is a Read button for the work higher on the page that links to the very same IA record.

### Relevant url?
https://openlibrary.org/books/OL26321569M

### Steps to Reproduce
Try it and see

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** safari
- **Operating system?** iPadOS 
- **Environment (prod/dev/local)?** prod

**Comment by BrittanyBunk** [comment] 2021-01-08 19:58
I brought this issue up before if you'd like to help me find it

**Comment by LeadSongDog** [comment] 2021-01-08 23:43
@BrittanyBunk This issue refers to the canonical page not the carousels.

**Comment by BrittanyBunk** [comment] 2021-01-08 23:48
@LeadSongDog it doesn't really matter, because it's the same issue. If you want me to be less specific and just say that there are mismatches of the thumbnail to reality, I can do that. I'll do that now.

**Comment by BrittanyBunk** [comment] 2021-01-08 23:49
@LeadSongDog ok, I changed it - now this is a duplicate.

**Comment by mekarpeles** [comment] 2021-01-09 19:46
@BrittanyBunk the availability for the Editions List on the Canonical Books Page is calculated in a specific way using Archive.org availability API at an edition level.

The specific problem you cited regarding **carousels** is different than this issue. It's not important that it's a "thumnail", it's important where the button is being calculated.

Recently we added code to ensure that carousels have accurate availability information. I think there's may very specifically be an issue with how Book Page the availability is being calculated **specifically for Not In Library** and specifically in the **Edition** List Tables** so I believe this issue should remain open.

In https://github.com/internetarchive/openlibrary/issues/2616, the title https://openlibrary.org/books/OL26571491M/A_haunted_house_and_other_short_stories no longer appears for me under related works for https://openlibrary.org/books/OL26571490M/Flush because this carousel specific issue should be resolved.

**Comment by mekarpeles** [comment] 2021-01-23 09:18
@LeadSongDog it looks like the bulk availability API for this item is returning `private`
https://archive.org/services/availability?identifier=traduction00arna_0

```
{
success: true,
responses: {
traduction00arna_0: {
status: "private",
available_to_browse: false,
available_to_borrow: false,
available_to_waitlist: false,
is_printdisabled: false,
is_readable: false,
is_lendable: false,
identifier: "traduction00arna_0",
isbn: null,
oclc: null,
openlibrary_work: null,
openlibrary_edition: null,
last_loan_date: null,
num_waitlist: null,
last_waitlist_date: null,
collection: "newberryfrenchpamphlets,newberry,americana"
}
}
}
```

Whereas the ground truth Loan endpoint reports `readable`:
https://archive.org/services/loans/loan/?&action=availability&identifier=traduction00arna_0
```
{
status: "OK",
lending_status: {
is_lendable: false,
is_printdisabled: false,
is_readable: true,
is_login_required: false,
max_lendable_copies: 0,
available_lendable_copies: 0,
max_browsable_copies: 0,
available_browsable_copies: 0,
max_borrowable_copies: 0,
available_borrowable_copies: 0,
users_on_waitlist: 0,
last_waitlist: null,
copies_reserved_for_waitlist: 0,
upgradable_browses: 0,
active_browses: 0,
last_browse: null,
next_browse_expiration: null,
active_borrows: 0,
last_borrow: null,
next_borrow_expiration: null,
orphaned_acs_loans: 0,
available_to_browse: false,
available_to_borrow: false,
available_to_waitlist: false,
user_is_printdisabled: false,
user_loan_count: 0,
user_at_max_loans: false,
user_has_browsed: false,
user_has_borrowed: false,
user_loan_record: [ ],
user_on_waitlist: false,
user_can_claim_waitlist: false,
user_has_acs_borrowed: false
}
}
```

**Comment by mekarpeles** [comment] 2021-01-23 09:20
@bfalling any idea what some items may be showing up as `private` which are `readable`? Is this something we can fix now that @judec's new metadata is in ElasticSearch?

**Comment by BrittanyBunk** [comment] 2021-01-23 15:39
@mekarpeles what would proof look like to you to reopen 2616?

**Comment by BrittanyBunk** [comment] 2021-01-23 15:42
@mekarpeles the problem still exists - and yes, this issue is the same as mine. Because the available edition is not showing up in the list, it's not showing up in the carousels.

**Comment by tfmorris** [comment] 2021-01-23 20:44
The metadata for that IA edition is messed up in other ways too. The [IA entry](https://archive.org/details/traduction00arna_0) links to OCLC, but **not** OpenLibrary. It has two different "authors" which differ only be a single period following the death date. Etc.

**Comment by BrittanyBunk** [comment] 2021-01-23 20:51
@tfmorris how does that cause the mess-ups seen here? Does it have to do with the dual author problem and redirecting? It's a little tricky to understand.

**Comment by tfmorris** [comment] 2021-01-23 20:55
> how does that cause the mess-ups seen here? Does it have to do with the dual author problem and redirecting? It's a little tricky to understand.

Just more evidence of messed up metadata for the investigation. Until there's a root cause analysis, it won't be known if all the metadata problems with this edition are related or not. If they turn out to be separate bugs, they can be split into multiple tickets.

**Comment by mekarpeles** [comment] 2021-01-24 00:36
Proposed solution is on petabox:

Call the function that generates those values directly from within `AvailabilityService.inc`:
`Lending\LendingFacets::get_search_doc_fields()`
https://git.archive.org/ia/petabox/-/blob/master/www/common/Lending/LendingFacets/LendingFacets.php#L214

Accepts a full_item_metadata object to pass along to get_status to avoid making a metadata API. Create your own array of metadata from the search metadata and pass it through to avoid additional calls to APIs (for non-lendable books).

To calculate is_readable w/o calling the Lending APIs, then we may approximate as:
`$status['is_readable'] = !$md_fields['access-restricted-item']`

**Comment by LeadSongDog** [comment] 2021-01-24 16:32
See https://openlibrary.org/show-records/ia:traduction00arna_0
Note the old ia: identifier. Also note that the character set mangled "Romanæ" to "Roman©Œ" and "intitulé" to "intitule ".

**Comment by Yashs911** [comment] 2021-01-27 05:52
@mekarpeles @LeadSongDog Might be related to this issue.
![image](https://user-images.githubusercontent.com/64412143/105948733-7e466880-6091-11eb-9fe8-682d6cb59a62.png)

**Comment by BrittanyBunk** [comment] 2021-01-27 15:28
@LeadSongDog I did bring up issues with not using a consistent language for book titles, so we just have to work through it if we decide to stay with inconsistency. Like would it be ok if those who are looking at book titles see "original title in original language (translation)" <- then have an identifier that can use the translation if the original's not the same language? 

Or would you like to create software that accoutns for special characters?

**Comment by LeadSongDog** [comment] 2021-01-27 16:57
@BrittanyBunk That’s a whole different issue. This was the result an old bug that mangled the import of MARC records by confusing different code sets. It has been fixed for newly acquired MARC files, but there’s a lot of bad old metadata still in play.

**Comment by LeadSongDog** [comment] 2021-02-10 05:16
Just to be clear, these buttons should be the same:

![66F48476-7B61-47D3-9F92-61189E05A532](https://user-images.githubusercontent.com/11435431/107467965-1d10a180-6b35-11eb-9d02-f3663ba64a58.jpeg)

**Comment by seabelis** [comment] 2021-02-25 08:58
Patrons also ask about this.

**Comment by mekarpeles** [comment] 2021-06-04 03:37
Updating this thread, the problem seems very explicitly to be with this API and the underlying metadata coming from Archive.org behind the scenes:

https://archive.org/services/availability?identifier=traduction00arna_0

On Open Library @jamesachamp & I used the admin interface to `sync` the OL book w/ the IA book (which likely performs some sort of Archive.org Catalog-level `Book Op`) and 10 minute or so later the `services/availability` API seemed to return the correct value.
https://archive.org/embed/openlibrary-tour-2020/openlibrary-availability-button-technical-walkthrough.mp4?start=1540

**Comment by mekarpeles** [comment] 2021-06-22 00:34
We've confirmed it's a data issue on Archive.org. The bulk availability API needs to again be updated, this time so the default value is not `private`. We have an option to add additional handling to treat specific collections (e.g. ones Open Library can't easily vouch for) as private. On the other hand, certain collections like `American Library` or `Library of Congress` may likely be blessable.

Related to #5316

**Comment by cdrini** [comment] 2021-07-06 19:50
Although ideally this would be fixed at the source, it seems like that's aways away. So let's try a shim. Note: Andrea to choose which collection to filter through; @mekarpeles to work with @bfalling to get the code through.

**Comment by mekarpeles** [comment] 2021-07-29 00:08
Anyone have more examples of when Bulk Availability is showing the wrong availability listing in the Editions List? (i.e. when it disagrees w/ the value under the book)

The fix needs to go right here (internal code):
https://git.archive.org/ia/petabox/-/blob/master/www/common/AvailabilityService.inc#L150

**Comment by LeadSongDog** [comment] 2021-07-29 02:06
#4379 looks to be related: traduction00arna_0 vs traduction00arna

**Comment by mekarpeles** [comment] 2021-07-29 18:48
protodonation and promise items should also be excluded from the availability API because these are essentially "promises" for a book rather than ones we have in our inventory.

**Comment by LeadSongDog** [comment] 2021-10-02 15:45
@mekarpeles Here’s another:
https://openlibrary.org/search/inside?q=Schofield+family+tree finds
https://openlibrary.org/books/OL15443993M/England%27s_thousand_best_houses?edition=englandsthousand00jenk_0
which can be borrowed but shows "Not in library" on the search results page

**Comment by mekarpeles** [comment] 2021-11-05 17:24
I think @bfalling is taking this one over because there are 3 pieces which require updating:

1. Adding Preview Status: denoting an `is_previewable` boolean status
2. Excluding Promise Items: Excluding mediatype:data results (which causes false-matches against promise items isbn lists)
3. Fixing Fallbacks: There are books the API erroneously reports as `private` because they have no `lending___status` (which is true for many open books, e.g. https://archive.org/services/availability?identifier=goody reports private but https://archive.org/details/goody is correctly open) -- the solution here seems to be for @judec and @ximm to walk certain items with e.g. `scanningcenter` or `repubstate`

**Comment by mekarpeles** [comment] 2022-02-05 06:11
I provisionally think this should be fixed now, once the next PI goes out for archive.org

**Closed by mekarpeles** 2022-02-05 06:11 UTC
Labels: Type: Bug, Module: Borrowing / Lending, Module: Books Page, Priority: 2, Lead: @mekarpeles
