### ISSUE TITLE
Clean up of the UI of the Subjects page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2504] opened 2019-10-12 22:28 UTC
https://openlibrary.org/subjects should not look like https://imgur.com/a/DWnYhA2. Instead, it would benefit from looking like https://imgur.com/a/FqazntY. The page could be a very nice directory then. Everything else on the page now can go underneath the re-imagined picture.

**Comment by tfmorris** [comment] 2019-10-14 02:19
The current page includes:

- separate listings for four different types of subjects (people, places,...)
- hand picked examples for each subject type
- textual listings without pictographic icons

Which are you proposing changing? Or all of the above?

**Comment by BrittanyBunk** [comment] 2019-10-14 15:09
I'm not proposing changing those - just to push those down the page and add in the layout in the picture to it. I mean, that part could be improved, but idk how right now.

**Comment by mekarpeles** [comment] 2019-10-14 17:03
I have a demo redesign of https://github.com/internetarchive/openlibrary/tree/refactor/everything and will followup on this post October

**Comment by mekarpeles** [comment] 2019-10-14 21:59
Merging as duplicate of #2072

**Closed by mekarpeles** 2019-10-14 21:59 UTC
Labels: CH: subjects, State: Work In Progress, Type: Feature
