### ISSUE TITLE
List search only finds exact matches

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6974] opened 2022-09-19 07:18 UTC
From a patron:
A List search result is only given if the exact, full name of a list is used in the search. Searching on words that are only part of a list name returns "No results found."

### Relevant url?

https://openlibrary.org/search/lists

### Steps to Reproduce

1. Go to ... https://openlibrary.org/search/lists
2. Do ... enter a partial list name, for example, https://openlibrary.org/search/lists?q=banned

* Actual: only exact matches returned
* Expected: any list containing search term should be returned

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

If this cannot be adjusted, maybe a tip about using wildcard search would be useful. For example https://openlibrary.org/search/lists?q=banned*
### Stakeholders

@cdrini

**Comment by cdrini** [comment] 2024-06-11 13:27
Closing as a duplicate of #2723 . Although happy update: This is no longer blocked! Lists _are_ now in solr, we just need to update API/UI to use solr instead of our old, postgres approach 🥳

**Closed by cdrini** 2024-06-11 13:27 UTC
Labels: Type: Bug, Theme: Search, Theme: Lists, Priority: 2, Lead: @cdrini, Affects: Experience
