### ISSUE TITLE
Ebook filtering not working on authors page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2251] opened 2019-07-31 18:20 UTC
### Description
Similar to the issue we had with search results (#2250). archive.org 's availability API has been throwing errors (apparently) when passed too many identifiers, causing our ebook filtering, which uses this API, do return no results.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/62237019-395b4c00-b39e-11e9-89f2-6bb351ba76a3.png)

### Relevant url?
https://openlibrary.org/authors/OL23919A/J._K._Rowling (make sure "ebooks" checked)

### Expectation
Should see books.

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Firefox 68
- **Operating system?** Windows 10

### Proposal & Constraints
We fixed this in the search results by decreasing the number of rows to `20`. Here we should decrease the number of rows to `50` (people are more likely to ctrl-f on an author's page, so we want to show more results here).

### Stakeholders
@mekarpeles

**Comment by tapaswenipathak** [comment] 2019-08-02 14:24
Hi @cdrini, @mekarpeles: I see everything, though on Google Chrome, should I check in Firefox 68?

![](https://i.gyazo.com/86fb49ce12b30894e8fbeee99a161b5c.jpg)

**Comment by cdrini** [comment] 2019-08-02 15:01
Sweet! Dropping this to priority high (feel free to change, @mekarpeles ); it looks like archive.org has stabilized.

**Comment by guyjeangilles** [comment] 2019-10-21 23:09
@mekarpeles I'm proposing to close this issue since it appears to be a duplicate of #2177

**Comment by jdlrobson** [comment] 2019-10-21 23:30
Duplicate. Retaining the older ticket.

**Closed by jdlrobson** 2019-10-21 23:30 UTC
Labels: GJ: proposed closure, Priority 1: High, State: Work In Progress, Type: Bug
