### ISSUE TITLE
Author merge which returns 400 Bad Request labelled a success

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8724] opened 2024-01-16 19:28 UTC
The merge listed below returns a 400 Bad Request status on the Javascript console, but the UI calls it a success.

### Evidence / Screenshot (if possible)
![Screenshot 2024-01-16 at 2 24 38 PM](https://github.com/internetarchive/openlibrary/assets/82178/a517e377-5c65-462a-9837-5e8ff1e14794)

### Relevant url?
https://openlibrary.org/authors/OL16963A/Emile_Monte%CC%81gut?merge=true&duplicates=OL1964447A,OL3450354A,OL4279219A,OL4404792A,OL6023387A,OL6056363A,OL6184875A,OL6389150A

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: Errors are correctly reported to the user so that they can follow up

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by benbdeitch** [comment] 2024-01-17 20:06
Hello! Would I be able to get assigned to this issue?

**Comment by cdrini** [comment] 2024-01-17 21:40
Duplicate of #8042 . Copied over the data from here to there. Leave a comment on that one and I will assign you @benbdeitch !

**Closed by cdrini** 2024-01-17 21:40 UTC
Labels: Type: Bug, Priority: 3, Affects: Librarians, Lead: @cdrini, Module: Merge Queue

**Comment by tfmorris** [comment] 2024-01-17 23:04
Oops, sorry for the duplicate! I guess I forgot about it in the intervening 6 months.
