### ISSUE TITLE
No way to add an author, independently of Work creation

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#512] opened 2017-07-06 20:16 UTC
@JeffKaplan has been asking, why don't we have a way to "Create an Author" without creating a book.

We do have a way to do this through APIs, but not for administrators or users.

**Comment by LeadSongDog** [comment] 2017-10-30 20:47
Dupe of #352 isn't it?

**Comment by guyjeangilles** [comment] 2019-10-22 23:59
I agree with @LeadSongDog. This appears to be a duplicate of the older issue #352. I propose closing this issue.

**Comment by tfmorris** [comment] 2019-10-23 05:40
Agreed. Let's be bold and just make it so...

**Closed by tfmorris** 2019-10-23 05:40 UTC
Labels: Close: Duplicate
