### ISSUE TITLE
Make VIAF and Wikidata IDs on author pages editable

### ISSUE THREAD

**Issue by Camillo-Pellizzari** [internetarchive/openlibrary#2426] opened 2019-09-28 17:40 UTC
### Is your feature request related to a problem? Please describe.
On author pages VIAF and Wikidata IDs aren't editable

### Describe the solution you'd like
It should be possible for users, or at least for librarians, to edit VIAF and Wikidata IDs on author pages

### Additional context
Additional suggestion: maybe, if VIAF is absent, OL could try reading it from Wikidata

**Comment by hornc** [comment] 2019-09-29 22:38
This is a dupe of #853 which has some technical details of how the ids are stored.

**Closed** 2019-09-30 13:53 UTC
Labels: Close: Duplicate
