### ISSUE TITLE
new books added to OL are showing up in Search with no covers/authors

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#323] opened 2016-09-28 16:15 UTC
newly added item: https://openlibrary.org/works/OL17235656W/Committed_to_World_Mission

Search results for item: https://openlibrary.org/search?q=Committed+to+World+Mission

Note: no cover & no author despite item having a cover and an author

**Comment by LeadSongDog** [comment] 2016-09-28 16:56
Hi @jessamynwest Your example is a compendium, with editors rather than authors given. 
That work was first added as:
https://openlibrary.org/works/OL17235656W/Committed_to_World_Mission?v=1
The original edition's addition was: https://openlibrary.org/books/OL25808538M/Committed_to_World_Mission?v=1 

Both were the same day 2015-11-09, made by Jon Isaak. The second edit to the work added the two editors as one "author": 
https://openlibrary.org/works/OL17235656W/Committed_to_World_Mission?b=2&a=1&_compare=Compare&m=diff
Subsequent edits to the edition added contributor details to both the TOC and the list of roles:
https://openlibrary.org/books/OL25808538M/Committed_to_World_Mission?b=7&a=1&_compare=Compare&m=diff

As there was already a linked OCR on IA, that is likely where the initial metadata arose too (need to check).

**Comment by jessamynwest** [comment] 2016-09-28 16:57
Ah, thank you -- that user added a lot of them all in one day. Still not clear why the cover is not showing?

**Comment by LeadSongDog** [comment] 2016-09-29 18:07
Also odd, the (bogus) author page is not linked to the work: https://openlibrary.org/authors/OL7252017A/Victor_Adrian_and_Donald_Loewen_eds.
Was this perhaps happening because the edition was created before the work had an author?

**Comment by LeadSongDog** [comment] 2016-09-29 21:40
This is probably connected with #153 somehow.

**Comment by hornc** [comment] 2019-04-09 21:35
The specific item's issues have been fixed, and the item looks to be correctly indexed now. I think this was originally caused by the various Solr indexing gaps we have struggled with for some time. Since @cdrini and I have made improvements to the solr code, hopefully this is no longer an issue. Let's monitor recent ongoing  imports and look for current examples of gaps. There is a known ~15 min delay for solr indexing to occur and for new data to appear in search.

**Closed by hornc** 2019-04-09 21:35 UTC
Labels: bug, import, priority
