### ISSUE TITLE
Can't add item to multiple lists without refreshing page.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1890] opened 2019-02-15 18:47 UTC
## Description

After adding an item to a list, the dropdown will not work again without refreshing the page; it's just unresponsive.

**Comment by jdlrobson** [comment] 2019-07-19 19:44
I've got a fix for this. This is another bug that was sadly caused by #1867 - there are likely many more breakages.

**Closed** 2019-07-24 18:39 UTC
Labels: Affects: UI, Needs: Review, Priority 1: High, Theme: Performance, lists
