### ISSUE TITLE
Creating new work doesn't save added author

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1716] opened 2018-12-13 00:15 UTC
## Bug
Visited https://openlibrary.org/authors/OL539266A/Michael_Pollan
Clicked "Add another"
![screen shot 2018-12-12 at 4 14 44 pm](https://user-images.githubusercontent.com/148752/49907006-33255900-fe29-11e8-9886-df2b83e104f3.png)

Filled in work.
Realised book page didn't link to author.

## **Expectation**: 

Since the author was made clear from the start of the workflow, the book should have been auto-populated with the author I added the work from.
## **Details**: 
All wikis.

**Comment by seabelis** [comment] 2018-12-13 05:48
Also when creating a new work. Populating the author in the initial form does nothing. Author must be added or created in the edition edit screen.

**Comment by LeadSongDog** [comment] 2018-12-13 14:11
#352 should be done first. Work edits should only select an OLxxxA id. Edition edits should only select a work id. Edition-specific contributors should not be conflated with authors.

**Comment by LeadSongDog** [comment] 2019-05-16 21:36
@jdlrobson 
The original bug seems to have been addressed. The form autopopulates.

**Comment by tfmorris** [comment] 2019-05-16 21:49
Yes, the form autopopulates now, but the author field doesn't get saved in the record. See #2128

**Comment by seabelis** [comment] 2019-07-30 12:57
Changed the title of this because the issue exists when adding a new work in general. The author drop-down appears to work, but then the author is not actually saved.

**Comment by guyjeangilles** [comment] 2019-10-20 00:12
@jdlrobson @tfmorris @LeadSongDog @seabelis Labeling this as backlogged and needing assessment since it's a high priority issue with no assignee. I'm assuming it would be @seabelis because she's the Lead Community Librarian, but chime in with your opinions.

**Comment by seabelis** [comment] 2019-10-20 14:06
If it's assigned to me does that mean I need to solve it? I'm still in bootcamp, lol!

**Comment by guyjeangilles** [comment] 2019-10-21 00:22
@seabelis Not necessarily. In short, the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki
> the assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

**Comment by seabelis** [comment] 2019-10-21 15:40
You can assign it to me but it may not get my full attention at least until December.

**Comment by tfmorris** [comment] 2019-12-17 18:32
I just ran into this again a couple of days ago and had to add the author to the record by hand afterwards: https://openlibrary.org/works/OL20563217W/Growth?_compare=Compare&b=2&a=1&m=diff

Since this has been reported several times, including via email to support, it would be good to bump it up in priority.

**Comment by LeadSongDog** [comment] 2019-12-17 22:49
Possible clue: that same work is not found by https://openlibrary.org/search?q=9780262042833&mode=everything
@tfmorris Is it possible you just forgot to click on the author dropdown? https://openlibrary.org/works/OL20563217W.json?v=1 shows  "authors": []

**Comment by tfmorris** [comment] 2019-12-17 23:38
@LeadSongDog Please go back and read the original description. There is no "author dropdown" involved since this is starting from the author page.

**Comment by LeadSongDog** [comment] 2019-12-18 05:37
@tfmorris My apologies, I must have been mislead by the issue title, which seems to vary from the bug report

**Comment by cdrini** [comment] 2020-01-28 17:52
This bug looks like it was introduced in 34e338a26d3ce44bff0a4c9bba66677c9d6500e6 ; where the add page was switched to use the same author autocomplete as regular book editions, but it looks like the books/add endpoint wasn't expecting the fields that that code is supplying. So it looks like this has been an issue since Oct 2018 😬

**Comment by seabelis** [comment] 2020-01-28 18:49
@cdrini I'm pretty sure it's been longer than that, but I can't swear by it.

**Closed** 2020-02-05 10:09 UTC
Labels: Affects: Data, Affects: UI, Lead: @cdrini, Priority: 1, State: Work In Progress, Type: Bug, ls: user-issue

**Comment by tfmorris** [comment] 2020-02-05 17:25
Were we able to improve the test coverage at all so that future refactorings don't break this again? It took us ~18 months to get to this regression.
