### ISSUE TITLE
Create a table creation software for the Table of Content

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7313] opened 2022-12-21 15:30 UTC
OpenLibrary allows to create a Table of Contents (ToC) for an edition, but the limits and abilities are difficult to figure. Manually including table row separators is also rather error prone. It would be great if some kind of editor helped in creating such a ToC.

### Describe the problem that you'd like solved

It would be great if there was some kind of grid where I could simply enter the table of contents, instead of having to do it completely manually.

### Proposal & Constraints

I imagine to be some kind of "spreadsheet" included in the ToC field, where one can choose the tier for each row. 

It could be similar to the classic spreadsheet at [Geobra](https://www.geogebra.org/classic#spreadsheet), but instead of calculation tools, it offers tiers.

### Additional context

![geobra-spreadsheet](https://user-images.githubusercontent.com/36878944/208941825-111f3382-5ff3-4f68-9e5e-a776dcef0c53.png)

https://github.com/internetarchive/openlibrary/issues/7261 (This is a part of Improve OpenLibrary's User Interface to make librarians work easier)

**Comment by mekarpeles** [comment] 2023-01-03 19:54
Broadly a duplicate of #6524 #2384

Related to #683

**Closed** 2023-01-03 19:55 UTC
Labels: Type: Feature Request, Needs: Triage, Needs: Lead
