### ISSUE TITLE
[Feature] State Books that are in the Internet Archive as in the OpenLibrary

### ISSUE THREAD

**Issue by ncorder** [internetarchive/openlibrary#3913] opened 2020-10-13 07:22 UTC
### Describe the problem that you'd like solved

Many books are listed on the Internet Archive but not in the OpenLibrary, including many books that are out of copyright of under Creative Commons. 

Example:
OpenLibrary: https://openlibrary.org/books/OL30618142M/Plane_Geometry
Internet Archive: https://archive.org/details/euclid-elements-redux_201809/euclid-a4

### Proposal & Constraints

Both systems let users list the ISBN and the OpenLibrary allows users to add the Internet Archive identifier. 

### Stakeholders

_______________________

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=93395014)](https://www.bountysource.com/issues/93395014-feature-state-books-that-are-in-the-internet-archive-as-in-the-openlibrary)

**Comment by mekarpeles** [comment] 2020-10-16 05:36
Duplicate of #732 -- this issue needs to be more specific in terms of the scope of the problem (e.g. and Archive.org search query which produces all items which should be imported into OpenLibrary.org) and the desired solution (e.g .a bot running once a month?).

Otherwise, this issue is always going to be true (i.e. drift between archive.org / openlibrary.org) and the issue is unactionable.

@ncorder I love the spirit of the issue, so don't take this as a down-vote -- I am making a tough decision to close this issue until it's updated to become actionable. Feel free to re-open as this becomes true :)

**Closed by mekarpeles** 2020-10-16 05:36 UTC
Labels: Needs: Triage
