### ISSUE TITLE
Flash Messages pane not displaying on any V2 pages

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1566] opened 2018-11-12 22:13 UTC
When I edit the author field on a works page it apparently is suppressing the intended message pane because when I go to another page type (e.g. search results page), I'll see a number of green "Thank you for improving the record" messages stacked together. More importantly, I may also see a "Unexpected type /type/redirect" error from some long past edit.

These messages are apparently getting returned and saved correctly, but the Javascript that displays them is apparently not working.

**Comment by jdlrobson** [comment] 2018-11-13 01:15
I can't replicate this right now as I don't have a working captcha on my docker instance and get "Recaptcha solution was incorrect" every time I hit save and 1568 is broken blocking replication on dev.openlibrary.org. However when I try these steps on openlibrary.org I'm not seeing any messages in the HTML.

Replication steps:
* Visit http://localhost:8080/works/OL20600W/Gulliver's_travels
* Enter author like so:
![screen shot 2018-11-12 at 5 07 53 pm](https://user-images.githubusercontent.com/148752/48384132-c853f700-e69d-11e8-9f4c-ca8e86d8a25b.png)
* Hit save.

I'm not sure how the "lost" message is supposed to look and/or how this gets rendered (is it from an inline script or from an API response or is it supposed to be baked into the HTML of the page?) Knowing this will help me understand how to fix this.

**Comment by jdlrobson** [comment] 2018-11-13 06:09
I just got two messages when I visited https://openlibrary.org/languages thanking me for an edit I didn't do.

Tom, next time this happens, can you tell me if the message you are expecting to see shows up when you navigate (via address bar) to https://openlibrary.org/languages ?

**Comment by tfmorris** [comment] 2018-11-15 17:45
Here's the HTML from a page where there error message *does* appear:

          <div class="flash-messages">
            <div class="error"><span>expected /type/author, found /type/redirect</span></div>
            <div class="clearfix"></div>
          </div>

It appears as the very first element in the <div id="content">. Perhaps searching for the class flash-messages will help figure out where it went missing.

**Comment by jdlrobson** [comment] 2018-12-13 17:15
Assigning myself to remember to look into this..

**Comment by LeadSongDog** [comment] 2018-12-13 17:35
Part of the difficulty is that when these messages display, they persist for only a second or two, then disappear. By the time you recognize what's happening it's too late for a screengrab.

**Comment by jdlrobson** [comment] 2018-12-13 17:43
Okay, I looked into this, and the problem is that we don't add flash-messages div to the HTML and we don't include the CSS. So what happens is the error gets delayed until you visit a non-V2 page. I can get a fix for this out this week..

**Comment by seabelis** [comment] 2018-12-14 11:11
@jdlrobson Yes, piled up somewhere...
![fullscreen capture 12142018 120758 pm bmp](https://user-images.githubusercontent.com/17739465/50000206-1ad44c00-ff99-11e8-9745-62acd8b5cea6.jpg)

Possibly related to https://github.com/internetarchive/openlibrary/issues/1670. Once the dam breaks I stop getting the offline screen for a while.

**Comment by LeadSongDog** [comment] 2018-12-14 19:53
I may be imagining it, but it seems that the flashes only come out when I do a search:  I don't see them on a key-based query.

**Comment by jdlrobson** [comment] 2018-12-14 20:50
Search is one of the few v1 pages (old non mobile friendly) so that doesn't surprise me. Above fix will take care of this!

**Closed** 2018-12-17 19:46 UTC
Labels: mobile & responsive
