### ISSUE TITLE
Try updating local environment to postgres 13 or 16

### ISSUE THREAD

**Issue by jimman2003** [internetarchive/openlibrary#5686] opened 2021-09-21 19:37 UTC
1st hurdle: After starting the cluster locally I get  `db_1            | 2021-09-21 19:23:50.123 UTC [1] FATAL:  database files are incompatible with server
db_1            | 2021-09-21 19:23:50.123 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.3, which is not compatible with this version 13.4 (Debian 13.4-1.pgdg100+1).` ...

I see two ways to fix this ^:
1. recreate the table using the schema + data in the new version
2. use pg_upgrade+ changes in some stuff in the db (settings...) https://www.postgresql.org/docs/13/pgupgrade.html

**Comment by cdrini** [comment] 2021-09-21 23:25
That's odd ; this file: https://github.com/internetarchive/openlibrary/blob/0d15279d99bb3c2c7bc1559c01c59f0e15bd1aa0/docker/ol-db-init.sh is the file that writes data into the db. But the data is not persisted between docker down/ups.

How did you update? If you update the postgres version in `docker-compose.override.yml` and down/up, that should do it :+1:

**Comment by jimman2003** [comment] 2021-09-22 05:02
I did that and also I rebuild for good measure

**Comment by jimman2003** [comment] 2021-09-22 05:04
The pg_dump might be the problem, might need to generate a new one as outlined by the OP

**Comment by jimman2003** [comment] 2021-09-22 06:36
Change 1: comment last line in db init (as a test) , got rid of the OP error 
Change 2: pass env variables to the db to set password and (ignore it)(for now) required by the new images
with the above changes , the db stays up \o/
need a new dev db dump now :)

**Comment by jimman2003** [comment] 2021-09-22 19:56
https://github.com/internetarchive/openlibrary/pull/5689

**Comment by jimman2003** [comment] 2021-09-22 19:59
it turns out that adding a explicit user solved hurdle 1 for some reason :)
so no new dev db dump required

**Comment by cclauss** [comment] 2023-07-09 12:56
https://github.com/internetarchive/openlibrary/labels/State%3A%20Blocked I because I cannot ssh into `ol-db1` or ol-db2`.

**Comment by mekarpeles** [comment] 2024-05-02 19:17
Closed by #5689

@jimchamp confirmed that changing compose.override.yml from using postgres 9.3 to 16.2 completed on the local environment (with the built in database) without error.

https://github.com/internetarchive/openlibrary/blob/1426c387aa4de12119422f8acbd9741964d7a009/compose.override.yaml#L45

**Closed by mekarpeles** 2024-05-02 19:17 UTC
Labels: Theme: Provisioning, Module: Docker, Type: Subtask of Epic, Priority: 2, State: Blocked, Affects: Operations, Lead: @jimchamp

**Comment by RayBB** [comment] 2025-01-04 21:05
FYI, postgres 17 is supposed to have huge performance improvements so we should probably jump all the way there if we can. https://www.postgresql.org/about/news/postgresql-17-released-2936/
