### ISSUE TITLE
Test pip dependencies with --use-feature=2020-resolver

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4093] opened 2020-11-13 18:44 UTC
Pip warns that end of October (which has passed) pip will change how dependencies are managed, possibly causing problems, and that we should test with ` --use-feature=2020-resolver`

**Comment by cclauss** [comment] 2020-11-14 18:26
Duplicate of #4086 this is running in Travis CI: https://github.com/internetarchive/openlibrary/blob/master/.travis.yml#L45

**Closed** 2020-11-14 18:26 UTC
Labels: Affects: Admin/Maintenance, Lead: @cclauss, Priority: 2, Type: Bug
