### ISSUE TITLE
Unable to add book: "Internal Server Error"

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5016] opened 2021-04-08 22:22 UTC
I tried to add a book with the following details:
* Title: `He Huli ʻUlaʻula: A Study in Scarlet`
* Author: `Fevronia H Watkins`
* Publisher: `Independently Published`
* Published: `November 25, 2020`
* ISBN 13: `9798589760521`

When I do I just get "Internal Server Error"

### Evidence / Screenshot (if possible)
<img width="988" alt="Screen Shot 2021-04-08 at 12 16 57 PM" src="https://user-images.githubusercontent.com/921217/114103319-a78b2e00-9864-11eb-8e33-fac2556c9329.png">

![image](https://user-images.githubusercontent.com/921217/114103403-ca1d4700-9864-11eb-9b5f-f67f39058cc2.png)

### Relevant url?
https://openlibrary.org/books/add

### Steps to Reproduce

1. Go to to the add books url, add books with the details as listed above

I tried adding debug=true to the html action following [this guide](https://github.com/internetarchive/openlibrary/wiki/Debugging) but didn't see any more detailed errors.

* Actual: Error
* Expected: No error
 
### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Brave
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

**Comment by cclauss** [comment] 2021-04-09 10:27
Closing as duplicate of #4869

**Closed by cclauss** 2021-04-09 10:27 UTC
Labels: Lead: @dhruvmanila, Needs: Triage, Theme: Unicode, Type: Bug
